### ISSUE TITLE
Produce quiz / survey / CTA for beat 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#10]
@brettgaylor this will be a team effort, who's accountable?

**Comment by jgmac1106** [comment]
You know I am big on storytelling for CTAs I would develop a common hashtag we could scrape from different social media challenges and have a variety of activities people could do.

For Beat One ask people to be honest. Have them tell a story about when their security was breached,
- It might be a time when your password was stolen.
- your brother put up an embarrasing post on FB bc you do not log out.
- Maybe as a new blogger you never got around to changing the default username and password and had your site hacked (my story).
- A credit card was stolen
- etc

Then ask people to publish a blog post, share an image of how being breached made them feel, or complete a yet to be completed Thimble remix about the "Breached Whale" or some other silly play on words.

They then share this across the SM channels of their choice using the hashtag.

**Comment by OpenMatt** [comment]
@brettgaylor some interesting ideas here from jgmac

**Comment by OpenMatt** [comment]
@brettgaylor this seems like another priority item to get done this week

**Comment by jgmac1106** [comment]
@brettgaylor Hope you don't mind lurking (borderline trolling) I might do as the campaigns are developed. 

If a framework (and an easily remixable instructional design) emerges from the first privacy campaign it will be a huge win.

Online gatherings will be the contribution engines that drive leadership and advocacy. They just need to get people interacting and communicating.

I have been running different open classrooms for a few years now. Some of our first participants are our biggest leaders.

I just got worried (probably overblown-- as no MoFO session, online or offline, I have attended has been this way) as I saw a campaign being defined as:
- Step 1: Watch this video (hopefully a teaser)
- Step 2: take this online quiz.

We need people making cool stuff and telling stories and then taking action.

Hoping the privacy campaign unfolds (or points direction) to have a large global hub with all these local nodes running and forking the sessions and activities.

**Comment by OpenMatt** [comment]
Interesting example: https://securetheinternet.org/
folks are signing a pledge that when the legislation appears, they will take action

**Comment by OpenMatt** [comment]
@brettgaylor @shaghdoosti who's the main driver for this?

**Comment by OpenMatt** [comment]
Is this still in scope for Beat 1? Or are we just going with a pared down "watch the video and sign-up" approach?

**Comment by OpenMatt** [comment]
Sounds like this is just a survey that won't require any additional production work -- so I'm going to close this. It's baked into the landing page stuff.
