### ISSUE TITLE
Delivery Schedule for Beat 2

### ISSUE THREAD

**Issue by KarinaRipper** [MozillaFoundation/encryption_campaign#100]
Hi team @brettgaylor @OpenMatt ! 

Wanted to touch base on the delivery schedule for Beat 2. 

Delivery of Final Cut - EOD Wednesday, February 10 
- Rough music

Delivery of Masters/Deliverables - EOD Monday, February 15
- Quicktime Movies - H264, 1920x1080, 23.98
- Screengrabs

Let me know if those dates sound good to you. 

Thank you!

**Comment by OpenMatt** [comment]
@brettgaylor can you update?

**Comment by brettgaylor** [comment]
Delivered!
