### ISSUE TITLE
Test snippet optin - ensure data enters ExactTarget correctly

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#102]
The snippet build is nearly completed: #23 

We need to test to make certain data entered into the snippet form fields land in ExactTarget properly, with correct tokens as well.

@stephaniemcv can you work with @ScottDowne (and whomever else you may need to pull in, like @bniolet) to double check data is stored properly in ET?

NOTE: the country field data, when filled out, is needed in ExactTarget for email targeting; as is source (e.g. "encryption snippet")

**Comment by valianttry** [comment]
@ScottDowne I chatted with @stephaniemcv apparently this was already tested successfully with the help of @jbuck . I'm closing!

**Comment by ScottDowne** [comment]
Woo hoo go team. Can I go on vacation now :D

**Comment by valianttry** [comment]
:wave:
