### ISSUE TITLE
Create poster frame for videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#103]
We need to create a poster frame with a play button for the snippet, and for social sharing.  You can see what the snippet looks like with a poster frame here:

![image](https://cloud.githubusercontent.com/assets/345974/12838005/1ec67b92-cb7d-11e5-9cc3-80f7be3d0ffe.png)

And with Facebook and YouTube you can upload this yourself manually. You don't want their auto poster frames as they are always something lame and awkward.

Jordan OK for me to assign this to you?  Or maybe @rohanporteous you might be able to take this on as part of delivery?

**Comment by lovegushwa** [comment]
@brettgaylor how are these?
![poster-1920x1080](https://cloud.githubusercontent.com/assets/12228435/12861783/c5c6873c-cc1a-11e5-864b-7dddeca1bb2c.jpg)

**For landing page, text over image.**

![poster-dark-1920x1080](https://cloud.githubusercontent.com/assets/12228435/12861799/d5ead7d0-cc1a-11e5-9c14-827cae601b47.jpg)

![poster-1920x1080-play](https://cloud.githubusercontent.com/assets/12228435/12862495/0f1bfbfa-cc21-11e5-9a62-98f0c9eb3c62.jpg)

![poster-dark-1920x1080-play](https://cloud.githubusercontent.com/assets/12228435/12862498/156c1ddc-cc21-11e5-83e2-ec4ca7b037e9.jpg)

**Comment by brettgaylor** [comment]
I think they need a play button.

**Comment by lovegushwa** [comment]
Final poster images:

https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvc3V0TTktNURSbE0&usp=sharing
