### ISSUE TITLE
Choose an emoji set for Beat 3 website

### ISSUE THREAD

**Issue by michellenebiolo** [MozillaFoundation/encryption_campaign#104]
From @Giorgio-Olivero, regarding the emoji sets to be used/displayed in Cryptoloji:

> a quick recap with the different options regarding the Emoji implementation:
> 
> **Platform/Vendor specific implementation**
> Pros: nothing​ ​special​ ​is required​​. Emoji-compatible platforms will display emoji with their native support.
> Cons: the look&feel of the campaign will be really fragmented on different devices. 
> See attached zip archive with a preview of the horrible things that can happen.
> 
> **Twemoji**
> http://emojipedia.org/twitter/
> P​​rovides https://github.com/twitter/twemoji​ ​- a​ ​simple library/framework​ ​that ​offers standard Unicode emoji support across all platforms.​ ​They also provide CDN support. 
> Pro: a solution like this would allow for a consistent look&feel on every browser/platform. That's actually the main reason why Twitter did​ it​.
> Code licensed under the MIT License
> Graphics licensed under CC-BY 4.0
> 
> **EmojiOne**
> http://emojione.com/
> http://emoji.codes/
> Indipendently run open source project, the graphics are ​ok but not as goo​d​ looking as the version ​provided ​by Twitter.
> Pro: ​they also ​made available a developer framework for proper ​web ​integration https://github.com/Ranks/emojione and CDN support https://cdnjs.com/libraries/emojione
> Code licensed under the MIT License
> Graphics licensed under CC-BY 4.0
> 
> **​Mozilla**
> http://emojipedia.org/mozilla/
> http://blog.emojipedia.org/first-look-emojis-for-firefox-os/
> Open source license, ok look but 'not really' in the emoji zeitgeist
> (hope I'm not making any gaffe here :)
> Cons: No developers' framework and no CDN support. Some characters are really heavily connotated as 'white people'.

We are exploring how different emoji sets work, in terms of visual outcome, on the "Magritte" onboarding and will keep you posted.

@OpenMatt We are hoping to discuss this and reach a decision about this fairly early next week – does that sound feasible?

**Comment by michellenebiolo** [comment]
We have worked on analyzing and comparing the effectiveness of the three emoji sets we shortlisted for Cryptoloji last week. 
You can find [a short recap of our findings at this link](https://drive.google.com/a/todo.to.it/file/d/0B1kZKM2Rzgy_dHVHN01oZngtMkU/view?usp=sharing). 

All in all, **we recommend using the Twitter set**, because:
- it has a wider range of emojis (including letters, which might be useful anytime we want to make encrypted text somewhat readable – see for example the word “Cryptoloji” on the last slide of the recap);
- it generally adheres better to a grid, with even most round emojis fitting in perfect squares; this would work well in the emoji-to-letter animation we suggested in our presentation on Thursday, and would also make for a “cleaner” look, especially with long and dense emoji strings;
- it has more streamlined, less detailed graphic style, with fewer and more vibrant colors.

@OpenMatt Please let us know if there are any other aspects we need to consider to help you make a final decision.

**Comment by OpenMatt** [comment]
@lovegushwa I think you're probably the decider here. can you update?

**Comment by michellenebiolo** [comment]
The Tweemoji set was approved during today's video call, thanks!

**Comment by lovegushwa** [comment]
@michellenebiolo @Giorgio-Olivero please forgive the slow response. We looked closely at the three emoji sets. EmojiOne is probably closest visually to the iconic apple emoji, but also the least visually consistent of the three. Mozilla emoji is interesting but lacking diversity and CDN. 

Let's use Twemoji. It looked quite good in the demo today.
