### ISSUE TITLE
Create risk-assessment document

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#105]
Tech specs from TODO: http://mzl.la/beat3_tech_specs
Concept wireframes: http://mzl.la/beat3_wireframes
Due: eod Feb 5

Next step: @simonwex will produce a risk-assessment document. To share w. TODO, etc.

**Comment by OpenMatt** [comment]
cc @michellenebiolo

**Comment by OpenMatt** [comment]
@simonwex has completed this here: http://mzl.la/beat3_tech_specs

**Comment by OpenMatt** [comment]
Main question from @simonwex is: who is building the API? We assume TODO? @abusedmedia @michellenebiolo is that correct?

**Comment by michellenebiolo** [comment]
Nope, sorry, we need you to provide us with the API to access server-side functionality (as mentioned in our statement of work).

**Comment by OpenMatt** [comment]
@michellenebiolo I discussed w. Giorgio -- we're going to have you guys get back w. an assessment on what would be involved for TODO to build the API instead of us. I will close this one and file a new one.
