### ISSUE TITLE
Updated VO in animatic for Beat 2

### ISSUE THREAD

**Issue by KarinaRipper** [MozillaFoundation/encryption_campaign#108]
Hi @brettgaylor and @OpenMatt, happy Friday!

Wanted to send you the animatic with the updated voice over by the talented Mister Jim Ripley. 
Here is the link: [https://vimeo.com/153425970]
Password: Mozilla

Mister Ripley's read was slower than the scratch VO, so we've slightly extended some spots. The total run time is now 95 seconds and we've adjusted our budget accordingly. 

As you know, animation is a slower process so we haven't included any of the work-in-progress in this animatic. The animation team is hustling along and we're excited to share it with you next week! Looking forward to hearing your thoughts on the new VO. 

Thank you!

Karina

@darrenpasemko

**Comment by OpenMatt** [comment]
sorry for slow reply -- @brettgaylor are you able to update?
