### ISSUE TITLE
Add logo to closing bumper

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#109]
Hi, @rohanporteous and @lovegushwa 

We got a non-negotiable piece of feedback that we need Mozilla's logo on the closing bumper for this video.  I'm sorry to ask but we need to output this tomorrow as an augment to final delivery - and we can do it at same time as #98, where we need a final video compressed for our microsite.

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson 
Finished. You can share this video and poster link directly with partners.

https://drive.google.com/folderview?id=0B2qu3ExKWIlvaXczQ2ZDNWd3akU&usp=sharing

**Comment by HPaulJohnson** [comment]
I think we are good to go. Thanks, @lovegushwa
