### ISSUE TITLE
Develop comms plan 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#11]
press, blogs, internal

**Comment by OpenMatt** [comment]
@HPaulJohnson as per your IM

**Comment by HPaulJohnson** [comment]
cc: @KevZawacki

**Comment by KevZawacki** [comment]
[Encryption comms plan](https://docs.google.com/document/d/1NrwSASCP4W7t_unT7qHy3C1u_li3g5GrI7Lbc9z2FVM/edit) (not static, still developing)

**Comment by OpenMatt** [comment]
Nice! @KevZawacki @HPaulJohnson what's the next step here?

**Comment by KevZawacki** [comment]
@OpenMatt Next step is opening tickets for individual comms deliverables (blog posts, media pitches, etc.) I'll get started now.

**Comment by OpenMatt** [comment]
@KevZawacki nice! now that those tickets are filed, are we ok to close this one? cc @HPaulJohnson

**Comment by KevZawacki** [comment]
@OpenMatt OK by me
