### ISSUE TITLE
Links for Share this now section

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/encryption_campaign#110]
![ofrsggu1](https://cloud.githubusercontent.com/assets/4368149/12918364/ca62a100-cf0c-11e5-990d-3c39f8ac97ad.png)

The 3 icons on "Share this now" section what should the link be? and "Join the conversation" (Medium) what is the link for that?

CC @lovegushwa @HPaulJohnson ?

**Comment by HPaulJohnson** [comment]
the Medium URL is: medium.com/encryption-matters

for the sharing buttons those should be standard links for sharing/posting to FB/Twitter/Email. I believe this is the standard format for those links but you should confirm by looking other sites/places where we have used sharing buttons:

FB: https://www.facebook.com/sharer/sharer.php?u=[URL]
Twitter: https://twitter.com/intent/tweet?url=[URL]&text=[tweet]
Email: mailto: mailto:?&subject=[Subject]&body=[Body]

I think we still need to provide copy for those however and will work on something now. cc/ @KevZawacki

**Comment by alicoding** [comment]
Thanks @HPaulJohnson I will make an update to Medium, twitter and facebook. What is the email suppose to be sent to again?

**Comment by HPaulJohnson** [comment]
RE: Email should just pop-up your email applications with a prepopulated subject line and email body (we'll leave the to: field blank).

**Comment by alicoding** [comment]
@HPaulJohnson so no email address that we want to send to?

**Comment by HPaulJohnson** [comment]
@alicoding - no specific email. the idea is it opens your email app and the sharer can add recipients directly from their contacts, depending on who they want to share it with.

**Comment by alicoding** [comment]
ah! got it. Thank you @HPaulJohnson

**Comment by HPaulJohnson** [comment]
@alicoding - language and links for each of the share buttons is in the attached: 

https://docs.google.com/document/d/1fTHv-bSDMhNOvUITU9Se3yGP-EjjfkiuWl-EobGDdjU/edit

For Facebook, my assumption is that the appropriate tags/metadata will be used to populate preview image on share?

**Comment by alicoding** [comment]
@HPaulJohnson that's a good question about the image. Can we just use the poster/thumbnail for the video for social share here?

**Comment by natalieworth** [comment]
I think the metadata can be optimized/ used for populating the image: https://developers.facebook.com/docs/sharing/webmasters/optimizing Although I'm not sure what we did with the EOY shares

**Comment by alicoding** [comment]
@natalieworth right, but I'm wondering if I can just use the same image we use for the video with Facebook and Twitter here?

**Comment by natalieworth** [comment]
Ohh sorry @alicoding, I'll talk to @lovegushwa. I'm assuming we could do something design-wise for the sharable image. Possibly with the encryption branding or a better image. Will update this afternoon

**Comment by alicoding** [comment]
This is done.
