### ISSUE TITLE
Testing Plan for Video 1 Launch

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#111]
We are going to do a small test initially launching the morning of February 10. The test channels will include 5% of EN snippet promotion with the embedded optin; as well as a test launch to 10% of our email list (~180,000 recipients). What questions are we trying to answer:
- Target: Video be shared at an average target rate of 5% of views on the microsite; 
- Email optin rate of 0.1% from the snippet;  (monitored by @stephaniemcv)  
- < 3% negative sentiment in social as measured in Sprinklr (monitored by @KevZawacki );
- At least average open and CTR based on our email advocacy benchmark; (monitored by @stephaniemcv)  
- Microsite engagement - all audiences (heat map and clicks);
- Constructive / helpful feedback from the "reply to give us feedback" PS (there is no benchmark for this qualitative measure. We will see what we get.).

cc @adamlofting @HPaulJohnson @shaghdoosti @OpenMatt

**Comment by stephaniemcv** [comment]
Numbers calculated from 2015 Advocacy emails.
Average OR: 21.69% Median OR: 14.33%
Average CR: 4.61% Median CR: 2.58%

**Comment by adamlofting** [comment]
Some early data from GA

<img width="1175" alt="screenshot 2016-02-11 15 18 53" src="https://cloud.githubusercontent.com/assets/1901816/12980146/189fa8e6-d0d3-11e5-94f1-de722f35787c.png">
<img width="895" alt="screenshot 2016-02-11 15 19 21" src="https://cloud.githubusercontent.com/assets/1901816/12980147/18a31030-d0d3-11e5-9e77-e923b021d0a1.png">
<img width="1184" alt="screenshot 2016-02-11 15 19 59" src="https://cloud.githubusercontent.com/assets/1901816/12980148/18a4b03e-d0d3-11e5-83f6-a6894fd78ac4.png">
<img width="1188" alt="screenshot 2016-02-11 15 20 18" src="https://cloud.githubusercontent.com/assets/1901816/12980149/18a65ba0-d0d3-11e5-9a47-6015b045327c.png">

It doesn't look like we have event tracking on the social share buttons. We should check/add this.

**Comment by adamlofting** [comment]
In the meantime, I count 42 tweets sharing the video here: https://twitter.com/search?f=tweets&q=mzl.la%2Fencrypt&src=typd

**Comment by KevZawacki** [comment]
Social data pulled from Sprinklr (9:40 a.m. PT on 2/11):

-- 85 conversations across Twitter, Facebook and Instagram

-- 100% of conversations are positive/neutral. Most are automated share language generated from the microsite: 

![screen shot 2016-02-11 at 9 41 13 am](https://cloud.githubusercontent.com/assets/11045250/12984782/385bc4b4-d0a4-11e5-821e-4c0120980d41.png)

A handful are more personal:

![screen shot 2016-02-11 at 9 42 50 am](https://cloud.githubusercontent.com/assets/11045250/12984847/95475a26-d0a4-11e5-9925-bb6cd9d2f14a.png)

Most conversations are coming from the U.S. and Canada:

![screen shot 2016-02-11 at 9 45 57 am](https://cloud.githubusercontent.com/assets/11045250/12984813/6aec897c-d0a4-11e5-92ba-8a959dcadb78.png)

**Comment by stephaniemcv** [comment]
Current Foundation List Size: 1,849,735
https://docs.google.com/a/mozilla.com/spreadsheets/d/19AmYYBfmqlCfk8J7_Cur9m9AuB3hnPrs2-42emFNXg4/edit?usp=sharing
![2016-ec-list-growth](https://cloud.githubusercontent.com/assets/11812272/12986349/a95a5e6c-d0ab-11e5-8c05-aa5742321aa4.jpg)

**Comment by stephaniemcv** [comment]
Email Performance Active Advocates at approx 24 hours: 
Open Rate: 31.18%
Click Rate: 5.41%

Email Performance NOT Active Advocates at approx 24 hours: 
Open Rate: 15.33%
Click Rate: 2.5%

![2016-ec-beat1-test-email-perforance](https://cloud.githubusercontent.com/assets/11812272/12986513/88666ca4-d0ac-11e5-9423-38c04e78d957.jpg)

Report Location: https://docs.google.com/a/mozilla.com/spreadsheets/d/1VTPpE4IbjDx-DX1T5X7k3PF-rEe1EeEDdzcXIXfzN1Y/edit?usp=sharing

**Comment by jgmac1106** [comment]
I find the bounce rate very interesting. Under 70% I wonder what they are
visiting next after the encryption video.

**Comment by adamlofting** [comment]
@jgmac1106 this could be affected depending on how the in-page event tracking has been setup (in GA you can define these as `interaction` or `non-interaction` events). The default is `interaction` events which turn a visit into a `non-bounce`.

**Comment by OpenMatt** [comment]
Closing.
