### ISSUE TITLE
End-of-video modal interrupts while filling out form

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/encryption_campaign#113]
If you're actively filling out the "Join Mozilla" form while the video ends, the modal interrupts what you're doing. 

Solutions could be:
- Not showing modal if changes have been made to the form
- Populating modal elements with values from other form when showing

**Comment by simonwex** [comment]
( https://lit-mountain-52009.herokuapp.com/encrypt/v3 )

**Comment by alanmoo** [comment]
There's no modal in v3 anymore.
