### ISSUE TITLE
Twitter card image is missing

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#115]
![_mozilla_-_twitter_search](https://cloud.githubusercontent.com/assets/9830371/12961324/b588f7c8-cff4-11e5-85ee-a40e06b55725.png)

Also, here is what a twitter card should look like:

![_youbeyou_-_twitter_search](https://cloud.githubusercontent.com/assets/9830371/12961379/0a25761c-cff5-11e5-8a91-2e5950fee851.png)

cc @alanmoo @natalieworth @lovegushwa

**Comment by natalieworth** [comment]
@lovegushwa I can take this on today if that works

**Comment by jbuck** [comment]
Hrm, it looks like it's working on https://cards-dev.twitter.com/validator

**Comment by brettgaylor** [comment]
@jbuck could this be because the URL within the tweet is coming from a URL shortener?

**Comment by jbuck** [comment]
@brettgaylor looks okay to me! https://www.dropbox.com/s/75rqdb3qt3c9vi5/Screenshot%202016-02-10%2016.04.23.png?dl=0

**Comment by alicoding** [comment]
I added the image this morning using Facebook's share image https://twitter.com/hashtag/youbeyou?f=tweets&vertical=default&src=hash this is what I see right now ![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/7mp4l3wr.png)

**Comment by alicoding** [comment]
Even with URL shortener ![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/4gcjxsau.png)

**Comment by natalieworth** [comment]
The 'Summary Card with Large Image' appears to be working but I think it seems to be an issue just on the small card preview with the square thumbnail not loading. I can't load a preview on mobile with the small card preview @alicoding

**Comment by alanmoo** [comment]
I think this was a propagation issue- the original link Andrea sent to me in IRC (https://twitter.com/iainmacl/status/697498205358006274?lang=en) now shows the card working...are there any instances of this still not working?

**Comment by alicoding** [comment]
I can't get the twitter card to appear with the small summary card preview at all. I've been testing with my mobile phone (Nexus), desktop and using Browserstacks with different screen sizes and still getting the large image.

I have come to a conclusion that this is not an issue with the code we have here, but rather a design issue as to what image we want this to be display. We have either the small card or large image card and we need to pick one.

**Comment by alicoding** [comment]
I've reassigned this ticket to @natalieworth to discuss with the team there and let me know if we want to change the image and I will be more than happy to change that.

**Comment by lovegushwa** [comment]
@alicoding @valianttry let's go with the large twitter card.

**Comment by natalieworth** [comment]
Thanks @alicoding @lovegushwa
