### ISSUE TITLE
Privacy Policy MUST be linked in the video modal

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#116]
![mozilla_advocacy](https://cloud.githubusercontent.com/assets/9830371/12961529/d5f10612-cff5-11e5-83d7-e9e26216ca55.png)

Again, it should directly mirror the snippet copy, and UX of the optin checkbox embedded in the snippet.

**Comment by valianttry** [comment]
For reference, here is the staging snippet with precise text and punctuation/capitalization:
http://scottdowne.github.io/eoy-snippets/signup-snippet/

also -- please use the URL linked in the snippet for the URL. NOTE the words "this Privacy Notice" is hotlinked and should also be hotlinked in the modal: https://www.mozilla.org/en-US/privacy/websites/

**Comment by alanmoo** [comment]
Ah, ok. Committed a change to staging already but I'll update to reflect this.

**Comment by valianttry** [comment]
:clap:

**Comment by alanmoo** [comment]
Done.
