### ISSUE TITLE
Final Cut for Beat 2 - Posting and Review

### ISSUE THREAD

**Issue by KarinaRipper** [MozillaFoundation/encryption_campaign#117]
@darrenpasemko New ticket for posting for posting link to Final Cut of Beat 2. Posting will happen later this tonight. Thank you!

**Comment by darrenpasemko** [comment]
Update: Sorry, there has been a delay on my end. but it will be ready by mid day. I need some more time to update all the new work. It's on its way!

**Comment by darrenpasemko** [comment]
@brettgaylor @OpenMatt @KarinaRipper @lovegushwa @valianttry 
Here's the first pass on the animation!
https://vimeo.com/155043161
Password: Mozilla
Talk more soon!
Sorry once again for the delay.

**Comment by darrenpasemko** [comment]
@brettgaylor @lovegushwa @OpenMatt @KarinaRipper @valianttry here's the new edit. I sent it through email, but I thought I would post it officially on Github too.
https://vimeo.com/155043161
Password: Mozilla

**Comment by OpenMatt** [comment]
@brettgaylor status?

**Comment by brettgaylor** [comment]
Shipped!
