### ISSUE TITLE
Check/add GA event tracking for social share buttons

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/encryption_campaign#118]
Follow up from #111

I see data for video and sign-up, but not for share.

Can we check if we're tracking these, and if not, add this in please.

<img width="1188" alt="screenshot 2016-02-11 15 20 18" src="https://cloud.githubusercontent.com/assets/1901816/12980251/85d1d9de-d0d3-11e5-9ed4-0d4318f8bdef.png">

**Comment by alicoding** [comment]
fixed :)

**Comment by adamlofting** [comment]
:+1: :trophy:

**Comment by adamlofting** [comment]
@alicoding did this get pushed live? I'm not seeing any data in GA yet.

**Comment by alicoding** [comment]
I have added it here https://github.com/mozilla/advocacy.mozilla.org/commit/20399122013a988f57d6c8ddeba411f1840bd8b6

Let me check if this is now on prod.

**Comment by alicoding** [comment]
Definitely there on prod @adamlofting

**Comment by OpenMatt** [comment]
@simonwex @alicoding any updates?

**Comment by OpenMatt** [comment]
Andrea Wood: Adam re-opened the github ticket because he's not seeing clicks in GA. Ali replied that he committed the code. i'm not sure of next step.

**Comment by valianttry** [comment]
yes thanks @OpenMatt i read the ticket. Adam is offline and unable to help, but we're launching to several million people today -- hence the P1. I assume the next step is **someone double checks Ali's code since it still seems to be broken according to Adam.**

**Comment by alicoding** [comment]
@simonwex and I are debugging this right now and will report back once we see the data on GA.

**Comment by OpenMatt** [comment]
awesome thanks guys.

**Comment by valianttry** [comment]
whoohoo :clap: thanks for the hustle @alicoding and @simonwex !!

**Comment by alicoding** [comment]
This is now fixed :) @simonwex can probably share the screenshot to verify this since I don't have access to this GA :)

**Comment by simonwex** [comment]
Verified:

![image](https://cloud.githubusercontent.com/assets/25260/13089754/fe397dec-d4a6-11e5-9a74-3ff1673c9a67.png)

**Comment by adamlofting** [comment]
:muscle: :bowtie: :+1: :sunny:
