### ISSUE TITLE
Design owned media assets

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#12]
For:
- [ ] snippet
- [ ] tiles
- [ ] other?

@shaghdoosti has a meeting on Monday with MoCo engagement to confirm these

**Comment by OpenMatt** [comment]
Next steps: @shaghdoosti can you confirm the deliverables needed here after your meeting?

**Comment by shaghdoosti** [comment]
yes - will do.

**Comment by OpenMatt** [comment]
@shaghdoosti any status updates from the meeting? @lovegushwa are the deliverables and next steps clear?

**Comment by lovegushwa** [comment]
@valianttry @HPaulJohnson @OpenMatt 
Shroud we kill issue for beat 1 and focus on #22 
Or will we have access to tiles?

**Comment by HPaulJohnson** [comment]
I think we should focus on #22 and #57 (this should be really simple) for beat 1. We should skip other tiles (as in directory) for now.

**Comment by OpenMatt** [comment]
ok. so @lovegushwa please close this ticket if the real work is happening in those others now.

**Comment by OpenMatt** [comment]
I'm going to close this. @lovegushwa tell me if that's wrong.
