### ISSUE TITLE
Add link to Medium back into footer

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#120]
We need to add the link to Medium "join the conversation" back into the footer of the landing page. This should be done Monday eve or Tuesday morning.

**Comment by alanmoo** [comment]
Where should the link direct users to? https://medium.com/@mozilla ?

**Comment by HPaulJohnson** [comment]
@alanmoo: https://medium.com/encryption-matters

**Comment by alanmoo** [comment]
When do you want it live?

-A

**Comment by HPaulJohnson** [comment]
Let's wait until @KevZawacki posts the initial piece of content their tomorrow. Kevin, an eta of when that might be?

**Comment by KevZawacki** [comment]
@HPaulJohnson @alanmoo Medium blogs will be live at 7:15 a.m. PT
