### ISSUE TITLE
Unable to play video - feedback from Desk.com

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#121]
We have had 4 cases of people saying they cannot get the video on the microsite to play. Some have provided browser and operating system data.

Windows Vista and Firefox
Windows 7and Internet Explorer

**Comment by alanmoo** [comment]
Do these users have adblockers running? Mavis was having trouble because of her blocker...

**Comment by stephaniemcv** [comment]
I will follow up and add that to my initial line of questioning if more pop up.

**Comment by alanmoo** [comment]
Has there been any more follow up on this?

**Comment by OpenMatt** [comment]
@stephaniemcv can you update here when you have a sec?

**Comment by stephaniemcv** [comment]
Closing as I've seen no more complaints in Desk.com
