### ISSUE TITLE
Create Mozilla Advocacy YouTube channel

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#124]
We are giving up on attempting to gain access to existing /mozilla Youtube channel and we need YT hosted video in order to have an embed code available for comms. In particular, we'll need YT embed code to provide to media contacts, PR agency and for Medium publication. 

@KevZawacki will set up the channel.

@lovegushwa and @natalieworth we'll need some quick branding (avatar and cover photo) to match branding and visual design of rest campaign. 

cc/ @simonwex

**Comment by KevZawacki** [comment]
Channel is set up [here](https://www.youtube.com/channel/UCltqjpqVd-IowlC-iLp91eg?feature=hovercard).

I'll send the log in credentials privately.

**Comment by KevZawacki** [comment]
@lovegushwa and @natalieworth, here are the specs for YouTube channel art: https://support.google.com/youtube/answer/2972003?hl=en 

@lovegushwa, are you able to upload the video, too?

**Comment by KevZawacki** [comment]
Done!
