### ISSUE TITLE
Build Beat 2 snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#125]
@lovegushwa @ScottDowne @alicoding @simonwex 

The Firefox product team has raised some concerns about the "disruptiveness" of the current video+embed snippet (see screengrabs and comments below). 

Questions:
- Is it possible to reduce the size of the video window? How hard is that?
- Is it possible to configure a 2nd variant using the existing snippet code that removes the video altogether (replacing it with the usual static Firefox Logo)

We could run these variants concurrently and test response / performance. This will help us make informed decisions about the design and tradeoffs.
![madhav feedback](https://cloud.githubusercontent.com/assets/9830371/13018314/b537ae24-d17d-11e5-92c7-69739518a40e.jpg)

One possible variant could look like this:
![madhav suggestion](https://cloud.githubusercontent.com/assets/9830371/13018313/b519a35c-d17d-11e5-9b97-c2ca88e63a56.jpg)

**Comment by JessicaVondrak** [comment]
Hi team,

It's possible to not include a video.  
![screen shot 2016-02-12 at 12 48 39 pm](https://cloud.githubusercontent.com/assets/17205874/13018547/5a51265c-d187-11e5-899d-99e32a4db2a3.png)

**Comment by valianttry** [comment]
Alternate ideas from @lovegushwa 
- Possible to play the video then replace it with the form so that they are in a linear sequence vs. both presented at the same time.
- Reducing fields: Email + Privacy checkbox
- We want to update you on important issues that protect your privacy. We're giving you a chance to review our Privacy Policy and opt in to receive emails. "We ask you to acknowledge our privacy notice because we believe in helping you make informed choices.."
- How what you're being asked to do relates to the content in the video. 
  Q: How can we build an experience that gets people more excited and engaged in.

**Comment by valianttry** [comment]
@simonwex 

-- Subscribe with required email.... then open a 2nd modal that asks them to provide some additional info and why (name + country)

**Comment by valianttry** [comment]
@OpenMatt can you add this dev work to our Plan ticket (@simonwex asked me to ask you :)

**Comment by OpenMatt** [comment]
@alanmoo @alicoding is this something you might be able to help with this week? Or are we waiting for @ScottDowne to return?

**Comment by alanmoo** [comment]
If this is something that needs to launch next week, I guess it'll be one of us. But I'm not familiar with working on the snippet, are you @alicoding?

**Comment by alicoding** [comment]
I never done it either, but first thing first one of us gotta try setup the
infrastructure to run this snippet service which I've failed to get it
working. I'm going to try again :(

**Comment by JessicaVondrak** [comment]
@alanmoo @alicoding  Have either of you worked with Giorgos?  He may be able help answer any snippet service questions.

@glogiotatidis  Would you be willing to assist here?  Or point us to someone on your team who can help with snippet service questions?  

Thanks!
Jess

**Comment by alicoding** [comment]
I've never work with but have heard Scott mentioned about Giorgos. It will
be really helpful to meet after my second try to setup the snippet service
to see if I can get it running on my machine and after that point I think
it will be easy enough to create or make any changes to the snippet Scott
created.

**Comment by glogiotatidis** [comment]
> I've never work with but have heard Scott mentioned about Giorgos. It will be really helpful to meet after my second try to setup the snippet service to see if I can get it running on my machine and after that point I think it will be easy enough to create or make any changes to the snippet Scott created.

Getting the service to work locally is a good step forward. Please bear in mind that snippet developing and testing is time consuming and more complicated than just simple html pages. I encourage you to build changes upon the current template and add control statements for the different variations.

Also you probably want to build the `legacy` branch locally, since this is the current running service.

You'll find documentation here http://abouthome-snippets-service.readthedocs.org/en/latest/developing.html

**Comment by OpenMatt** [comment]
- Thanks for your help, @glogiotatidis !

**Comment by OpenMatt** [comment]
- Let's use this ticket as the "build" ticket. The design ticket is here: https://github.com/MozillaFoundation/encryption_campaign/issues/140
- Next step: finalize the design choice, so we know what we need to build.

**Comment by OpenMatt** [comment]
@alanmoo can you update status?

**Comment by alanmoo** [comment]
There are a few plans in motion.

1.) no dev work needed for snippet itself, as it will be an existing template with a link to a signup page on the advocacy site (which I'm awaiting design in order to build)

2.) Minor updates to the existing snippet with either the video or signup form, which I can make based on Scott's previous work. However, the timeline on QA may result in this one being better suited for later this week. I believe there was talk about A/B testing to figure out which version works best, is that right @lovegushwa and @vailanttry?

**Comment by alanmoo** [comment]
Er, @valianttry. (GitHub's mobile site is feature incomplete)

**Comment by JessicaVondrak** [comment]
@alanmoo 
Hi Alan -
I can chime in from a template snippet perspective.
for #2)  We already have an existing template with the video.  We can just link the text to the advocacy site.  This should eliminate any additional updates for you.  If we want to test A) Video with linked text B)  Sign-up form only.  We are all set to go!   

Keep me in the loop with timing or any additional questions!
Jess

**Comment by valianttry** [comment]
Just completed a round of feedback from the marketing team. Given the late hour and additional changes requested (plus the QA and dev work remaining) we have run out of time to execute Option 2 in time for beat 2 video launch. (Option 2 was tweaking the embedded optin form). Option 2 variant doesn't need to be tied directly to a campaign, so we will pick it back up and finish it at a later time TBD. 

For now, we're going to focus on executing snippet Option 1 which is embedded video + text link + html modal form.

cc @alanmoo @lovegushwa

**Comment by alanmoo** [comment]
Can we close this or is there more to do?

**Comment by alanmoo** [comment]
@valianttry Can this be closed?
