### ISSUE TITLE
Add animated "encrypt" header

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#126]

**Comment by alanmoo** [comment]
I'm close to recreating it, @lovegushwa @natalieworth.

https://www.dropbox.com/s/9kc9u3uqtq3jr2m/encrypt-animation.mov?dl=0

After the time has elapsed, I'm going to make them snap to the correct letters/pattern. I also need to clean up the start a bit- I'm thinking there's nothing there when it first comes up, and then each one flickers on.

**Comment by natalieworth** [comment]
Thanks @alanmoo ,
There is also a smaller (shortened) version of the after effects file and a gif here if needed:
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0WlpZdWktUFRWTU0&usp=drive_web&ddrp=1#
cc @lovegushwa If you could review when you're back from the long weekend: https://d157rqmxrxj6ey.cloudfront.net/natalieworth/33342/
cc @alicoding (I've updated the after effects file, but I think Alan may have already recreated it ^)

**Comment by alanmoo** [comment]
Yeah, I'm using JS to randomly generate the animation, and after a fixed time it becomes the right letters. Check it out at: https://advocacy-mozilla-org-sta-pr-85.herokuapp.com/encrypt/

I can fine tune some of the numbers- how often something changes, how long it lasts, and the probability of a shape changing as opposed to a character. I'm playing with it a bit more tonight to see if I can get the ending smoothed out before tomorrow, though I'm really happy with it how it is now too. Thoughts, @natalieworth and @lovegushwa?

**Comment by natalieworth** [comment]
Thanks @alanmoo , this is looking good! Is it possible to speed it up to animate within 1-1.5 seconds, or so the 'encrypt' animation is loaded by 1.5 seconds? I think the 'R' in 'encrypt' may have also shifted down a bit. The baseline looks a little lower than the other encrypt characters. And just wondering if a new animation loads randomly on each refresh of the page?

**Comment by lovegushwa** [comment]
@alanmoo yeah this looks great. I agree @natalieworth  We could speed it up to 1.5 seconds.

**Comment by natalieworth** [comment]
@alanmoo @lovegushwa This is awesome. I'm going to close as it's now live :+1:
