### ISSUE TITLE
Identify additional assets for Beat 2 social

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#128]
As we are closing off production this week, are there any additional items that will be needed for social such as screen grabs, alpha channeled artwork, etc?

Let's use this ticket to finalize any other deliverables we're expecting from @darrenpasemko .  cc @KarinaRipper , @lovegushwa

**Comment by brettgaylor** [comment]
just a bump on this @HPaulJohnson - Darren is doing final delivery tomorrow.  Are there other elements we need from him?

**Comment by HPaulJohnson** [comment]
@darrenpasemko is it possible to get the following for use on social media: 

.gifs
- (:06) Crypty with “Encryption” text   (could be cut together with the exploding cat)
- (:38) Exploding cat with “Encryption Power” text 
- (:48-:52) Little character turning into message bubble
- (:56-1:01) Little character turning into + sign

video shorts
- (:16-:40) Starting with “there’s a very good chance…” and ending with exploding cat and “encryption power”
- (:41-:56) Starting with “how do you know if a site is using encryption…” and ending with imessage animation and “...only the person you intended can see them”
- (1:08-1:13) Starting with the “web we love is safer because of encryption” and ending with “Join Mozilla"

stills (would be great if we could have the background and foreground separated if this is simple)
- (:07) 
- (:22)
- (:33)
- (:37)
- (:38)
- (:52)
- (:56)
- (:59)
- (1:05)
- a few stills between (1:08-1:09)

**Comment by darrenpasemko** [comment]
Paul, can you confirm the tech specs for those video shorts? 1920X1080,
23.98 fps, H.264, Unrestricted kbps?
Brett mentioned that Mozilla would handle the GIFS.
Everything else is in order. I'll let you know if I have any questions.
Darren

On Wed, Feb 17, 2016 at 3:39 PM, Paul Johnson notifications@github.com
wrote:

> @darrenpasemko https://github.com/darrenpasemko is it possible to get
> the following for use on social media:
> 
> .gifs
> - (:06) Crypty with “Encryption” text (could be cut together with the
>   exploding cat)
> - (:38) Exploding cat with “Encryption Power” text
> - (:48-:52) Little character turning into message bubble
> - (:56-1:01) Little character turning into + sign
> 
> video shorts
> - (:16-:40) Starting with “there’s a very good chance…” and ending
>   with exploding cat and “encryption power”
> - (:41-:56) Starting with “how do you know if a site is using
>   encryption…” and ending with imessage animation and “...only the person you
>   intended can see them”
> - (1:08-1:13) Starting with the “web we love is safer because of
>   encryption” and ending with “Join Mozilla"
> 
> stills (would be great if we could have the background and foreground
> separated if this is simple)
> - (:07)
> - (:22)
> - (:33)
> - (:37)
> - (:38)
> - (:52)
> - (:56)
> - (:59)
> - (1:05)
> - a few stills between (1:08-1:09)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/128#issuecomment-185460617
> .

## 

Darren Pasemko
Director
4644 S.E. 51st Ave
Portland, Oregon, U.S.A.
97206
(646) 406-1320
www.pasemko.com

**Comment by lovegushwa** [comment]
@darrenpasemko yep those specifications are perfect.

**Comment by darrenpasemko** [comment]
Thanks Jordan!
D

On Wed, Feb 17, 2016 at 5:00 PM, lovegushwa notifications@github.com
wrote:

> @darrenpasemko https://github.com/darrenpasemko yep those
> specifications are perfect.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/128#issuecomment-185485158
> .

## 

Darren Pasemko
Director
4644 S.E. 51st Ave
Portland, Oregon, U.S.A.
97206
(646) 406-1320
www.pasemko.com

**Comment by darrenpasemko** [comment]
@brettgaylor @lovegushwa @OpenMatt @KarinaRipper @valianttry Here's the new edit. I sent it through email, but I thought I would post it officially on Github too.
https://vimeo.com/155043161
Password: Mozilla

**Comment by darrenpasemko** [comment]
Can I just pop everything in a Drop Box folder?

**Comment by brettgaylor** [comment]
Sure, that works!  We also use Google Drive a lot.

**Comment by darrenpasemko** [comment]
@brettgaylor @HPaulJohnson @lovegushwa @KarinaRipper @OpenMatt  So I've shared a Drop Box folder with everyone. It contains the final video, in three different formats from full HD, to a Vimeo ready H.264 file. All the stills requested as psd files, and the video excerpts requested. Thanks. Let me know if anything is missing, or if you have any problems downloading the files. Total Size:3.31 GB.

**Comment by OpenMatt** [comment]
- thanks @darrenpasemko ! 
- what are the next steps here? @brettgaylor @HPaulJohnson can we close this?

**Comment by brettgaylor** [comment]
We have all the image/video assets we need.  Need a few GIFs, which I'm opening a ticket for here
https://github.com/MozillaFoundation/encryption_campaign/issues/169
