### ISSUE TITLE
Share text is too long

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#129]
From Jascha:
Hey Andrea,

Looks like the social shares are tuned wrong (you have to delete text to send). 

![social_shares_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/13088378/db8f48cc-d4a0-11e5-871a-3b82ca1f0eef.png)

**Comment by HPaulJohnson** [comment]
@alicoding not sure where the "via Mozilla" language came from? it's not in the final ticket (#110) copy deck:

https://docs.google.com/document/d/1fTHv-bSDMhNOvUITU9Se3yGP-EjjfkiuWl-EobGDdjU/edit

Quick fix is to remove that copy.

**Comment by HPaulJohnson** [comment]
cc @alanmoo Twitter is specifically what needs fixing. Please use copy from doc.

**Comment by alicoding** [comment]
@HPaulJohnson that was requested in the QA call last week, but let me look into this quickly.

**Comment by alicoding** [comment]
https://github.com/mozilla/advocacy.mozilla.org/pull/88 fixes is up and should be on production shortly.

**Comment by alicoding** [comment]
This is now fixed and it's on production https://github.com/mozilla/advocacy.mozilla.org/pull/88
