### ISSUE TITLE
File contractor agreement for TODO

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#13]
- Giorgio will provide wireframes, pitch, quote. As per meeting w. them Mon Jan 11.

**Comment by OpenMatt** [comment]
@lovegushwa will send them a sample pitch

**Comment by OpenMatt** [comment]
- This one is blocked on Jordan + Giorgio meeting to discuss pitch format.

**Comment by OpenMatt** [comment]
Question from Giorgio:
"During one of the previous calls Matt mentioned that the launch of beat3 could be shifted from the 25th to the 11th. For us that would be too critical. We'd rather keep the original launch deadline. Any update on the scheduling?"

**Comment by OpenMatt** [comment]
Jordan wrote back:

The interactive decryption campaign will launch the week of February 29th.
Also we're very interested in a possible collaboration with Arduino. Can you tell us more about what might be possible during the pitch meeting next week?

Giorgio: yes.

**Comment by lovegushwa** [comment]
@OpenMatt @valianttry 
Reviewed deck of pitch ideas today with TODO.

We decided on a direction, TODO will respond with a quote in a day or two.

**Comment by OpenMatt** [comment]
ok sounds good.

**Comment by OpenMatt** [comment]
this is done! processing paperwork.
