### ISSUE TITLE
Agree on how we measure Active Advocates in each campaign beat

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#130]
This is our North Star KPI so we need a firm agreement on what "actions" count in each beat as a metric for an Active Advocate.

More from @adamlofting : 

```
* What are the actions throughout the campaign that you think count as advocacy?
    We've talked about Share and Pledge as possible actions but we should decide and map these to the beats
```

Once that's decided, we can work out how to count which of the people taking these actions are existing vs new advocates to work out our active advocates KPI for each month.

Then we can record our total in this sheet for Feb and Mar: https://docs.google.com/spreadsheets/d/1HJVAYns-SksMRkUZz5ivqnKd9B-07PT8gsKLKKrwRto/edit#gid=0

**Comment by valianttry** [comment]
My suggested actions to count (to launch this conversation):

### Beat 1 Primary Actions  (Primary content: Video)
- Email audience: Share
- Snippet audience: Opt-in 

### Beat 2 Primary Actions (Primary content: Video)
- Email audience: Share (includes NEW optins from snippet)
- Snippet audience: Opt-in 

### Beat 3 Primary Actions (Cipher exercise: Email only)
- Email audience: Respond to cipher CTA (includes NEW optins from snippet)
- Email audience: Share it 

### Beat 4 Primary Actions (Primary content: Video)
- Email audience: Share (includes NEW optins from snippet)

### Beat 5 Primary Actions (Primary content: Video)
- Email audience: Share (includes NEW optins from snippet)
- "I will stand up for encryption" -type pledge (ask for country as well if possible to fill in data)

Questions:
- "Watch" might be a worthy metric, but I opted for "share" -- definitely something for us to discuss. Let's say someone watches 3/5 videos -- that seems like an active advocate if we look at the sum total of multiple video views -- but if someone only watches the first video that seems like less of a signal they are the engaged sort we need. 
- If our CRM is not yet activated, how will we know if additional people are taking a 2nd action during Beat 2, 3, etc? 
- Also we can't attach the action of "sharing" to a specific individual (right?) -- we can only count the # of shares and calculate a "% of people who click share" as a subset of page views. So how will we be able to know -- for instance -- that the same 10,000 people aren't responsible for most of the actions every beat vs. new optins?

**Comment by valianttry** [comment]
@brettgaylor @shaghdoosti

**Comment by adamlofting** [comment]
> **KPI: ‘Active Advocates’**
> Each month, we measure how many people returned to Mozilla to take further advocacy actions. First time actions are not included in this count.

Helpful test question: "Is this person being an advocate for Mozilla by doing this thing?"

My views:
- 'Watching' makes you 'active', but not an advocate. We should aim for lots of watching, but we should think of it as priming for future advocacy actions. The payoff for this work doesn't show in our KPI until we ask people to be an advocate later.
- Likewise, we want lots of opt-ins, but this isn't advocacy until they take an advocacy action. Think of this work also as priming for future KPI performance.
- For sharing, and lack of CRM during this campaign we're not going to have precise data, but we should be able to get a ballpark figure from Google Analytics and a bit of email data. For example, we can see how many shares came from our existing email list. We can also get a decent anonymous count of unique versus repeat actions in GA over a given time frame. It won't be perfect, but we'll know if we're closer to 5k, 50k or 500k.
- For pledge, we can cross check against new vs old members of the email list and get a more accurate (but not totally precise) count and use that for our Active advocates count.

> Respond to cipher CTA

^ I can't tell from that description if that resembles watching, or something we should count as advocacy. 

Points worth repeating in this context:
- Some data is important, and we should care about it but it doesn't show up directly in our Active Advocates topline KPI - that's part of the design. The impact of a good opt-in campaign will show up in the Active Advocates KPI in the following months if we do well with retention.
  - The KPI doesn't exclude us from caring about other metrics, but it is the north star that all other metrics support.
- Also to note, we're not reporting our KPI per beat, just by month. Data about the performance per beat is just helpful to us for internal learning and evaluation.

**Comment by OpenMatt** [comment]
@valianttry @adamlofting rich discussion. what's the next best step here? Should we sched a 15-minute meeting to finalize and document?

**Comment by valianttry** [comment]
cc @shaghdoosti

**Comment by adamlofting** [comment]
I've booked a call for us to work through Jan and Feb as practical examples of what this KPI looks like.

This document should help guide that call:
https://docs.google.com/spreadsheets/d/1HJVAYns-SksMRkUZz5ivqnKd9B-07PT8gsKLKKrwRto/edit#gid=0

**Comment by valianttry** [comment]
@adamlofting since "share" is going to likely factor large can you also invite @HPaulJohnson ? He's done some numbers crunching ...

**Comment by adamlofting** [comment]
:+1:
