### ISSUE TITLE
Design - add video playlist component to microsite

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#131]
@natalieworth @alanmoo 
Let's add the playlist component to the three landing page versions.

![screen shot 2016-02-16 at 2 03 08 pm](https://cloud.githubusercontent.com/assets/12228435/13092657/18cacb02-d4b6-11e5-895a-01e9761558f3.png)
For use with video 2

 ![screen shot 2016-02-16 at 2 03 18 pm](https://cloud.githubusercontent.com/assets/12228435/13092673/29d9437e-d4b6-11e5-90c5-2bb1ef10b3d5.png)
video 3

![screen shot 2016-02-16 at 2 03 26 pm](https://cloud.githubusercontent.com/assets/12228435/13092676/2d6c6890-d4b6-11e5-956b-42b97f15a38b.png)
video 4? (unsure if we are making this one)

**Comment by natalieworth** [comment]
@alanmoo Also posting the UI and annotations for the dev work here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NkI5c3pQNFlDMDg&usp=drive_web&ddrp=1#

**Comment by lovegushwa** [comment]
see issue #146
