### ISSUE TITLE
Review copy for Firefox Friends email

### ISSUE THREAD

**Issue by kellymj** [MozillaFoundation/encryption_campaign#133]
@KevZawacki, we have drafted [copy](https://docs.google.com/document/d/1ZLM2bDLolSLWi3JkE1HFiCxoA9Rpj5s49FZFg4kgB7w/edit?usp=sharing) for the Firefox Friends audience. Who should review and give it the final approval before we send?

Also, we'll need a graphic. I'm looking for a PNG static of the video with a play button, 768px x 
334px.

(Github noob here. Should I assign this to someone? If so, who? thx!)

**Comment by KevZawacki** [comment]
Thanks, @kellymj. I'll share with @valianttry, who can then ship to policy and legal for review. When do we need approval by?

@valianttry, I've created a fresh doc with the copy [here](https://docs.google.com/a/mozilla.com/document/d/1Gg6zeFwYvRBvA7gtqUoRBuAc5vlRu5aiB-tfUeA0ZhI/edit?usp=sharing), and also updated our approvals spreadsheet.  

Re: the graphic. @lovegushwa and @natalieworth, do we have anything that meets MJ's specs (PNG static of the video with a play button, 768px x 334px)?

**Comment by natalieworth** [comment]
@KevZawacki I've exported png's for the file specs above of the beat 1 video. One is @2x if needed for retina:
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0VnFIYnF4YWxVaGs&usp=drive_web&ddrp=1#
Let me know if these are good or if I can help out with anymore images, thanks

**Comment by KevZawacki** [comment]
@natalieworth rocks! :+1: 

@kellymj, do these do the trick? Also, still waiting on copy approval.

**Comment by KevZawacki** [comment]
@kellymj A couple more questions from policy:

How large is the Firefox and Friends audience?
When do we need final approval by?

Thanks!

**Comment by HPaulJohnson** [comment]
@KevZawacki anything more than needs to be done with this one or can we close?

**Comment by KevZawacki** [comment]
@HPaulJohnson Still awaiting approval -- I messaged @valianttry / @shaghdoosti earlier today

**Comment by KevZawacki** [comment]
Hi @kellymj, policy and legal have finished reviewing / making edits. You can find the final version here: https://goo.gl/oYH13Z

I've also pinged Jess O. to let her know. Thanks for your patience!
