### ISSUE TITLE
Image of Video for Beat 1 Kicker email

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#134]
@lovegushwa or @natalieworth 
I need a 600x300 image of the video with the play button. Can be same as the starting picture on the landing pages.

Email is scheduled to send on Friday 2/19. If possible, can I get it by tomorrow for the review group?

**Comment by natalieworth** [comment]
Hey @stephaniemcv , I've exported 2 images for this (one is @2x or 144dpi for retina if needed and the other at 72dpi). Let me know if this works for the email template you're setting up:
<img width="600" alt="landing-page-video-600x300 2x" src="https://cloud.githubusercontent.com/assets/14876567/13118070/60070f5c-d557-11e5-9f77-77b772b5a78c.png">
Link to the files are here:
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NEoxNmcwektLUUU&usp=drive_web&ddrp=1#

**Comment by stephaniemcv** [comment]
The .png will work! Thank you!

**Comment by natalieworth** [comment]
@stephaniemcv I'm going to close this, but feel free to reopen if you need anything additional/ changed
