### ISSUE TITLE
Add new agent to Desk.com

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#135]
@adamlofting 
Can we please add Maryam as an agent. Desk.com blew up again with cases for Encryption. 

Also, it looks like some of the agents haven't logged in a long time. Can we maybe slot other people in for them?

**Comment by adamlofting** [comment]
Maryam has been added :+1: 

We're using Flex Agents which means we can add as many accounts as we need, and are only billed based on the numbers of hours they are logged in, so it's fine to have dormant accounts with this setup.

FWIW, you have admin permissions to add new people too, so if you hear anyone else who needs access feel free.
