### ISSUE TITLE
Design - Beat 2 social assets

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#138]

**Comment by HPaulJohnson** [comment]
@KevZawacki here is a (currently blank) doc to start hacking on copy for beat 2 social: 

https://docs.google.com/a/mozilla.com/document/d/1Nrm7-Cbodhky9x-O050BxaHo66_8mtE0h6VA-QAUSiw/edit?usp=sharing

**Comment by KevZawacki** [comment]
Dropped in initial ideas. Maura and Liz have access, too.

**Comment by lovegushwa** [comment]
**gif specifications to test**

Twitter: 1024 x 512 12fps  /  512 x 256  24fps
Facebook: 1200 x 630 12fps / 600 x 315 24fps

**Comment by natalieworth** [comment]
Twitter image assets: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0TmFfcmRFcGRnbjg&usp=drive_web&ddrp=1#
Facebook image assets: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0S25LM183RV9BQnM&usp=drive_web&ddrp=1#
Just working on uploading the gif's this morning and will post here. Thanks
cc @HPaulJohnson @lovegushwa

**Comment by natalieworth** [comment]
@HPaulJohnson @lovegushwa Exported gifs are here (some are lower res due to the looping, so we may need to test the quality on facebook/ twitter before posting to make sure it's not too low):
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bkI0M04zSmlaMzg&usp=drive_web&ddrp=1#
I can also export different resolutions if needed

**Comment by HPaulJohnson** [comment]
Thanks, @natalieworth, these look awesome. I'm going to finalize the copy in the a.m. and send these along for approval. 

I think the only outstanding item is the shorter video clips. Was anyone able to get those off Darren's dropbox? @lovegushwa

**Comment by brettgaylor** [comment]
(+1) (+1) (+1)

@natalieworth is the https gif meant to loop? Doesnt for me.

**Comment by brettgaylor** [comment]
@HPaulJohnson I was able to open that dropbox - did you have trouble?  I shared the folder with you in case you didn't have before.

**Comment by natalieworth** [comment]
@HPaulJohnson @brettgaylor @lovegushwa I can export the short videos. I believe they needed to include some sort of Mozilla branding too, right?
Yes, @brettgaylor! Https should loop, I'll update it, thanks

**Comment by HPaulJohnson** [comment]
@brettgaylor - I don't have dropbox premium so wouldn't let me download without paying. 

@natalieworth if you could export and add some branding that would be awesome.

**Comment by brettgaylor** [comment]
Yeah I think they could use some branding. They end quite abruptly. Happy
to help with this today!

**Comment by natalieworth** [comment]
That would be awesome @brettgaylor , I'm just working on fixing that one gif but can connect after about the short videos if that works

**Comment by natalieworth** [comment]
Just double checked the gifs and they are all good to go (but we'll still need to test on facebook/ twitter if possible). All should be looping, with only 2 in a continuous looping pattern (back and forth). Images should be good to go now too for both facebook and twitter. Everything can be found in the beat 2 folder:
https://docs.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0MUNvNW45a3h0TWc&usp=drive_web
cc @HPaulJohnson

**Comment by brettgaylor** [comment]
All Facebook gifs here:
https://giphy.com/channel/ynjldhrazxrozxj3b3jrcy5jyq/

**Comment by HPaulJohnson** [comment]
@brettgaylor link on giphy says this channel page is private. can you open it up?

**Comment by brettgaylor** [comment]
try now?

**Comment by HPaulJohnson** [comment]
yep, works. thx.

**Comment by natalieworth** [comment]
@HPaulJohnson I have uploaded the updated social graphics for facebook/twitter (native share). I'm just going to connect with Jordan for the external mozilla/ url branded one's, but will post here asap:
Facebook (native): https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0ZnA3bHdFSnBCcXM&usp=drive_web&ddrp=1#
Twitter (native): https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bkwzLUtueWRLNzQ&usp=drive_web&ddrp=1#

**Comment by natalieworth** [comment]
@HPaulJohnson Closing this, but reopen if you need changes to any of the Beat 2 social assets.
