### ISSUE TITLE
Design - Beat 2 posters

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#139]

**Comment by natalieworth** [comment]
Beat 2 posters (edited dark and regular version) can be found here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0ZmFCdmVwLU1PaUU&usp=drive_web&ddrp=1#

**Comment by natalieworth** [comment]
Hey @brettgaylor do you think this image would be stronger for the static video 2:
<img width="960" alt="crypty" src="https://cloud.githubusercontent.com/assets/14876567/13161824/1a06c818-d655-11e5-8afd-57bf1292c9bf.png">
I'm good with either, or I can try and source another one from the video

**Comment by lovegushwa** [comment]
@natalieworth yeah this is the right image.

**Comment by lovegushwa** [comment]
@natalieworth @brettgaylor we need to consider how a play button will effect this image.
We might need to create something with crypty that's asymmetrical

**Comment by natalieworth** [comment]
Ah yes that's a good point @lovegushwa I'll experiment with this one

**Comment by natalieworth** [comment]
@lovegushwa quick update on how this could look with the current crop of the static image. I'll test out an asymmetrical version to see if that could work
<img width="932" alt="screen shot 2016-02-18 at 4 37 49 pm" src="https://cloud.githubusercontent.com/assets/14876567/13163002/0dcce6d2-d65e-11e5-8240-d82d7aa0c939.png">

**Comment by brettgaylor** [comment]
Where is the language for the website written and approved?  We might want to remove “throughout history” since we made those edits to the video.

This is looking great!

**Comment by natalieworth** [comment]
@brettgaylor Yeah, good idea to update the language. The link for the doc I'm using for language is here if you want to check it out: https://docs.google.com/document/d/1rZnC_4uIv7fVlps_RwTIcDR4ohHgIxN6vt_eLMEWcwo/edit I just flagged your comment on there too for review

**Comment by natalieworth** [comment]
Asymmetrical options:
Medium Crypty:
<img width="944" alt="screen shot 2016-02-18 at 4 39 52 pm" src="https://cloud.githubusercontent.com/assets/14876567/13163596/5051533a-d663-11e5-817e-84c045908d73.png">

Peeking Crypty:
<img width="961" alt="screen shot 2016-02-18 at 4 43 52 pm" src="https://cloud.githubusercontent.com/assets/14876567/13163601/563f3938-d663-11e5-8efc-31bd58b585f9.png">

**Comment by brettgaylor** [comment]
I like asymetrical!  She looks more friendly.

**Comment by natalieworth** [comment]
Put these on redpen if anyone needs to comment directly: https://redpen.io/p/rbb08fa5c283b3f60d

**Comment by natalieworth** [comment]
@lovegushwa Tried experimenting with colours sampled from the animation, or keeping the black background, but trying to get it less muddy looking:
<img width="604" alt="screen shot 2016-02-19 at 11 40 34 am" src="https://cloud.githubusercontent.com/assets/14876567/13187209/b8fc3e72-d6fe-11e5-9cb3-578b8b8ce3ca.png">
<img width="605" alt="screen shot 2016-02-19 at 11 40 24 am" src="https://cloud.githubusercontent.com/assets/14876567/13187213/bbb2fde0-d6fe-11e5-8183-b0b158d48425.png">
<img width="612" alt="screen shot 2016-02-19 at 11 49 10 am" src="https://cloud.githubusercontent.com/assets/14876567/13187225/d18b1d28-d6fe-11e5-9bb6-56da4eae2c2e.png">

**Comment by lovegushwa** [comment]
@natalieworth the last version (directly above this comment) looks good!

**Comment by natalieworth** [comment]
@alanmoo updated poster 2 jpeg is here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0MGtyT0E1c2p5d2M/view

**Comment by alanmoo** [comment]
👍

**Comment by natalieworth** [comment]
@alanmoo Forgot to update the thumbnail for this too! Sorry! New thumbnail for beat 2 is in this file: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0OTA0eE00cWNJMEE/view
Other thumbnails can still be found here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bk50N0Zab0RLbkE&usp=drive_web&ddrp=1#

**Comment by natalieworth** [comment]
This is updated with final version on encryption site.
