### ISSUE TITLE
Design - Beat 2 snippet

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#140]

**Comment by lovegushwa** [comment]
@valianttry checkout the redpen here:
https://redpen.io/hp282243217e57f1fb

Please confirm:
- the language for option 1 and 1B
- if we want to borrow the order and language from our advocacy.mozilla.org/encrypt signup form
- the language for 2 and 2B
- your preference for option 2 or 2B

**Comment by valianttry** [comment]
My instinct is:
- Option 1 is too hard to build in the short timeline (r-)
- Option 1B is totally do-able since the modal build is on us and there's no snippet dev needed (r+)
- Option 2 + Option 2B we should ask the snippet team and Firefox UX team to weigh in and R+ whichever one they like most. Outstanding questions:
  -- We lose country data if we opt to omit it, which has long-term implications for relationship building. Worth discussion.
  -- Is 2 or 2b easier to build? Worth checking with dev to see if there's much more effort with 1 vs. the other variant
- Options 2c and 2d seem beyond scope right now (r-)

**Comment by lovegushwa** [comment]
@valianttry I will post redirect UX/UI for Option 1 tomorrow, but these should be good to show to MOCO folks today or early tomorrow, no need to include our form design.

Option 1
<img width="1482" alt="screen shot 2016-02-18 at 4 10 40 pm" src="https://cloud.githubusercontent.com/assets/12228435/13162576/8dc29e12-d65a-11e5-9500-40c04d4df02f.png">

Option 2
<img width="1251" alt="screen shot 2016-02-18 at 3 46 41 pm" src="https://cloud.githubusercontent.com/assets/12228435/13162614/bcb2db56-d65a-11e5-9a40-c687cb9e7c00.png">

Option 2B
<img width="1245" alt="screen shot 2016-02-18 at 3 47 02 pm" src="https://cloud.githubusercontent.com/assets/12228435/13162583/9b39f4c8-d65a-11e5-811d-f4ad2692525d.png">

**Comment by lovegushwa** [comment]
@valianttry final redpen: https://redpen.io/p/ur7d2d8000796b0937

**Comment by OpenMatt** [comment]
@lovegushwa @valianttry please update here once you've made a final design decision.

**Comment by valianttry** [comment]
Negotiating language with Marketing team here:
https://docs.google.com/document/d/1f8aD_1ALc4UCuycVLqVeRSUMW_mmL9zSbvXoE13wKXY/edit

Final forthcoming. @lovegushwa we should chat with @alanmoo about efforts for each of the above variants today -- when's good?

**Comment by valianttry** [comment]
FYI @alanmoo here is snippets documentation: https://wiki.mozilla.org/Websites/Snippets

**Comment by alanmoo** [comment]
Thanks!

**Comment by lovegushwa** [comment]
@valianttry check out the final snippet design. If these are good to go i'll move them over to the build ticket.

Option 1
<img width="1273" alt="screen shot 2016-02-22 at 1 17 10 pm" src="https://cloud.githubusercontent.com/assets/12228435/13233111/fd44ffdc-d966-11e5-8f7c-ec83ecea20c4.png">

Option 2A
<img width="1233" alt="screen shot 2016-02-22 at 12 42 43 pm" src="https://cloud.githubusercontent.com/assets/12228435/13233128/14fd532c-d967-11e5-854d-7052c080b246.png">

Mouse over notice on why we collect your email, name and country:
Will work like this when you mouse over "information": http://www.scientificpsychic.com/etc/css-mouseover.html

<img width="1236" alt="screen shot 2016-02-22 at 1 32 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/13233509/c8791f16-d968-11e5-8322-3d3e1ac88763.png">

Option 2B
<img width="1234" alt="screen shot 2016-02-22 at 1 07 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/13233203/7b3a3b14-d967-11e5-8181-c2d9337a4e1c.png">

**Comment by lovegushwa** [comment]
We will also need to include after click "submit" to "expect a confirmation email"
... re @ScottDowne beat 1 snippet design.

**Comment by valianttry** [comment]
I sent this to the Marketing Team for final review. Their feedback is due tomorrow a.m.

**Comment by valianttry** [comment]
From Legal:
- This language is officially approved from the legal team

They also had some really good feedback unrelated to legal stuff:
- Can we add a little "envelope" icon somewhere that signals this is intended as an email optin exercise?
- We need to make certain the "X" to opt out of this snippet is included in the design UX;
- We can't actually link to the privacy notice in the popup, so when we say "link right here" it isn't clickable -- so we should clarify the language, I made a slight tweak in the Google Doc: https://docs.google.com/document/d/1f8aD_1ALc4UCuycVLqVeRSUMW_mmL9zSbvXoE13wKXY/edit

**Comment by lovegushwa** [comment]
@valianttry @alanmoo final snippet and signup form designs here. If these are good to go lets move to a build ticket!

Option 1
<img width="1274" alt="screen shot 2016-02-22 at 6 03 32 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239426/ee6c33cc-d98e-11e5-9390-11f7ee6356fa.png">

Redirect form
<img width="1192" alt="screen shot 2016-02-22 at 6 24 53 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239770/ad5cad5a-d991-11e5-96c0-df4088dd3151.png">

<img width="1198" alt="screen shot 2016-02-22 at 6 24 39 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239771/b31ddab6-d991-11e5-8ae1-f761b0f9ab3e.png">

Option 2A
<img width="1232" alt="screen shot 2016-02-22 at 6 07 30 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239467/49d3dd78-d98f-11e5-9e45-7d95e0979fc9.png">

Mouse over notice
<img width="1233" alt="screen shot 2016-02-22 at 6 07 44 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239469/59139c60-d98f-11e5-817e-f0b8a9e19bbc.png">

Option 2B
<img width="1234" alt="screen shot 2016-02-22 at 6 04 13 pm" src="https://cloud.githubusercontent.com/assets/12228435/13239470/63ab79a4-d98f-11e5-9dd0-88efbd17646a.png">

**Comment by lovegushwa** [comment]
Final deliverables for option 1 here #173 
Option 2 is on pause.
