### ISSUE TITLE
Social strategy for Beat 4

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#142]

**Comment by HPaulJohnson** [comment]
We've been working on ideas in ticket #143 

Plan for next phase of social is now being tracked in this doc: 
https://docs.google.com/document/d/1TQwKVN_A-KwCNVevD_IBIUET4q_r87qxm0SZfHdLV5c/edit

Working on a set of 5 ideas for this phase to be used across FB, Tiwtter and paid.

**Comment by HPaulJohnson** [comment]
Duplicate of #144
