### ISSUE TITLE
Design - Benchmark social for Beat 4

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#143]

**Comment by HPaulJohnson** [comment]
@sabrinang did some awesome work on this here: https://docs.google.com/presentation/d/16Ui3J3OaT71qj_uH62EgyI3rguSPyp3oVDlb4Cz-yYo/edit#slide=id.g11c0759461_1_86

not sure if we can close and use #144 to track progress?
