### ISSUE TITLE
Design - Beat 4 social assets

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#144]

**Comment by lovegushwa** [comment]
@OpenMatt @HPaulJohnson 
Spoke with Paul about this yesterday. Were going to try several different approaches here, could be a great place to git some additional design firepower ( @sabrinang  ?)

Direction 1: (advocacy info graphics) I think @KevZawacki may be helping research this.
Direction 2: Humor / meme, the focus here is creating something thats highly shareable first.
Direction 3: ??

We need to articulate these three directions better and benchmark by next Tuesday.

**Comment by HPaulJohnson** [comment]
Meeting on 3/2 to discuss initial list of ideas, here: https://docs.google.com/a/mozilla.com/document/d/1TQwKVN_A-KwCNVevD_IBIUET4q_r87qxm0SZfHdLV5c/edit?usp=sharing

**Comment by HPaulJohnson** [comment]
Honed initial brainstormed list of ideas into a set of 5 that we are now building out. These 5 assets will be used across FB, Twitter and paid channels. 

Progress now being tracked in this doc:
https://docs.google.com/document/d/1TQwKVN_A-KwCNVevD_IBIUET4q_r87qxm0SZfHdLV5c/edit

**Comment by HPaulJohnson** [comment]
In addition to the social concepts being built in the doc above, @KevZawacki drafted a copy to accompany any social embeds of Video 3 on Wednesday. These have been sent separately for policy review to expedite. 

https://docs.google.com/document/d/1jukxu4ixu1atrDrwAho9RUVnZDfyagkMgpk8kCVpfzY/edit

**Comment by brettgaylor** [comment]
What do you all think of including a few quote cards from the video to use
in social?

**Comment by HPaulJohnson** [comment]
@brettgaylor /@ birthdayboy - I like it. Some of the ideas we are building now use quotes, but not pulled from video. 

@lovegushwa - this would be pretty easy to do, right. could leverage some of the cool visual assets you are creating for the video too? if you have something quick/handy add it to the doc above so we can get it through the approval ringer quickly.

**Comment by brettgaylor** [comment]
Aj+ also has good benchmarks here. Check out what they do during
presidential debates.

Nytimes also good with this.

**Comment by HPaulJohnson** [comment]
Yea, would also love to talk to AJ+ sometime how they measure ongoing engagement, impact, etc within the social platforms themselves (beyond the basic, views/likes/shares). Also, checkout some of the cool benchmarking work @sabrinang did in #143

**Comment by brettgaylor** [comment]
@sabrinang that deck is :fire: !!!  So inspiring.

**Comment by brettgaylor** [comment]
This is an example of the quote benchmark I was referencing:
https://twitter.com/ajplus/status/706650705281429504

**Comment by HPaulJohnson** [comment]
@KevZawacki see this folder for the social optimized version of the video for use in our initial posts for Video 3 (tomorrow): 

https://drive.google.com/file/d/0B2qu3ExKWIlvTy1wbXdKOWxONUE/view?usp=sharing

**Comment by lovegushwa** [comment]
@HPaulJohnson @KevZawacki  CC @sabrinang 
We need a review / perhaps some copy tweaks to the historical figure social share:
https://redpen.io/ae7b4dbdfd4337a1e2

Some high level feedback from todays design critique:
- Paul Revere quote, difficult to understand, I think we need to change this one.
- Ben Franklin quote, American centric  (this might be ok but Laura had a hard time with it.)
- We should AB test character vs. silhouette (my money is on the character.) 

Sabrina is working on fixing some issues with the backgrounds, illustration colors and legibility of the type. She can re-post tomorrow, let her know what to do about Paul Revere (change the quote, use a different character.)

**Comment by HPaulJohnson** [comment]
@lovegushwa @sabrinang left some quick comments in the redpen. 

Agree we should ditch Paul Revere as it's not a clear enough connection to our campaign. 

I like Ben Franklin character and Snowden silhouette. Not totally apples to apples but we could try each and see what works better. We can also do a simple test with Franklin of Silhouette vs. Character.

I think we should prob run these by rest of team and Policy before going too much further. @KevZawacki can you work with Sara to review? Snowden in particular might be sensitive though I think we should try it for sure.

**Comment by KevZawacki** [comment]
@lovegushwa These are great -- very exciting. Left a handful of comments in the RedPen.

@HPaulJohnson Will send this content to Sara now. Will report back with policy/legal's thoughts.

**Comment by HPaulJohnson** [comment]
reviewed feedback with @sabrinang today and she will finish up 2 concepts this week and we'll use on an ongoing basis to continue promoting microsite/content (both concepts are fairly evergreen).

**Comment by HPaulJohnson** [comment]
this work will continue in #212 and beyond as we develop a plan for ongoing promotion of this content after campaign is over in various social channels.
