### ISSUE TITLE
Build - Beat 2 snippet

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#145]

**Comment by OpenMatt** [comment]
- This is about implementing design changes to the snippet, as per design ticket here: https://github.com/MozillaFoundation/encryption_campaign/issues/140
- Currently blocked on making a final decision about which of those design choices we will implement
- @lovegushwa @alanmoo and @valianttry are meeting on this today to work out next steps

**Comment by OpenMatt** [comment]
Looks like this is actually a dupe of https://github.com/MozillaFoundation/encryption_campaign/issues/125 -- closing and will keep working there.
