### ISSUE TITLE
Add video playlist component to landing pages

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#146]
Design and dev implementation of the microsite carousel (for archiving the episode content).

**Comment by natalieworth** [comment]
@alanmoo Here is the link to the .ai file with the dev annotations. Just ping me if you need me to update or export anything additional. I'm just working on editing and exporting a final static image for the Beat 2 video. Will post here when it's finalized. Thanks!
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NkI5c3pQNFlDMDg&usp=drive_web&ddrp=1#

**Comment by lovegushwa** [comment]
@alanmoo for your reference: 

v1 landing
![screen shot 2016-02-18 at 1 47 41 pm](https://cloud.githubusercontent.com/assets/12228435/13159481/ee6fce7e-d646-11e5-810e-8c9dd7e4963c.png)

v2 landing + all states
![screen shot 2016-02-18 at 1 53 31 pm](https://cloud.githubusercontent.com/assets/12228435/13159522/186df1f6-d647-11e5-90d1-d07abd79b5ce.png)

![screen shot 2016-02-18 at 1 48 20 pm](https://cloud.githubusercontent.com/assets/12228435/13159416/8bf3abe4-d646-11e5-9e4b-4215c862da0e.png)

![screen shot 2016-02-18 at 1 48 31 pm](https://cloud.githubusercontent.com/assets/12228435/13159417/920373fc-d646-11e5-99d4-081b93aee7f9.png)

![screen shot 2016-02-18 at 1 48 44 pm](https://cloud.githubusercontent.com/assets/12228435/13159423/9e568892-d646-11e5-8078-6cbddcfdc399.png)

![screen shot 2016-02-18 at 1 48 54 pm](https://cloud.githubusercontent.com/assets/12228435/13159428/a5f0f2f4-d646-11e5-96cc-69b0271df2a4.png)

![screen shot 2016-02-18 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/12228435/13159432/abec4988-d646-11e5-8841-e8a5a9a8d88e.png)

**Comment by lovegushwa** [comment]
@natalieworth here is the checklist of things Alan will need:
- [x] Video 2 poster image
- [x] Video 1 and 2 thumbnail @2x
- [x] Coming soon pattern thumbnail @2x (it's currently kinda bright, maybe we can knock it back a little)

(something darker like this ... this might be to dark but you get the idea)
![screen shot 2016-02-18 at 1 57 36 pm](https://cloud.githubusercontent.com/assets/12228435/13159617/9ff231dc-d647-11e5-804b-895e5caff9e2.png)

**Comment by lovegushwa** [comment]
@alanmoo we should keep the episode description text for all landing page version, not just in v1 as shown above.

**Comment by lovegushwa** [comment]
if you need to see the old playlist component wireframes they are here: #131

**Comment by natalieworth** [comment]
@alanmoo @lovegushwa Exported deliverables for this are here:
- Darker version of video 2 poster image: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0dlU5alZuSXN5LVU/view
- Regular version of video 2 poster image: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0cGFPMHFjQndiN0E/view
- Video 1 thumbnail @2x: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0anFDUTA1ckI2eG8/view
- Video 2 thumbnail @2x: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0U3hpUWNGM0hrTWc/view
- Coming soon thumbnail @2x:  https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0WWN5X2EtWkZqNzA/view (darkened this version too)

**Comment by OpenMatt** [comment]
@alanmoo is working on this now, as per today's stand-up mtg.

**Comment by alanmoo** [comment]
PR has been submitted sans the actual video information- where can I get the video/final copy?

A deployment should be generated and linked to from https://github.com/mozilla/advocacy.mozilla.org/pull/95 in the morning.

**Comment by alanmoo** [comment]
https://advocacy-mozilla-org-sta-pr-95.herokuapp.com/encrypt/

**Comment by alanmoo** [comment]
QA in #171

**Comment by alanmoo** [comment]
I've added url params https://advocacy-mozilla-org-sta-pr-95.herokuapp.com/encrypt/?video=1 or https://advocacy-mozilla-org-sta-pr-95.herokuapp.com/encrypt/?video=2 for direct linking to videos

**Comment by alanmoo** [comment]
Where can I find the text copy for the description of the beat 2 video? @valianttry
