### ISSUE TITLE
Update beat 2 landing page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#147]

**Comment by OpenMatt** [comment]
@alanmoo any status update on this one?

**Comment by alanmoo** [comment]
AFAIK this is effectively the same as adding the playlist, just making the site land on the Beat 2 video/details. Is that correct, @lovegushwa?

**Comment by brettgaylor** [comment]
@alanmoo here's two tickets
https://github.com/MozillaFoundation/encryption_campaign/issues/171
https://github.com/MozillaFoundation/encryption_campaign/issues/172

**Comment by alanmoo** [comment]
Dupe of #146.
