### ISSUE TITLE
Get signed contractor agreement from Darren Pasemko

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#15]
- need signoff on Darren's creative brief to start contracting proposal
- pitch/treatment https://docs.google.com/document/d/1AJkQTko64o6Cz5g1HXDCaY-vuh5ComkSGKeaemqh7Cg/edit?ts=569349a7

**Comment by OpenMatt** [comment]
## Next steps

Needed from Darren: a quote for beat 2.

**Comment by OpenMatt** [comment]
Darren is working to get this back to us

**Comment by OpenMatt** [comment]
Most of Darren's work will focus on Beat 2 -- but we may incorporate some early versions in Beat 1 as well.

**Comment by OpenMatt** [comment]
We now have Darren's proposal -- this is now blocked on @brettgaylor to approve the general scope / ballpark quote. Once I get greenlight from Brett I will file paperwork for Contractor Agreement.

**Comment by OpenMatt** [comment]
@brettgaylor let me know when we have green light to issue Contractor Agreement

**Comment by OpenMatt** [comment]
Brett says go ahead

**Comment by OpenMatt** [comment]
bugzilla ticket filed, pending review from Pamela https://bugzilla.mozilla.org/show_bug.cgi?id=1240920

**Comment by KarinaRipper** [comment]
Hi Matt - Nice to meet you :) I'm producing for Darren on Beat 2 and wanted to check in on the status of the contract agreement. Any news on when it will be ready? Thanks! @OpenMatt

**Comment by OpenMatt** [comment]
Hi @KarinaRipper -- here's the contractor agreement signed on our side. can you have Darren sign, then post the signed version here?

**Comment by KarinaRipper** [comment]
Thanks @OpenMatt Darren and I have it and are reviewing now :)

**Comment by OpenMatt** [comment]
@KarinaRipper can you email me back a signed copy?

**Comment by darrenpasemko** [comment]
I'll have this signed and returned tomorrow. Sorry, I was concentrating on last minute revisions today.
