### ISSUE TITLE
Tableau data missing - help?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#150]
Hey @adamlofting -- 

I've been chatting with Jessica Vondrak on snippets team about data coming from the video snippets. She's provided a few spreadsheets of data including comparison data from other videos on the snippet. I've compiled the data here:
https://docs.google.com/spreadsheets/d/1tPLH1AfHpbRRuCX8WcR3Y16qNDpBwCyvHmGt0S6NKrI/edit#gid=0

It looks like perhaps Scott didn't include all the metrics tracking in his code -- but can you investigate? It would be good to make sure this is all working well before our 2nd video launch Wed 2/24. We have new snippet designs that are less disruptive and likely already have the metrics coding in the template, but worth double checking all is well.
#140

**Comment by adamlofting** [comment]
Sure, I can help check. (Noting that I've not actually instrumented any in-snippet tracking before :bowtie: )

@valianttry which missing data are you looking for? the `watched 1/4` and `watched 3/4` of the video? Or the `sign-ups`? 

@ScottDowne can you point me at the code for this?

**Comment by OpenMatt** [comment]
@ScottDowne is on PTO. Not sure if maybe @alicoding or @alanmoo can help.

**Comment by alicoding** [comment]
The only info I have right now is https://github.com/ScottDowne/snippets/blob/signup-snippet/campaigns/signup-snippet/snippet.html

**Comment by brettgaylor** [comment]
Those events were custom made by scott, I believe.  We didn’t ask him to track 1/4 or 3/4 plays - just started, 1/2 and full.

**Comment by adamlofting** [comment]
Thanks @alicoding - that helps.

@brettgaylor that makes sense to me. I can't imagine we'd make any campaign adjustments based on the 1/4 or 3/4 play stats so don't think we're missing anything important here.

The `CTR` value is missing in that spreadsheet, but it's just a calculation using the other data that _is_ there so doesn't need events tracking (I'd add it but the sheet is locked). It's ~1.5%.

Looking at the code shared by @alicoding this does also send [custom events for the sign-ups](https://github.com/ScottDowne/snippets/blob/signup-snippet/campaigns/signup-snippet/snippet.html#L1463), but maybe these were missed in the spreadsheet? 

@valianttry - can you confirm which metrics you were looking for in this ticket please?
