### ISSUE TITLE
Basket Errors - Beat 1 Kicker Emails On Hold

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#151]
From Jess:
Several errors happened in the past 24 hours. It's been requested that we hold off sending emails at this time until the scope of the problem is understood. (Whenever we send an email, it increases the traffic of Basket for people who visit the email preference center. We need to minimize traffic to Basket until we know what's up.)

**Comment by OpenMatt** [comment]
- Discussed in stand-up today. We are in holding pattern -- waiting for MoCo update on timelines.

**Comment by OpenMatt** [comment]
@stephaniemcv any updates on this one?

**Comment by stephaniemcv** [comment]
They found the issue and greenlighted us to send. So the Kicker emails went
out Friday afternoon.
