### ISSUE TITLE
Beat 1 Kicker Email QA Feedback

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#152]
![for__review_-_active_advoactes__can_you_spread_the_word__-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/13181789/9a07e1a8-d6e3-11e5-9a2a-b9c36fd3a600.png)

**Comment by valianttry** [comment]
Stephanie you can also update the views sentence to "viewed more than 350,000 times since we released it last week."

**Comment by stephaniemcv** [comment]
Done and done. Thanks for the review!

**Comment by OpenMatt** [comment]
Assuming this can be closed now -- please re-open if that's wrong.
