### ISSUE TITLE
Write a blog post report-out on beat 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#156]
- What did we do?
- How did it go? 
- What data did we collect?
- What kind of press did we get?
- What did we learn? 

We can maybe start a draft here: 
public.etherpad-mozilla.org/p/beat1

**Comment by OpenMatt** [comment]
@valianttry @KevZawacki what do you think about my suggested outline headers? Do those feel like the right buckets?

@KevZawacki : want to start filling out the press section, plus any other initial thoughts / ideas you have?

**Comment by KevZawacki** [comment]
Just dropped in press information (links we can add outside of etherpad).

**Comment by OpenMatt** [comment]
@adamlofting do you think maybe you could include a quick summary of key KPI data, to flesh out that part of the picture in terms of how beat 1 and now beat 2 have been performing?

**Comment by KevZawacki** [comment]
Updating the etherpad with the latest comms data

**Comment by adamlofting** [comment]
@OpenMatt I've added some high-level notes about the result of the survey, and web analytics so far.
- @stephaniemcv could you add the latest email sign-up numbers?
- @HPaulJohnson can you add the FB video views?
- @valianttry can add the snippet video views data if you have it? (I'll ping Jessica to see if there's a report I can access now as well, but currently I don't have this data)

**Comment by adamlofting** [comment]
@valianttry no action needed for you now. :+1: 

I have the snippet video views, and have added these to the pad.

**Comment by HPaulJohnson** [comment]
Added social stats (and some updated stats from GA re: video views). @KevZawacki is going to add some stats re: media/press hits

**Comment by valianttry** [comment]
@KevZawacki @HPaulJohnson @OpenMatt @adamlofting I left some comments in the pad -- so much awesome stuff and work !

It would be good to try and provide some comparison data if we can find it -- even if it's an imperfect comparison. It's difficult to claim something is exceptional without providing _some_ measuring stick.

We also answered a lot of Qs about email through testing -- @stephaniemcv let's add those findings in.

It would be good to just lean in a little harder about what our assumptions were and what we've learned that _we can apply to future beats._ -- can we go a little beyond the list of data and dig into that a bit?

**Comment by OpenMatt** [comment]
### Next steps

Let's carve this into individual blog post pieces, assign and publish. 
- **1) High-level.** What was our original goal w. this campaign? What were our hypotheses and goals?
  - Assigned to: @valianttry & @shaghdoosti working together?
- **2) Metrics.** How did we do in terms of... social? video views? translating that into longer-term relationships / "active advocates?, etc? How does that compare to relevant benchmarks from other orgs? (as much as possible, based on data we have.) 
  - Assigned to: @HPaulJohnson + @adamlofting 
- **3) Press.** Round-up of best press coverage, etc. Summarizing key stats, etc. 
  - Assigned to: @KevZawacki 
- **4) Content / creative**. What did we make? What did we learn from making it? 
  - Assigned to: @brettgaylor 
- **5) Findings with our email performance**. 
  - Assigned to: @stephaniemcv  

(please add / edit and revise the above as you see fit.)

**Comment by OpenMatt** [comment]
- We're going to publish these to fundraising.mozilla.org for now. 
- To avoid stop energy and get this done w. busy people, I would say: just start writing and post a draft here when you have it.

**Comment by KevZawacki** [comment]
@OpenMatt Here's my section:

"Press around Mozilla's encryption campaign and our support for Apple has been tremendous. As of Thursday, March 3 — about little more than halfway through the campaign — we've garnered 90 stories on five continents. Capstone coverage includes Mark's interview on NPR's Morning Edition (which reaches 13 million listeners each day!); Mark's op-ed in CNN; and stories in The Intercept, Fast Company, Reuters, CBC and WIRED UK. In addition to this expansive coverage, we've forged valuable new relationships at top news outlets. In short: We've quickly established Mozilla as a leading authority on encryption and protecting the open Internet. 

"We're also seeing unprecedented engagement on social. When we tweeted our support of Apple, thousands of people retweeted us — including Edward Snowden. That particular tweet had 3.2K retweets and 3.7K favorites. For comparison, our net neutrality victory tweet had 401 retweets and 203 favorites."

**Comment by valianttry** [comment]
@stephaniemcv should write something about findings with our email testing!

**Comment by OpenMatt** [comment]
Added!

**Comment by OpenMatt** [comment]
@KevZawacki awesome! you can prep that as an individual blog post on fundraising.mozilla.org.

**Comment by KevZawacki** [comment]
@OpenMatt Don't believe I have log in credentials for the site.

**Comment by valianttry** [comment]
@KevZawacki maybe use Google Docs to draft for now? I'll work on your credentials for that site (and anyone else who needs authorship access).

**Comment by valianttry** [comment]
@KevZawacki sent you credentials, lemme know if you don't have them.

**Comment by KevZawacki** [comment]
Just finished [my post](https://docs.google.com/document/d/16mFHxv2AOP5hbf-9AR7rtpMfOZ1H9mTM_t6STYnl_HQ/edit) for fundraising.mozilla.org.

@HPaulJohnson or @valianttry, can you give a quick read / thumbs up before I publish?

**Comment by KevZawacki** [comment]
We have posts from myself, Stephanie, and Andrea up on https://fundraising.mozilla.org/. 

Strong start -- I'm going to close this ticket, but feel free to re-open if the need emerges.
