### ISSUE TITLE
Sketch - visual systems for advocacy video

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#158]
Let's look at AJ+ and similar video system and dissect all the types of components we need to build:
_We will review at the end of day Monday_
- style for into
- ”lower thirds” text 
- on screen text - quotes
- on Screen text - facts
- ANY OTHER COOL IDEAS!

**Comment by lovegushwa** [comment]
Benchmark from @brettgaylor https://episode6.donottrack-doc.com/en/

**Comment by brettgaylor** [comment]
Here's one from AJ+
https://www.youtube.com/watch?v=6aBygmdZAfs

Notice they have a consistent opening animation, text, "lower thirds" for when they caption people's names, on screen text, etc.  They also have a specific way they close each video, and a consistent way they ask users to share the video.

Obviously their content is more exciting than ours - we only have one sit down interview :)

**Comment by natalieworth** [comment]
Beat 4 video benchmarking and inspiration/ alternative visual systems are now up on a Pinterest board: https://www.pinterest.com/nataliejworth/mozilla-encrypt-video-benchmarking/
