### ISSUE TITLE
Create style - ident

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#160]
See benchmarks in #158
Into includes Mozilla logo and ENCRYPT animation currently used at the end of videos 1 and 2

**Comment by lovegushwa** [comment]
See benchmarks in #158

**Comment by natalieworth** [comment]
'Encrypt' ident/ mozilla end cards can be found in the drive here: https://docs.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0WGNPM2YzeHkxams&usp=drive_web
<img width="1345" alt="screen shot 2016-03-23 at 5 05 57 pm" src="https://cloud.githubusercontent.com/assets/14876567/14004728/98962eb0-f119-11e5-8d3a-d23ec5bbe499.png">
