### ISSUE TITLE
Create style - "lower thirds" text

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#164]
See benchmarks in #158
We should think about a way to handle various length names and titles.

**Comment by natalieworth** [comment]
Final consolidated files for beat 4 video (premiere) here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NTZidEFfTF9aVUU&usp=drive_web&ddrp=1#
