### ISSUE TITLE
Create style - On screen text: facts & quotes

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#166]
See benchmarks in #158

**Comment by natalieworth** [comment]
Final consolidated files for beat 4 video (premiere) here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0NTZidEFfTF9aVUU&usp=drive_web&ddrp=1#

**Comment by natalieworth** [comment]
Facts and Quotes .ai file from @lovegushwa is here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvWWd6M050TW9GNWs&usp=drive_web&pli=1&ddrp=1#
