### ISSUE TITLE
Build landing page for Beat 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#17]
- Natalie and @lovegushwa will create the wireframes this week, and UI next to ship by 22nd.
- Devs will likely build around Jan 25-29

**Comment by OpenMatt** [comment]
@lovegushwa can you copy Natalie on this ticket?

**Comment by cassiemc** [comment]
cc @natalieworth

**Comment by OpenMatt** [comment]
- @lovegushwa says:
- @ScottDowne is re-building the web fellows / the advocacy home page by the beginning of Feb. It might make sense if he build the microsite as well. (cc @alicoding )

**Comment by cassiemc** [comment]
Not sure if that will all work out time-wise, there are several open web fellows pages to be built, so adding encryption in the same timeframe might be too much. I'll let @ScottDowne and @simonwex speak to that, though.

**Comment by ScottDowne** [comment]
@OpenMatt @cassiemc I'll need to know more about it, but it's possible we can fit it in.

I'll need to know how many pages are involved, where it'll live, and if the styling and layout are similar to advocacy/open web fellows.

**Comment by OpenMatt** [comment]
- 1) how many pages are involved
  - one 
- 2) where it'll live
  - @lovegushwa do you know? 
- 3) is the styling and layout similar to advocacy/open web fellows?
  - @lovegushwa: what do you think?

**Comment by lovegushwa** [comment]
@ScottDowne @openmatt
I think we can pull styling from Advocacy / Fellows. Will confirm.

Will be one page, this is what we need to build.
- graphic header.
- video player.
- CTA loads after video.
- room / plans for a carousel later in campaign (once we have 4 videos /
  one interactive piece.)

Wireframes this week, UI and hand off next week.

**Comment by ScottDowne** [comment]
@lovegushwa cool, doesn't sound hard.

**Comment by OpenMatt** [comment]
- Ok. Sounds like we're ok here in terms of having the dev resources booked that we'll need. 
- @simonwex: ok by you?

**Comment by simonwex** [comment]
@OpenMatt yup, Scott's on boar.

**Comment by OpenMatt** [comment]
@lovegushwa can you signal here when we're ready to hand off from design to build?

**Comment by lovegushwa** [comment]
yep @OpenMatt I'm going to meet with @natalieworth about UI. We're trying to wrap this up today, I think tomorrow it will be ready for @ScottDowne if everything goes well.

**Comment by OpenMatt** [comment]
@lovegushwa do we still need this ticket? Or is the build happening elsewhere?

**Comment by lovegushwa** [comment]
see #40
