### ISSUE TITLE
QA microsite

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#171]
Using this URL
https://advocacy-mozilla-org-sta-pr-95.herokuapp.com/encrypt/

**Comment by alanmoo** [comment]
@brettgaylor You had thoughts on the modal behavior?

**Comment by brettgaylor** [comment]
I think it's good, the only thing i wonder is if clicking on the video should play/pause?

**Comment by alanmoo** [comment]
The video itself has controls when playing, and clicking outside the video pauses it- is that not enough?

**Comment by brettgaylor** [comment]
Probably!  On my setup I just need to scroll down to the controls if I happen to click outside the video. So it just feels a little clunky to me - you can pause it by clicking outside, but can't replay it by clicking back on the video, which I think has become assumed behaviour due to youtube.

**Comment by alanmoo** [comment]
Ah, I see. So perhaps if the video is paused, clicking on it again starts it?

**Comment by brettgaylor** [comment]
Yes.

**Comment by valianttry** [comment]
On my 15" laptop the site is pretty constrained -- I realize the resolution / screen size is hard to get right for all screens but is this optimized for _most_? Just checking!

![screen shot 2016-02-23 at 12 24 42 pm](https://cloud.githubusercontent.com/assets/9830371/13265732/671cb2fc-da29-11e5-9407-2c7f54ec4352.png)

**Comment by alanmoo** [comment]
The site is responsive, so wider than 980px it will lock the content at center, and in browsers less than 980px wide, the content will scale down/rearrange as needed.

**Comment by valianttry** [comment]
:clap: thanks @alanmoo !

**Comment by valianttry** [comment]
New optin page feedback (looking at https://advocacy-mozilla-org-sta-pr-97.herokuapp.com/encrypt/signup/):

We need to replace the double-dash with a long Emdash so they match:

![screen_shot_2016-02-23_at_5_50_30_pm](https://cloud.githubusercontent.com/assets/9830371/13273140/1dcd40d0-da56-11e5-8df6-50b5a7d0fa11.png)
(that was my fault, it's that way in the Google Doc)
- All the error messages are working great
  However, I clicked "signup" but nothing happened (maybe not yet fully functional?)

**Comment by alanmoo** [comment]
Yeah, not yet functional

**Comment by valianttry** [comment]
@alanmoo did you get affirmation that the optin page can handle the traffic: Approx 100,000 - 300,000 page views and optins / day?

**Comment by alanmoo** [comment]
Bucket is handling the optins just like the snippet so that shouldn't be a problem and the rest of the site has been moved behind a CDN. So yes.

**Comment by alanmoo** [comment]
Signup form should be working now

**Comment by alanmoo** [comment]
Everything's merged together on staging:

https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/2/?video=2
https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/?video=2

and the snippet target (not the final URL yet)

https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/signup

I'll push to production later this evening, but please let me know if there's anything terribly wrong in the meantime.

@valianttry @brettgaylor @HPaulJohnson @OpenMatt @lovegushwa

**Comment by valianttry** [comment]
I noticed after the video plays the message that pops up is about privacy. I suggest we change it to say: "Will you spread the word about our friend, encryption?" The social links there use text about #youbeyou as well.. I know @HPaulJohnson is working on getting final social language in #179 ; we should update it if possible.

![mozilla_advocacy](https://cloud.githubusercontent.com/assets/9830371/13275218/59425b3a-da67-11e5-98df-de0bff118513.png)

**Comment by valianttry** [comment]
Is it possible to direct people who click "signup" on the microsite to the new optin design? We're getting criticism for the old version that's not very transparent. 

![new optin practices](https://cloud.githubusercontent.com/assets/9830371/13275256/d927a5c6-da67-11e5-8695-fcc52071de17.png)

**Comment by lovegushwa** [comment]
@alanmoo ( @valianttry this might answer your question)
<img width="517" alt="screen shot 2016-02-23 at 7 58 10 pm" src="https://cloud.githubusercontent.com/assets/12228435/13275275/1c51e01e-da68-11e5-9f14-af6b41b6f0e0.png">
- Can we use "First Name" rather than "Name"
- Let's underline the link in "Why do we ask for this information" rather than use a blue link color. (It should like just like "this privacy Notice")
- change "Join the list" to ""Join the email list"

**Comment by valianttry** [comment]
Oh thanks @lovegushwa i didn't see the link! I also think to be clearer we should change the title to "Join Mozilla's email list" or if that's too long, "Join the email list"

**Comment by valianttry** [comment]
Not a P1, but we should change the optin invitation at the top right (updates may not always be about "advocacy" per se). Let's use "email updates" instead:

![mozilla_advocacy](https://cloud.githubusercontent.com/assets/9830371/13275387/7508b3e4-da69-11e5-927d-73ed1851363f.png)

**Comment by lovegushwa** [comment]
@alanmoo UI tweaks

<img width="1125" alt="screen shot 2016-02-23 at 7 54 18 pm" src="https://cloud.githubusercontent.com/assets/12228435/13275333/ac0bedee-da68-11e5-977b-6357ceaec0cc.png">
- A: use all caps here
- B: align start of thubnails to edge of "Meet Encryption"
- C: add a bit more line spacing to these captions (see example)
- add some space between "episode" and "0:00" (time)
- D: Make titles and "Stay tuned" a pixel or two smaller
- E: Make this book weight

**Comment by lovegushwa** [comment]
@alanmoo @simonwex this is a big one, P1 if possible. 

looks like the video is defaulting to the .mp4 not the .webm
There is a huge difference in quality and file size here. The .webm is 9mb rather than 15mb and the quality is much better.

**Comment by brettgaylor** [comment]
> looks like the video is defaulting to the .mp4 not the .webm

@alanmoo you probably know this but if you put webm as first file and then mp4 as fallback, they will default in that order.

**Comment by HPaulJohnson** [comment]
RE: Sharing copy. Let's use the following: 

Share CTA (per Andrea's suggestion): 
"Will you spread the word about our friend, encryption?"

For the email share text: 
(Subject): "Check out this great video on encryption."
(Body): "I just watched a video about how encryption works in our everyday lives and thought you would really like it. Check it out at https://mzl.la/encrypt. Hope you enjoy it!"

For twitter share text: 
I just learned how encryption works in our everyday lives. Check it out at mzl.la/encrypt via @mozilla #encrypt

For Facebook share text: 
"I just watched a great video about encryption.
Watch it yourself and learn more about how encryption works in our everyday lives."
advocacy.mozilla.org/encrypt

@lovegushwa / @natalieworth if we have a chance to update the accompanying graphics please add those here, too.

**Comment by alanmoo** [comment]
None of these look particularly difficult, I'll tackle them after I eat, on my way home now. The only catch is changing social content will happen for all the videos, the groundwork isn't quite there to be unique per video. So I'll update them for beat 2 and then make them variable later this week. Sound good?

**Comment by HPaulJohnson** [comment]
works for me @alanmoo. thanks.

**Comment by lovegushwa** [comment]
@alanmoo P1:  this is my last change, it's going to make the page look much better.

Updated video 2 poster image:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvWUxudjh5b2pEUmM/view?usp=sharing

**Comment by alanmoo** [comment]
@lovegushwa 👍

**Comment by valianttry** [comment]
@alanmoo you're a late night hero :clap: 

![what-were-the-funniest-quotes-from-the-2012-presidential-election-37409777-nov-6-2012-1-600x400](https://cloud.githubusercontent.com/assets/9830371/13276007/c857a248-da6f-11e5-896d-e90706d452fe.jpg)

**Comment by alanmoo** [comment]
Everything's been done. One minor question @lovegushwa: By making "Coming soon" book weight, did you mean bolder? The weights don't quite translate the same to web fonts.

**Comment by alanmoo** [comment]
I've deployed this to production and it should be available within an hour (due to the CDN).
