### ISSUE TITLE
Final assets for beat 2 snippet

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#173]
Hello everyone, please drop the final snippet in the feed below:
- [x] design
- [x] poster 480x270.jpg - no play button ( @natalieworth )
- [x] email signup URL (@alanmoo )
- [x] video file 
- [x] copy ( @valianttry  )

**Comment by lovegushwa** [comment]
DESIGN
<img width="1275" alt="screen shot 2016-02-22 at 5 59 16 pm" src="https://cloud.githubusercontent.com/assets/12228435/13261570/97cdf4e2-da15-11e5-9c3f-723582dde354.png">

Landing page:
<img width="1800" alt="encryption-ui-011-05" src="https://cloud.githubusercontent.com/assets/12228435/13267011/be6efc26-da2f-11e5-93f8-8274e094aed6.png">

<img width="1800" alt="encryption-ui-011-06" src="https://cloud.githubusercontent.com/assets/12228435/13267041/ea25e528-da2f-11e5-9cdf-332e4aed9b55.png">

**Comment by alanmoo** [comment]
https://advocacy.mozilla.org/encrypt/signup (not live yet)

**Comment by valianttry** [comment]
Final copy for below the search bar:
"Mozilla stands up for online privacy. If you want to be in-the-know about our work and learn about opportunities to stand with us, sign up to be on our email list. We’ll send you important updates, news, and opportunities to take action."

hotlinked text should look like this:
![snippet_2nd_iteration_language_options_-_google_docs](https://cloud.githubusercontent.com/assets/9830371/13266190/b673b402-da2b-11e5-9305-a5bdd07b727b.png)

**Comment by valianttry** [comment]
Link for snippet text link:
https://advocacy.mozilla.org/encrypt/signup?ref=EncryptionQ1_2016&utm_campaign=EncryptionQ1_2016&utm_source=firefox&utm_medium=snippet&utm_content=MeetEncryption_Beat2

**Comment by natalieworth** [comment]
Beat 2 poster: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0b3QxY3RwcGlySG8/view

**Comment by lovegushwa** [comment]
Final video file: https://drive.google.com/file/d/0B2qu3ExKWIlvcC1VS25sZDRfazg/view?usp=sharing

**Comment by alanmoo** [comment]
Is there an mp4 file too?

**Comment by lovegushwa** [comment]
@alanmoo this is just for the snippet. I'll give you separate links for the landing page video.

**Comment by alanmoo** [comment]
Ah, it would help to look at the name of the ticket I'm commenting on :smile:

**Comment by natalieworth** [comment]
@lovegushwa Updated version of the beat-2 poster (480x270):
https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0R3RZMHl4X1JaTEk/view
I feel it still seems to look a bit soft, but I checked it with the beat-1 poster and they were both the same size. I've also exported it at 144 dpi for retina, but could try doubling the 480x270 if it's still too soft?

**Comment by valianttry** [comment]
From Jessica Vondrak:

Hi Andrea -

10am should be perfect. 

All the files look good.  See screenshot below.  Two things:

1)   We could consider moving the image on the web poster slightly to the left to make the play button more centered.  Minor tweak but it could also be left as is.
2)  We need at 40x50  or 64x64 png icon to include by the text.  I dropped in just the Mozilla branded logo as an example. [[@natalieworth or @lovegushwa this is news to me, any way to bang this out quickly? Could it be the cat or another image from the video?]]

I'll plan to be online for the 2 hours prior to launch to finish any details. 

Thanks!
Jess

**Comment by lovegushwa** [comment]
@valianttry working on this

**Comment by lovegushwa** [comment]
@valianttry 

Snippet icon:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvdW0wZUk1azhPTTA/view?usp=sharing

Poster: 
https://drive.google.com/a/mozilla.com/file/d/0B20-0lpP23c0R3RZMHl4X1JaTEk/view?usp=sharing

**Comment by JessicaVondrak** [comment]
Hi Jordan and Andrea - I dropped in the assets and it's close to perfect.  :)  

2 things:
1)  @lovegushwa The icon is awesome; just one minor tweek.  I think we may need to add some padding to the top of the image to make it appear more centered with the text. (see screenshot below).   I tried re-sizing the image, but it looked blurry and still not centered.  I think the issue may be the text is a little longer than we usually utilize in the snippet which makes it appear not aligned.  We can play around with it on vidyo later if that's easier?  
![screen shot 2016-02-24 at 12 08 44 pm](https://cloud.githubusercontent.com/assets/17205874/13283686/71afda84-daef-11e5-8af9-93372b80daac.png)

2)  @valianttry I had to change the tagging on the link to match the rules for the snippet service.  Can you just confirm that it will work for your tracking purposes as well.

It looks like this:  https://advocacy.mozilla.org/encrypt/signup/?utm_source=desktop-snippet&amp;utm_medium=snippet&amp;utm_content=MeetEncryption_Beat2&amp;utm_term=5440&amp;utm_campaign=EncryptionQ1_2016

**Comment by valianttry** [comment]
Thanks @JessicaVondrak ! I've asked @adamlofting to confirm the URL is OK and I don't know if @lovegushwa is up and at 'em yet this morning (he's in PST). Will get to these asap.

**Comment by adamlofting** [comment]
It looks like the ampersands got html-encoded, which might not work. 

Instead this should be: 
https://advocacy.mozilla.org/encrypt/signup/?utm_source=desktop-snippet&utm_medium=snippet&utm_content=MeetEncryption_Beat2&utm_term=5440&utm_campaign=EncryptionQ1_2016

Note the `&` instead of the `&amp;` between each parameter.

**Comment by JessicaVondrak** [comment]
Hi @adamlofting - 
The snippet service requires you to include the`"&amp;"`  -  it will create an error if you eliminate those characters.

**Comment by adamlofting** [comment]
Interesting... as the GA parameters have worked correctly in the past for all previous snippets, perhaps when the URL gets rendered to the end user it ends up as `&` anyway.

Unless this is a recent change in how the service works, I expect the URL you provided above will work fine for our tracking.

Once it goes live we can check in the GA real time report:
https://analytics.google.com/analytics/web/#realtime/rt-traffic/a49796218w86119768p89349767/

**Comment by JessicaVondrak** [comment]
GA will definitely pick up the data for clicks on the link.  We use this same tagging structure for all of our links and use GA to track "clicks".  

I'm not sure if this impacts anything you want to track beyond "clicks"?  Is there a separate way you are tracking actual conversion (sign-ups)?

**Comment by adamlofting** [comment]
That's great then - beyond clicks is all handled in GA if it happens on our webpage.

**Comment by JessicaVondrak** [comment]
Perfect!  :)

**Comment by valianttry** [comment]
per @shaghdoosti -- let's make one word change:

"Mozilla stands up for online privacy." change to: "Mozilla stands up for online security."

possible @JessicaVondrak ?

**Comment by lovegushwa** [comment]
Revised icons:
@valianttry @JessicaVondrak there are a few options in this folder, try a and see what looks best.

https://drive.google.com/folderview?id=0B2qu3ExKWIlvSDFZYzlHMTZ5UFU&usp=sharing

**Comment by JessicaVondrak** [comment]
@lovegushwa 
I think #1 looks best...thoughts?  My eyes are crossing bc they look very similar!
#1 ) 60x70png ![screen shot 2016-02-24 at 6 40 13 pm](https://cloud.githubusercontent.com/assets/17205874/13294836/2e017680-db26-11e5-9680-a9f748b7366d.png)
#2)  64x64png 
![screen shot 2016-02-24 at 6 44 34 pm](https://cloud.githubusercontent.com/assets/17205874/13294977/c90aa098-db26-11e5-9b5e-9de761470d63.png)

**Comment by lovegushwa** [comment]
@JessicaVondrak 1 looks great, ship it! :)

**Comment by JessicaVondrak** [comment]
Great, done!

**Comment by JessicaVondrak** [comment]
Final URL for Tracking with finalized Snippet ID #  5540:

https://advocacy.mozilla.org/encrypt/signup/?utm_source=desktop-snippet&amp;utm_medium=snippet&amp;utm_content=MeetEncryption_Beat2&amp;utm_term=5540&amp;utm_campaign=EncryptionQ1_2016
