### ISSUE TITLE
Build - Final landingpage updates & email form

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#174]
LANDING PAGE
- [x] video 2 copy
- [x] compressed video 2 files

EMAIL FORM
- [x] email form design
- [x] tabzilla .png
- [x] background images
- [x] rollover copy for " *Required. Why do we ask for this information?"

**Comment by lovegushwa** [comment]
@alanmoo 
Email form design:

<img width="1800" alt="encryption-ui-011-05" src="https://cloud.githubusercontent.com/assets/12228435/13267293/66f955ca-da31-11e5-8fc1-d11865f449ae.png">

<img width="1800" alt="encryption-ui-011-06" src="https://cloud.githubusercontent.com/assets/12228435/13267298/6e4a7cbe-da31-11e5-8376-a8fcc74528f3.png">

**Comment by lovegushwa** [comment]
Tabzilla and background patterns: 
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvMGZFSDFiZkNkSEE&usp=sharing

**Comment by lovegushwa** [comment]
Landing page - video 2 copy:
https://docs.google.com/a/mozilla.com/document/d/1rZnC_4uIv7fVlps_RwTIcDR4ohHgIxN6vt_eLMEWcwo/edit?usp=sharing

**Comment by lovegushwa** [comment]
rollover copy for " *Required. Why do we ask for this information?"

We care about your privacy and helping you make informed choices. That’s why we link to our Privacy Notice  so you can easily read it. To receive emails we require only your email address — “First Name” and “Country” aren’t required to sign up, but if you tell us your country we can send you local news and events — it’s your choice!

**Comment by alanmoo** [comment]
Are there specs on placement of Tabzilla?

**Comment by lovegushwa** [comment]
@alanmoo @cadecairos @simonwex 

Final landing page video files:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvcWMyME9DbVo0VTg&usp=sharing

**Comment by lovegushwa** [comment]
@alanmoo 
Final Landing page - video 2 copy:
"Meet Encryption, and learn how she's hard at work to keep you safe online."
