### ISSUE TITLE
Update FB & Twitter share message/image on /encrypt landing page for Beat 2

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#179]
We need updated copy and images for FB and Twitter share buttons on campaign home page. 

cc/ @alicoding @lovegushwa @natalieworth

**Comment by HPaulJohnson** [comment]
New copy to be added here once social copy completes approval process.

**Comment by HPaulJohnson** [comment]
As per QA ticket #171, let's update the sharing copy as follows: 

RE: Sharing copy. Let's use the following: 

Share CTA popup: 
"Will you spread the word about our friend, encryption?"

For the email share text: 
(Subject): "Check out this great video on encryption."
(Body): "I just watched a video about how encryption works in our everyday lives and thought you would really like it. Check it out at https://mzl.la/encrypt. Hope you enjoy it!"

For twitter share text: 
I just learned how encryption works in our everyday lives. Check it out at mzl.la/encrypt via @mozilla #encrypt

For Facebook share text: 
"I just watched a great video about encryption.
Watch it yourself and learn more about how encryption works in our everyday lives."
advocacy.mozilla.org/encrypt

still need updated graphics for FB and Twitter.

**Comment by alanmoo** [comment]
I've dropped these in, but @alicoding can you double check these work as expected in the morning?

**Comment by lovegushwa** [comment]
Facebook with URL: https://drive.google.com/file/d/0B2qu3ExKWIlvb2d3WEstRjVmUTQ/view?usp=sharing

Twitter with URL:
https://drive.google.com/file/d/0B2qu3ExKWIlvNzlaM2N5Ym9HUUU/view?usp=sharing

**Comment by alanmoo** [comment]
@alicoding can you throw this into your existing PR?

**Comment by alanmoo** [comment]
Merged in and deployed.

**Comment by lovegushwa** [comment]
@alicoding just created new .png's this should help with better compression on facebook

Facebook with URL: https://drive.google.com/file/d/0B2qu3ExKWIlvOUlCYWdMNFhET2M/view?usp=sharing

Twitter with URL: https://drive.google.com/file/d/0B2qu3ExKWIlvYkxQUTFxTl9sWmc/view?usp=sharing
