### ISSUE TITLE
Email Process and Performance Tracking

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#180]
In the spirit of being open, I'd like to create a single point where email content, testing and results can be easily accessed by anyone. All feedback welcome!

My hope is that by the end of the campaign we have a structure that can be applied to campaigns in the future.

https://docs.google.com/a/mozilla.com/spreadsheets/d/1ikv9lEajYaLw0edrNNWcJX09_WGE_ITJo96K8jL4xew/edit?usp=sharing

@valianttry @shaghdoosti @mmika

**Comment by OpenMatt** [comment]
@stephaniemcv I'm going to close this as it seems done.
