### ISSUE TITLE
URL plan for future beats

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#183]
The structure of URL's has been a bit rough in the last few beats as I didn't have a clear picture of what the needs of them were. Up until now, this is what we've had (all URLs start with `advocacy.mozilla.org`)
### Current scheme
- `/encrypt/` - the page with "sign up" CTA (I'll call it 'social'), showing the latest video
- `/encrypt/2` - the page without the "sign up" CTA ('direct'), showing the latest video
- `/encrypt/3` - the alternate social page (which never got A/B tested due to optimizely issues)
- `/encrypt/?video=2` - social page where the number links to the video for a specific beat
- `/encrypt/2/?video=2` - direct page where the number links to the video for a specific beat

This isn't sustainable/ideal for a few reasons, namely @alicoding's told me Optimizely has issues with it, and it leads to some unnecessary complexity in other ways. So I'd like to adjust behavior going forward.
### Proposed scheme
- `/encrypt/social/` - Latest video on social page
- `/encrypt/direct/` - Latest video on direct page
- `/encrypt/{direct || social}/2`\- Number indicates video, and clicking on a different video will update the URL, but not reload the page or add another page to browser history
- `/encrypt/?video=2` will still work for linking directly to a video, but none of the share links will use it, nor will that be a URL generated by the site in any way.

Thoughts? Are there any other details I might be missing that could be useful?

**Comment by alanmoo** [comment]
Any thoughts on this @valianttry @HPaulJohnson @adamlofting @OpenMatt ?

**Comment by HPaulJohnson** [comment]
Makes sense to me. Ideally, we'd have a system where we could also customize the share language for each piece of content. Not sure if that works with this scheme but something to also consider.

**Comment by alanmoo** [comment]
As in A/B testing of the content within a design?

**Comment by brettgaylor** [comment]
This is great.  Avoids us confusing the numbers in the URL with the beats.

**Comment by HPaulJohnson** [comment]
@alanmoo as in the share message might be unique to a specific piece of content. As an example, with the first video a share message about general privacy was appropriate and with the second video we wanted a share message that was much more focused on encryption.

**Comment by alanmoo** [comment]
URLs need to have parameters at this point in time, so I've set up some forwarding:

`/encrypt/social` and `encrypt/` redirect to `encrypt/social/{latestVideoNumber}`
`/encrypt/direct` and `encrypt/hybrid` add the latest video number to themselves automatically

**Comment by alanmoo** [comment]
All other routes that were previously used redirect to the appropriate pages with new URLs.

Key new URLs going forward:

`/encrypt/` remains for latest video, social page
`/encrypt/direct/3` for video 3 in the email blast @stephaniemcv 
`/encrypt/hybrid` for that hybrid page with just one video, if we need to link to it from the snippet (but the existing url the snippet is using will still work)
`/encrypt/social/{videoNumber}` to directly access a video

**Comment by stephaniemcv** [comment]
https://advocacy.mozilla.org/encrypt/direct/3 redirects to https://advocacy.mozilla.org/, does that mean it's not ready yet?

**Comment by alanmoo** [comment]
I haven't deployed to production yet.

Staging is up though.https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/direct/3I'll deploy to production when I get in to the office, before the daily stand.

-Alan
