### ISSUE TITLE
Snippet error with Video 2: Snippet has been taken down

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#185]
Hi Andrea -

There's a glitch occurring with the video on the snippet that Stephen Horlander pointed out.  We need to pause while we investigate.  See comments below....

"The pages loads briefly, then flashes, then reflows the layout because the video is too big. Video of the issue: http://people.mozilla.org/~shorlander/bugs/about-home-reflow.webm"

It wasn't occurring yesterday, so it's likely snippet service related. The size of the video is the same as others, so I'm guessing it's related to the new templates that were sent to production today.

We can re-launch as soon as we get it fixed (hopefully tomorrow!)

@Jordan - There is a possibility we may need to re-size the video.  Just wanted to give you a heads up!

I'll let you know as soon as we determine the fix.

Thanks,
Jess

**Comment by lovegushwa** [comment]
@valianttry 
Let's try this file: https://drive.google.com/file/d/0B2qu3ExKWIlvcC1VS25sZDRfazg/view?usp=sharing
It's 5.6mb (the older files was 6.9mb)

**Comment by valianttry** [comment]
Apparently Giorgos (with snippets team) uploaded several new templates which may have caused the problem.... new video is getting uploaded by Jessica V now.

**Comment by valianttry** [comment]
Update: Snippet with Video 2 is still down. Everyone who can fix it is on PTO. Discussing alternatives with Michaela Smiley.

**Comment by valianttry** [comment]
New copy for Beat 2 snippet that is text + icon only:
https://docs.google.com/document/d/1f8aD_1ALc4UCuycVLqVeRSUMW_mmL9zSbvXoE13wKXY/edit

**Comment by lovegushwa** [comment]
@valianttry I don't think there is any design work for this?

**Comment by valianttry** [comment]
Correct. There may be some design tweaks to the embedded form in the future but it is no longer urgent / applicable for this campaign.
