### ISSUE TITLE
Collect and ship campaign metrics for 2/29 call

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#186]
@HPaulJohnson @valianttry 

Lots of data already collected in #156.

Kevin will share numbers with EJ once this ticket is updated.

**Comment by KevZawacki** [comment]
Here's what we have so far:

**Video views across channels**:      
- Microsite: 120k  
- Snippet: 500k  
- Facebook:@hpauljohnson?  

**Snippet email signup**:      
- New opt-ins: @stephaniemcv? 

**Web analytics**:
- ~75% of visits result in people watching the campaign videos
- Of the 120k times people have started watching the video on the site, 20k have gone on to share the video on Facebook, Email or Twitter (~13%)
- ~55% share on Facebook, 30% on Email, 15% on Twitter

**Comment by stephaniemcv** [comment]
Beat 1 added between 2/11-2/23 ~ 148,000, Beat 2 added between 2/25-2/26 ~ 5,000

**Comment by KevZawacki** [comment]
Emailed what we have so far to EJ. Paul and Andrea are on the thread.

EJ's slide [here](https://docs.google.com/presentation/d/1Iq0zr1p5ihn_nwUwbc8dXOQ-fpAsyUu2Uc9bQm2Trl8/edit?ts=56d07c43#slide=id.g11b4b8ef56_0_3).

**Comment by HPaulJohnson** [comment]
From: https://public.etherpad-mozilla.org/p/beat1

Video views across channels:
- Microsite:266K video "events" (163K started + 91K ended)
- Snippet: 500k
- Facebook:125K

Snippet email signup:
- New opt-ins: Beat 1 added between 2/11-2/23 ~ 148,000, Beat 2 added between 2/25-2/26 ~ 5,000
  Note: Some of these come from the microsite traffic vs. snippet. Any way to distinguish?

Social
- Shares from microsite: 21K (11K FB + 6K email + 3K Twitter)
- 6.5K Moz/Encryption mentions on Twitter
- 4K shares & retweets
