### ISSUE TITLE
Build beat 5 Campaign Pledge petition page

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#188]
#### Context
- In conjunction with the beat 5 video, we're going to release a global pledge around standing up for encryption.
- People will commit to taking action, and also share which country they are in so that we can send them relevant advocacy actions when the time comes. 
#### Deadline
- Needs to be ready to ship to production Monday, Mar 21
#### Design

Design ticket for this page: https://github.com/MozillaFoundation/encryption_campaign/issues/205
#### Requirements

The build for this requires: 
1) A petition page with the form fields: name, email and country. 
2) A thank you page with social share options 

For reference, it can be based on https://advocacy.mozilla.org/encrypt/signup

**Comment by shaghdoosti** [comment]
@OpenMatt

**Comment by valianttry** [comment]
For reference, it can be based on https://advocacy.mozilla.org/encrypt/signup

**Comment by brettgaylor** [comment]
Would this be something that we'd use Share Progress for? cc @HPaulJohnson

**Comment by OpenMatt** [comment]
@shaghdoosti what is the deadline / timeline for this? When does it need to be live?

**Comment by shaghdoosti** [comment]
Needs to be live same day as video is launched.

**Comment by OpenMatt** [comment]
note: @alanmoo is on PTO as of Monday, Mar 21. So we need to ensure the work is well handed off and that we have dev support ready to step in in case we run into last-minute snags, etc. 

cc @simonwex

**Comment by OpenMatt** [comment]
@alanmoo are there parts of this you can begin now, or are you blocked on design?

**Comment by alanmoo** [comment]
I saw the proposed design on Friday, if the general behavior is approved, I can get started on that.

**Comment by alanmoo** [comment]
Is this form being submitted to the same database as the rest of the signup forms?

**Comment by lovegushwa** [comment]
@alanmoo were waiting for final copy approval from @shaghdoosti but I don't think it will change.
I'll follow up with details in the morning but this should get your rolling.

v1  (priority)
![encryption-ui-022-01](https://cloud.githubusercontent.com/assets/12228435/13836914/93a265aa-ebc3-11e5-8ed1-c6abb178e03d.png)

v1  -  display social share modal after form is submitted
![encryption-ui-022-02](https://cloud.githubusercontent.com/assets/12228435/13836916/9a2f7f0c-ebc3-11e5-9124-0a6725e478df.png)

v2  -  you can switch the video order (opposite of shown), note "email signup" language has changed to "take the pledge" top of page and lower left.
![encryption-ui-022-03](https://cloud.githubusercontent.com/assets/12228435/13836920/a0c197ba-ebc3-11e5-8ce8-f347c983dea3.png)

v2  -  display pledge form modal after video play
![encryption-ui-022-04](https://cloud.githubusercontent.com/assets/12228435/13836924/a80fca96-ebc3-11e5-83e2-f2fa7703be3b.png)

**Comment by alanmoo** [comment]
These look pretty straightforward. What will the URLs look like? (Direct/social?)

**Comment by OpenMatt** [comment]
@alanmoo does this seem feasible to get done today / tomorrow before you go on PTO next week?

**Comment by valianttry** [comment]
This looks good -- now that I see it in the UX, seems that somewhere on the pledge, near the form fields, we need to be clear that people are opting in to receive email. Right now it looks like you're just signing something and it's not transparent that means you're opting in for future communications. Even if most people who sign this are already opted in, we should still be clear. There is a sentence or existing language from the /signup form that can likely be ported over for this purpose (easy enough).

**Comment by lovegushwa** [comment]
@alanmoo sorry for not clarifying:
v1 - email
v2 - social / organic

**Comment by lovegushwa** [comment]
@alanmoo strings of copy for landing page:

v1
LEFT
Pledge to stand up for Strong encryption

We’re seeing more and more governments attempt to undermine encryption. Will you help others understand what encryption is and stand up for strong encryption when it matters most? Sign on to be an encryption champion.

RIGHT
Become an Encryption champion

Let us know what country you’re in so if debates are happening in your country we can email you the most relevant updates. We’ll also send you useful tips about how to use encryption that you can share with friends. 

MODAL
Thanks for signing the pledge! Can you help us spread the word?  

v2
VIDEO
Stand Up For Strong Encryption

We’re seeing more and more governments attempt to undermine encryption. You can help  stand up for strong encryption when it matters most.

TOP OF PAGE
Become an encryption champion
( Take the Pledge )

LOWER LEFT
Take the Pledge 

Will you help others understand what encryption is and stand up for strong encryption when it matters most? Sign on to be an encryption champion.
( Sign now )

MODAL LEFT
Pledge to stand up for strong encryption

We’re seeing more and more governments attempt to undermine encryption. Will you help others understand what encryption is and stand up for strong encryption when it matters most? Sign on to be an encryption champion.

MODAL RIGHT
Let us know what country you’re in so if debates are happening in your country we can email you the most relevant updates. We’ll also send you useful tips about how to use encryption that you can share with friends.

**Comment by lovegushwa** [comment]
@alanmoo Updated UI, big changes to v2 modal

v1
![encryption-ui-023-01](https://cloud.githubusercontent.com/assets/12228435/13857950/82f190f2-ec39-11e5-993e-0630f74aa70d.png)

v1
![encryption-ui-023-02](https://cloud.githubusercontent.com/assets/12228435/13857954/88d9a680-ec39-11e5-97c5-b9bc75fbd379.png)

v2
![encryption-ui-023-03](https://cloud.githubusercontent.com/assets/12228435/13857960/8cb07f7c-ec39-11e5-8f78-4b00aa67c262.png)

v2
![encryption-ui-023-04](https://cloud.githubusercontent.com/assets/12228435/13857965/913d6cb2-ec39-11e5-98db-fd811998212b.png)

**Comment by lovegushwa** [comment]
@alanmoo some details to help with the build:

![screen shot 2016-03-17 at 10 56 44 am](https://cloud.githubusercontent.com/assets/12228435/13858018/dfb62f1e-ec39-11e5-9ef6-fd7a5c9efc7e.png)

![screen shot 2016-03-17 at 12 16 46 pm](https://cloud.githubusercontent.com/assets/12228435/13858068/27385448-ec3a-11e5-9e96-7951364cdd09.png)

**Comment by shaghdoosti** [comment]
Sorry I'm a little confused -- where are we using the model? my assumption was that we'd be sending everyone to the version with the form on the right (which looks amazing by the way!) The difference would be we'd try to per-populate data from people who are already on our list -- and it would blank for people who are new to the list. 

This could have been a misunderstanding on my part -- but would love clarity. @stephaniemcv @lovegushwa

**Comment by lovegushwa** [comment]
Hi @shaghdoosti v2 is a evergreen version. However we can't count folks coming in on paid, organic and partner as "active advocate" so is there a reason not to give those channels the complete campaign narrative arch?  (unless were counting total pledges and active advocates separate?)

**Comment by alanmoo** [comment]
Questions:

1.) V1 Modal shows up only after clicking "Take the Pledge", right? Nothing happens after the video ends?
2.) V2 the modal above appears at the end of the video and when clicking the CTA? Does the share CTA appear in another modal after signing up?

**Comment by shaghdoosti** [comment]
@lovegushwa  --a few things: 
1. People who are coming in from paid promotions -- should go to the first video so they get the whole experience 
2. People coming in from social from beat 5 -- should go to the page where the pledge is on the right hand side. (They'll be counted as pledge signers but not active advocates.) 
3. In general -- on this beat I think we need to optimize for pledge signups -- which I think means capturing people straight after watching the video -- knowing that many of them won't watch the full thing. Therefore having the form on the right means we'll get more pledge signers than if we do it as a modual that comes up after the video. 

Does that clarify things?

**Comment by lovegushwa** [comment]
@shaghdoosti @HPaulJohnson let me know if I'm getting this right?

V1 - email, organic, social 
V2 - paid (load video 1 first).

**We will need a special URL for paid. Is this cool?**

**Comment by lovegushwa** [comment]
@alanmoo 

1.) V1 Modal shows up only after clicking "Take the Pledge", right? Nothing happens after the video ends?  ... **Nothing happens after the video plays**

2.) V2 the modal above appears at the end of the video and when clicking the CTA? Does the share CTA appear in another modal after signing up? ... **If it's not to weird to do back to back modals, yes.** @HPaulJohnson any feels about this?

**Comment by lovegushwa** [comment]
@alanmoo we should also display v2 modal when some one clicks on "Take the pledge" or "Sign Now" on the v2 page.

**Comment by HPaulJohnson** [comment]
@lovegushwa that's basically right for paid. We want a version that includes all the videos (v2) so we can send new visitors through the whole journey. We still want the flexibility to feature any of the videos through @alanmoo's awesome URL structure (/social/1, /social/2, etc) as we are still testing which videos do best at engaging the most people in our campaign. I think v2 as scoped here supports those efforts. 

I think for new visitors/social, the modal should be sign up. We don't need a second modal as long as they can click out after submitting and there's still the "share this" panel at the bottom of the main page. Again, v2 does everything we need it to do for paid/social.

**Comment by lovegushwa** [comment]
@shaghdoosti can you revise the "why do we ask for this information?" popup ? 

![screen shot 2016-03-18 at 9 50 15 am](https://cloud.githubusercontent.com/assets/12228435/13885294/e372ace4-ecee-11e5-9715-d79b38515679.png)

We care about your privacy and helping you make informed choices. That’s why we link to our Privacy Notice so you can easily read it. To receive emails we require only your email address — “First Name” and “Country” aren’t required to sign up, but if you tell us your country we can send you local news and events — it’s your choice!

**Comment by shaghdoosti** [comment]
Actually -- @valianttry what do you think here? After reading the text we have I feel like we should leave the country field as optional. @lovegushwa @alanmoo I know that's different to what I said -- but if this is the message people are seeing consistently It would be bad to not practice it.

**Comment by OpenMatt** [comment]
Blocked by https://github.com/MozillaFoundation/encryption_campaign/issues/222 and https://github.com/MozillaFoundation/encryption_campaign/issues/223

**Comment by alanmoo** [comment]
@mmmavis

**Comment by lovegushwa** [comment]
@alanmoo @mmmavis are we in good shape for hand off? Also do you have anything on staging for QA?

**Comment by alanmoo** [comment]
I've got a little more to do today/tomorrow but I explained everything to Mavis yesterday. Will post here when up on staging.

**Comment by alanmoo** [comment]
I believe I've taken care of all of this. It's up for testing at https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4 and https://lit-mountain-52009.herokuapp.com/encrypt/social/4.

Keep in mind the `/encrypt` route goes to the social page, so that's what http://mzl.la is still going to. I'm not sure what the desired out come of this all is.

I'm submitting a PR into the main repo for technical review, but noting that it shouldn't be merged until the appropriate video details are in.

Closing this issue for sanity, please open up individual issues and assign them to @mmmavis (but cc me in the body), as she'll be handling the rest of this while I'm on the road. (I've opened #225, for reference.)
