### ISSUE TITLE
Scope putting email sign-up field directly on snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#19]
Hey @ScottDowne 

We're brainstorming about the encryption campaign. I talked to Jean Collings about the possibility of putting an email field and submit button directly on the snippet for email optin to our Mozilla Foundation list. Here is what the snippet team has done (FF for Android) - below. What would it take to build this for the desktop? Assume this would be EN only, but possible also 1 other locale (likely PT-BR). 

![2016-01-13_1206_-_jcollings_s_library](https://cloud.githubusercontent.com/assets/9830371/12306941/497c9a4e-b9f1-11e5-81a7-5fd97dc5a55c.png)

cc @OpenMatt

**Comment by valianttry** [comment]
Here is the key content that needs to be embedded on the snippet:

![donate_mozilla_org___give_to_mozilla_today](https://cloud.githubusercontent.com/assets/9830371/12307109/2af5ca5e-b9f2-11e5-92c7-55025900636c.png)

**Comment by ScottDowne** [comment]
This is possible. Just make that button communicate with a server that communicates with exact target. This is all back end, the user doesn't visually go to anything, until it's all done and we can setup like a thank you/share page to send them.

Cannot do this directly from snippet -> exact target, I think.

Needs to be snippet -> petitions.mozilla.org(or something) -> exact target

**Comment by ScottDowne** [comment]
Multiple locales shouldn't be hard, we just need to know the country, and pass that to exact target, and I think the snippet already knows that, so we might not even need to ask them country, maybe.

**Comment by valianttry** [comment]
@ScottDowne here are follow up Qs:
- How much time do you think this would take for you to code after we nail design? 
- If the user does not ever need to see / be aware of the interim step using petitions.mozilla.org I think it's fine to just use it.

I will launch design and build tickets for this

**Comment by OpenMatt** [comment]
@ScottDowne can you answer those questions today?

**Comment by ScottDowne** [comment]
It'll take a day or two for dev. Turns out sending the sign up directly
from snippet to exact Target is possible. No need to put something like
petitions.mozilla.org in the middle. It'll be seamless to the user. We can
even display thank you/errors in the snippet. They'll never navigate away
if we don't want them to.

**Comment by OpenMatt** [comment]
@ScottDowne given that work is pressing ahead here https://github.com/MozillaFoundation/encryption_campaign/issues/23, can we close this one?

**Comment by ScottDowne** [comment]
Yup, totally :)
