### ISSUE TITLE
Design wrappers for Share Progress landing page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#192]
We need to add Mozilla/Encrypt campaign branding to our Share Progress share page. We'll also need to style the Share Progress buttons to be embedded on existing pages.

**Comment by HPaulJohnson** [comment]
Reviewed requirements for this with @lovegushwa. Step 1 (setting up new buttons on our existing pages) doesn't require design work so not needed for Beat 4 launch. Design needed for wrapper on dedicated sharing landing page and the goal is to have that work complete in time for Beat 5 launch to optimize sharing post-pledge.

**Comment by lovegushwa** [comment]
@HPaulJohnson I haven't had much time for this, let's connect Monday.

**Comment by OpenMatt** [comment]
@lovegushwa status?

**Comment by lovegushwa** [comment]
@HPaulJohnson this is something we can adjust the color on today to bring it a little closer to brand.
Sorry this is tight be let's make a tweak happen today.

**Comment by lovegushwa** [comment]
@HPaulJohnson super simple update to the share progress template. 

Mozilla logo (sized for this page):
https://drive.google.com/folderview?id=0B2qu3ExKWIlvbUpTV203azVVWnM&usp=sharing

Dark blue header color #1C325E
Light blue footer color #5381B9

<img width="1005" alt="screen shot 2016-03-22 at 3 31 19 pm" src="https://cloud.githubusercontent.com/assets/12228435/13969987/2fa980ea-f043-11e5-916f-4d87f77e80aa.png">

**Comment by HPaulJohnson** [comment]
@lovegushwa I think I need some help translating that to the HTML that Share Progress needs modified. I've included the HTML for the page below that needs updating maybe but @mmmavis maybe we could discuss tomorrow how this might work?

`<!doctype html>
`<html lang="en">
`<head>
` <meta charset="utf-8">
`<title>PAGE_TITLE</title> 
`<meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1">
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
`<link href="/basic.css" media="all" rel="stylesheet" type="text/css" />
`</head>
`<body>

`<div id="header"><div id="header_content"><h1>Mozilla Foundation</h1></div> 
`</div> 
`<div class="content"> {ShareAction}
`</div> 
`<div id="footer">
`<div id="footer_content">Page Disclaimer</div> 
`</div> 
`</body>
`</html>

cc @alanmoo

**Comment by alanmoo** [comment]
I'm not quite sure what you're asking- you need the background color on the header/footer? You should be able to add `style="background-color: #1C325E"` to the header tag to make it have a background color. (`<div id="header" style="background-color: #1C325E">`)

**Comment by HPaulJohnson** [comment]
Finishing the dev work part of this in #233
