### ISSUE TITLE
Update share message on landing page for Beat 4

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#196]
Current share language is specific to Video 2, including images of Crypty. We need to update for launch of 3rd video on 3/9.

Eventually we'll test a bunch of different messages via Share Progress but as a baseline we'll start with something more generic that fits all videos. 

@lovegushwa working on Facebook and Twitter graphics for cards. Copy is here: https://docs.google.com/document/d/1te8zKolI_Fn-96Bn4g0LsZc8NxD6bKqB2AdZV9SFI70/edit

@alanmoo I will ping you tomorrow when this is ready to be updated.

**Comment by lovegushwa** [comment]
@HPaulJohnson check out the shares here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvaXkxdFdQNFBXTlk&usp=sharing

Let me know which of these you want to set as default for beat4 (in-case share progress is not up and running.)

**Comment by HPaulJohnson** [comment]
@alanmoo - Here is the default share copy for email/twitter/facebook buttons on landing page. Regardless of whether we can implement Share Progress in time, we should use these to update site in time for Video 3 launch tomorrow. 

**Email Share:**
[subject] Learn why encryption matters
[body] This video explains why encryption is so important. You should watch it and share it with your friends to start a conversation. Check it out at https://advocacy.mozilla.org/encrypt

*_Facebook Share: *_
[header] Encryption matters
[body] I care about protecting #encryption and you should too. To learn more about how it works and why it’s worth protecting, check out this great site from @Mozilla at https://advocacy.mozilla.org/encrypt 

![encryption-facebook-card](https://cloud.githubusercontent.com/assets/10078715/13619079/1d202bac-e53c-11e5-9292-f9db94cec426.png)

**Twitter Share:**
I care about #encryption and you should too. Learn more about how it works from @Mozilla at mzl.la/encrypt

![encryption-twitter-card](https://cloud.githubusercontent.com/assets/10078715/13619091/22662fbc-e53c-11e5-8072-36db139d0949.png)

**Comment by HPaulJohnson** [comment]
@lovegushwa all the options look so good. lot's of good stuff to start testing with here.

**Comment by HPaulJohnson** [comment]
Code for Share Progress buttons generated in #191
