### ISSUE TITLE
Email 4 - New Color Palette

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#197]
@lovegushwa 
There's been concern about our campaign templates looking too similar to Firefox and You. Can we move toward a less grey/blue color scheme?

I would need a new background color, top bar color, button color. 

For images I would need a new Mozilla logo (190px × 49px) and Facebook and Twitter icons (45px x 45px) - this is an increase in size so they're easier to tap on a mobile device

![templated](https://cloud.githubusercontent.com/assets/11812272/13605574/754d5886-e505-11e5-979a-cdc0ff4afb3b.jpg)

**Comment by lovegushwa** [comment]
@stephaniemcv working on this now.

**Comment by lovegushwa** [comment]
@stephaniemcv @valianttry 

Hi friends, my preference is B. 
I think this "Warm" option is different enough from the firefox and you template.

We could also do C. but the lighter blue header will end up being less flexible (might clash with colors in the header image on future emails for example.)

<img width="1197" alt="screen shot 2016-03-08 at 5 49 57 pm" src="https://cloud.githubusercontent.com/assets/12228435/13622818/593c4b10-e556-11e5-883d-39088a849d18.png">
Option A is the original template.

**Comment by lovegushwa** [comment]
@stephaniemcv

If option B you just need to change the background and button. If C, I included the new blue for the header and logo below as well. 

<img width="698" alt="screen shot 2016-03-08 at 8 13 18 pm" src="https://cloud.githubusercontent.com/assets/12228435/13625242/5be98bc0-e56a-11e5-8b8b-0ba867f3ae7d.png">

**Comment by lovegushwa** [comment]
@stephaniemcv logos and icons here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvbjQyd2JPUGRHV28&usp=sharing

**Comment by valianttry** [comment]
@lovegushwa what do you think about making "mozilla" red? That connects it a little more to our original template design (with a large red wordmark). I really like the red button and the updated background shade! Thanks @lovegushwa :clap:

**Comment by lovegushwa** [comment]
@valianttry @stephaniemcv 
If we use the red I would go with option F (red logo, mini header, button) ... We're not using this mozilla red in the visual system (we use a lighter neon red) so I would recommend option B for now. 

<img width="1100" alt="screen shot 2016-03-09 at 9 41 36 am" src="https://cloud.githubusercontent.com/assets/12228435/13644598/73bf03a8-e5db-11e5-99ff-270ec9b9f9d5.png">

**Comment by lovegushwa** [comment]
Mozilla red: #C13832
