### ISSUE TITLE
Update landing page / beat 4 video

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#198]
@alanmoo @HPaulJohnson 
Working through this check list now.
- [x] Video 3 poster image
- [x] Video 3 thumbnail @2x
- [x] Video 3 for email ( 600x300 )
- [x] Video 3 copy
- [x] Video 3 social share images
- [x] Video 3 / compressed video files

**Comment by lovegushwa** [comment]
Video 3 copy:
https://docs.google.com/document/d/1rZnC_4uIv7fVlps_RwTIcDR4ohHgIxN6vt_eLMEWcwo/edit

@HPaulJohnson @KevZawacki can you confirm the changes in this doc?

**Comment by HPaulJohnson** [comment]
@lovegushwa - copy confirmed for Video 3 descriptor on landing page

**Comment by alanmoo** [comment]
Sorry, I can't figure out what I'm looking at. What are the strings I need to put in the video title and description?

**Comment by HPaulJohnson** [comment]
Here is the copy for video 3: 

Episode 3: March 9, 2016 
Encryption, Journalism, and Free Expression 

Encryption doesn’t just protect your privacy — it also enables free expression. Encryption shields journalists and their sources, allowing individuals to tell powerful stories without placing themselves in imminent danger.

**Comment by lovegushwa** [comment]
@alanmoo social share images are here: #196

**Comment by HPaulJohnson** [comment]
Updated copy also in #196 

These should be the default for tomorrow, regardless of how far we get Share Progress implementation today.

**Comment by lovegushwa** [comment]
@alanmoo 
Poster: 
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvUU5sY2NiU05uamc/view?usp=sharing

Thumbnail: 
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvbGY4ZFdtdmpFblU/view?usp=sharing

**Comment by alanmoo** [comment]
What is the CTA that appears after the video in the modal on the "direct from email" page?

**Comment by lovegushwa** [comment]
@HPaulJohnson 
Can you sort out a new Share CTA for @alanmoo ?

<img width="1366" alt="screen shot 2016-03-08 at 4 02 06 pm" src="https://cloud.githubusercontent.com/assets/12228435/13620782/2a1dd934-e547-11e5-8c1e-c31701115ce6.png">

**Comment by HPaulJohnson** [comment]
Let's replace with this copy: "Help spread the word about encryption and why it's worth protecting"

**Comment by lovegushwa** [comment]
@alanmoo @simonwex 
Here are the final videos:

LANDING PAGE:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvbTd6MkFPem1ieEE&usp=sharing

NATIVE (for facebook):
https://drive.google.com/file/d/0B2qu3ExKWIlvTy1wbXdKOWxONUE/view?usp=sharing

**Comment by alanmoo** [comment]
These are live on the test server I set up in #200, awaiting approval from @alicoding in the morning to deploy to staging
