### ISSUE TITLE
Process initial invoice from ASC

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#2]
in progress

**Comment by OpenMatt** [comment]
wire transfer will go out today / tmrw I believe

**Comment by OpenMatt** [comment]
Paid. Done!

**Comment by rohanporteous** [comment]
Great, thanks! How's the next contract/payment going for the project in full?

**Comment by OpenMatt** [comment]
Mailing out the contract tmrw https://github.com/MozillaFoundation/encryption_campaign/issues/1

**Comment by rohanporteous** [comment]
Perfect! Can you please CC both lara@ and katrina@ as well? (Head of Ops and Finance Manager, respectively).
