### ISSUE TITLE
Scope audience segmentation needs

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#20]
@adamlofting we are starting to develop a plan for email strategy and have Qs about our segmentation capabilities.

We anticipate that we will want to select audience segments based on the following attributes (we may think of others):
-- previous actions on campaigns such as Net Neutrality or German data retention in BSD (e.g. we may want to customize content for more committed action takers vs. people brand new to our list)
-- opens (opened any previous encryption campaign messages; opened message 1 but not message 2; etc) 
-- click through (on specific messages)
-- donors (in case we run a fundraising appeal during the course of the campaign). We may want to target donors who have donated during an advocacy campaign in the past
-- geo (country or language)

We anticipate sending up to 2 messages per week throughout the 3-month campaign calendar.
We also would ideally like to set up some custom "welcome" or email on-boarding strategy based on variants such as source/channel. Is Journey Builder functional?

cc @OpenMatt @shaghdoosti

**Comment by adamlofting** [comment]
> opens (opened any previous encryption campaign messages; opened message 1 but not message 2; etc)
> click through (on specific messages)

These two are part of Exact Targets standard tracking

> donors (in case we run a fundraising appeal during the course of the campaign). 

We have the same donor history data that we used during EOY - is donor / is monthly donor / HPC / etc

> We may want to target donors who have donated during an advocacy campaign in the past

Out of scope for now. We haven't linked our donation history to campaigns in the past. This is a future goal for Salesforce CRM.

> previous actions on campaigns such as Net Neutrality or German data retention in BSD (e.g. we may want to customize content for more committed action takers vs. people brand new to our list)

This is part of the Salesforce CRM plan. This data isn't currently in Exact Target. If MoCo / DEG can support like they did for EOY we can do a interim data job like we've done for the EOY donor data.

> geo (country or language)

Just what we've currently recorded in the database. Country code, and language. Language is EN for all except the new DE group.

> We anticipate sending up to 2 messages per week throughout the 3-month campaign calendar.
> We also would ideally like to set up some custom "welcome" or email on-boarding strategy based on variants such as source/channel. Is Journey Builder functional?

No Journey Builder yet. @jessilyndavis could confirm, but I don't think it's on a roadmap in time for this campaign.

We can add a Welcome email to our mofo list though, and it could be tailored to encryption for the course of the campaign.

**Comment by adamlofting** [comment]
I think the options available are noted above, so assigning this ticket to @valianttry to choose what segmentation we want to implement. Then we should file tickets to follow up on those decisions.

**Comment by OpenMatt** [comment]
@valianttry let us know next steps / when those tickets have been filed so we can close this one.

**Comment by OpenMatt** [comment]
@valianttry will co-ordinate with @shaghdoosti on next steps for this one

**Comment by valianttry** [comment]
@stephaniemcv

**Comment by OpenMatt** [comment]
@valianttry any updates on this one?

**Comment by valianttry** [comment]
We have an email strategy meeting scheduled for next week. (Wed)

**Comment by valianttry** [comment]
I have done some analysis of our past advocacy campaigns, my scratch sheet is here:
https://docs.google.com/spreadsheets/d/1_QfHfOTBmGJFyo5USxCpK-2o2D-Jc4LVkSpnShDfLNI/edit#gid=2140398734

I'm going to add a summary here in a bit.

**Comment by adamlofting** [comment]
Given the time, I think we should restrict the possible scope of this request as it will require manual data wrangling and coordination with DEG.

We have a database table similar to our donation records which is a record of all the constituent groups people are in. We can use this to build a list of people who have taken specific previous actions. E.g. flag all people who Signed NN petition, or signed surveillance petions etc. But, we'll need to get the specific list of constituent groups from BSD to make this selection.

This is also only worth doing if we're delivering different content based on this data. E.g. people who have taken a previous action will get a different email.

This is all possible, but lets make sure we're using energy well. Ie is the message we're sending different enough (and likely to make enough difference) to be worth spending the time on this data wrangling at this point in the campaign? It definitely was worth if for EOY. It may or may not be in this case.

**Comment by valianttry** [comment]
I think we can learn a lot by segmenting people who participated in at least one campaign in 2015. I've opened a new ticket to create 2 new constituent groups: #86

**Comment by OpenMatt** [comment]
Thanks guys. @valianttry now that you've filed #86, do we still need this ticket?
