### ISSUE TITLE
Beat 4 QA

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#200]
I've got the site up at https://lit-mountain-52009.herokuapp.com/encrypt/
https://lit-mountain-52009.herokuapp.com/encrypt/direct
https://lit-mountain-52009.herokuapp.com/encrypt/hybrid

Please play around with URLs (such as ones from previous emails, changing out the base domain for the one above) and switching between videos, and make sure share messages are correct. The card images will not be updated until the site goes live.

@HPaulJohnson @brettgaylor @valianttry

**Comment by HPaulJohnson** [comment]
@alanmoo Quick run through and everything looks good (with exception of cards which I realize we can't test until tomorrow). 

All of the old/existing links (in social and paid media channels, at least) don't break with this new URL structure. However, it is problematic in a few isolated cases where we referenced video 2 and just used the generic short link. Example: https://twitter.com/mozilla/status/702587745995247616. There are only a few isolated cases like this one so I don't think it's a deal breaker (and the response curve on these is pretty complete) but wanted to point it out as these generic links will point to video 3 as part of the default starting tomorrow, correct?

**Comment by HPaulJohnson** [comment]
I should also note that the issue above is exclusive to Twitter. On Facebook posts we can go back and edit the link retroactively to point to the appropriate video; on Twitter we can't edit existing tweets.

**Comment by HPaulJohnson** [comment]
@alanmoo one more note about Facebook share is that the default URL that FB displays is now d.shp.org - that's because we are using the Share Progress code to generate these I assume. 

See screenshot here: https://www.evernote.com/shard/s46/sh/100df303-ccb8-41dd-bf08-a13d1823f635/16b32d733dc46132aa0f4e411e6395df

I have a question about this out to Share Progress to see if we can address (it's a bit weird branding wise from a user's perspective). It might be solve with the custom subdomain that we've created (share.mozilla.org); I'm hoping when they adjust for this on their end that URL will show up instead.

**Comment by alanmoo** [comment]
You are correct about everything. The short url has always linked to the latest video, that was my understanding of its intended behavior from the beginning.

**Comment by HPaulJohnson** [comment]
@alanmoo cool, thx - we'll just live with the twitter awkwardness then (it's only a few posts that are more than a week old), update links on Facebook to point to correct video and try to address the d.shpg.org URL that is showing up on FB share on the Share Progress side.

**Comment by lovegushwa** [comment]
@alanmoo Looking great!
I have only one fix, on the hybrid version can we fix the paragraph so the last word "danger" is not all by itself? Maybe squeeze the column so "imminent" returns down to the next line. 
![screen shot 2016-03-09 at 9 27 34 am](https://cloud.githubusercontent.com/assets/12228435/13644191/5dd3a51e-e5d9-11e5-8e87-cec610c8e1dc.png)

**Comment by davidascher** [comment]
Typographic geek sez:
Use a non breaking space before danger. Width independent. (Aka cheap
orphan control).

**Comment by alanmoo** [comment]
Brilliant!
