### ISSUE TITLE
Triggered email for Beat 5 pledge

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#201]
With beat 5 the idea is we want people to sign a pledge. On the page there will be a form that's much like a petition. Once people sign the pledge we want to send them an email that gives more information on software they can use and a pro forma email they can send. 

@stephaniemcv is working on this issue and I'll let her elaborate. Also wanted to flag for @alanmoo 

CCing @brettgaylor and @valianttry too.

**Comment by OpenMatt** [comment]
@shaghdoosti status?

**Comment by stephaniemcv** [comment]
We can close this. We didn't have to time to make this happen.
