### ISSUE TITLE
Page titles?

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#203]
Simple question, but we probably should have the microsite `<title>` tag be something other than "Mozilla Advocacy", no? When links get shared on the web that pull that tag, they're not [very](https://news.ycombinator.com/item?id=11222993) [engaging](https://news.ycombinator.com/item?id=11148417)...

**Comment by brettgaylor** [comment]
Yes, good flag!  We don't actually have a formal name for the campaign.  What about "Learn about encryption - Mozilla Advocacy" cc @valianttry

**Comment by valianttry** [comment]
seems good to me :+1:

**Comment by OpenMatt** [comment]
@alanmoo ok for you? shall we close?

**Comment by alanmoo** [comment]
Assigned to myself until I implement

**Comment by mmmavis** [comment]
https://github.com/mozilla/advocacy.mozilla.org/pull/123/commits/5323ef7a6d28760acf38b388ff71a536a66995b8 covers this. Closing this ticket now.
