### ISSUE TITLE
Beat 5 emails in layout review

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#206]
Please review the email copy, links and rendering. Note any feedback in this ticket.

**Comment by OpenMatt** [comment]
@stephaniemcv next steps / timelines on this one?

**Comment by stephaniemcv** [comment]
I need final url and image before I can route around for layout review

**Comment by lovegushwa** [comment]
@stephaniemcv I did not see my name, but mail was pre-populated. Could be my name is not in the database? ... or perhaps the form auto fills with email?

![screen shot 2016-03-30 at 4 10 45 pm](https://cloud.githubusercontent.com/assets/12228435/14160637/5dc4dcae-f692-11e5-82f6-9a86e478ba7c.png)

Shows I added my name and "Qatar" before submitting. 
![screen shot 2016-03-30 at 4 11 05 pm](https://cloud.githubusercontent.com/assets/12228435/14160644/667bacd8-f692-11e5-83ef-baad87a2be65.png)

**Comment by natalieworth** [comment]
@stephaniemcv Mine email was also pre-populated like Jordan's. I also selected 'Canada' as my country.

**Comment by stephaniemcv** [comment]
@lovegushwa @natalieworth  Country info passed through! Yay!
And name will not populate, just email address, we didn't want to look too creepy.

**Comment by brettgaylor** [comment]
I signed up , Canada, brett@mozillafoundation.org

**Comment by stephaniemcv** [comment]
@brettgaylor Country info success!

**Comment by valianttry** [comment]
@stephaniemcv I selected United States -- email of record is andrea@mozillafoundation.org and it auto-populated.

THIS IS SO HIGH TECH WE'RE AWESOME :tada:

**Comment by valianttry** [comment]
@stephaniemcv just noticed that the URL text appears to be a smaller font than the rest of the email:

![_test_the_good_news_about_encryption_-_andrea_mozillafoundation_org_-_mozilla_mail](https://cloud.githubusercontent.com/assets/9830371/14164084/1975c5c6-f6b1-11e5-9bbb-113fc099e562.png)

**Comment by KevZawacki** [comment]
Email looks great! Tiny tweak: We should capitalize "web" in the P.S. 

I signed up: kevin@mozillafoundation.org, Zimbabwe.

**Comment by stephaniemcv** [comment]
@valianttry Country info confirmed! I bumped up the url font size by a point.

@KevZawacki Country info confirmed and "web" is now "Web"
