### ISSUE TITLE
Finalize all text for Beat Five video

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#209]
@mmika can you post a link to a google doc or etherpad here so we can track and approve?

**Comment by mmika** [comment]
@OpenMatt here's the link. I chose 5 headlines for the US, 5 for the UK and a few for France and India. As discussed w/ Sara, we are trying not to use headlines w/ 'US government' 'DOJ' 'Facebook' 'Apple' 'Backdoor' -- we're also not using Kazakhstan and Brazil. 

https://docs.google.com/a/mozilla.com/document/d/1T_uXwAPiy0QP_GpbgRkGqeL3T-avO3mp54sKNT9C2WA/edit?usp=sharing

**Comment by brettgaylor** [comment]
@mmika Can have 5 countries, though?

**Comment by mmika** [comment]
@brettgaylor Added Iran and South Africa to the doc -- though both those examples are particular cases. // In Iran there are 'claims' re banning encryption and very little reporting. -- the South African case is about encryption capabilities of TV boxes. Let's see if we can find a headline for Australia. Would love to keep it as diverse as possible. @shaghdoosti

**Comment by brettgaylor** [comment]
The headline I have for Australia currently is pretty useful:
"

Even Learning About Encryption In Australia Will Soon Be Illegal -
Lifehacker
"

_Should we go with that one?_

**Comment by shaghdoosti** [comment]
Yes -- love that headline from Australia. Let's make sure that we never describe the video as describing what's happening around the world though and maybe frame it as 'Here are some ways encryption is being undermined that you might not know about'

**Comment by brettgaylor** [comment]
+1 - I think with the current creative frame, it should be thought of less as an exhaustive list of international threats to encryption, and rather as a “raising of the stakes”.

**Comment by brettgaylor** [comment]
@shaghdoosti @mmika Please place final headline choices in this document:
https://docs.google.com/spreadsheets/d/1t4kJN-TAMPRoiRJY2XmUPp_ve5PqcD3xFS0-ahyFjyg/edit#gid=0

**Comment by mmika** [comment]
@brettgaylor @shaghdoosti done!

**Comment by brettgaylor** [comment]
@mmika @shaghdoosti I'm concerned about the India headline: "Uproar over Indian encryption law forces government to retreat -- Reuters"  This seems to suggest that the government is re-considering a bad law, which doesn't help the narrative of this particular video.  Can we use another country example that mentions "encryption" in the headline?

**Comment by OpenMatt** [comment]
@mmika @shaghdoosti @brettgaylor I'm assuming we can close this one -- please re-open if that's wrong.
