### ISSUE TITLE
add Stephanie to this repo

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#21]
hello @OpenMatt !

Can you make certain Maryam, Natalie, and Stephanie are all able to work in this repo? I tried to tag Steph and her handle didn't come up. There will be others who are in MoCo for example who we should be able to tag easily. Which leads to this question: Is this repo open or closed? It helps if it's open, unless there's a compelling argument to keep it closed / secure.

**Comment by OpenMatt** [comment]
The repo is fully open / public. New collaborators that aren't already automatically showing up can be added at the bottom of the page here:
https://github.com/MozillaFoundation/encryption_campaign/settings/collaboration

GitHub can't search it's entire user list every time you mention someone, so it asks that you point it at a given team or set of collaborators. Everyone on this Team MoFo will show up already:
https://github.com/orgs/MozillaFoundation/teams/mofos

If you know someone's GitHub username, you can still @mention them and it will work. Their handles just won't automatically pop up.

**Comment by OpenMatt** [comment]
- I added Natalie here: https://github.com/MozillaFoundation/encryption_campaign/settings/collaboration
- @valianttry : I can't find GitHub usernames for Maryam or Stephanie. Can you add them?

**Comment by stephaniemcv** [comment]
Hello!

**Comment by OpenMatt** [comment]
I think it's just Maryam who still needs to be added as a collaborator now
https://github.com/MozillaFoundation/encryption_campaign/settings/collaboration
