### ISSUE TITLE
Make storyboards for Beat 5 video

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#210]
Presentation deck w. early rough concept: https://docs.google.com/presentation/d/1B9DHjP_ldOFbOVGm4dQbt-O3DOlrjLNeC5Kwm8J-5kM/edit#slide=id.g11deee1bbf_0_34 

@darrenpasemko can you start work on storyboards and share here? 

cc @brettgaylor

**Comment by darrenpasemko** [comment]
Thanks Matt. Will do. I'm working on the boards today.

**Comment by darrenpasemko** [comment]
I'm working on the animatic, and the budget today.
I should have the animatic by this afternoon, and the budget will follow.
I would like to collaborate with Marc Ripper from Fort Ripper on this one (Karina's husband).
He would help me with Cinematgraphy, Assistant Direction, Editing, and Color. 
I will Produce, Direct, Assistant Edit, and Animate.
Karina Ripper is unavailable for this one sadly.
More to come.

**Comment by darrenpasemko** [comment]
@OpenMatt @brettgaylor Can delivery be the 23rd of this month? Next Wednesday?

**Comment by brettgaylor** [comment]
I think we need delivery EOD Monday in order to be able to package it for our campaigning.  There's also a pretty major event in the encryption news cycle that we will want to be able to hit.

**Comment by darrenpasemko** [comment]
Okay, it's going to be tight, but we'll make it happen.

**Comment by darrenpasemko** [comment]
@brettgaylor Here's the storyboard panels...
https://docs.google.com/document/d/15fsa2SKTj0NhoNPccqmqHli-eNBStgeh0HR1_PA0_Hs/edit
I'll cut this into an animatic this evening. More to come.

**Comment by darrenpasemko** [comment]
@brettgaylor @OpenMatt In terms of final delivery, are we thinking along the lines of Beat 2. Final Delivery: 1920X1080, H.264, 23.98 fps, 4:4:1. I'll also provide a Prores (HQ) version. Will you need still frames this time around too? Let me know. Thanks guys.

**Comment by darrenpasemko** [comment]
@brettgaylor @brettgaylor 
The animatic: https://vimeo.com/159176239
Password: mozilla
