### ISSUE TITLE
Develop social strategy for Beat 5

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#212]
@HPaulJohnson cool?

**Comment by HPaulJohnson** [comment]
@OpenMatt cool

**Comment by HPaulJohnson** [comment]
@lovegushwa and I talked about the basic deliverables for social support of beat 5: 
- Copy and embedded video version
- Copy + images of headlines/press clippings used in video
- Copy + short video clips or .gifs; 1 version of :15-:30 sec clip of primary video content + 1 version that is just the CTA around signing the pledge.

These will get us started in both organic and paid channels. We still have a few assets in the hopper from last beat and we will revisit additional concepts later this week/early next for extended/ongoing promotion of campaign via social.

**Comment by HPaulJohnson** [comment]
@KevZawacki has basic copy for use in social promotion of beat 5 

https://docs.google.com/document/d/1q5FSi_aK3sWQhwRIcM5y3A8iP0bQpywLTE7FvUlkizY/edit 

This has been submitted for approval today.

**Comment by KevZawacki** [comment]
The beat 5 social @HPaulJohnson links above has been approved.

**Comment by OpenMatt** [comment]
Cool. Anything further to do on this one, or can we close?

**Comment by lovegushwa** [comment]
@natalieworth we can also use this copy for the .gifs ... one with the phone drop and one with the phone returning to the hand: https://docs.google.com/spreadsheets/d/1t4kJN-TAMPRoiRJY2XmUPp_ve5PqcD3xFS0-ahyFjyg/edit#gid=0

**Comment by lovegushwa** [comment]
@natalieworth  

AI. for video cards, can be used for .gif (typography and copy) 
https://drive.google.com/folderview?id=0B2qu3ExKWIlvOFZzd2V0Z0Rwd2c&usp=sharing

**Comment by lovegushwa** [comment]
@HPaulJohnson final static facebook and twitter social graphics:
Twitter
https://drive.google.com/folderview?id=0B2qu3ExKWIlvNHZPcTBqTEc1RjQ&usp=sharing

Facebook
https://drive.google.com/folderview?id=0B2qu3ExKWIlvWGppelBuUWVsUHc&usp=sharing

**Comment by natalieworth** [comment]
@lovegushwa @HPaulJohnson I'm just uploading gif versions here from my after effects file. I'll upload the facebook one's first and then export to Twitter based on feedback/ approval :) https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvZXQ1ZFJ3SEc1S1U&usp=drive_web&ddrp=1#

**Comment by lovegushwa** [comment]
@natalieworth I love "the power is in our hands" ... I would increase the scale of that type substantially (also a note that I sent to Darren). 

Also it would be cool to do a combo version where we start with "will you stand up for strong encryption" ... phone animates to hand ... "the power is in our hands"

**Comment by HPaulJohnson** [comment]
+1 to @lovegushwa's comments. 

are we still planning on doing a version that flips through all the headlines too?

**Comment by lovegushwa** [comment]
@HPaulJohnson yeah I'm going to make that one today.

**Comment by natalieworth** [comment]
@lovegushwa @HPaulJohnson I have the gifs on the drive from last week:
Facebook(1200x630): https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0dXFhUzZlVzFaMW8&usp=drive_web&ddrp=1#
Twitter (1024x512): https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0c29BUW5UV01tclk&usp=drive_web&ddrp=1#
Let me know if any changes or additional gifs are needed and I can re-export :)

**Comment by HPaulJohnson** [comment]
@lovegushwa pasting the social assets you emailed this evening here so everything's in one place and closing this one out.  

GIFS:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvSTdKeGQzcGRxUTg&usp=sharing

Facebook:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvWGppelBuUWVsUHc&usp=sharing

Twitter:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvNHZPcTBqTEc1RjQ&usp=sharing

Video (check tomorrow late morning):
https://drive.google.com/folderview?id=0B2qu3ExKWIlvU255Nm03YThBckU&usp=sharing
