### ISSUE TITLE
Final pre-launch check-list and QA for Beat 5

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#213]
Let's do as much QA as possible now on this: https://lit-mountain-52009.herokuapp.com/encrypt/
https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4

**Comment by shaghdoosti** [comment]
Sara to check: 

All the copy on the page including landing page copy and video description to make sure they are correct and approved. 

Steph/Kevin/Sara/Maryam to check: 

If the form works ie: 
-Are the required field actually required
-are the optional fields actually optional
-do the explainer buttons work 
-When signing does the button work 
-Is the thank you page the right page

If the emails link to the right page
If the share buttons work 
If the video play works 

Design checklist
- [ ]  video poster
- [ ]  video thumbnail 
- [ ]  video metadata
- [ ]  email graphic
- [ ]  landing page and social video files
- [ ]  social graphic (for landing page share)

**Comment by OpenMatt** [comment]
Let's do as much QA as possible now on this: https://lit-mountain-52009.herokuapp.com/encrypt/
Primary page here: https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4

**Comment by alanmoo** [comment]
For above QA, please file a new ticket with labels "beat 5" and "dev" (making sure it's not a duplicate before opening, there are a few open already)

**Comment by stephaniemcv** [comment]
Just to clarify, this is the form for new people? We're not testing for if changed data passes back to Basket?

**Comment by lovegushwa** [comment]
@alanmoo looking great! 

Can you change the "--" to an em dash in the video 3 copy @mmmavis can also do.
<img width="1016" alt="screen shot 2016-03-21 at 1 33 23 pm" src="https://cloud.githubusercontent.com/assets/12228435/13933375/1e6b5fb2-ef6a-11e5-8f3e-47d1a12c926f.png">

---

[updates from Mavis] this has been fixed: https://lit-mountain-52009.herokuapp.com/encrypt/social/3

**Comment by shaghdoosti** [comment]
I just signed up and it looks good -- the only flag is that on the 'why do we collect information button' the paragraph that appears has really odd spacing. 

<img width="432" alt="screen shot 2016-03-21 at 1 58 02 pm" src="https://cloud.githubusercontent.com/assets/13626384/13933999/1956df62-ef6d-11e5-9d0c-698d2d5a92b1.png">

**Comment by HPaulJohnson** [comment]
Paul to check the following on the landing page:
- Social share buttons working correctly on all landing page versions, including Share Progress versions being served correctly and default meta tags updated with current video sharing info (descriptions and image).
- Google Analytics properly capturing opt-in and share measurements in a way that can be used to capture Active Advocates. @adamlofting what's the best way to QA this part?

**Comment by mmmavis** [comment]
re [your comment](https://github.com/MozillaFoundation/encryption_campaign/issues/213#issuecomment-199482284) @shaghdoosti :grin: 

> I just signed up and it looks good -- the only flag is that on the 'why do we collect information button' the paragraph that appears has really odd spacing. 

Could you tell me which browser you were on? It looks fine on my FF v45
<img width="1140" alt="screen shot 2016-03-21 at 5 05 30 pm" src="https://cloud.githubusercontent.com/assets/2896608/13938065/4b544ed6-ef87-11e5-978d-faf12b554e04.png">

**Comment by alanmoo** [comment]
This server is using a demo basket URL. If you're not concerned about testing garbage ending up in the database, we can switch it to submit to the real database.

**Comment by adamlofting** [comment]
> Google Analytics properly capturing opt-in and share measurements in a way that can be used to capture Active Advocates. @adamlofting what's the best way to QA this part?

This site doesn't have staging GA, so you'll need to test on prod. Check that the events are showing up in the real-time report: https://analytics.google.com/analytics/web/#realtime/rt-event/a49796218w86119768p89349767/

For active advocates (or our proxy measure) we need to ensure we add the GA tracking parameters to our emails so we can identify which traffic is from existing supporters. This is standard for us, but always worth double checking :+1:

**Comment by KevZawacki** [comment]
Just finished QA. One copy change: "Strong" in the hed should be lowercase (see screenshot below). 

![screen shot 2016-03-22 at 8 35 36 am](https://cloud.githubusercontent.com/assets/11045250/13951757/473c96dc-f009-11e5-9b8b-efa6388381b1.png)

@mmmavis Not sure this warrants its own ticket, but happy to open one if needed.

Onto @shaghdoosti's list: 

Are the required field actually required? **Yes**
Are the optional fields actually optional? **Yes**
Do the explainer buttons work? **Yes**
When signing does the button work? **Yes**
Is the thank you page the right page? **Yes**

If the share buttons work. **Yes**, but the copy is from beat 2
If the video play works. **Yes**

**Comment by OpenMatt** [comment]
@mmmavis can you make that copy change @KevZawacki noted?

**Comment by lovegushwa** [comment]
@KevZawacki @mmmavis actually for this version of the landing page the text should read as "Stand Up For Strong Encryption" to keep consistency with the other video titles.

**Comment by KevZawacki** [comment]
@lovegushwa A-ha, thanks!

**Comment by mmmavis** [comment]
@lovegushwa 

![screen shot 2016-03-22 at 1 21 32 pm](https://cloud.githubusercontent.com/assets/2896608/13969038/7e057970-f03d-11e5-95b5-1d30972f6c01.png) Should we change letter casing for the header in red as well or it's good as is?
