### ISSUE TITLE
Urgent: Copy change on the website

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#214]
The current copy on the site that describes the beat 4 video says: 

Encryption doesn't just protect your privacy -- it also enables free expression. Encryption shields journalists and their sources, allowing individuals to tell powerful stories without placing themselves in imminent danger. 

It needs to be urgently changed to: 

Encryption doesn't just protect your privacy -- it also  (helps) enable (remove s) free expression. Encryption (helps) shield (remove s) journalists and their sources, allowing individuals to tell powerful stories.

(please remove: without placing themselves in imminent danger.)

Clean version: 

Encryption doesn't just protect your privacy -- it also helps enable free expression. Encryption helps shield journalists and their sources, allowing individuals to tell powerful stories.

@alanmoo

**Comment by alanmoo** [comment]
What's the "Clean version"?

**Comment by shaghdoosti** [comment]
The clean version is the text as it should be appear -- the one on top of that shows the words I've added and cut. 

Just realized that github didn't display my original markings so updated that so that it shows.

**Comment by alanmoo** [comment]
https://advocacy-mozilla-org-staging.herokuapp.com/encrypt/social/3 that look good?

**Comment by shaghdoosti** [comment]
Yes -- thank you!

**Comment by alanmoo** [comment]
Ok, promoted to production. Should take about an hour to go around the world.
