### ISSUE TITLE
Bug in Chrome w/ unrendered HTML

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#215]
Hey Alan - I noticed today a weird thing where it looks like I'm seeing the template-free version of the page or something.  But it's only in Chrome.

It's on all the /encrypt URLs, as well as the Heroku page you put up for Sara's text changes.

I took a screencast - first is looking at stuff w/ Firefox, which is normal, then in Chrome
https://dl.dropboxusercontent.com/u/7968133/chrome%20bug.m4v

**Comment by alanmoo** [comment]
Yeah, I've noticed that too and have been investigating. Seems to be related to the routing changes I made...will continue to investigate.
