### ISSUE TITLE
Design snippet for video + email optin

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#22]
We have permission from the snippets team to test an embedded email optin directly on the desktop snippet. This has big implications for our ability to recruit encryption campaign participants with the least friction possible. An embedded email optin removes some usual friction from a typical optin sequence.

Usual sequence:
1.  clicking a text link in snippet >> 2. landing on a web page to fill out form fields [DONE]
New sequence:
1. type email, name into form fields and select country (dropdown) >>  click "submit" [DONE]

We should design 2 variants of this type of snippet: 1) with video replacing the Firefox logo; and 2) one with video placed below the logo and search bar.

@lovegushwa

**Comment by OpenMatt** [comment]
@lovegushwa see #23 for dev / build ticket w. @ScottDowne. Good screen grabs there.

**Comment by ScottDowne** [comment]
@lovegushwa if we want to vidyo some time, and just give me feedback on what I got now, and I make some or a lot of changes ;) Might be enough?

**Comment by valianttry** [comment]
@ScottDowne as soon as you have a solid view for screengrab, we probably want to run it by legal (hopefully it will be a quickish review). I'll also talk to Jean as they've obviously used optin on mobile snippet and likely had legal review that.

**Comment by OpenMatt** [comment]
@valianttry is wrapping up conversations w. legal today or Monday -- then will update here.

**Comment by lovegushwa** [comment]
@valianttry @OpenMatt any updates via legal?

**Comment by valianttry** [comment]
Sorry i only updated the build ticket: There is a meeting with legal tomorrow morning at 1030PST. I will have certainty after that.

**Comment by lovegushwa** [comment]
no problem! thanks.

**Comment by valianttry** [comment]
Confirmed from legal we do need a checkbox next to this text:
- I’m okay with Mozilla handling my info as explained in this Privacy Notice. (The words "this Privacy Notice" should be linked to: https://www.mozilla.org/en-US/privacy/websites/.) 
- Also confirmed we can now accept name in Basket!

So the snippet should have these elements:

[video]
[search bar]
"Mozilla stands up for online privacy. Will you join us? Sign up to get important email updates and opportunities to stand with us."
[first name]
[country]
[submit]
[checkbox] I’m okay with Mozilla handling my info as explained in this Privacy Notice.

**Comment by valianttry** [comment]
@ScottDowne is it possible that after someone clicks "submit" we can show a short message that says:

"Great! Look for a confirmation email in your inbox to complete your subscription."

@stephaniemcv how does this text sound to you?

**Comment by stephaniemcv** [comment]
I recommend we be extremely redundant and explicit in what the subscription is. 

"Great! Look for a confirmation email in your inbox to complete your subscription to our email list."

Not sure what we officially call it, email list, news list, communication list...

**Comment by valianttry** [comment]
+1 seems good!

**Comment by ScottDowne** [comment]
Yup I have placeholder text in there. It's configured in the snippet
service to whatever we want. I'll update my demo though to keep it in sync.

**Comment by OpenMatt** [comment]
@lovegushwa is any further design work needed here, or should we now close this and just push ahead in the build ticket?

**Comment by lovegushwa** [comment]
@OpenMatt let's move all work over to the build ticket
