### ISSUE TITLE
Add subtitles to Video 3

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#220]
To support the next phase of testing in paid media channel we'd like to test video with subtitles vs. one without (what we've been doing up until now). 

This will help us understand the value of adding subtitles to all future video content as we optimize for completed video views in this channel. 

Ideally we could ship these next week. 

cc:/ @brettgaylor @natalieworth @lovegushwa

**Comment by HPaulJohnson** [comment]
@natalieworth reviewed the transcript and this should be final, word for word, what needs to be subtitled. 

https://docs.google.com/document/d/1Udq82ffJ0FUKisC-b_KO3Hh9ovYbFXOhMmETo0qGXmY/edit

**Comment by natalieworth** [comment]
EN Subtitle version is exported and can be found on the drive here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2qu3ExKWIlvNzFCSDFRbmx5RlE&usp=drive_web&ddrp=1#
