### ISSUE TITLE
Autofill form from URL query params

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#223]
From what I understand, visitors directed from email will have query params that we need to use to auto populate the pledge form. The component should be able to handle this

**Comment by alanmoo** [comment]
@mmmavis, check with @stephaniemcv on the params that are going to be used.

I noticed in the encrypt-signup.jsx component  `valueLink` is being used, I'm not sure if that's necessary or not, as this was a copy from this component being used slightly differently elsewhere.

**Comment by stephaniemcv** [comment]
I believe parameters should be 

%%COUNTRY_%%

%%emailaddr%%

**Comment by mmmavis** [comment]
@alanmoo @stephaniemcv can you remind me which page users will be directed to from email? It is `https://advocacy.mozilla.org/encrypt/signup` (or testing purposes: https://lit-mountain-52009.herokuapp.com/encrypt/signup)? And what fields will be auto populated? All of country, first name, and email?

**Comment by alanmoo** [comment]
The signup URL is something else. They'll be directed to /encrypt/social or /encrypt/hybrid. Since it's the same signup component across the board, I was planning on looking for props (or a single object) getting passed in to the component. If it's there, pre-populate whatever data fields it has. Then from hybrid.jsx and social.jsx, pass the signup component this.props.params (or only the appropriate keys, depending on how you implement it)

**Comment by mmmavis** [comment]
Cool that makes sense.
So the urls included in email will be something like 

https://advocacy.mozilla.org/encrypt/social/?country=Canada&email=mavis@example.com

**Comment by alanmoo** [comment]
Yup, or /social/4?country=....

Stephanie, can you share a sample URL so we know exactly what we'll be working with?

**Comment by mmmavis** [comment]
@stephaniemcv 

For the URL, is it possible if we can include the country info in [2-letter format](https://github.com/mozilla/advocacy.mozilla.org/blob/master/components/encrypt-signup.jsx#L82-L780)? e.g., CA for Canada and DE for Germany? That way it would be so much easier to autofill the country field.

**Comment by mmmavis** [comment]
https://lit-mountain-52009.herokuapp.com/encrypt/social/4?country=ca&email=mavis@example.com
https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4?country=ca&email=mavis@example.com

**Comment by stephaniemcv** [comment]
This is the only example of a URL passing data that I've seen in ExactTarget
https://www.mozilla.org/newsletter/existing/%%TOKEN%%/

It looks like the field in Basket can accept up to 30 characters but I like the idea of keeping it to the 2 letter country code.

**Comment by OpenMatt** [comment]
@mmmavis are the next steps clear on this one? need any help?

**Comment by mmmavis** [comment]
ummm I don't know how we can parse "TOKEN" into name and country. Is there a database or service we can look up for name and country **from** token?

@stephaniemcv do you know what a token is? is it like user account name sort of thing?

**Comment by mmmavis** [comment]
ummm I don't know how we can parse "TOKEN" into name and country. Is there a database or service we can look up for name and country **from** token?

@stephaniemcv do you know what a token is? is it like user account name sort of thing?

**Comment by mmmavis** [comment]
oops close by accident

**Comment by stephaniemcv** [comment]
Oh sorry, that was an example of what I'd seen. We're not actually supposed to use TOKEN
It's a field pulled from Basket like the other parameters

**Comment by mmmavis** [comment]
@stephaniemcv if %%COUNTRY_%% and %%emailaddr%% are available to us, would something like this work?

https://advocacy.mozilla.org/encrypt/social/?country=%%COUNTRY_%%&email=%%emailaddr%%
https://advocacy.mozilla.org/encrypt/hybrid/?country=%%COUNTRY_%%&email=%%emailaddr%%

**Comment by stephaniemcv** [comment]
let me try it in the email

**Comment by stephaniemcv** [comment]
Well it takes me to the landing page. I also used https://advocacy.mozilla.org/encrypt/hybrid and it didn't populate any data.

**Comment by mmmavis** [comment]
Ah sorry @stephaniemcv , changes haven't been pushed to production (advocacy.mozilla.org) yet. Could you please use any of 
https://lit-mountain-52009.herokuapp.com/encrypt/social/?country=%%COUNTRY_%%&email=%%emailaddr%%
https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/?country=%%COUNTRY_%%&email=%%emailaddr%%
just for testing purposes for now? Also let me know if I can help with testing! 

Thanks for helping!

**Comment by stephaniemcv** [comment]
Woo! It's looking good! First test pre-populated the email and then passed my name and new country data through!
