### ISSUE TITLE
Test mobile functionality of sign up modal

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#225]
I've got `overflow: scroll` in there, but I'm not sure it works properly, haven't had a network setup that I can test on a real device.

STR: 
1. Open `/encrypt/social` route
2. Tap `Sign now` below video.
3. Try to sign up.

**Comment by mmmavis** [comment]
Signing up on https://lit-mountain-52009.herokuapp.com/encrypt/social on my iPhone 6s worked out fine!

**Comment by OpenMatt** [comment]
@mmmavis what are the next steps to closing this one? Any further testing required? 

cc @simonwex in case he has guidance to offer...

**Comment by mmmavis** [comment]
I'll ask someone who has an Android phone (or anything other than iPhone 6s) to test before I close this ticket.

**Comment by lovegushwa** [comment]
@mmmavis @alanmoo 
https://lit-mountain-52009.herokuapp.com/encrypt/social signup form works on my nexus 5, this is NOT the page that's getting the bulk of our traffic. 

https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4 is getting the bulk of the traffic, that form works.

**Comment by alanmoo** [comment]
Great, closing as this is on staging.
