### ISSUE TITLE
Update assets for video 4

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/encryption_campaign#226]
Need thumbnails, poster, and video files. @lovegushwa, please post those here and assign this to @mmmavis for implementation when ready, cc @simonwex for upload of video as usual.

**Comment by mmmavis** [comment]
note for myself: 
this is the file to update: https://github.com/mozilla/advocacy.mozilla.org/blob/master/data/encryptVideos.js

**Comment by OpenMatt** [comment]
Blocked on https://github.com/MozillaFoundation/encryption_campaign/issues/211

**Comment by lovegushwa** [comment]
@mmmavis attached are the poster and thumbnail images for video 4:

Thumbnail: 
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvdWotUmlHME1Nb2s/view?usp=sharing

Video poster:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvZllBWVFBOTB2LTA/view?usp=sharing

**Comment by lovegushwa** [comment]
@alanmoo ^

**Comment by alanmoo** [comment]
Will be closed by https://github.com/mozilla/advocacy.mozilla.org/pull/121
