### ISSUE TITLE
Design/ Editorial Illustrations for Medium Article

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/encryption_campaign#230]
Create illustrations for @KevZawacki 's upcoming Medium article: https://docs.google.com/document/d/1lcZhH3HT8ut4EN-UX4q6jzFk3Azf3RoYgeY-FFIs9uQ/edit

**Comment by KevZawacki** [comment]
@natalieworth, let me know how I can help

**Comment by natalieworth** [comment]
@KevZawacki thanks, I'll ping you tomorrow morning if that works. @lovegushwa was hoping we could try and experiment a bit with the illustration/ editorial opportunities for this medium post which would be awesome! Going to look at a couple of benchmarks tonight for them.

**Comment by natalieworth** [comment]
hey @KevZawacki, when are you needing these illustrations by? Jordan and I have started a moodboard here: https://www.pinterest.com/nataliejworth/editorial-illustration/ and are working on them this afternoon, but wasn't sure if you were needing these asap?

**Comment by KevZawacki** [comment]
Hi @natalieworth, these illustrations definitely aren't a P1 -- Paul and I aren't anticipating publishing for another couple weeks, at least. We'll likely end up using the blog / illustrations alongside Codemoji.  

Really dig the mood board, btw!

**Comment by HPaulJohnson** [comment]
+1 to @KevZawacki - I think we will use this as part of our ongoing promotion, especially in parallel with code-moji. Not a p1 and I'm going to remove Beat 5 label.

**Comment by natalieworth** [comment]
@KevZawacki @HPaulJohnson Just confirming that this will still be posted with the upcoming Codemoji release? I've started creating these illustrations for it so far. I still have to refine and create an additional one:
![isometric_v4_artboard 2](https://cloud.githubusercontent.com/assets/14876567/15306571/a06a06c0-1b80-11e6-8715-58e37ecd9a9e.png)
![isometric_v4-03](https://cloud.githubusercontent.com/assets/14876567/15306572/a2708f02-1b80-11e6-9b65-5d06a32c8cbd.png)
![isometric_v4-04](https://cloud.githubusercontent.com/assets/14876567/15306573/a3d6d0f4-1b80-11e6-9130-75dccd509338.png)

**Comment by KevZawacki** [comment]
@natalieworth These are fantastic -- thank you!

We're still working with the Issues Durable Team to determine when/where the Codemoji + History of Encryption blog will publish. 

But in the meantime, we can use these designs in our existing medium.com/encryption-matters stories. Can I pull the images directly from this ticket? Or is there a Drive folder?

**Comment by natalieworth** [comment]
@KevZawacki Awesome! I've just got to finish off 2 with the texture and fix one of them. Did you need them asap?

**Comment by KevZawacki** [comment]
@natalieworth No rush! Anytime before the end of May should work. Does that sound doable?

**Comment by natalieworth** [comment]
@KevZawacki Yes! That works great!

**Comment by natalieworth** [comment]
@KevZawacki I have the first 3 illustrations finished and they are on the drive here:
https://docs.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0bjJ3WFhJRVB2Tms&usp=drive_web
I can make additional one's as needed depending on the content, so feel free to leave any ideas or updates here :) The current 3 I based on 'Encryption Through the Ages' article: (1)iphone + FBI, (2) encryption and eCommerce development from the 90's for online shopping, and (3) Caesar's cypher

**Comment by KevZawacki** [comment]
@natalieworth These are awesome. Thanks again!
