### ISSUE TITLE
Update defult facebook and twitter cards on new landing pages

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#231]
@alicoding super simple update to the default facebook and twitter cards on the video 4 landing pages. 
This should be updated right before we go live (March 28 is perfect.) 

Please update these images:
cc @HPaulJohnson 

Twitter:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvdnpzZ2Q5WHRtVzA/view?usp=sharing

Facebook:
https://drive.google.com/file/d/0B2qu3ExKWIlvaloyNHlxVi1pajA/view?usp=sharing

**Comment by lovegushwa** [comment]
@HPaulJohnson can you provide @alicoding any updated text?

**Comment by HPaulJohnson** [comment]
@alicoding here is the update default language:

twitter: Encryption needs you! Sign Mozilla's pledge to stand up for encryption & a more secure Web at mzl.la/encrypt

facebook: Encryption needs you! Sign Mozilla's pledge to stand up for encryption and a more secure Web at advocacy.mozilla.org/encrypt

**Comment by alicoding** [comment]
Currently we don't do share for text and image differently per video... They're all using the same share text and image. Is this suppose to be for all pages or specific to a URL?

**Comment by lovegushwa** [comment]
@alicoding your right we do use the same share text and image for all videos. Sorry the title of this ticket is confusing ... anyhow that's why we want to update it next Monday before we launch.

**Comment by alicoding** [comment]
https://github.com/mozilla/advocacy.mozilla.org/pull/124

**Comment by HPaulJohnson** [comment]
@alanmoo do you have the URL of where these images will be hosted. Need that to do some final testing on the Share Progress page/buttons.

**Comment by alanmoo** [comment]
From Ali's PR linked above,

https://advocacy.mozilla.org/assets/img/share/Encryption-facebook-b5-06.png
https://advocacy.mozilla.org/assets/img/share/Encryption-twitter-b5-06.png

But they're not up at those URLs yet
