### ISSUE TITLE
Finalize wrapper and publish new share page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#233]
@alanmoo per our conversation today, we need to clean up the Share Progress page wrapper called "Encryption Campaign." Final tweaks including: 
- Adding Mozilla logo to header
- Adding link back to advocacy site in header
- Fixing display in footer

Once that's done, I can use the completed wrapper to generate the URL for the final share page.

**Comment by alanmoo** [comment]
@HPaulJohnson  @lovegushwa  can you log in to share progress and check out the wrapper to make sure it's right?

**Comment by HPaulJohnson** [comment]
@alanmoo looks good to me, thanks. I'll review with @lovegushwa this morning and close this upon his approval.

**Comment by lovegushwa** [comment]
@HPaulJohnson hey I'm cool with the design, it might be good to tweak the copy above the share image so folks know what they are seeing (the share graphic) is what we're asking them to share.

**Comment by HPaulJohnson** [comment]
Thanks to some great work by @alanmoo this is good to go. With Beat 5 we'll be A/B testing Share Progress buttons embedded in a modal post-pledge signing vs. Redirecting to a Share Progress share page.
