### ISSUE TITLE
Update default email, facebook and twitter share buttons

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#234]
Now that we have kinks worked out on Share Progress buttons, let's start the next beat with a clean set of data/analytics. 

Here's the new button code (to go live in conjunction with Beat 5 content on site): 

div class='sp_163584 sp_em_small'

div class='sp_163585 sp_fb_small' 

div class='sp_163586 sp_tw_small'

**Comment by alanmoo** [comment]
Will be closed with an upcoming PR
