### ISSUE TITLE
Copy changes for v1 landing page

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#235]
@alanmoo we need to make a slight update to the v1 landing page. Plan here is:
CC @shaghdoosti 
- New CTA  is  "Stand up for strong encryption" ... Were changing from "Pledge to Stand Up For Strong Encryption" because it's problematic to say "Convert to my religion" and then ask some one to watch a video. Feels too much like overt sales and the video should do the selling.
- Remove the meta data, it makes the headline look more like a video title and less like a CTA
- Remove the second CTA "Become an encryption champion" and add the neon arrow. A "hey start here" without the need for a 2nd headline. Will also help push people down to the form on mobile. 
- Would love if we could make the 2nd paragraph italic so it feels like instructions.

<img width="799" alt="screen shot 2016-03-23 at 4 11 33 pm" src="https://cloud.githubusercontent.com/assets/12228435/14003887/3c8a4ecc-f113-11e5-92eb-147c2c0b85fb.png">

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson  I suggest we add an additional card in place of the ENCRYPT logo at the end of the video as a super clear in video CTA. Could be "Take the Pledge"? We should give Darren direction for this asap. 

https://vimeo.com/159846574  "mozilla"
(we will a 2nd versions, one with the ENCRYPT logo and URL for use on Social and Paid.)

**Comment by lovegushwa** [comment]
@alanmoo ^ the comment addressed to Brett and Paul wont impact you, it's just about the in video CTA.

**Comment by HPaulJohnson** [comment]
@lovegushwa - I agree, replace ENCRYPT as the video end card (it's redundant with persistent site header) and reinforce "Take the Pledge" CTA instead.

**Comment by alanmoo** [comment]
@lovegushwa LMK how this looks: https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4

**Comment by lovegushwa** [comment]
@alanmoo this looks great. One minor tweak:

Can you push the signup fields down just a little so there is a little more space under "friends" ... Around the same amount of blue space between "select your country" and "first name."

An alternative to this is making the text are above a few pixels wider so "friends" is not all by it's lonesome. 

![screen shot 2016-03-25 at 1 15 36 pm](https://cloud.githubusercontent.com/assets/12228435/14053033/dc00ece4-f28b-11e5-9b0f-e704436e9e23.png)

**Comment by lovegushwa** [comment]
@alanmoo while your at it one minor global change I have been wanting to make, it would be rad if the email icon was a little bit smaller in the circle (to optically march twitter and facebook). It wont take much.

Also can you change the "--" to an em dash in the video 3 description?  

![screen shot 2016-03-25 at 1 21 12 pm](https://cloud.githubusercontent.com/assets/12228435/14053144/ac6240a4-f28c-11e5-9890-db91844f249a.png)

![screen shot 2016-03-25 at 1 23 32 pm](https://cloud.githubusercontent.com/assets/12228435/14053211/e89d5996-f28c-11e5-9f78-a1a118c92d5d.png)

**Comment by alanmoo** [comment]
Hmmm...I thought the `--` had been changed...wonder what happened there...

**Comment by lovegushwa** [comment]
@alanmoo 
Weird, just cleared my cache and tested in Safari (which I don't really use.) seeing the same --

**Comment by alanmoo** [comment]
Are you looking at staging? That hasn't been deployed to prod yet, it's wrapped up in the same PR as all the rest of this.

**Comment by alanmoo** [comment]
And by staging, I mean the dev server at https://lit-mountain-52009.herokuapp.com/encrypt/

(Which has these changes now too)

**Comment by lovegushwa** [comment]
@alanmoo yeah that's the problem. cool

**Comment by lovegushwa** [comment]
@alanmoo one last wish.
Was looking at the meta data and how the titles break in the playlist component. I think it would work / look better / be more constant if you move the meta data from below the video titles too above the titles. IE "episode 4" would sit above "Stand up for strong encryption"

![screen shot 2016-03-25 at 1 38 29 pm](https://cloud.githubusercontent.com/assets/12228435/14053552/43122b5c-f28f-11e5-9685-5f71aea69f5a.png)

**Comment by alanmoo** [comment]
Done

**Comment by lovegushwa** [comment]
@alanmoo this is a weird thing, were using the blue background color in the video behind the Mozilla logo and the ENCRYPT ident. We can't change the ENCRYPT ident, it was made by Agency at the start if the campaign and we don't have the aftereffets files so were locked into the blue color. Is it possible to place a tinny rule around the video player so when were using the brand blue, we don't get this weird effect of not seeing the video as a window? Other option could be making the page BG color slightly darker.

![screen shot 2016-03-25 at 2 39 46 pm](https://cloud.githubusercontent.com/assets/12228435/14054854/e905ca28-f299-11e5-9f36-642acaefb536.png)

**Comment by alanmoo** [comment]
@lovegushwa  What color? White?

**Comment by alanmoo** [comment]
<img width="1081" alt="screenshot 2016-03-28 09 41 03" src="https://cloud.githubusercontent.com/assets/1682681/14079113/3ffd4f64-f4c9-11e5-8d2b-344cd44f88e8.png">
This is a 25% opacity white, lmk if this is good.

**Comment by lovegushwa** [comment]
@alanmoo ^ I'm cool with this! Just what we needed.
