### ISSUE TITLE
Link shortener for Codemoji

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#236]
@simonwex I was in a meeting today with TODO, @Giorgio-Olivero asked if you could give an update about using https://bitly.com/ as a link shortener. Can you follow up with Giorgio in this ticket?

Example of a super long link we currently use to share messages: 
http://el.s.todo.to.it/cryptoloji/1033/?data=eyJtZXNzYWdlIjoi8J%2BRu%2FCfmKnwn42P8J%2BPgiDwn5CR8J%2BPgiDwn5iB8J%2BahPCfkqXwn5iT8J%2BTkiIsImtleSI6IvCfmIAifQ%3D%3D#/landing

**Comment by simonwex** [comment]
@lovegushwa, let's talk about domains off of GitHub, it's a precursor to this. Once we settle on that, I can make some api keys.

**Comment by Giorgio-Olivero** [comment]
yeah, the link can be even longer, this would be the max length:

http://el.s.todo.to.it/cryptoloji/1033/?data=eyJtZXNzYWdlIjoi8J%2BRkuKMmvCfk6PimJ3ijJrimJ3ijJrijJrimJ0g4pid8J%2BPiPCfkJvwn5KP8J%2BQo%2BKYnfCfjbvwn5Cb8J%2BOhuKbtfCfjZ7wn5K9IPCfk6Mg8J%2BTo%2BKYnfCfkr3wn5Cb4oya4pu18J%2BPrfCfkJsg8J%2BOhuKMmuKYnSDwn5K98J%2BPrfCfjbvijJrim7Xwn46hIPCfkovimJ3wn46h8J%2BPreKMmuKbtfCfj4jimJ3wn5K98J%2BOofCfkJvwn5KL8J%2BRkvCfj4jijJrim7Xwn4%2Bt8J%2BSvfCfjabwn4278J%2BRkvCfj4jwn4%2BtIPCfjobwn4%2BI8J%2BNu%2FCfkZLwn46G8J%2BNpvCfkr3wn46h8J%2BQm%2FCfjabwn5GS8J%2BPiOKbtfCfkr3wn4278J%2BQm%2FCfj4jijJrim7Xwn5K98J%2BQm%2FCfko%2Fwn5Cj8J%2BSj%2FCfjqHwn5K94pu18J%2BPiPCfkZLwn5Cb8J%2BSvfCfjqHwn5Cj8J%2BSj%2FCfkZLijJrim7Xwn5K98J%2BOofCfkKPwn4%2BI4oya8J%2BRkuKbtfCfkr3wn46h8J%2BQo%2FCfkJvwn5GS4pu18J%2BOoSIsImtleSI6IvCfmI0ifQ%3D%3D#/landing

**Comment by Giorgio-Olivero** [comment]
adding @abusedmedia @michellenebiolo

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @shaghdoosti  @HPaulJohnson @brettgaylor  CC @simonwex 
I want to confirm everyone is cool with a https://bitly.com/ shorted link. So when some one shares that super long link @Giorgio-Olivero posted above, the short version will look like this: http://bit.ly/1pMgkGf
(users can see the bit.ly domain in the link.)

**Comment by valianttry** [comment]
perhaps a stupid Q, but why aren't we using mzl.la/?

**Comment by lovegushwa** [comment]
@valianttry that's a good question! mzl.la is not set up to handle the volume of traffic we're going to hopefully have. CC @simonwex

**Comment by HPaulJohnson** [comment]
@lovegushwa - assuming mzl.la doesn't work, bit.ly works for me as the sharable link url.

**Comment by lovegushwa** [comment]
@simonwex we should be good to move ahead with bit.ly

**Comment by lovegushwa** [comment]
@simonwex looks like we can move ahead with bit.ly 
CC @Giorgio-Olivero @abusedmedia @michellenebiolo

**Comment by ScottDowne** [comment]
@cadecairos @simonwex this should do it. https://github.com/ScottDowne/bitly-secret-service

Still needs to go up to Heroku and probably be moved to https://github.com/mozilla/bitly-secret-service

**Comment by ScottDowne** [comment]
Actually, I'm going to adds some docs in the readme for the envs.

**Comment by cadecairos** [comment]
:tada: Thanks for the quick turn-around!

**Comment by cadecairos** [comment]
> Still needs to go up to Heroku and probably be moved to https://github.com/mozilla/bitly-secret-service

Can you start the transfer to mozilla?

I'll set up a Heroku app.

**Comment by cadecairos** [comment]
> mzl.la is not set up to handle the volume of traffic we're going to hopefully have

@lovegushwa Exactly what kind of traffic are we looking at here?

**Comment by ScottDowne** [comment]
Currently it's live here: https://bitly-secret-service.herokuapp.com/generate/

It'll also live here soon: https://bitly.mofoprod.net/generate/

Instructions to use it:

Example usage:

```
curl -H "Content-Type: application/json" -X POST -d '{"url":"http://el.s.todo.to.it/cryptoloji/1033/?data=eyJtZXNzYWdlIjoi8J%2BRu%2FCfmKnwn42P8J%2BPgiDwn5CR8J%2BPgiDwn5iB8J%2BahPCfkqXwn5iT8J%2BTkiIsImtleSI6IvCfmIAifQ%3D%3D#/landing"}' https://bitly-secret-service.herokuapp.com/generate/
```

Should return a bitly link, example: http://bit.ly/1YTJo9D

**Comment by cadecairos** [comment]
https://bitly.mofoprod.net is live, and is the preferred endpoint, since it'll use Mofo SSL instead of Heroku.

The site will instruct browsers to only let `https://teach.mozilla.org` hit the endpoint (using CORS headers) and also limits requests to 20/minute/IP which mean's any given user should be able to use the shortener without any problems, assuming they aren't sending more than one request every three seconds.

The rate limit is completely configurable, if we want to relax it.

Edit: tagging @Giorgio-Olivero

**Comment by abusedmedia** [comment]
Hey @cadecairos can you white-list http://todotoit.github.io/codemoji/?  This way we can test quickly and allows other to use the app properly. 
Thanks

**Comment by cadecairos** [comment]
@abusedmedia `http://todotoit.github.io` is now the allowed origin for the endpoint, sorry for the delay!

**Comment by abusedmedia** [comment]
Thanks, now it's using the shortener. We need to add a little loader to streamline the ux of that detail, though.

**Comment by lovegushwa** [comment]
@abusedmedia can I close this issue or do you still need something from us?

**Comment by abusedmedia** [comment]
The only concern would be, once the final domain name will be defined, that the backend needs to white-list that domain either in order to make the system to work properly.
Don't know if keeping open this or make a new specific issue, though.

**Comment by cadecairos** [comment]
I've already white-listed the production domain we plan on using :+1:

**Comment by irowebbn** [comment]
Codemoji user here, looks like the link shortener is returning links with an extra "s" in them, making them invalid addresses. The issue has already been brought up on the codemoji repo [here](https://github.com/mozilla/codemoji/issues/199). Looks like the "s" isn't anywhere in codemoji's code, but coming directly from the mofoprod bitly generator (for which I am insufficiently credentialed to diagnose)
