### ISSUE TITLE
External links for Codemoji

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#237]
@Giorgio-Olivero @shaghdoosti @alanmoo CC @simonwex 

Legal:  https://www.mozilla.org/en-US/about/legal/
Privacy notice:  https://www.mozilla.org/en-US/privacy/websites/
Learn more about encryption:  Let's pop up a new page, it's going to give us more flexibility.

@alanmoo our plan is to host the Codemojo app on Teach since we can link to additional teaching recourse around Encryption and it positions us well to frame this as a educational experience. 

Can you generate a link for us? Could even be a redirect, we just need a link to give TODO that we can hook to a external page with TBD encryption content at a later date. 

If this is not something you can do, can you send me in the right direction?

**Comment by alanmoo** [comment]
I haven't worked with the teach site, and I'm not sure what you're looking for. Is Codemoji going to be hosted on TODO's servers? Once that's clear, @mmmavis or @cadecairos may be able to help here better than I can.

**Comment by Giorgio-Olivero** [comment]
> Is Codemoji going to be hosted on TODO's servers?

no.

adding @abusedmedia @michellenebiolo

**Comment by alanmoo** [comment]
Then what is needed, somewhere to host the app?

**Comment by simonwex** [comment]
@Giorgio-Olivero could you post details on the server here? Is there a publicly-available repo? Have you done any load-testing?

**Comment by lovegushwa** [comment]
@alanmoo @simonwex  This ticket is not about where we will host "Codemoji"  

We basically just need to create a page when some one clicks on a little button in "Codemoji" that says "Learn more about encryption"... TODO needs a link like https://teach.mozilla.org/encryption ...
We develop content for this "Learn more about encryption"  page at a later date, but TODO needs a link now since were finishing up our contract with them.

**Comment by alanmoo** [comment]
Ah, got it. I don't see why using that URL (https://teach.mozilla.org/encryption) would be a problem, but maybe someone with more familiarity with that repo could confirm. @Pomax or @mmmavis maybe? Is that URL a reasonable one to set aside for the purpose @lovegushwa describes above?

**Comment by mmmavis** [comment]
yea https://teach.mozilla.org/encryption should be fine (cc @hannahkane in case there's already a plan about reserving this url for other purposes)

@lovegushwa 

> We develop content for this "Learn more about encryption" page at a later date, but TODO needs a link now since were finishing up our contract with them.

Is there a deadline for developing the "Learn more about encryption" page on Teach site?

**Comment by hannahkane** [comment]
I don't know of any plans to use teach.m.o/encryption for anything else.

**Comment by brettgaylor** [comment]
Can we use teach.m.o/codemoji?  

we’ve tried not to frame this as “encryption” for a few reasons - we don’t want users to think they can safely secure their messages with the app

**Comment by mmmavis** [comment]
> Can we use teach.m.o/codemoji?

works for me!

**Comment by lovegushwa** [comment]
@mmmavis @brettgaylor just to clarify. We're not talking about where we host the product, this thread is about a deeper dive encryption page that we need a link for in the on boarding experience (see above.) I'll create a another icket for hosting the product on teach.

Let's go with https://teach.mozilla.org/encryption for this encryption information page.
(and we can host product on https://teach.mozilla.org/codemoji)

@mmmavis can you confirm this works and I'll flag TODO and close this ticket?

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @abusedmedia @michellenebiolo here are the external links you need:

Legal: https://www.mozilla.org/en-US/about/legal/
Privacy notice: https://www.mozilla.org/en-US/privacy/websites/
Learn more about encryption: https://teach.mozilla.org/encryption

**Comment by Giorgio-Olivero** [comment]
thanks @lovegushwa

**Comment by mmmavis** [comment]
@lovegushwa yea both https://teach.mozilla.org/encryption and https://teach.mozilla.org/codemoji work. Note that they'll be remain 404 until we put something there.

**Comment by lovegushwa** [comment]
Thanks @mmmavis !
