### ISSUE TITLE
Share links for Codemoji

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#238]
@Giorgio-Olivero hey I want to confirm the links / platforms were approved to use on the share screen:
- facebook
- twitter
- email
- SMS
- tumblr

**Not approved to use Whatsapp**

![screen shot 2016-03-24 at 4 44 51 pm](https://cloud.githubusercontent.com/assets/12228435/14034352/cc2fe100-f1df-11e5-9a14-39dbe6176e5f.png)

**Comment by Giorgio-Olivero** [comment]
adding  @michellenebiolo @abusedmedia

**Comment by abusedmedia** [comment]
@lovegushwa, we are going also to remove tumblr sharing icon which is not very reliable across devices. 
Giving support to the main social network (FB, TW) and the main personal comm tools (@, SMS) with the possibility to copy the link for whatever further sharing way, could be considered enough in the project scope. Ok?

**Comment by lovegushwa** [comment]
@abusedmedia yes, please go ahead with your plan.

**Comment by lovegushwa** [comment]
@abusedmedia yes!

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @michellenebiolo @abusedmedia looks like this ticket is good to close.
