### ISSUE TITLE
Revise Codemoji logo

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#239]
@Giorgio-Olivero I will get this to you by end of day tomorrow.

**Comment by Giorgio-Olivero** [comment]
adding @michellenebiolo @abusedmedia

**Comment by lovegushwa** [comment]
Need a little more time for this, but coming very soon.

**Comment by lovegushwa** [comment]
@Giorgio-Olivero 
Here is a proposed revision of the identity: 

<img width="848" alt="screen shot 2016-04-04 at 3 57 02 pm" src="https://cloud.githubusercontent.com/assets/12228435/14267321/56e5027e-fa84-11e5-86eb-5d6f06467397.png">

<img width="1170" alt="screen shot 2016-04-04 at 3 57 42 pm" src="https://cloud.githubusercontent.com/assets/12228435/14267330/5bf81f9e-fa84-11e5-955c-d891fafbf988.png">

I spent some time trying to get codemoji to work as well as previous version, as you can see from the process it's difficult to introduce the same emoji and make the logo read properly. 
![screen shot 2016-04-04 at 4 32 36 pm](https://cloud.githubusercontent.com/assets/12228435/14267344/7b545dc6-fa84-11e5-9d82-a5091918dc6b.png)

My conclusion was use face emoji and replace the "O" ... and use yellow letters so the emoji and letters read as a single word at first glance ... because it's yellow we need to use it on a dark background ... This is the logic.

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @michellenebiolo @abusedmedia
We could animate the logo by rotating through different face expression emoji, similar to the on boarding. 
We could choose maybe 5 different expressions as possible final states of the animation.

<img width="904" alt="screen shot 2016-04-04 at 4 27 40 pm" src="https://cloud.githubusercontent.com/assets/12228435/14267521/f006989a-fa85-11e5-958f-afea7d8307f2.png">

**Comment by lovegushwa** [comment]
Traveling but will try and post final artwork tomorrow.

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @michellenebiolo @abusedmedia

Sorry about the wait on this, Final logo artwork here: 
https://drive.google.com/file/d/0B2qu3ExKWIlvRGRwMU1aTVhicGs/view?usp=sharing

**Comment by lovegushwa** [comment]
@Giorgio-Olivero @michellenebiolo @abusedmedia

Here is the final, final updated logo with a revised letter "M"
https://drive.google.com/file/d/0B2qu3ExKWIlvdWxzTDVDbzRPY2M/view?usp=sharing
