### ISSUE TITLE
Design: video thumbnails for the Encryption Campaign Survey

### ISSUE THREAD

**Issue by mmika** [MozillaFoundation/encryption_campaign#240]
@lovegushwa 
Here's the survey draft for your reference: 
https://docs.google.com/document/d/1nmugvF9qilXQi3pKiVAlIhMJM46T2WH7ZUyvoU8iP28/edit

**Comment by lovegushwa** [comment]
@natalieworth can you take this on? ... Basically you will need screen shots of each video, we can probably grab the poster image for videos 1 and 2, but you will need to make new screenshots for videos 3 and 4. Just connect with @mmika to make sure she has everything. 

@mmika do we have a launch date for this?

**Comment by mmika** [comment]
Thank you @lovegushwa and @natalieworth -- no launch date yet.

PS -- not sure about the size for each still shot. -- @adamlofting thoughts?

**Comment by natalieworth** [comment]
I can help out with this! I'll just need to know resolutions and can then assist :)

**Comment by adamlofting** [comment]
There's not a precise size needed, but about 250px wide will work fine.

**Comment by mmika** [comment]
@natalieworth upping this

**Comment by natalieworth** [comment]
I posted the 4 video screenshots on the drive here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0THE5MmNPQ2RYckk&usp=drive_web&ddrp=1#
I have exported each at 250px x 150px and then also 500px x 300px (as the 250px seemed a bit low resolution on my retina display). Let me know if these work or if any additional sizes are needed :)
@lovegushwa @mmika @adamlofting

**Comment by mmika** [comment]
@natalieworth Thank you!:)

**Comment by natalieworth** [comment]
@mmika Closing this ticket but let me know if there is anything else that you need design-wise :+1:
