### ISSUE TITLE
Use Encryption email 

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#241]
@lovegushwa @alanmoo 

To follow up our discussion our first encryption tip is for people to use FileVault and the PC version. Right now -- we want to send them to a landing page that has instructions for a PC and Mac as well as a button that says 'I did it'. 

If people press the button they will then land on a share page. Ideally this email would go out a few days after the encryption email goes out. In other words aiming for a 4th of April send.

**Comment by natalieworth** [comment]
@shaghdoosti I'm assuming this is the ticket created in anticipation for the first email on how to encrypt? Not sure if it needs updating or let me know what design work you're needing for this. I'll discuss with @lovegushwa too.

**Comment by natalieworth** [comment]
Moving this content into the design ticket for the filevault/ bitlocker email here: https://github.com/MozillaFoundation/Advocacy/issues/13
