### ISSUE TITLE
Minor text changes to pledge page: Needs to be clearer it's an email signup

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#244]
I have concerns the language on the pledge page doesn't make it abundantly clear that people are signing up to receive future email. (Channeling Marshal and compliance here.) I propose a few minor tweaks:

OLD TEXT:
_Let us know what country you’re in so if debates are happening in your country we can email you the most relevant updates. We’ll also send you useful tips about how to use encryption that you can share with friends._

_We’re seeing more and more governments attempt to undermine encryption. Will you help others understand what encryption is and stand up for strong encryption when it matters most? Sign on to be an encryption champion._

NEW TEXT WITH CHANGES:
Become an encryption champion and sign up for email updates. Let us know what country you’re in so if debates happen near you we can email you the most relevant information. We’ll also email you useful tips about how to use encryption you can share with friends._

We’re seeing more and more governments attempt to undermine encryption. Will you help others understand what encryption is and stand up for strong encryption when it matters most? Sign on to Mozilla's email list and be an encryption champion.

cc @KevZawacki @shaghdoosti

**Comment by alanmoo** [comment]
Check https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4 and https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4 those look right?

**Comment by KevZawacki** [comment]
More clarity is definitely a good thing here. Changes look great, @valianttry.

**Comment by alanmoo** [comment]
@KevZawacki so I can merge them in?

**Comment by KevZawacki** [comment]
@alanmoo Yep, let's do it.
