### ISSUE TITLE
Design+Email: update email templates based on Q1 learnings 

### ISSUE THREAD

**Issue by mmika** [MozillaFoundation/encryption_campaign#245]
@valianttry @shaghdoosti @stephaniemcv @lovegushwa @natalieworth 
Let's discuss!

**Comment by natalieworth** [comment]
I've been working on auditing the previous emails and templates that have been designed for Foundation emails. This document may help https://docs.google.com/presentation/d/1J5Ein_yp-6tCkScDqEERQ7ZmfVnSI6gNjVYGbCFHy6M/edit#slide=id.p It would be great to have a template for future fundraising too

**Comment by natalieworth** [comment]
Going to assign myself to this just so I don't miss it while @lovegushwa is in Toronto. @mmika What's the timeline for this?

**Comment by lovegushwa** [comment]
@natalieworth @mmika so we went though this process in early January here:
https://github.com/MozillaFoundation/encryption_campaign/issues/39

I suggest we change the title of this ticket to something like 
Design+Email: update email templates based on Q1 learnings 

We should find out as much as we can from @stephaniemcv about any tests that were run, what templates are currently in use, and any new templates / modifications we want to propose and test. 
Stephanie can guide us!

**Comment by lovegushwa** [comment]
Also want I want to make sure this is something we need? @valianttry @shaghdoosti will have strong feelings about what's worked and what to try next. 

I can see the need to design a update your software or install and use this product template for example.

**Comment by shaghdoosti** [comment]
Would love to jam on this and I do want to test different templates over a longer period to get a sense of what's working. 

Just as an FYI here is our latest email calendar: https://github.com/MozillaFoundation/encryption_campaign/issues/249

**Comment by stephaniemcv** [comment]
The main test we did over the campaign was Beat 2 and one of the main takeaways of that was that people seemed to click buttons more.

https://fundraising.mozilla.org/encryption-campaign-testing-email-design/

I would love to do a similar test, older style template vs newer style. I'd like to see if the data replicates, if the new one gets more clicks, but the older one gets more action.
