### ISSUE TITLE
We need a favicon

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#246]
The main advocacy site has the mozilla favicon, we should just use this
https://advocacy.mozilla.org/

Alan, though you might be best suited for this non critical thing :)

**Comment by alanmoo** [comment]
I don't see a favicon on advocacy...

**Comment by brettgaylor** [comment]
![image](https://cloud.githubusercontent.com/assets/345974/14162796/20f98f7e-f6a4-11e5-8ff0-f8f473cc2b6d.png)

i see just the "M", do you?
