### ISSUE TITLE
Copyright* poster - internal comms

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#248]
Let's get the really rad creative work we're doing in offices!
@natalieworth work with @KevZawacki to develop a headline and some lettering treatments for a poster.

**Comment by KevZawacki** [comment]
@natalieworth If you can share a rough idea of what the poster will look like / length of text required, I can start putting together some copy.

**Comment by natalieworth** [comment]
@KevZawacki Sounds good, I'll put together some rough ideas and benchmark a few things and post here, thanks

**Comment by natalieworth** [comment]
Hey @KevZawacki , I've got a couple rough ideas here that I'm hoping to try. I think in terms of content, 2 will be a bit shorter and then the 3rd a little longer (maybe 3-4 sentences). Here are the 3 concepts I've narrowed down to explore first (although I'm sure once I have approved content from you, I'll be able to try out a variety of options with the posters). I've posted a couple examples below, but have a larger benchmarking board here: https://www.pinterest.com/nataliejworth/mozilla-crypty-poster/
1. Educational/ throwback (to the original concepts and Mr. DNA with the 2nd video):
   ![3a4177580fc69198cd19b1a84e66fcf6](https://cloud.githubusercontent.com/assets/14876567/14293226/88a73a88-fb20-11e5-83f2-06942c174a93.jpg)
   ![44153d7db9b81fe22105bcb76b9329f4](https://cloud.githubusercontent.com/assets/14876567/14293229/8e927f84-fb20-11e5-8851-1660457d336b.jpg)
2. Encryption Power (more abstract/ also from the theme of the video):
   ![720410f3d814aa666cd719c150abaa8d](https://cloud.githubusercontent.com/assets/14876567/14293285/cb12ae8e-fb20-11e5-8c8e-91f80a74e6df.jpg)
   ![0716fa4a381fbbc401bf7de216619129](https://cloud.githubusercontent.com/assets/14876567/14293287/cf14b766-fb20-11e5-946f-46e04e00dc65.jpg)
3. Typographic/ grassroots:
   ![7d6d2176effa9e59e525d110103a24c6](https://cloud.githubusercontent.com/assets/14876567/14293240/97ec34ee-fb20-11e5-9003-effee8bb7216.jpg)
   ![ba1da3c36df9fa5902d86845eb6ffc48](https://cloud.githubusercontent.com/assets/14876567/14293249/a06a63b6-fb20-11e5-954a-8504b530e2f9.jpg)

And here are the rough sketches:
![img_3518](https://cloud.githubusercontent.com/assets/14876567/14293322/fa2c78ee-fb20-11e5-9638-9eb9cc6846a8.JPG)
![img_3519 2](https://cloud.githubusercontent.com/assets/14876567/14293324/fdb95432-fb20-11e5-99d3-94084fde58ac.JPG)

In terms of content ideas for the posters:
1. Educational headline (possibly 'Encryption' or 'Encryption Tools')—then the remainder I will do visually/ with illustrations.
2. A headline (possibly keeping 'Encryption Power' if that works?) and then maybe 1 short sentence like "Helping to protect your privacy."
3. Was hoping be a little more expressive/ grassroot-sy. Perhaps 3-4 sentences on what encryption stands for or does? E.g. "Encryption stands for privacy. It stands for safety and security, etc....) This example is kind of a longer and stronger tone, but hopefully helps to get the idea across:
![gender_big](https://cloud.githubusercontent.com/assets/14876567/14293521/cd7853f8-fb21-11e5-918d-3a25c7145ca1.gif)

These are all rough ideas, so feel free to add or riff off any that you feel could work better! I'm around all day today too, so just ping/ post any questions. Thanks :)

**Comment by natalieworth** [comment]
@KevZawacki Sorry, the sketches are upside down, but if you click on them they flip around

**Comment by KevZawacki** [comment]
@natalieworth Awesome sketches and benchmarks! Can't wait to see Crypty dotting the walls of Mozilla offices.

Some copy ideas, which correspond to your suggested content above: 
1. Encryption (can't do much variation here :smile:)

2a. Encryption Power! Encryption makes the Web a safer place
2b. Encryption Power! Encryption is good for you (and the Internet)  
2c. Encryption Power! Keeping your privacy under wraps
2d. Encryption Power! Everything is better in ciphertext

3a. Who uses encryption, anyway? Only journalists, whistleblowers, activists, and everyone who banks, shops, and communicates online.  
3b. Encryption makes the Web a safer place to create, teach, learn, play, and organize. Tell the world: Encryption isn't a luxury — it's a necessity. 
3c. Encryption protects your search queries. It protects your banking information. And it protects your medical records. Simply put, encryption protects you. 

If we feel like being cheeky and paying homage to iconic PSAs, we might sub in copy like:

-- "I want YOU! to encrypt your data" (Crypty as Uncle Sam)
-- "We can do it! (It = Encrypt)" (Crypty as Rosie the Riviter)

Also seeking input and ideas from @HPaulJohnson.

**Comment by natalieworth** [comment]
@KevZawacki Thanks! This is perfect!

**Comment by lovegushwa** [comment]
@natalieworth this is great benchmarking. 
I think the image below is the right direction (more of a graphic poster and less of an explainer info-graphic.) ... I like the shorter more open ended headlines. 

I do really like ... "Who uses encryption, anyway? Only journalists, whistleblowers, activists, and everyone who banks, shops, and communicates online." ... Also -- "I want YOU! to encrypt your data" (Crypty as Uncle Sam) -- "We can do it! (It = Encrypt)" (Crypty as Rosie the Riviter) is cool.
<img width="480" alt="screen shot 2016-04-07 at 3 46 14 pm" src="https://cloud.githubusercontent.com/assets/12228435/14369267/71f71592-fcd8-11e5-8c75-5687818a5f8f.png">

**Comment by natalieworth** [comment]
Could we roll this into a potential copyright poster once the campaign is underway? :D
