### ISSUE TITLE
Write email copy for Beat 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#25]
including tests, segment copy

**Comment by OpenMatt** [comment]
- Who should we assign this to? Who's producing the first draft / next step?
- @stephaniemcv @shaghdoosti ?

**Comment by OpenMatt** [comment]
@shaghdoosti is going to take this one. To be completed: Wed, Jan 27

**Comment by OpenMatt** [comment]
@shaghdoosti status update?

**Comment by OpenMatt** [comment]
@shaghdoosti has completed first draft. Working on second drafts now.

**Comment by OpenMatt** [comment]
Final copy for beat 1 will be completed by Thurs / Fri.

**Comment by shaghdoosti** [comment]
Hey Friends -- 

Here is the email copy for beat 1. <[https://docs.google.com/document/d/1CEXBJC1jN2wRefRbHzJMSTyUDrC1lMDwbn5od449Hdc/edit](url) @KevZawacki if you could look over that would be great. @stephaniemcv would love to work together around the feedback piece and the header design too!

Feel free to have a look -- this copy hasn't been through approval yet. Will go through that process once Kevin and Steph have had a look.

**Comment by KevZawacki** [comment]
@shaghdoosti Looking good! Just dropped suggestions into the doc.
