### ISSUE TITLE
Finalize and hand off "Codemoji"  

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#250]
Let's get this Codemoji project wrapped up and ready for public use (yay!)

Mozilla people: 
@simonwex figure out technical side of this hand-off
@HPaulJohnson confirm where exactly we want this to live, and when we need it by
@OpenMatt work with TODO on final contract things

TODO:
@Giorgio-Olivero @abusedmedia @michellenebiolo
- Make final copy changes
- Update the logo
- Confirm both string of emoji and message get shared when using platforms
- Confirm link shortner is working
- Make sure Twitter emoji gets lots of credit! 
  (they were upset at not getting credit on another mozilla project.)
- Hand over everything via @simonwex 

A few tickets that need attention:
Link shortener @simonwex : https://github.com/MozillaFoundation/encryption_campaign/issues/236
Identity: https://github.com/MozillaFoundation/encryption_campaign/issues/239

Final approved copy:
https://docs.google.com/presentation/d/1gtyRuMikSPCh5o3zHFgjJvbPk07BHo616U8lcTpwl6g/edit#slide=id.g1271bc7a07_4_12

**Comment by michellenebiolo** [comment]
Hi everyone, some feedback and updates on our task list.

**Make final copy changes:**
- We suggested a few edits on [your deck](https://docs.google.com/presentation/d/1gtyRuMikSPCh5o3zHFgjJvbPk07BHo616U8lcTpwl6g/edit#slide=id.g1271bc7a07_4_12) and received final feedback on one (for which we are implementing the final version as provided). 
  Are the remaining edits accepted or rejected?
- The deck linked above does not include screenshots of: 
  - the desktop version (which has additional copy, namely the help hints)
  - a couple of instances where we suggest slightly different copy for users who have received a scrambled message via the Mozilla newsletter. If you still plan on sending an email with a scrambled message etc., please check these too. **You need to check these on [the spreadsheet](https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543), cells L67 and L82.**
  
  **For everything else, you can proofread on [the latest iteration of the website](http://el.s.todo.to.it/cryptoloji/1111).**
- We are suggesting [this copy for the pre-defined texts when sharing](https://docs.google.com/document/d/1pihz1MtYkzeUjcRGa58w7GEeJZj8MFnc-nYobpbqenA/edit) Codemoji.
  Please comment or provide final copy so we can implement it.
- We are suggesting [this copy for the Credits page](https://docs.google.com/document/d/1jrBg0-EhKtv0db3Lu0B8n9kvyNDIkddlMqZN8mSBbdA/edit) (with special thanks to Twitter).
  Most of this copy will also be used to present the project on the GitHub repository (as you can see in the second half of the shared document).
  Please let us know about this one too.
- We are waiting on copy from you for the “Learn more” page (#219).
  
  **Please let us know when we can plan on having all feedback on copy and the missing "Learn more" content.**

**Update the logo:**
I think this is being handled through #239.

**Confirm both string of emoji and message get shared when using platforms:**
This is true for sharing through Twitter (although the emoji string will be cut down to the number of available characters) and email. 
For Facebook, we cannot generate a customized message including the string of emoji that the user is sharing. 

**Confirm link shortner is working:**
Leaving this for @abusedmedia 

**Make sure Twitter emoji gets lots of credit:**
We are thanking them prominently in the Credits page, hope that's ok.

**Comment by abusedmedia** [comment]
About the shortner, we're awaiting feedback from @simonwex since we need the endpoint service that can be used client-side (making an ajax request). Once the endpoint has been set up, we'll able to complete the integration and testing in about a working day.

**Comment by lovegushwa** [comment]
@HPaulJohnson can you review this Codemoji share copy?

From TODO
We are suggesting [this copy for the pre-defined texts when sharing](https://docs.google.com/document/d/1pihz1MtYkzeUjcRGa58w7GEeJZj8MFnc-nYobpbqenA/edit) Codemoji.
Please comment or provide final copy so we can implement it.

**Comment by lovegushwa** [comment]
@shaghdoosti can you confirm this copy? (email list variant of the app)

From TODO 
If you still plan on sending an email with a scrambled message etc., please check these too. **You need to check these on [the spreadsheet](https://docs.google.com/spreadsheets/d/1STrOHP3L2VmxmBqjIc3PPbJn0-tq5Qu2gOCgFTtXK_o/edit#gid=298121543), cells L67 and L82.**

**Comment by lovegushwa** [comment]
@shaghdoosti can you do final sign off on the deck here? I confirmed the changes we made last week and added the mobile views that need one last look.

https://docs.google.com/presentation/d/1gtyRuMikSPCh5o3zHFgjJvbPk07BHo616U8lcTpwl6g/edit#slide=id.g1271bc7a07_0_34

**Comment by lovegushwa** [comment]
@michellenebiolo 

Regarding:
- We are waiting on copy from you for the “Learn more” page ( #219 ).

You should not need any content from us. We will build the "Learn more" page at a later date. 
Just be sure to link to https://teach.mozilla.org/encryption and we can take care of the content.

**Comment by lovegushwa** [comment]
@michellenebiolo 

Regarding:
- We are suggesting [this copy for the pre-defined texts when sharing](https://docs.google.com/document/d/1pihz1MtYkzeUjcRGa58w7GEeJZj8MFnc-nYobpbqenA/edit) Codemoji.
  Please comment or provide final copy so we can implement it.

Credits content looks great. Let's go ahead with what TODO is proposing.

**Comment by shaghdoosti** [comment]
@lovegushwa the copy in the deck looks good to me.

**Comment by HPaulJohnson** [comment]
@lovegushwa added comments to the doc for social share language. Some small tweaks but largely good. Generally speaking, we really need to get the emoji-message into the post/tweet/email as that's the whole fun of the thing.

**Comment by shaghdoosti** [comment]
@lovegushwa looked at the spreadsheet too -- all looks good to me.

**Comment by michellenebiolo** [comment]
Hi! All good except sharing copy: I replied to @HPaulJohnson's [comment in the file](https://docs.google.com/document/d/1pihz1MtYkzeUjcRGa58w7GEeJZj8MFnc-nYobpbqenA/edit). 
Unfortunately we need to work around some technical limitations as regards both posting generated content and copy length. Please let me know if you have further suggestions so we can solve this.

**Comment by michellenebiolo** [comment]
Hi @lovegushwa, do you have a deadline for us? 
The only bits missing should be:
- final edit on the Facebook card pre-set text
- link shortner endpoint set up by @simonwex 
  (+ logo that is being finalized in another thread)

**Comment by lovegushwa** [comment]
@michellenebiolo I would like to hand off in the next day or two.
- I updated the logo ticket. 
- @HPaulJohnson @simonwex can you look at @michellenebiolo last comment so we can close this project and hand off?

**Comment by lovegushwa** [comment]
@michellenebiolo if not difficult, I would like to change the footer on the desktop version so it looks like this: 

<img width="848" alt="56e5027e-fa84-11e5-86eb-5d6f06467397" src="https://cloud.githubusercontent.com/assets/12228435/14454606/46595d98-0050-11e6-8078-7dcc8d1bc255.png">

**Comment by HPaulJohnson** [comment]
@michellenebiolo thanks for the feedback in the doc re: what's possible to post on a user's FB wall. Given that, I think the original text you suggested works fine.

**Comment by cadecairos** [comment]
@HPaulJohnson I've got a bit.ly account set up, but I need to know exactly what method codemoji will use to generate short links, so I can get the right credentials to the right people (OAuth or API Key). Who can we ask about this?

**Comment by lovegushwa** [comment]
@abusedmedia @michellenebiolo please see @cadecairos question above ^

**Comment by abusedmedia** [comment]
Hi @cadecairos 

Codemoji is a front-end app therefore it can only make an ajax request to some endpoint in order to get a short url (providing a longer one as param).

I don't think it's a good idea to put credentials or OAuth' secrets into the front-end app to call bit.ly endpoint directly (for security reasons). 
It would be better to use some backend middleware that would act as a bridge (keeping credentials/secrets) between the front-end and bit.ly service.

**Comment by ScottDowne** [comment]
Updated https://github.com/MozillaFoundation/encryption_campaign/issues/236 with details about using the link shortener.

**Comment by brettgaylor** [comment]
Notes from Toronto meeting:
@lovegushwa @ScottDowne 
MAKE HINT IDEA MORE PROMIMENT
-in all share messages - email, twitter, FB
-in the email itself
-add animation/call attention to hint 

ADD USER FEEDBACK TO DESK

ADD GOOGLE ANALYTICS
-events - click “share”

**Comment by brettgaylor** [comment]
Approved disclaimer languge:
Codemoji is a fun way for you and your friends to learn about ciphers.

You shouldn’t use it for secure communications, though.  Thankfully, modern encryption tools are way stronger than emojis ;)

Use Codemoji to learn about ciphers with your friends!

[I UNDERSTAND]

@lovegushwa

**Comment by lovegushwa** [comment]
Moving to this ticket here: 
https://github.com/MozillaFoundation/Advocacy/issues/7
