### ISSUE TITLE
Post Survey Emails in layout review

### ISSUE THREAD

**Issue by stephaniemcv** [MozillaFoundation/encryption_campaign#255]
One survey is for the random 100K group we surveyed at the beginning at the campaign.
One survey is for everyone else.

Please review the email copy, test the link and survey and note any feedback in this ticket.

**Comment by brettgaylor** [comment]
Got it!  When I responded I got an email from "askjoin".  seems legacy - possible to join?

**Comment by stephaniemcv** [comment]
Totally legacy. I believe it was a mailing list at one point? I'm a little fuzzy on the history of it. It's on my list to get us setup on something less confusing, like join. Fundraising has "donate", we should have something clear too.

**Comment by brettgaylor** [comment]
We used to call our mailing list efforts "Join Mozilla"
