### ISSUE TITLE
Chrome bug on landing page for decryption

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#257]
When I receive a message to decrypt, the button to proceed back into the tool is pushed too far down the page in chrome:
![image](https://cloud.githubusercontent.com/assets/345974/14750134/1353fe28-0878-11e6-9065-401ef714fdaa.png)

**Comment by abusedmedia** [comment]
Hi @brettgaylor 
It should be fixed now (current link is [http://todotoit.github.io/codemoji](http://todotoit.github.io/codemoji) )
