### ISSUE TITLE
Resizing codemoji window causes loading state and it doesn't seem to load

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/encryption_campaign#259]
@lovegushwa 

Not sure how critical this is. Probably not super critical, because a refresh fixes it. Happening in firefox 46.

Steps to reproduce:
1. Open http://todotoit.github.io/codemoji/#/encrypt in firefox with a browser window that's more than 1023px wide. Full screen should be more than enough width.
2. Resize to less than 1024px. Or just resize the width until you see the loading image.

If you refresh, it'll fix, and show a mobile view.

Expected: A mobile sized screen when I get to a width less than 1024.
Actual: A indefinite loading screen.

It happens too if I go from 1023px to 1024px.

**Comment by ScottDowne** [comment]
@abusedmedia Thoughts?

**Comment by abusedmedia** [comment]
we'll have a look..

**Comment by abusedmedia** [comment]
@ScottDowne, It should be fixed now.

**Comment by ScottDowne** [comment]
:+1:
