### ISSUE TITLE
Typing into message input box as soon as page loads causes browser to lock (using Firefox with Multi-process enabled)

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/encryption_campaign#260]
I'm using Firefox 49 on Linux

STR: 
1. load up http://todotoit.github.io/codemoji/#/encrypt
2. As soon as you can see it, click the message input area and type something in

The app should lock up for a while...

**Comment by cadecairos** [comment]
Update: this only affects Firefox when it's using e10s (Multi-process)

**Comment by ScottDowne** [comment]
I'm using multi process firefox (nightly), and it works fine for me, but could be my machine. I don't think it's `*just*` e10s though.

I'm also not super concerned with not default future version features causing issues. Good to have a heads up though. Closing this, we can reopen if we need to take an action.
