### ISSUE TITLE
analytics on codemoji

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/encryption_campaign#261]
We need to setup/ensure the metrics for http://todotoit.github.io/codemoji/#/encrypt are working.

Looks like GA exists on the page, but I doubt it has the proper id. Not sure what else could go wrong.

Also, we want to setup some events for various actions for the process.

@adamlofting

**Comment by ScottDowne** [comment]
and cc @valianttry

**Comment by abusedmedia** [comment]
Hi @ScottDowne 
We've already implemented GA, asked before in #242.

Actually it records each major state change (landing, onboarding, encrypt, etc) as page-visit and each action (specific button clicked) as event as well as the user pick the right/wrong emoji on decrypt page.

Let me know if you're thinking something else.

**Comment by adamlofting** [comment]
We'll need to do this through a Mozilla GA account as part of our data practices.

I can request a new profile to track this, but first need to know what domain / subdomain is this going to be hosted on?

**Comment by abusedmedia** [comment]
No problem to replace the GA id property with another provided by you.
Do you think we could have access to that property in order to monitor the user behaviour?

**Comment by ScottDowne** [comment]
I'm going to close this as a dupe of #242 and we should move discussion there too.
