### ISSUE TITLE
Design callout box for fundraising email + "donate" buttons to match

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#262]
for reference:
https://github.com/mozilla/donate.mozilla.org/issues/702

We will be sending a fundraising email to the list and callouts get most of the clicks in our FR emails. 

Maybe the callout can feature Crypty?? However... the callout design shouldn't be too busy and distract from the text.

@stephaniemcv do we have a version of our updated templates that also allows for a callout box in the layout? Possibly related: #245 

cc @natalieworth @lovegushwa 

**Email launch date:** Tuesday 5/10

**Comment by lovegushwa** [comment]
@valianttry 
Crypty is a good idea. We should also look at something evergreen. Could be a good test to run here?

@natalieworth can you drive this?

**Comment by stephaniemcv** [comment]
I have an updated template with a callout in progress...let me see if I can get it finished by QA time. 

I would love to test our older style template with the call out vs the new template with the 600x300 header and a button midway down on our largest proposed audience segment. Something big and bold like Crypty snuggling up with a donate button.

**Comment by natalieworth** [comment]
Yes, I can work on this!

**Comment by valianttry** [comment]
@stephaniemcv I worry we have 2 very different designs in this channel if we continue to use the old template... can we at least update the background color / font / leading maybe? Need to train this audience.....

**Comment by stephaniemcv** [comment]
Valid point. I'll work on getting the updated template to work with a callout.

**Comment by natalieworth** [comment]
@stephaniemcv Just to confirm, are you only needing design for the call-out box, or do you need help with the email design-wise?

**Comment by stephaniemcv** [comment]
Just the call out box design. Actually, @natalieworth for the design you come up with can I get a 300x300 and a 600x300 version? I want to see how it looks and it'll be a backup if I can't get the two columns for mobile rendering to play nicely.

**Comment by natalieworth** [comment]
@stephaniemcv For sure, that works!

**Comment by stephaniemcv** [comment]
:+1:

**Comment by natalieworth** [comment]
@stephaniemcv @valianttry Have some options featuring the crypty video illustrations up on redpen here: https://redpen.io/p/tfe204330c12fe5a73
I was using the simplified language/ content from the EOY fundraising call-outs, but would be great if you could post updated content and feedback and then I can insert into the design.

cc @lovegushwa for you review too please :)

Thanks! :)

**Comment by stephaniemcv** [comment]
redpen and I are fighting, so here are my comments.

I personally think the simplified language from EOY works well here. 

The only one's I'm not loving are Crypty callouts 03 and Crypty callouts 04 - because just text as an image in an email is not the best utilization of what little space we have. 

Also I worry about Crypty callouts Artboard 6, because when the image happens to scale even smaller (thanks mobile!) the pieces background may make the text hard to read.

Crypty callouts 01 and Crypty callouts 02 I would like to see the button outline and text font be heavier.

Overall, much love for these!

**Comment by natalieworth** [comment]
@stephaniemcv @valianttry Thanks for the feedback! I've inverted the donate button so it's more prominent over the image: https://redpen.io/p/tfe204330c12fe5a73
1: https://redpen.io/pn9f8d648c7e500c65
2: https://redpen.io/qr5acdedf1335a056f
3: https://redpen.io/fea8dc6daa7b864168
4: https://redpen.io/fp9e5b0106bd488622
5: https://redpen.io/xveb94844c8676cdc7

cc @lovegushwa

**Comment by natalieworth** [comment]
These are my 2 preferred options @stephaniemcv. I think the 3 characters are easier to understand as a standalone image vs. crypty. The 'donate buttons' also have more prominent treatments so they stand out more too: :)
1: ![crypty_callouts89_artboard 6 copy 3](https://cloud.githubusercontent.com/assets/14876567/15156846/b9e8db7c-169d-11e6-91ba-62cd5bb8ec49.png)
2: ![crypty_callouts89_artboard 6 copy 2](https://cloud.githubusercontent.com/assets/14876567/15156847/bb85f564-169d-11e6-84a2-a505856e2d24.png)

**Comment by valianttry** [comment]
Crazy thought: and if it's too late ignore: Possible to have their eyeballs pointed at the "donate now" button? I've seen a few tests where directing "gaze" toward the button matters (arrows, eyes; etc). If it's too late ignore this! These are beautiful.

**Comment by natalieworth** [comment]
@valianttry Yes! That's a great idea. I was reading about red buttons too in optimization (vs. other colours) and they have a higher click rate compared to others. Would be great to use the red button option with the eyes pointed towards the 'donate now':
<img width="902" alt="screen shot 2016-05-10 at 11 59 52 am" src="https://cloud.githubusercontent.com/assets/14876567/15158976/292724a4-16a7-11e6-85c1-daa73a3c0420.png">

cc @stephaniemcv

**Comment by natalieworth** [comment]
@stephaniemcv I have the final exported files here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B20-0lpP23c0QmJIWnd6YnlKY1U&usp=drive_web&pli=1&ddrp=1#
I have exported one's at high and a lower quality (and used the previous settings and size that we used for the EOY campaign)—if there's any issue with them feel free to ping me and I can adjust asap :)

**Comment by natalieworth** [comment]
@stephaniemcv I'm going to close this design ticket, but feel free to reopen or ping me if anything is needed
