### ISSUE TITLE
Send pre-campaign survey

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#28]
As per @adamlofting KPI proposal: https://docs.google.com/document/d/1UzvIUhi93yREAwwJ7JsizesCfRHnZOR2ah1CMjnsu-o/edit#

Need to finalize copy for survey and send

@shaghdoosti said she has edits, so assigning this to her to follow up w. Adam.

**Comment by OpenMatt** [comment]
cc @valianttry

**Comment by OpenMatt** [comment]
@shaghdoosti are you the right assignee for this? what are the next steps?

**Comment by adamlofting** [comment]
I sent out a meeting invite for Friday this week. But we can work on this asynchronously between now and then too.

**Comment by OpenMatt** [comment]
Sara and Adam will meet Wed, Jan 20

**Comment by OpenMatt** [comment]
@shaghdoosti can you update here w. next steps coming out of your meeting?

**Comment by adamlofting** [comment]
I'm going to make some changes to the survey tomorrow AM, and @shaghdoosti is going to work on the copy for the corresponding email.

**Comment by shaghdoosti** [comment]
A few more details: 

We're sending the survey to a sample of 100,000 people. (our estimate is that we get 1000 responses) 

I'm drafting the content that has a hook around (we want to create awesome content for you) but doesn't mention encryption. Adam is going to tweek the questions. 

This survey will be sent to the same segment at the end of the campaign.

**Comment by jgmac1106** [comment]
The same 100000 people or just to the respondents who completed the
pre-survey so you can match results?

**Comment by adamlofting** [comment]
This will be the same 100,000 people. We're looking for general trends in the population, and not wanting to link answers to individuals records. 

@jgmac1106 do I recall you know a thing or two about surveys? I'll post the latest version here soon, and another pair of eyes on the questions would be very welcome.

**Comment by adamlofting** [comment]
I've updated the survey ready for feedback.

Things to note:
- For people who answer `Yes` or `Somewhat` to questions 1 and 2 we now offer a free text box to capture their definition (definition is 'soft required') 
  - We will then review these answers manually to see if we think the attempted definition is correct (admin questions are setup in survey gizmo to store these analysis)
  - The other goal here is to capture much more 'user voice' and look for recurring themes that can inform campaign content planning
- For question 3, if you answer `Yes` we then ask _where_ you use encryption. 
  - The goal was to test if people know where encryption already helps them, and to see if this knowledge shifts over the campaign. But, this current set of answers needs work. 
  - Perhaps we should focus on a smaller set, and ask people if they think things are encrypted. E.g. Facebook Private messages : Options Y / N / Sometimes / Don't know
  - Thoughts?
- I'm not happy with the language of the final question. So am looking for any suggestions here.
  - Currently: "I would take action to protect our ability to encrypt data and messages"
  - 'data and messages' feels wordy, but data means different things to different people.
  - ... our right to encrypt our data? ('right' makes more sense to me, but not sure if that's our language)
  - ... should this be stronger? e.g. I am willing to take action...? 

Here's the preview:
https://www.surveygizmo.com/s3/2534675/Mozilla-Encryption-Survey

**Comment by jgmac1106** [comment]
The survey looks good. Get some nice charts pre and post. While matching
users by IP address could allow for some more statistical testing I think
pretty charts are all that really matter. They will move people more than
effect size.

Still even with non-matched pairs a large effect size with your normal
ANOVA will still indicate a "difference" regardless of the lower power
caused by non-matched pairs. Lets just hope we hit the normal 1% response
rate.

One word of caution we are lowering the variance with a three point rather
than a four or five point scale.

I would switch would to "want"
Then
"I want to encrypt  my online information"
Or
"I want to protect my online information"

There is is an important distinction between encrypt and protect. I do not
know the rights answer. The second "protect" casts a wider nomological net
but it is more approachable to the people who would no or somewhat to
question one.

**Comment by adamlofting** [comment]
Thanks @jgmac1106 

As the campaign is to educate people ahead of possible encryption-specific advocacy actions, I think we want the word encryption in that statement. Reflecting on this now, I think we can be even more direct about that.
- "I will oppose any government attempts to undermine encryption"

@shaghdoosti how do you feel about that? ^

> One word of caution we are lowering the variance with a three point rather than a four or five point scale.

Yeah... I was cautious too. But now that we're asking people to write their own definitions I wanted to reduce the mental burden by simplifying the rest of the survey as much as possible.

**Comment by jgmac1106** [comment]
+1

**Comment by OpenMatt** [comment]
@shaghdoosti will answer Monday

**Comment by adamlofting** [comment]
I'm currently leaning towards dropping question 3 'I use encryption'.

I think what we wanted to learn from that question will be covered in the definitions in question 1 and 2.

**Comment by OpenMatt** [comment]
@shaghdoosti next steps?

**Comment by valianttry** [comment]
Just reviewed this, love the simplicity. I worry that people will select "somewhat" for the first survey, then also select "somewhat" at the second even if they are a little more knowledgeable. In other words, I worry the scale is too simple. Can we use numeric 1 - 5 (5 being very knowledgeable)?

**Comment by adamlofting** [comment]
We have a plan for that :smile: 

If they pick 'somewhat' we ask them to attempt a written definition, new textbox appears. And then we'll review/grade those answers. We can use a more detailed scale in that situation.

**Comment by OpenMatt** [comment]
cool! @shaghdoosti are you going to do a final review, then we can go ahead and send?

**Comment by shaghdoosti** [comment]
Yes -- it's on my list for today.

**Comment by valianttry** [comment]
Sounds good @adamlofting !

**Comment by shaghdoosti** [comment]
@stephaniemcv

**Comment by shaghdoosti** [comment]
Hey everyone - 

Seems like we're all good to go on the survey questions. I've done a new draft of the email. @adamlofting let me know if this is neutral enough. @valianttry what's the approval process for surveys? My assumption is --policy and Mark? 

Here's the link: https://docs.google.com/document/d/1PkPdOAKifeg9IqXbD2QNCvD4Z4zha72_88zs7IdGGnY/edit

**Comment by adamlofting** [comment]
This works for me :+1:

**Comment by adamlofting** [comment]
Last discussion point to resolve...

> My other hesitation is over the tonality of 'oppose any government attempts'. It's so strident compared to the rest of this. It's great campaign and rally language, but to me it feels abrasive here, and giving too much of a preview of our positioning, or something. I'd prefer if you tweaked it to something softer, like 'I will not support attempts' - removing the words 'oppose' and 'government'.

Does this work for you @shaghdoosti 
- "I will not support attempts to undermine encryption"

A tougher (somewhat sneakier) test would be to also ask the opposite, and see if people notice.
- "I will support a court-ordered process for obtaining encrypted data"

**Comment by valianttry** [comment]
I worry a little about the double negative in the first option. Here are a couple others for your consideration: 
- "I will speak out to support encryption if asked."
- "I will support laws or policies that strengthen encryption"  
- "I will take action in the future to support encryption"

**Comment by OpenMatt** [comment]
Let's ensure we're clear on final steps to close this ticket.  
1) @shaghdoosti can you address / make whatever edits are required to the document to address @valianttry 's point above? 
2) @valianttry Do you want to answer @shaghdoosti 's question re: approval process? Do we need @msurman + Policy to sign off before sending?

**Comment by msurman** [comment]
Do we want a simple opening question that is non-encryption oriented?

"I am concerned / worried about my privacy online?'

Maybe a rating scale on this topic.

I like keep thing survey simple, but I think you want something to tie knowledge to the broader issue space.

I like the wording I see in the current survey that says:

"I will oppose any government attempts to undermine encryption *" 

Not sure if that's what we're going with.

On the explaining one, maybe add 'to others' to the end of the sentence?

**Comment by valianttry** [comment]
We do not need @msurman to sign off -- i already spoke to David. Mark isn't the email signor and we have a lot of reviewers / experts eyeballs on both the email and the survey (including policy).

also we're really at critical hour to send this -- @msurman Chris Riley had feedback on this text yesterday we're feverishly trying to address, but are your recommendations ^ critical at this point? Sara's survey a few months ago provided data on how important privacy is to the people on our list so I don't think it's additive.

**Comment by msurman** [comment]
Let me be more clear about what I'm hoping we can know from the survey:

Is there a correlation between caring about privacy and knowledge about encryption?
Bonus: would this be different if you asked people about privacy vs. security?

This comes out of a conversation w/ Mitchell about the campaign. If we can know that by adding one question and don't think it's going to reduce response rates, it would be worth knowing. 

Re: sign off, let's have a discussion re: who signs off on what when during our first meeting when all the team is back (me + team). Main question is where will VP advocacy be signing off, knowing that I am currently acting in that role.

**Comment by shaghdoosti** [comment]
Hey everyone - 

A few things -- we're aiming to get this out on Tuesday now. 

1) Re the privacy question -- I do worry that if we put it upfront it'll bias the encryption questions. That said there's a important point here though about what we're trying to measure. My suggestion would be that we put a rating box at the end of the survey. ie: How much do you care about the following issues from 1 - 5 and then list: Making sure governments respect my privacy, making sure governments respect my privacy, ensuring third parties can't see my data, knowing where my personal information is stored.(Having the more nuanced answers and seeing if they shift after beat 4 and 5 would be really useful) 

2) The government question was flagged by policy and they raised a good point that the question seemed to bias towards certain answers. I suggest changing "How concerned would you be if governments or companies attempted to undermine encryption" (1 -5 rating box) -- reading back through the questions I'm also concerned that people wouldn't know exactly what 'action' was and that would color their answers.

**Comment by msurman** [comment]
Subject to Adam's 'does this make the survey too complex' analysis, I like this. Even if something much simpler, the suggestion of putting something on privacy or security at the end will help. 

Also, if we do a list of issues (as opposed to say a single issue) at the end, good to include one or more that use the work security or secure. E.g. I'm concerned about the security of my personal data. Mitchell specifically wanted to see how privacy vs. security as a concern relate to how people view encryption.

**Comment by adamlofting** [comment]
Thanks all. I think this line of discussion is making the survey stronger. 

I've shipped an updated version capturing the current feedback, so if this is OK it can be sent tomorrow while I'm offline. https://www.surveygizmo.com/s3/2534675/Mozilla-Encryption-Survey

Summary:

I replaced the `I will oppose government attempts...` question with...

```
I would be concerned if governments or companies attempted to undermine encryption *
(rating)

I care about... 

... making sure my data is *stored securely*
(rating)

... making sure people who store my data *respect my privacy*
(rating)

... *knowing* who can see my data
(rating)

... *controlling* who can see my data
(rating)
```

Rating option for all is:
`Strongly disagree / Disagree / Neutral / Agree / Strongly agree / Don't know`

**Comment by msurman** [comment]
Love it

**Comment by OpenMatt** [comment]
Now that content is done, what's the next step to send? @shaghdoosti are you taking point on that?

**Comment by shaghdoosti** [comment]
Yep -- Already sent the new questions back to policy. Once we have the go I'll let Steph know and she's already setup and ready to push it out.

**Comment by shaghdoosti** [comment]
Policy just signed off. @stephaniemcv we're good to move this production with goal to send today (if possible) if not -- tomorrow morning.

**Comment by stephaniemcv** [comment]
if the link didn't change from what I used in the test email, then everything is built. It'll be sent out tomorrow around 8am-ish.

**Comment by OpenMatt** [comment]
@stephaniemcv nice! got a status update?

**Comment by stephaniemcv** [comment]
Email was sent evening of 2/2. Unofficially, OpenRate (13.4%)and ClickRate(3.2%) are looking good. I'll have official numbers at the 24 hour mark.

**Comment by adamlofting** [comment]
We've had 2,200 completed surveys so far which beats our goal of 1,000.

**Comment by adamlofting** [comment]
For those following along, here's an early look at the survey results:
https://docs.google.com/document/d/1YfjD0c7sfMPhHmEU2UOAaMvOrFr-zoEQzeTU_arUdrE/edit#heading=h.7qz0sjmzcqpy

We should dig into this data more in time, but I'm sharing this early in case it helps with planning for the latter part of the campaign.
