### ISSUE TITLE
Choose / finalize concept for video 1

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#3]
@brettgaylor @rohanporteous @HPaulJohnson

**Comment by OpenMatt** [comment]
@brettgaylor @rohanporteous can you guys log a quick status update + next steps here?

**Comment by OpenMatt** [comment]
## Feedback and next steps on concept

(from @brettgaylor Jan 7 email)

### 1) Script / concept fit
- MoFo should probably deliver an exact script before we land on a concept
- vagueness on MoFo side re: script is probably making it harder to get to a crisp concept

### 2) Abstraction / complexity
- This most recent iteration of the perspective video adds too much abstraction.  
- The video needs to entice our audience to go on the journey with us, and telegraph levity of approach throughout the campaign
- We don't necessarily need in this video to be high concept --  it should be direct 
- working too closely in metaphors may  confuse our audience about what encryption does and how it works.  
- We already know we have headwinds here in terms of people's familiarity with this issue and the stakes involved.  
- We can maybe afford to take some of those liberties in later beats, but at the head we feel it's unwise with this subject.

### 3) In-camera vs. other
- doing this completely in-camera adds potential points of failure (e.g., casting, space, etc.(
- once we get this footage in the can, it will be difficult to course correct if needed via additional editing, graphics or writing.  
- plus: travel time on our side means: having everything rest on a studio shoot we can't attend feels risky.

## Next steps
- a) Mozilla will get you a script of narration by EOD Monday.  
- b) Meanwhile, Agency will iterate on whether your ideas around perspective could be realized via motion graphics, animation and typography - assets that are localizable, malleable and digital.   
- This would inform the visual system of the remainder of the campaign, as well as be informed by @lovegushwa (Jordna) and our team and the additional creatives we bring in for the other videos in the campaign. 
- To be clear: I’m advocating we not take a live action approach.  We'd love to see another pitch deck in this direction.

c) From that script (what you hear) you would deliver the concept for what we see. The script becomes document of record and evolves from words to storyboards to video.

d) We think we can push delivery forward a week till February 4th.

**Comment by rohanporteous** [comment]
## Script

That's fine on my end. I've pulled Tom off all outlines/scripting for the time being

## Abstraction/complexity

I think this could have been resolved when the script was coming together, as the idea itself didn't _have_ to be overly complex. But am also fine with simplifying!

## Treatment

Understand this point of view as well. That said, with the turnaround time I think we should also be realistic about ability to be agile, no matter what the style. Easier to change elements of course, but will still need a degree of trust without input if we're to be efficient with production time.

## Next steps

**A)** Script by Monday would be great! I think it might be best to work on the treatment once that's done as they're very linked, so it would be really good to know the content beforehand. 

**B & C)** Don't think the perspective idea will necessarily translate to (or be as powerful in) other more digital approaches, so will likely want to try something else. Good to be clear that motion graphics can be incredibly time consuming, so with the reduced time we'll have to very smart in our choices, and get ideas locked off early. (Can always return to the idea of altered/customized stock footage to reduce that burden and make sure we can get it done). Have approach some additional motion graphics people for capacity. Could potentially get different ones to assist with different shots, as necessary.

RE assets/guides: we'll likely have to just approach this slightly intuitively for this video, focusing on getting this one done while keeping extensibility in the backs of our minds throughout, and returning to rollout/any templates after launch.

**D)** Good to know! Is that week no longer as crucial, or you're just re-assessing feasibility? Unfortunately I'm flying to Sydney on the 1st, so won't be able to make the most of that time. But it gives us two more days at least.

**Comment by brettgaylor** [comment]
Thanks, Rohan - we've come back with a new script here https://github.com/MozillaFoundation/encryption_campaign/issues/6

**Comment by OpenMatt** [comment]
@rohanporteous let's work through all the issues you mentioned in the script ticket.

**Comment by OpenMatt** [comment]
@brettgaylor I think this ticket is now redundant -- the concept is baked into the script we're working on in #6. I'm going to close this -- re-open if you think there's still work left to be done here.
