### ISSUE TITLE
Write / pitch / place op-ed by Mark

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#30]
- [x] Build op-ed media list 
- [x] Identify top-tier targets ([here](https://docs.google.com/document/d/1NrwSASCP4W7t_unT7qHy3C1u_li3g5GrI7Lbc9z2FVM/edit#), page 3 -- needs OK from @HPaulJohnson) 
- [x] Craft pitch ([here](https://docs.google.com/document/d/1NrwSASCP4W7t_unT7qHy3C1u_li3g5GrI7Lbc9z2FVM/edit#bookmark=id.qkctwmnoq7p6), pitch no. 3 -- needs OK from @HPaulJohnson)  
- [x] Gauge MoCo/agency bandwidth to assist 
- [x] Pitch

@HPaulJohnson What's the earliest we can begin pitching?

**Comment by OpenMatt** [comment]
@HPaulJohnson

**Comment by KevZawacki** [comment]
Content of the op-ed will be similar to beat 2 blog by Mark (#34)

**Comment by KevZawacki** [comment]
Will begin pitching on Monday, Jan. 25

**Comment by OpenMatt** [comment]
@KevZawacki how'd it go?

**Comment by KevZawacki** [comment]
Still pitching; no bites yet. About halfway through our list of tier-one targets. Pitching and follow up will continue into next week.

**Comment by HPaulJohnson** [comment]
Op-ed complete, pitching continues.

**Comment by KevZawacki** [comment]
Placed in CNN! Closing ticket.
