### ISSUE TITLE
General pitch to media

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#32]
- [x] Build encryption media list
- [x] Identify targets (50+ publications in North America, Australia and UK)
- [x] Craft pitches ([here](https://docs.google.com/document/d/1NrwSASCP4W7t_unT7qHy3C1u_li3g5GrI7Lbc9z2FVM/edit#bookmark=id.w8rynobwm60k))
- [x] Pitch, beginning Feb. 16

@HPaulJohnson

**Comment by OpenMatt** [comment]
@KevZawacki what's the next step here? Is this over to @HPaulJohnson to review?

**Comment by KevZawacki** [comment]
@OpenMatt: @HPaulJohnson has reviewed. Once we have a couple pieces of encryption content published, we're ready to begin pitching. Milestone added.

**Comment by KevZawacki** [comment]
This will occur once we have two videos + the interactive activity published. Adjusting milestone accordingly.

**Comment by HPaulJohnson** [comment]
@KevZawacki can you update this based on latest input from MoCo Comms team?

**Comment by KevZawacki** [comment]
@HPaulJohnson I'll be speaking with Alex S. at MoCo this week to figure out the details, and will update this ticket accordingly. But, it's looking like A&P will work with our media list and pitches to conduct outreach.

**Comment by KevZawacki** [comment]
Developing... pitching will begin Feb. 10, alongside video 1 launch. 

Kevin will pitch friendlies / privacy reports; A&P to pitch consumer tech press. More details by end of the week.

**Comment by KevZawacki** [comment]
See A+P Playbook for agency role: https://goo.gl/38VRh7

**Comment by KevZawacki** [comment]
Latest: Pitching begins Tuesday, Feb. 16.

**Comment by KevZawacki** [comment]
Update: Currently at 39 stories globally.

**Comment by cassiemc** [comment]
:boom: @KevZawacki you're killing it

**Comment by OpenMatt** [comment]
+1 :)

**Comment by KevZawacki** [comment]
Pitching continues. I anticipate closing this ticket in late March, ~one week after beat 5 launches.

**Comment by KevZawacki** [comment]
Majority of beat 5 pitching took place Thursday, March 31. ([Here's one of the stories it garnered](http://www.trustedreviews.com/news/mozilla-wants-your-help-to-save-the-internet).)

We'll continue to pitch press around encryption for the next several months, but this marks the end of beat-specific pitching. :boom:
