### ISSUE TITLE
Campaign creative direction deck

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/encryption_campaign#38]
Documenting the design benchmarks, websites, video bumpers, and idents of existing television, video, or online channels for the encryption campaign:

**Comment by natalieworth** [comment]
@lovegushwa Links are here to the existing art direction you started and the current Pinterest board:
Initial art direction from Jordan:
https://docs.google.com/presentation/d/11HrepQP5rXFRsPh2CA-2P2U_DyUj8wjIVSMeSgPJ4qQ/edit#slide=id.gf4b30d392_9_27
https://docs.google.com/presentation/d/1CR7mrJss1CR5Ojns96Oq4vaSxfMzd5FN0dZiE2HFqqY/edit#slide=id.gf49c66da1_0_133

Pinterest benchmarking:
https://www.pinterest.com/lovegushwa/idents/

Google slides benchmarking/ images:
https://docs.google.com/presentation/d/1e0lvdUQO_T-lYxIUs6btYQ04cNHFPO8rLcPUXJHx6UA/edit#slide=id.p

**Comment by OpenMatt** [comment]
@natalieworth nice work! what's the next step here? Is this on @lovegushwa to review?

**Comment by natalieworth** [comment]
Thanks @OpenMatt, yes, I'm hoping @lovegushwa can review and we can begin to develop a more solidified design direction based off of these benchmarks for the campaign. I think we can leave this open until we have a good direction

**Comment by OpenMatt** [comment]
assigning to @lovegushwa as he has the next step here.

**Comment by lovegushwa** [comment]
Thanks for pulling this ticket together @natalieworth 
For Beat 1 let's focus these benchmarks around developing a general campaign aesthetic to be used in: 
- identity
- email and landing page UI
- social share
- contractor art direction (beat 2 and beat 3)

Let's use the art direction deck to consolidate (it's now open for MOFO's to edit)
https://docs.google.com/a/mozilla.com/presentation/d/11HrepQP5rXFRsPh2CA-2P2U_DyUj8wjIVSMeSgPJ4qQ/edit?usp=sharing

I will get this rolling and then @natalieworth you can help me edit in a day or two.

**Comment by OpenMatt** [comment]
sounds good guys. @lovegushwa is this ticket still something the wider group needs to discuss? Seems like no, so I'll remove the needs discussion label. Add it back if that's wrong.

**Comment by lovegushwa** [comment]
Converting this ticket to a campaign creative direction deck.

**Comment by OpenMatt** [comment]
@lovegushwa is it ok to close this one?

**Comment by lovegushwa** [comment]
@OpenMatt yeah, we should revisit this when we have time.
