### ISSUE TITLE
Build email templates

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/encryption_campaign#39]
Initial drafts and refined wireframes for the campaign's email templates (taking inspiration from Kristina's work on the Advocacy site):
Advocacy wireframes:
https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.en.6YeM-53K40k.O/m=m_i,t/am=PiPeQMCcjPuDuMY4gGbpCxT23nt-dpHiJwc8qD9hAIjULQD-b_b_AP4P2ou2UA/rt=h/d=1/t=zcms/rs=AHGWq9A3sBaB6Z1U026wF9Nqhgnzh0lBrw

There will be 3 templates for Beat 1 email:
1. Email with video directly embedded and CTA to share
2. Email with text and HTML/CSS CTA button to watch the video on microsite
3. Email with text and gif/ graphic image as a link to the video on microsite

There will then be 4 templates to accommodate the varying email lengths and content:
1. Standard email template consisting of text and images
2. Graphic/ image based email
3. Video based email
4. 'Dear Friends'/ personal email from Mark

Limitations:
- Background color is an option, but background image breaks in many clients
- System fonts only (for HTML text)
- Single column preferably (we can use FF&You grid/modular system if more flexibility is needed)
- max width of email = 600px
- Hero images in templates scale and render more easily than call out images in sidebars
- A simpler design is better for Advocacy because of the need for fast turn around
- Buttons are best for mobile users as text links can be hard to tap
- It may also be helpful to have an alt-text styling guide for when images don't render

cc @lovegushwa

**Comment by natalieworth** [comment]
Beat 1 initial email:
![img_3372-1](https://cloud.githubusercontent.com/assets/14876567/12362167/c2c5bcf6-bb76-11e5-89b3-daf45af413e3.JPG)

General email template wireframes:
![img_3371](https://cloud.githubusercontent.com/assets/14876567/12362193/dc6f4492-bb76-11e5-9c60-9f4f17f50460.JPG)

**Comment by OpenMatt** [comment]
@natalieworth @lovegushwa what are the next steps here?

**Comment by natalieworth** [comment]
@OpenMatt We'll need to further refine the wireframes in Illustrator, then begin the UI for dev build. I'm sure @lovegushwa can advise too when he's back from the MLKJ holiday.

**Comment by lovegushwa** [comment]
Let's talk about the fire fox and you email

First Ben Niolet provided the FF&You HTML:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvQi1DSlZ4aHI5V2M/view?usp=sharing
Lot's of reasons to use it including not needing to write new code and it's proven/tested and built for exact target. (@mmmavis @stephaniemcv )

Second check out this breakdown on what we can modify / re-purpose:

ESSENTIAL ELEMENTS
<img width="873" alt="screen shot 2016-01-19 at 3 57 25 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436776/110bca50-becd-11e5-897e-e7d3d40bbf0e.png">
Keep: Tabzilla
Remove / change: FF logo, links, background color

 <img width="799" alt="screen shot 2016-01-19 at 3 57 43 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436808/474f3fde-becd-11e5-8e07-6423754aceda.png">
Keep: hero images, typography
Remove / change: content column BG color

<img width="810" alt="screen shot 2016-01-19 at 3 57 56 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436832/6866ef28-becd-11e5-95d7-0a830b3ecb8e.png">
Keep: button style

<img width="808" alt="screen shot 2016-01-19 at 3 58 12 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436869/addf6332-becd-11e5-9c23-cd1a2cdcd58c.png">
Keep: break between content sections

NICE TO HAVE
<img width="812" alt="screen shot 2016-01-19 at 3 59 00 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436875/c3728ae4-becd-11e5-8d8f-ea931a36a36e.png">
Keep: graphic CTA lower in email

<img width="812" alt="screen shot 2016-01-19 at 3 58 28 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436887/defbf002-becd-11e5-9319-4566aaf2085b.png">
Keep: cool graphic lists that look 2 column

<img width="829" alt="screen shot 2016-01-19 at 3 59 28 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436914/1dee0728-bece-11e5-9c7b-514645f16c2c.png">
Keep: download buttons, maybe we wont ever have people download but could be used for social share

<img width="833" alt="screen shot 2016-01-19 at 3 59 45 pm" src="https://cloud.githubusercontent.com/assets/12228435/12436930/4127d84a-bece-11e5-81ca-14c6934e6ee8.png">
Keep: 2 column promo squares, could also be used for social.

**Comment by OpenMatt** [comment]
Note that the first use of this template will occur: Feb 8 w. launch

**Comment by stephaniemcv** [comment]
I agree with everything @lovegushwa noted about the FF&Y template. I think modifying this will best suit the campaign since the first deadlines are pretty tight. 

Some other notes to add to @natalieworth Limitations list above based on the rough wire frames
- Embedded video code is not supported by the majority of email clients. It can be done but it's very code heavy. Best practice is a linked image of the video. Sometimes you can do an animated gif but there are caveats to this as well.
- Emails consisting of only graphics are a challenge on mobile devices as graphic text when scaled can become too small to read. Also emails with 500 characters or less is more likely to be caught in SPAM filters.

**Comment by lovegushwa** [comment]
R?
@valianttry @stephaniemcv @shaghdoosti @HPaulJohnson @cassiemc @mmmavis @kristinashu

Hey folks please review the first round of email templates, again were using the FireFox + You template because it's already optimized, set up for exact target and we have the code!

##### Advocacy specific email templates

Test 1: We were going to test an embedded video @stephaniemcv recommends against it (thank you :)

Test 2: text and CTA button
https://redpen.io/p/aha81bb9490be6eb9c

Test 3: still of video or animated .gif + CTA button
https://redpen.io/p/xkd67d3afe0c3c922f

##### New template for MLN adapted from @kristinashu original design

https://redpen.io/p/vfdf531416d978c198

**Comment by valianttry** [comment]
I left comments in the redpens. Nice job!

**Comment by OpenMatt** [comment]
Nice! 

### Final steps to consider this design approved and close out this ticket:
- [ ] 1) address @valianttry 's RedPen comments
- [x] 2) get design review from @cassiemc 
- [ ] 3) gather optional feedback from @stephaniemcv @shaghdoosti @HPaulJohnson @cassiemc @mmmavis @kristinashu in this ticket by end of day today (Jan 22) (Note: this is feedback only. Final approvers are @cassiemc and @valianttry )

@lovegushwa sound right?

**Comment by OpenMatt** [comment]
Flagging as needs discussion so that we do a quick check-in in today's retrospective call

**Comment by cassiemc** [comment]
Design review is done, R+, they are all great options. Left some considerations in the redpen.

**Comment by OpenMatt** [comment]
@valianttry want to provide final design approval? Then @lovegushwa I assume we can close this one?

**Comment by lovegushwa** [comment]
@OpenMatt @valianttry revising based on redpen feedback, will post and close in the next hour.

**Comment by lovegushwa** [comment]
@mmmavis @stephaniemcv @simonwex @OpenMatt 
We can convert this to a build ticket, who's going to be working on this?

These email variants are ready to build using the FF+You HTML here:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvQi1DSlZ4aHI5V2M/view?usp=sharing

![teach-email-06-jordan-03](https://cloud.githubusercontent.com/assets/12228435/12560748/48388c9c-c351-11e5-961c-f05b54b5f63f.jpg)

![teach-email-06-jordan-04](https://cloud.githubusercontent.com/assets/12228435/12560762/51914c98-c351-11e5-9de7-def2e544e16f.jpg)

![teach-email-06-jordan-05](https://cloud.githubusercontent.com/assets/12228435/12560766/594e0c5a-c351-11e5-92b9-d430d89bc919.jpg)

**Comment by OpenMatt** [comment]
@ScottDowne can you work on the build for this? Or should we assign to someone else? (cc @simonwex )

**Comment by ScottDowne** [comment]
Does dev start or begin on Jan 29th?

Either way, I was thinking of taking some time off in Feb, so it might not be me that takes this.

**Comment by stephaniemcv** [comment]
I can take this. It should only take slight modification of current code in ET.

**Comment by lovegushwa** [comment]
@stephaniemcv yay! 
I'm going to convert this to a build ticket.

**Comment by OpenMatt** [comment]
@stephaniemcv how's it going? need any help?

**Comment by stephaniemcv** [comment]
Thanks to a last minute assist from @lovegushwa, the first three templates have been created in Exact Target.

**Comment by HPaulJohnson** [comment]
As discussed on today's retrospective, seems like this is good to go. Nice work! Closing.
