### ISSUE TITLE
Finalize campaign KPIs

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#4]

**Comment by adamlofting** [comment]
The team are meeting today to discuss impact goals and KPIs.

**Comment by OpenMatt** [comment]
@adamlofting will update here based on that meeting. 
- @adamlofting: let's update and keep using this existing document: KPIs http://mzl.la/encryption_kpis

**Comment by adamlofting** [comment]
We discussed many possible points of impact during the call, and developed a strawman impact goal to be evolved and improved over the course of the workweek (this initial take hasn't been seen by all the team yet).

We've been working on the impact goals in [this document](https://docs.google.com/document/d/1UzvIUhi93yREAwwJ7JsizesCfRHnZOR2ah1CMjnsu-o/edit#heading=h.7x19v3h0771f) which I have also added to the http://mzl.la/encryption_kpis document just now.

**Comment by OpenMatt** [comment]
* Ok thanks @adamlofting. Sounds like your work on this is done for the time being, and you're passing the baton back to the rest of the team to discuss and come back w. next steps in their work week. 
* @valianttry can you be responsible for updating this ticket / following up?

**Comment by adamlofting** [comment]
Latest update:
- I took another pass at this document today including building a survey to use as part of the evaluation process
  - This is all strawman for the team to build upon
- The team at the workweek will continue to review this and get it to reflect their goals
- We have a check-in booked for Thursday AM (PST)
- Goal is to sign-off the Impact Goal and KPI targets by the end of the week

**Comment by OpenMatt** [comment]
Great! Thanks Adam.

**Comment by adamlofting** [comment]
Marking this as closed unless anything else comes up while this is being reviewed this week.

https://docs.google.com/document/d/1UzvIUhi93yREAwwJ7JsizesCfRHnZOR2ah1CMjnsu-o/edit#
