### ISSUE TITLE
Build landing page / microsite

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/encryption_campaign#40]
Area to document wireframes for the encryption landing page/ microsite (potentially using elements from Kristina's existing wireframes for the Advocacy site):
https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLZEhObmFseGxOeEU&usp=sharing#

**Comment by natalieworth** [comment]
Final sketched wireframe:
![img_3368](https://cloud.githubusercontent.com/assets/14876567/12362550/c43404ec-bb78-11e5-9d23-2ad695a8e883.JPG)

Benchmarks for the landing page in issue #38

**Comment by natalieworth** [comment]
Elements to include:
- Can have multiple CTA buttons- Email Opt in's/ Social Share
- UX that can accommodate adding upcoming videos
- area to house video content

cc @lovegushwa

**Comment by natalieworth** [comment]
Initial wireframes for the microsite (based off of Kristina's wireframes for the Advocacy site here: https://drive.google.com/a/mozillafoundation.org/folderview?id=0B2irLVDJivhLZEhObmFseGxOeEU&usp=sharing#
Redpen for microsite wireframes: https://redpen.io/p/rv00aaeaa82563cde2
cc @lovegushwa

**Comment by natalieworth** [comment]
Most recent wireframes up on Redpen: https://redpen.io/p/rv00aaeaa82563cde2
For now (due to time constraints), it would be best to focus on finalizing the wireframes and upcoming UI for Beat 1 and then focus on Beat 2-5. I will add the additional wireframes for Beat 1 (with the variations included for email and social media opt-in)

**Comment by lovegushwa** [comment]
R?
@valianttry @shaghdoosti @HPaulJohnson @cassiemc @ScottDowne  @kristinashu

Please review these wireframes today if you get a chance. (See link above.)

**Comment by cassiemc** [comment]
R+ on beat 1, looks good.

**Comment by natalieworth** [comment]
I have the wireframes updated for Beat 1. If everyone is able to review them, then @lovegushwa  and I can tweak, and begin UI for Monday. 
Couple of issues that will have to be resolved for Monday/ Tuesday build:
- How video will be hosted/ or alternative, if it is self-hosted, what the UI platform will be for play, pause, full-screen, etc.
- which platforms we are encouraging for social share
- Any additional information for the Newsletter
- @HPaulJohnson @KevZawacki I'm assuming we will also need a bit of copy for the first beat
- Also need to decided (before beat 3) if the 'Cryptoloji' should come before or after the videos, or change depending on the beat launches
  Redpen: https://redpen.io/p/st2595cb1c9edaee5c

@valianttry @shaghdoosti @HPaulJohnson @cassiemc @ScottDowne @kristinashu @flukeout

**Comment by kristinashu** [comment]
Looks good, can't wait to see the design!

**Comment by HPaulJohnson** [comment]
Looks good, @natalieworth. Left some comments in the Redpen's. 

@KevZawacki and I have it on our list to draft copy for this and we'll work on that early next week based on these wireframes.

I want to confirm that we will be plugging in Optimizely on this page? I think many of the comments/feedbacks can actually be things we test and will want to optimize for. Sharing and email collection seem like critical parts of our plan and therefore would be great to run some tests around those two pieces of content. 

For sharing, I'll set a meeting with you and @lovegushwa to demo Share Progress so you can better understand how it can be integrated with this page.

**Comment by natalieworth** [comment]
@HPaulJohnson Sounds great, thanks!

**Comment by OpenMatt** [comment]
Nice work team. What are the final steps to closing this ticket?

@valianttry: can you provide final design approval?

**Comment by shaghdoosti** [comment]
@valianttry would love to know if you agree with this -- my instincts are that the signup should be next to the video.  I worry that if the actions are below the video we'll see a lot less conversions.

**Comment by ScottDowne** [comment]
@shaghdoosti I would probably ask design that question.

My 2 cents are to go with just the signup, and put the video in the post signup/thank you.

**Comment by ScottDowne** [comment]
It's worth testing a video, and in various places.

**Comment by OpenMatt** [comment]
- we agreed to try testing an on-the-side variant in today's call. (removing above and below) @lovegushwa @natalieworth are you guys clear on next steps here?

**Comment by OpenMatt** [comment]
https://redpen.io/p/rv00aaeaa82563cde2

**Comment by natalieworth** [comment]
I've updated the Beat 1 landing page based upon today's meeting and the comments from redpen.  We were able to finalize:
- social share: include email, facebook, and twitter options (can add more in future beats to test other icons for sharing)
- opt-in will include a pop-up with input for name, email, and country ( @valianttry confirm if these options are good, or if just email is preferred)
- pop-up for opt-in allows the design to be more accessible for mobile and desktop/ variety of screens
- End of video will include the options again to share via email, facebook, or twitter along with the title of the video just watched and the option to replay

I'm currently working on finishing the variant with the opt-in beside the video that Sara suggested and will post this evening. If anyone has any final comments or suggestions to these wireframes I can update this evening and repost. Thanks! 

![encryption-wireframes-11-02](https://cloud.githubusercontent.com/assets/14876567/12569684/e7b66512-c385-11e5-8cfe-be2ea81f787b.png)
![encryption-wireframes-11-03](https://cloud.githubusercontent.com/assets/14876567/12569685/eb71fc3e-c385-11e5-9ce6-3ee0c779709d.png)
![encryption-wireframes-11-04](https://cloud.githubusercontent.com/assets/14876567/12569686/edf32cd0-c385-11e5-8bcf-4c145a4630a0.png)

cc @lovegushwa @HPaulJohnson @valianttry

**Comment by ScottDowne** [comment]
I may have gotten this mixed up with the snippet issue. @shaghdoosti was your question about the video beside in regards to the snippet or the landing page?

For what it's worth, putting it beside is quite a large change from previous snippets and might be something we want to run by the snippet team.

**Comment by natalieworth** [comment]
![encryption-wireframes-11_artboard 79](https://cloud.githubusercontent.com/assets/14876567/12570008/04fcb88a-c389-11e5-8e38-dca322104218.png)

@ScottDowne I think @shaghdoosti was referring to the design layout above for the landing page. I've removed the content of the video for this version as the responsiveness of this would then interfere with the carousel and create an awkward stacking order.

**Comment by lovegushwa** [comment]
@alicoding @natalieworth @shaghdoosti @HPaulJohnson @valianttry 
Final, final Beat 1 wire-frame variants. 

![encryption-wireframes-12-01](https://cloud.githubusercontent.com/assets/12228435/12592753/99a59440-c422-11e5-9bf0-6b0239da3819.png)
![encryption-wireframes-12-02](https://cloud.githubusercontent.com/assets/12228435/12592765/a90e98e6-c422-11e5-97d5-f46fa189e8ca.png)
![encryption-wireframes-12-03](https://cloud.githubusercontent.com/assets/12228435/12592770/b0b5d136-c422-11e5-85ea-7a7759cbd53c.png)
![encryption-wireframes-12-04](https://cloud.githubusercontent.com/assets/12228435/12592774/b4bf7c00-c422-11e5-8208-bc351cc72e10.png)
![encryption-wireframes-12-05](https://cloud.githubusercontent.com/assets/12228435/12592778/b9ba90a0-c422-11e5-9842-1f766766bb10.png)
![encryption-wireframes-12_artboard 79](https://cloud.githubusercontent.com/assets/12228435/12592780/bdbe5704-c422-11e5-934c-8f81c13a9a8c.png)

**Comment by KevZawacki** [comment]
@HPaulJohnson Microsite copy tightened up and ready for your review [here](https://goo.gl/7HcEBM).

**Comment by HPaulJohnson** [comment]
thanks, @KevZawacki. 

@shaghdoosti and @valianttry if you could take a look at draft copy for landing page and provide any edits/feedback that would be great.

**Comment by rohanporteous** [comment]
Hey @lovegushwa, I believe @brettgaylor was going to open a new issue following my call with him but just in case I thought I'd follow up here:

Do you have any designs for this? The final moments of the video could obviously benefit from considered stylistic integration with the site, so would love to have access to whatever you've got or get some points on direction in the meantime. Let me know.

**Comment by HPaulJohnson** [comment]
@lovegushwa @natalieworth - copy has been reviewed and updated (see issue #68).  It is ready go into the designs.

**Comment by lovegushwa** [comment]
R? @cassiemc @kristinashu @valianttry 
CC @shaghdoosti @HPaulJohnson @OpenMatt @brettgaylor 

Final Encrypt campaign UI for beat 1, please check the redpen and review. I'm pushing to close this be end of day. https://redpen.io/p/yk6b656ce94eb032d4

**Comment by cassiemc** [comment]
Overall is good @lovegushwa. The color combo of purple and pink feels a little dangerously gendered to me though, esp. with some of the other design elements (soft rounded corners, abundance of copy / social links – can't put my finger on a like example but it's reminiscent of other women's issue microsites). So might consider another color option.

**Comment by rohanporteous** [comment]
While this is completely not for me (sometimes I just can't help myself, huh)… generally looking great @lovegushwa. I agree with Cassie, and would possibly play with mixing up bold colors for different pages/beats etc to feel a bit broader. 

Main reason for writing though is to just add one small point: with so many bold colors happening it's a little hard to tell exactly what the UX should be—what action should they be taking at each stage? Currently so many elements vying for attention that this could be made slightly clearer, through whatever means you think works best. But not terrible :)

**Comment by lovegushwa** [comment]
@rohanporteous are you ok with waiting until early next week to resolve the graphic end cards?
https://github.com/MozillaFoundation/encryption_campaign/issues/85

I need some time to sort out the color pallet.

**Comment by lovegushwa** [comment]
@alicoding here is the final UI (what's Alans handle? can you CC him?)
I need to follow up with a few additional elements like the sign-up popup, video CTA's and any images you need tomorrow.
CC @ScottDowne 

**V1 (direct from email)**
<img width="1800" alt="encryption-ui-annotation-011-02" src="https://cloud.githubusercontent.com/assets/12228435/12741443/381d0424-c931-11e5-8b61-02fe6b30c3c3.png">
<img width="1800" alt="encryption-ui-annotation-011-01" src="https://cloud.githubusercontent.com/assets/12228435/12741447/3e7a2608-c931-11e5-9e4c-b8c816a14a5b.png">

**V2 (organic/social)**
<img width="1800" alt="encryption-ui-annotation-011-04" src="https://cloud.githubusercontent.com/assets/12228435/12741459/579a8632-c931-11e5-8eb7-02fde0ec9845.png">

**V3 (organic/social)**
<img width="1800" alt="encryption-ui-annotation-011-03" src="https://cloud.githubusercontent.com/assets/12228435/12741475/7d639d9a-c931-11e5-8246-2743aae5bcf3.png">

**Comment by alicoding** [comment]
cc @alanmoo

**Comment by lovegushwa** [comment]
@alicoding  @alanmoo

Redpen (these do not display at %100, I checked): https://redpen.io/p/ab619073e3fbcf32e1 

72.dpi .pngs: https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvbTJqV01nRVUzSTA&usp=sharing

Final Ai file:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvTFVReXl6TmxhaDQ/view?usp=sharing

**Comment by OpenMatt** [comment]
@alicoding @alanmoo @ScottDowne are we all set to push ahead with the build, now that design is done? Just want to make sure the hand-off is all good from your side.

**Comment by alicoding** [comment]
@alanmoo and I started working on the build now, so we're all good :+1:

**Comment by lovegushwa** [comment]
Checklist of items still needed:
- [x] Static video image
- [x] Placeholder for header animation
- [ ] Animated header (.gif or .svg even better)
- [x] Medium icon 
- [x] Error state for form text
- [x] Button states 
- [x] UI after video plays
- [x] Video variants

**Comment by natalieworth** [comment]
Static video image: https://drive.google.com/file/d/0B20-0lpP23c0d2s1cFR1ZzI5UkE/view?usp=sharing
Button states: Mock-up example for this here: https://d157rqmxrxj6ey.cloudfront.net/natalieworth/30204/ _(sorry dev friends if my code hurts/ is janky)_ We are hoping to just have it invert in colour with a slight animation on hover on/off.

Will post placeholder image early tomorrow morning. Thanks

**Comment by alanmoo** [comment]
We also still need guidance on what happens when the user clicks either "Sign Up" button in V2

**Comment by lovegushwa** [comment]
@alanmoo this was what we originally planned. Pro's and Cons? (not really time to design a different solution, do you have something else in mind? If not can we stick with the popup)
![eb71fc3e-c385-11e5-9ce6-3ee0c779709d](https://cloud.githubusercontent.com/assets/12228435/12833154/9e62a562-cb53-11e5-94ef-3b7bfa5a79ff.png)

**Comment by natalieworth** [comment]
Here's a temporary placeholder svg for the 'encrypt' wordmark:  while I work on exporting an svg animated version https://drive.google.com/open?id=0B20-0lpP23c0WGV1OHUzd0RKeEk

Also Medium's newest logo icon: http://fortawesome.github.io/Font-Awesome/icon/medium/

**Comment by lovegushwa** [comment]
@alanmoo UX popups for after video plays!
@shaghdoosti @valianttry are these good to go?

![encryption-ui-012-01](https://cloud.githubusercontent.com/assets/12228435/12853908/84f40f92-cbeb-11e5-9122-c69f32404aed.png)

![encryption-ui-012-02](https://cloud.githubusercontent.com/assets/12228435/12853914/89e9a9bc-cbeb-11e5-8489-cda0d4f13fb6.png)

**Comment by natalieworth** [comment]
+1

**Comment by shaghdoosti** [comment]
Look good to me.

**Comment by valianttry** [comment]
:+1:

**Comment by lovegushwa** [comment]
@alanmoo ok final UI and assets for after video:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvaldhV3hpZUV6aVk&usp=sharing

![encryption-ui-012-01](https://cloud.githubusercontent.com/assets/12228435/12858428/04d8d6e8-cc05-11e5-857e-2da034f1d76a.png)
![encryption-ui-012-02](https://cloud.githubusercontent.com/assets/12228435/12858432/0a89dde4-cc05-11e5-983f-08cb53df6810.png)

**Comment by lovegushwa** [comment]
@alanmoo final video files are here:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvTzRGM1FZazI5Rm8&usp=sharing

**Comment by lovegushwa** [comment]
@alanmoo poster images are here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlvc3V0TTktNURSbE0&usp=sharing

**Comment by alanmoo** [comment]
Am I correct in assuming that the Medium icon should be inside a circle like the rest of the icons?

**Comment by lovegushwa** [comment]
@alanmoo yes, please treat the Medium icon like the others.

**Comment by alanmoo** [comment]
In that case, it's probably best just to use an SVG like the others. (Playing with CSS to center icons on a circle can be a surprising time sink.) Would a designer be able to generate that?

**Comment by alanmoo** [comment]
Scratch that last request, I found something else in the project I could adapt to generate the icon-on-circle style.

**Comment by alanmoo** [comment]
@lovegushwa @HPaulJohnson Does the share modal appear after the user clicks submit in the sign up modal in v2?

**Comment by lovegushwa** [comment]
@alanmoo if this is simple to implement let's do it. If you need more time we can do this later in the week.

**Comment by alicoding** [comment]
What's left for this ticket to be closed?

@lovegushwa @valianttry ?

**Comment by alanmoo** [comment]
I’m still working on getting the animated encrypt text up, it’s a bit complex integrating the JS into react, especially with the server side aspects of it

**Comment by alicoding** [comment]
I think we can close this ticket and file another issue for the animated logo if needed.
