### ISSUE TITLE
Create Medium publication to house beat blogs

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#41]
Needs further discussion. Initial email sent to Gabe at Medium seeking guidance and insight.

@HPaulJohnson

**Comment by jgmac1106** [comment]
Would also suggest creating a beat specific tag or just using the mozilla
tag for authors who are sharing but are not efitors or writers for the
publication.

**Comment by OpenMatt** [comment]
@KevZawacki who do you need to discuss with?

**Comment by KevZawacki** [comment]
@OpenMatt Further discussion needed with Paul and our contacts at Medium. It'll be happening this week.

**Comment by OpenMatt** [comment]
Ok I'm going to remove the "needs discussion" flag and just leave with @KevZawacki to follow up and push ahead.

**Comment by KevZawacki** [comment]
[Publication created](https://medium.com/encryption-matters). Working with @HPaulJohnson, @natalieworth and @lovegushwa on images and copy.

**Comment by OpenMatt** [comment]
@KevZawacki great! can we close? if so please go ahead.

**Comment by OpenMatt** [comment]
@KevZawacki do you think it would be appropriate for us to also post our "working open on the campaign" style posts here as well? Progress reports / updates on what we're learning ourselves as campaigners, etc? Or do you see this as a different audience / goal?

**Comment by KevZawacki** [comment]
@OpenMatt Different audience, I think. The existing Medium publication will be for a very broad audience. Progress reports would likely confuse / distract.

**Comment by jgmac1106** [comment]
@openmatt I would make that a separate publication but controlled by the
same account. You can spin up as many pubs as you want. What will be just
as important is encouraging people who are not in the pubs to use a
community based tag or an @mention to track others writing about the topic.

My guess is you may end up with different editors and writers of the
publications.

Hopefully "working open" would have more writers from across MoFo/MoCo than
the Publication "Encrypt."

I also am hoping the content featured on Medium lives somewhere outside of
their silo. Syndicating to a publication through the "Import" story is
really easy.

**Comment by OpenMatt** [comment]
thanks @jgmac1106 -- @KevZawacki what do you think about creating a separate publication? We just need an interim solution (like, through Feb and maybe March) before we get on our own new and imrpved proper blog / CMS solution, which @simonwex says won't be ready short-term. Ultimately we'll want something like http://fundraising.mozilla.org/ for all our Advocacy work. But could use something quick and dirty to get started sooner.

**Comment by KevZawacki** [comment]
@OpenMatt Sounds good to me. Let me know if/how I can help get it off the ground.

**Comment by OpenMatt** [comment]
@KevZawacki awesome! Can you a) create it for us, and b) get @valianttry whatever credentials she'll need to post to it? I assume @valianttry will probably be our first poster, though the entire team will need the ability to post to the publication.

**Comment by OpenMatt** [comment]
also, let's stop using this ticket (since its closed) and use this one going forward instead: https://github.com/MozillaFoundation/encryption_campaign/issues/79#issuecomment-177018418
