### ISSUE TITLE
Approve video 1 art direction 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#43]

**Comment by brettgaylor** [comment]
Expected Thursday January 21

**Comment by brettgaylor** [comment]
Works for me

@lovegushwa want to take a look?
https://drive.google.com/a/mozillafoundation.org/file/d/0B3UIshL1Uom0OEF5a3pGcG5OaFE/view

**Comment by OpenMatt** [comment]
@lovegushwa once you approve please update here and close this ticket.

**Comment by lovegushwa** [comment]
@OpenMatt @brettgaylor left comments in the ticket R+ with a few small tweaks.
