### ISSUE TITLE
Lock script for video 2

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#47]

**Comment by OpenMatt** [comment]
@brettgaylor status of this one?

**Comment by OpenMatt** [comment]
* shared with @Jochai1 yesterday
* will need to take an additional pass to incorporate those notes
* a bit unclear on next steps
* @brettgaylor can you update status?

**Comment by OpenMatt** [comment]
From Brett's email:
- Brett is working with our policy team to lock the script for your video.  
- generally they are on board but for this one but it's important to get the language right
- Brett has asked them to close their comments by Jan 20
- Brett will approve those first thing Wednesday
- Should not effect Darren's ability to deliver the animatic Friday

**Comment by OpenMatt** [comment]
Darren says:
- has been reaching out to subcontractors 
- hoping start date for animation is Monday the 25th.
- By then I'd like the animatic approved, and hopefully I have a good amount of layout and modeling done. 
- I'm still planning on getting you some sort of animation test soon too. I'm just doing a little technical research right now.

**Comment by shaghdoosti** [comment]
Quick update. From myself and @valianttry 

I sat down with Jochai and went through the script to solve some of the challenges he had highlighted from the policy team perspective. 

I've tracked the changes in the document. Jochai will want to see the final script as well if we tinker with it again but I think the only think standing in the way of this script being locked is fact checking. @HPaulJohnson Is there any chance you could help on that? 

Here's the script: https://docs.google.com/document/d/1AJkQTko64o6Cz5g1HXDCaY-vuh5ComkSGKeaemqh7Cg/edit

**Comment by HPaulJohnson** [comment]
yes, @shaghdoosti, I can help fact check tomorrow. going to also enlist @KevZawacki to help to expedite if this is the blocker.

**Comment by HPaulJohnson** [comment]
@KevZawacki has fact checked historical examples used in the script (Da Vinci, Queen Elizabeth and Founding Fathers) and everything checks out. We are good to go.

**Comment by OpenMatt** [comment]
- @darrenpasemko : Darren, let's work in this thread instead of email where possible, to keep everyone in the loop who needs to be

**Comment by OpenMatt** [comment]
@darrenpasemko asks:

@brettgaylor: Any news on the script? Has the VO been approved? Schedule wise things are getting tight.

**Comment by brettgaylor** [comment]
Worked out a final few points with Jochai, he is going to take a final pass before EOD today.

**Comment by darrenpasemko** [comment]
Thanks Brett.

On Thu, Jan 21, 2016 at 12:35 PM, Brett Gaylor notifications@github.com
wrote:

> Worked out a final few points with Jochai, he is going to take a final
> pass before EOD today.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/47#issuecomment-173700291
> .

## 

Darren Pasemko
Director
4644 S.E. 51st Ave
Portland, Oregon, U.S.A.
97206
(646) 406-1320
www.pasemko.com

**Comment by shaghdoosti** [comment]
Jochai is on a plane for most of today -- Brett if you can look at the comments you can see our concerns around that section.

**Comment by brettgaylor** [comment]
We sorted it out and found something that works.

One nagging issue with fact checking of Da Vinci.

**Comment by brettgaylor** [comment]
@KevZawacki I looked into the Da Vinci references after Jochai raised some concerns about the veracity of claims that he used mirror writing, and also whether this is technically encrpytion - I found a few websites where scholars disputed this.  Given that, I wonder if you could help find one non-western/northern example of encryption?  Any asian/arabic references we might be able to use? 

After that, this script should be considered locked!

**Comment by brettgaylor** [comment]
Actually, I just found some good examples here:
http://www.theatlantic.com/technology/archive/2016/01/the-long-and-winding-history-of-encryption/423726/

And closed the script :)

**Comment by darrenpasemko** [comment]
Let me know when the narration is confirmed locked. After that I'll get cracking on revising the animation script. I hope to do so tomorrow morning. Maybe we can get that approved by the end of day tomorrow (Friday the 22nd). I'll start the animatic over the weekend, and I'll have it ready by Monday. An animation test is in the works too. Thanks!

**Comment by brettgaylor** [comment]
Narration is locked

**Comment by OpenMatt** [comment]
Awesome! So: @darrenpasemko please push ahead.

**Comment by brettgaylor** [comment]
Not sure if some of my communications aren't coming through, but this is
locked and final. Feel free to close!

**Comment by darrenpasemko** [comment]
Sorry Brett, I thought there was still one detail hanging. We're locked! Awesome. Thanks everyone. Pushing forward today.

**Comment by darrenpasemko** [comment]
Here's an animation test for Video 2. 
https://vimeo.com/152782114
Password: Mozilla
More to come over the weekend.

**Comment by valianttry** [comment]
@darrenpasemko that is SO delightful! It's really awesome to see her "come alive" :ok_woman:

**Comment by darrenpasemko** [comment]
Thanks so much Andrea!

**Comment by lovegushwa** [comment]
@darrenpasemko yeah this is looking good!

**Comment by brettgaylor** [comment]
Agreed. Like the frame rate and how she appears. Can't wait to see what a
transform looks like!

**Comment by lovegushwa** [comment]
Hey folks, is this the final locked script?
https://docs.google.com/document/d/1AJkQTko64o6Cz5g1HXDCaY-vuh5ComkSGKeaemqh7Cg/edit

If not can you drop in a link? Thank you!

**Comment by OpenMatt** [comment]
@brettgaylor is that the correct version?

**Comment by darrenpasemko** [comment]
That is! That's the correct and final locked script.

**Comment by darrenpasemko** [comment]
Just a reminder, we need approval on the text overlays to make sure those words are confirmed. "ENCRYPTION" in SCN01. "Cyphertext" in SCN02. "Plaintext" in SCN03. "ENCRYPTION POWER!" in SCN11. "Protecting Human Rights!" in SCN16. SCN16 was the only sticky point I believe. Thanks!
