### ISSUE TITLE
Get storyboard approval for video 2

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#49]

**Comment by brettgaylor** [comment]
Darren will provide initial storyboards Thursday for approval January 22nd.

**Comment by OpenMatt** [comment]
@darrenpasemko status of this one? I know it kinda overlaps w. some of what we discussed in #47

**Comment by darrenpasemko** [comment]
Hi Matt. The completion of the voice over script was pushed in the schedule. So the storyboard and animatic phase is also pushed. Today I am revising the animation script to match the new voice over script, and then I'm starting the storyboard/animatic. These items will be ready Monday the 22nd for review.

**Comment by OpenMatt** [comment]
@darrenpasemko great! I assume you mean Monday the 25th right? Will look for those today.

**Comment by darrenpasemko** [comment]
I'm still in the thick of it. The storyboard is in the works. I hope to have finished late this afternoon.

**Comment by darrenpasemko** [comment]
Update: I'm pushing through the storyboard, but it's going to take me until the evening to finish up. Some of the panels require detail in order to really communicate the actions. Sorry for the delay.

**Comment by brettgaylor** [comment]
No worries.  I will check in tomorrow for approval and comments.

> On Jan 25, 2016, at 4:52 PM, Darren Pasemko notifications@github.com wrote:
> 
> Update: I'm pushing through the storyboard, but it's going to take me until the evening to finish up. Some of the panels require detail in order to really communicate the actions. Sorry for the delay.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/MozillaFoundation/encryption_campaign/issues/49#issuecomment-174711192.

```
Brett Gaylor
Open Web Fellows + Advocacy Media
Mozilla






```

**Comment by darrenpasemko** [comment]
The first pass storyboard panels are done. I'll throw them into a Google Doc after lunch. The next step would be to record temp narration and edit an animatic. I'll have both of these finished today. Getting there.

**Comment by darrenpasemko** [comment]
The storyboard is up: https://goo.gl/RG1jwm
I need some feedback. I'm going to take a step away from it. I'd love to chat about it tomorrow. I also got my wife to record a temp track for the audio, to get a sense of how the script is reading (she has a great voice). I'll edit that tonight, and start piecing together a rough animatic to see how these visuals are really playing out.

**Comment by brettgaylor** [comment]
Hey, @darrenpasemko !  Honestly, these are fantastic.  Awesome work.

Folks are going to leave some comments in the google doc, and I'll make sure to connect with you tomorrow morning to close the final feedback.

Can't wait to see this in animated form!

**Comment by darrenpasemko** [comment]
Thanks Brett. Talk more today! I've hired on a Producer. Karina Ripper. She rips it up! I'm sitting down with her from 1:30-3:00.

**Comment by darrenpasemko** [comment]
Here's the animatic! 
https://vimeo.com/153425970
Password: Mozilla

Notes...
The Animation test has been quickly inserted to the animatic at the start. The morphs are non-existent right now, as that will happen in the animation phase, but are suggested in the edit. The camera cuts to different shots of the "cypher-text" bits falling to the ground at start. The particle systems will be dynamic and organic once animated. Currently the animatic stutters between stills, as most animatics do, so there is a bit of a loss in translation there. There is no final design and no final backgrounds. I've added storyboard arrows to suggest camera moves. I've added some supplemental actions to sweeten the edit. At times character animation will be center stage, such as at the start of SCN12, and that's not perfectly flushed out during the animatic phase. We'll let the animators bring that to life. I've replaced the typewriter with a pencil, let me know if that fits the bill.

I'm happy to go through it with the team if needed. I'm ready to make revisions. Looking forward to talking more. If we can get a sign off by end of day tomorrow that would be incredibly helpful.
Darren

**Comment by OpenMatt** [comment]
Thanks @darrenpasemko !

@brettgaylor : I assume next step here is for you to give notes

**Comment by brettgaylor** [comment]
Hey @darrenpasemko + @KarinaRipper!

This is looking great.  I only have 3 flags at the moment:

1) I may have missed in the script that we were using a "key" morph.  I'd like to move away from this as keys are a metaphor that is often used to describe encryption, and we're actually trying to run an experiment where we never use this phrase at all :)  Can we try a heart instead?  I will update the script accordingly

2) After hearing this readthrough (I wished I'd had more time to do this before locking script), there's some redundancy and phrasing that I think can be tightened.  I don't think it will have any effect on the animation at all, but it's another thing I'll address in the script before we record narration.

3) The words "cyphertext" and "plaintext" I think get a little lost in what I imagine that animation will look like - I wonder if we could display them on screen?

Other than those points, approved!

**Comment by KarinaRipper** [comment]
Hi @brettgaylor! 
Thanks so much for the quick feedback and approval, woohoo! 
Darren and I are taking a look now at the notes and will make revisions to the animatic and repost.  

For the script changes (note 2), this one is more pressing, any chance that your team can make this happen today? The animation is timed to the script so it will be affected, so it's super important to have this locked down prior to animating. We'll need this as soon as we can have it so we can re-record temp VO and adjust timing of the animatic.  @OpenMatt 

Thank you!

**Comment by KarinaRipper** [comment]
@brettgaylor checking in, will the Mozilla team be able to make progress on the changes to the script today? Hoping we can lock down the script and timing of the scratch VO in the animatic today. Muchas thanks!

**Comment by darrenpasemko** [comment]
I'll make Encryption a heart rather than a key! You got it. (Sorry about that, just experimenting)

In terms of: "The words "cyphertext" and "plaintext" I think get a little lost in what I imagine that animation will look like ..."  I was attempting to let the abstract animation breath a little here... 

The camera is over head, pieces are plummeting downward to the surface. The pieces are breaking into smaller pieces as they fall. My plan was to let the VO do the talking here, while a little bit of visual poetry plays out. The quiet before the "morph storm."  

We can use English words? If so I'll revise SCN03 to be more in line with SCNS 04-06. The word "Plaintext" is formed by the cyphertext bits. That would work.

Thanks Brett. Let me know.

**Comment by brettgaylor** [comment]
Hey guys - no won't be able to have #2 done today, but can get to it tomorrow morning.  I really do think its a word here/there and won't effect timing.

Re: cyphertet/plaintext, I agree that the animation should breath, I wasn't imagining that any of the pieces of encryption would re-assemble into those words, just that they would be super-imposed over the top of the animation.  This also isn't ultra-critical - it's just that these are really new words to most folks, and I think they are worth calling out.

> We can use English words? If so I'll revise SCN03 to be more in line with SCNS 04-06. The word "Plaintext" is formed by the cyphertext bits. That would work.

^ Not sure I get that piece. Can you try again explaining?

**Comment by darrenpasemko** [comment]
Thanks for addressing the VO script tomorrow. Good timing, as the animators are ideally going to start on Monday.

Sorry B, I thought you were saying you wanted the pieces to form the words "cyphertext" and "plaintext." Gotcha now! Just super-impositions.

I would recommend not doing super-impositions of text, unless you're doing it elsewhere in the series, or want to do elsewhere within BEAT 2.

On the other hand I think the VO works in delivering that info, without having to see the words on screen. But I leave it to you and the Mozilla Team to make that call. I will follow suit with whatever you need.

**Comment by darrenpasemko** [comment]
I just added the super-imposed text to the animatic. This will work! I'd be down to add more too! It gives it more of a campy instructional feel. Let me know if there's anywhere else you want it.

**Comment by darrenpasemko** [comment]
In the next animatic, I'm going to play with some more superimposed text for fun. I'll propose something; just to see. It'll be easy to take it off if it doesn't work. It gives the piece an extra bit of playfulness. I'm already seeing some good results.

**Comment by darrenpasemko** [comment]
New Animatic...
https://vimeo.com/153425970
Password: Mozilla

Brett, the heart transformation wasn't working so well. So I tried another route. I tried to expand upon the device of superimposed text, which you had suggested using on "Cyphertext" and "Plaintext." I really liked those results.  I also thought the animation could "freeze frame" when the text comes on to the screen, that could be silly and fun.

Superimposed text reminded me of standard, retro,campy instructional films. I think superimposed text playing off the authoritative warm voice of the Narrator could work really well. I think the text adds levity, and sense of humor, and gives the film more personality. 

The tone of the text elements is inspired by this: https://vimeo.com/album/2472533/video/13497928
I also sent this video to Jason as a reference for the music. He loved it!

I don't know if this helps, but I can't get Same Elliot's voice out of my head for the Narrator.
https://www.youtube.com/watch?v=cSTPOgqeloI
https://www.youtube.com/watch?v=1R07cCydCeY

All that being said, this where I'm at. Talk more this weekend.

**Comment by brettgaylor** [comment]
Great, I agree, there's promise in those text overlays.

Some notes there:

-I like "encryption" on screen, but can we get away with not hiding her eyes?  Same with closing shot

-I feel like it isn't working as well for the historical spots (monks, intrigues, fathers).  I think we should just skip it for these 

-Try "credit card" vs "swipes" 

-Add elipses to "today".  So  “today…”

-"Your chats" vs "your fun chats"

-"…important stories" during the journalist piece

**Comment by darrenpasemko** [comment]
I'll make these revisions.
"Important Stories" looked a little clunky over that shot, but I'll give it another whirl. You got it.

**Comment by valianttry** [comment]
- 1 the text is distracting from the delightful animation, and doesn't add a lot.

**Comment by darrenpasemko** [comment]
If the copy of the text is fun (a little off-key), and plays off the narration, by reiterating the VO in a new way (akin to a hype-man), I think it's great. It's definitely my sense of humor. But, if the word choice is more literal and straight forward, I suppose we could lose the girth of the text overlays, and just use it where it is absolutely crucial. In at least 3 spots, to follow the rule of threes. Maybe that's our best bet?

**Comment by darrenpasemko** [comment]
Plus, I just tried playing with text for fun. At the end of the day we can squash the text overlays all together. Let me cut together a tamer, version, and we'll see how that works, and go from there?

**Comment by darrenpasemko** [comment]
Hiyo! Here's a new version: https://vimeo.com/153425970
Password: Mozilla

New "Encryption" title at the beginning. I think "cyphertext" and "plaintext" work well. I love the Mozilla logo at the end. The remaining text elements I think are more up for debate, just two other moments. "Encryption Power," in SCN11 and "Protecting Human Rights" in SCN16. I'll discuss fonts with Jordan tomorrow. All text elements will have a motion graphic treatment, growing on, and flickering with color. Similar in effect to the Intro title "Encryption." Of course everything is still in animatic phase, so the motion is choppy. Thanks.

P.S.
How's the new VO script coming along? Can I get my paws on it tomorrow?

**Comment by brettgaylor** [comment]
Connection troubles - will review new animatic tonight.

Script is only two words - will update tonight.

**Comment by brettgaylor** [comment]
I update the script here:
https://docs.google.com/document/d/1AJkQTko64o6Cz5g1HXDCaY-vuh5ComkSGKeaemqh7Cg/edit

And in the storyboard.  Just removed 2 redundant words.

**Comment by brettgaylor** [comment]
Love the updates, especially how encyrption moves a little bit and looks at the words in opening and closing.

I like the other texts as well - I was wondering if these could have perhaps the same rainbow treatment as transitions in or out as the opening "encryption" does?  could be too much, maybe only use in "encryption power!".

One thing - these words are areas where we may have external approvals come in, so let's just make sure that we do these in a way that if they need to be changed or removed it isn't a huge problem.  One in particular, "human rights", is an example.

This is looking great though and I think ready for animation.

**Comment by darrenpasemko** [comment]
Nice! Thanks for revising the script.

I planned on doing the same rainbow treatment with transitions (in some
variety) on all the text elements. We'll tone the effect down on the text
elements that lay in the body of the video. I'll hold off on the animation
of these words until we have approval. It won't be a problem.

Thanks B!

On Mon, Feb 1, 2016 at 6:58 AM, Brett Gaylor notifications@github.com
wrote:

> Love the updates, especially how encyrption moves a little bit and looks
> at the words in opening and closing.
> 
> I like the other texts as well - I was wondering if these could have
> perhaps the same rainbow treatment as transitions in or out as the opening
> "encryption" does? could be too much, maybe only use in "encryption power!".
> 
> One thing - these words are areas where we may have external approvals
> come in, so let's just make sure that we do these in a way that if they
> need to be changed or removed it isn't a huge problem. One in particular,
> "human rights", is an example.
> 
> This is looking great though and I think ready for animation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/49#issuecomment-178003992
> .

## 

Darren Pasemko
Director
4644 S.E. 51st Ave
Portland, Oregon, U.S.A.
97206
(646) 406-1320
www.pasemko.com

**Comment by KarinaRipper** [comment]
Good morning @brettgaylor !

Also wanted to check in on the text elements/final word choices within the piece. Could the legal team review today so we can lock these words into animation? These are going to be customized and will have a fun motion graphic treatment, so we would like to get approval on the words soon. Let us know. 

Thank you!

Karina
