### ISSUE TITLE
Design new email template

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#5]

**Comment by OpenMatt** [comment]
@lovegushwa are you taking this one?

**Comment by OpenMatt** [comment]
@lovegushwa let me know timelines for when we might ship the new template?

**Comment by lovegushwa** [comment]
@OpenMatt this is one of the tickets I hope to collaborate on with @natalieworth this week.

**Comment by OpenMatt** [comment]
See wireframe https://github.com/MozillaFoundation/encryption_campaign/issues/39

**Comment by OpenMatt** [comment]
duplicate
