### ISSUE TITLE
Approve TODO interactive pitch for beat 3

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#50]

**Comment by brettgaylor** [comment]
This should be done after initial pitch January 19th.
- [ ] @brettgaylor
- [ ] @valianttry 
- [ ] @lovegushwa

**Comment by brettgaylor** [comment]
Pitch went well, we agreed next steps are better definition of scope and a budget before we can make final call.  We anticipate budget by EOD January 20th

**Comment by OpenMatt** [comment]
great. will look for that and then push ahead w. contractor agreement for them.
