### ISSUE TITLE
Create art direction for revealing information within videos

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#51]
@rohanporteous , we'll want to see what this looks like and sign off

Are you guys imagining this work this week or next?

**Comment by lovegushwa** [comment]
@lovegushwa

**Comment by OpenMatt** [comment]
@rohanporteous please update here?

**Comment by rohanporteous** [comment]
@OpenMatt updated on the other thread to keep things streamlined while brett was checking in remotely, but should have some more by COB today, and will now post those updates here.

Depending on how the blizzard/power situation goes I'm planning to do a bit of extra work tomorrow to have them mostly done before next week.

**Comment by OpenMatt** [comment]
great thanks!

**Comment by rohanporteous** [comment]
@lovegushwa @brettgaylor slightly updated graphics: https://drive.google.com/file/d/0B3UIshL1Uom0RXdpTmw1VmhvaWs/view?usp=sharing exploring something for the boss that isn't just another search after the receptionist's. 

The last transitions out are just exploring what they could all do when they disappear at the end. As I'm writing this, I just realized I was subconsciously referencing the old TV turn off. Could be simpler.

As all the other people in the office will also have some extra messages, it would be good to have a brainstorm early next week and have a whole bunch that we're comfortable showing, all shining slightly different lights on online privacy, some serious, some a bit more funny. Is this possible?

**Comment by lovegushwa** [comment]
@rohanporteous
Looking great! The splash on the bottle is a really nice touch. The only bit I think needs a little more polish is how the magnifying glass animates on the search. Seems like it's slightly fast, or it should bounce back a little. I'm totally splitting hairs. I love how it fades out.

**Comment by rohanporteous** [comment]
Great :)

**Comment by OpenMatt** [comment]
@brettgaylor do you want to review as well, or are you ok leaving this w. @lovegushwa to approve?

**Comment by OpenMatt** [comment]
@brettgaylor do you want to sign off? Anything more we need to do here?

**Comment by lovegushwa** [comment]
@brettgaylor @OpenMatt @rohanporteous Should we be final providing feedback on motion again now? Or do we need to review this once we're close to a final cut?

**Comment by brettgaylor** [comment]
i think if @lovegushwa is satisfied you can close.

> On Jan 29, 2016, at 6:12 PM, lovegushwa notifications@github.com wrote:
> 
> @brettgaylor https://github.com/brettgaylor @OpenMatt https://github.com/OpenMatt @rohanporteous https://github.com/rohanporteous Should we be final providing feedback on motion again now? Or do we need to review this once we're close to a final cut?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/MozillaFoundation/encryption_campaign/issues/51#issuecomment-177027571.

```
Brett Gaylor
Open Web Fellows + Advocacy Media
Mozilla






```

**Comment by rohanporteous** [comment]
@lovegushwa I think feedback for motion might be getting a little late as examples of motion elements were sent through a while ago, and they've been rolled out to most clips now. trying to finalize everything really soon/tonight so early next week will mostly focus on SFX/final frames.

That said, minor tweaks are OK if there are problems of course.

**Comment by lovegushwa** [comment]
@rohanporteous  overall the motion is looking good, a few straightforward changes I would like to make:

<img width="1350" alt="screen shot 2016-01-30 at 5 42 09 pm" src="https://cloud.githubusercontent.com/assets/12228435/12699750/4f0bc348-c77c-11e5-801b-9714d80ecea7.png">
1. Let's make the motion elements sit a bit lower in the frame so we can see more (it's ok if it's cropped, it's currently a bit to extream.)

<img width="1351" alt="screen shot 2016-01-30 at 6 29 04 pm" src="https://cloud.githubusercontent.com/assets/12228435/12699825/663fbbf2-c77f-11e5-9613-e11871de1bf2.png">
2. Your original rectangle search box might look better.

<img width="1352" alt="screen shot 2016-01-30 at 6 25 13 pm" src="https://cloud.githubusercontent.com/assets/12228435/12699816/fdda807e-c77e-11e5-95d8-d94cfe0cc8e6.png">
3. Can we pull on the colon and the period on the credit card number?

<img width="1348" alt="screen shot 2016-01-30 at 6 14 41 pm" src="https://cloud.githubusercontent.com/assets/12228435/12699787/643c6a1e-c77d-11e5-9ba9-a51a8812dffe.png">
4. How these spin with peoples heads is not working. 

CC @brettgaylor

**Comment by rohanporteous** [comment]
@lovegushwa @brettgaylor sounds good. On each:
1. Can do. Main reasoning for crop was to be clear that people didn't really need to read it in this shot, as it's always going to be difficult. But can show more, of course.
2. Yep. Will change back to square.
3. Yep.
4. Yep… hence the test. Will keep it simple!
