### ISSUE TITLE
Design social media assets to accompany beat 1

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#52]
Develop and copy and design for Facebook and Twitter to accompany beats 1-5 of campaign. Assets will be used for organic Mozilla social profiles and paid advertising tests. 

To accommodate testing and to allow for consistent promotion across each two week beat interval we'll need ~10 ideas per beat. This will probably be frontloaded to allow for most testing in first few beats which will be optimized/rolled-out in latter part of campaign. 

Next steps: Kickoff/brainstorm initial ideas with @KevZawacki and @lovegushwa this week.

**Comment by KevZawacki** [comment]
Additional brainstorming: https://docs.google.com/document/d/1-qQnKBZZUExY9dLl1CGdbrUFLkuwL1DPkEegLxlIROI/edit

**Comment by HPaulJohnson** [comment]
Kickoff/brainstorm scheduled for Thursday with @lovegushwa, @KevZawacki and @natalieworth 

Kevin and I will also be discussing with MoCo social team and their new agency on Thursday and they seem willing/motivated to chip in with content ideas and testing strategies.

**Comment by OpenMatt** [comment]
@HPaulJohnson any updates or next steps coming out of those meetings?

**Comment by HPaulJohnson** [comment]
Some ideas brewing here: 

https://docs.google.com/document/d/17Sb-x0K5bDfn7ATg8uP5Z02x5WuSBII-KE2vz-0ZPA0/edit

We are meeting again this afternoon with Razorfish for a second round of brainstorming. Next week we will start to build out a few of these ideas around beats 1 & 2.

**Comment by HPaulJohnson** [comment]
Initial brainstorming complete. Meeting set for next week to build out copy & visuals for a few of the initial ideas with the goal of having 3+ concepts ready by end of next week. 

Updating milestone to reflect this next phase.

**Comment by rohanporteous** [comment]
Hey @HPaulJohnson @lovegushwa @OpenMatt, has this had any movement so far? Might be able to get our senior designer onto these early next week if we set up goals/needs tomorrow.

**Comment by HPaulJohnson** [comment]
@rohanporteous: we've come up with some initial ideas to explore which I'll review with @lovegushwa tomorrow a.m. and then send over your way. We also have progress on the landing page which will help us with overall visual identity we can incorporate into social. More to come tomorrow.

**Comment by rohanporteous** [comment]
@HPaulJohnson great, thanks! Sally (our SD mentioned above) is just reviewing the still photos too, and will be able to use some of them on the website/in social as required as well.

**Comment by HPaulJohnson** [comment]
Wrapping up brief for creative/design phase and plan is to sprint on initial concepts for Beat 1 next week. 

Also, had a good planning session with MoCo colleagues to shape paid media portion of this plan and will share out mid-week next week. On the paid media front it looks like we will be able to enlist their help in the setup and deployment of the tests (once we deliver creative and targeting) which should be extremely helpful.

**Comment by rohanporteous** [comment]
@HPaulJohnson great! If you could include [Sally](http://agency.sc/team/sally-woellner/) (sally@agency.sc) and [Lara](http://agency.sc/team/lara-ihnatowicz/) (lara@agency.sc) on any updates early next week they might be able to have things well underway before I land Wednesday morning. (FYI @OpenMatt RE PM).

**Comment by rohanporteous** [comment]
@OpenMatt @HPaulJohnson @lovegushwa FYI I just received [the photos from the photographer](http://danielmcmahonphotography.shootproof.com/gallery/2375660/home). (Should be able to use your own email addresses). There's a tonne of behind the scenes shots in there which we were necessarily after, but I believe it was just him making the most of his time in between his opportunities to grab separate moments with the talent, and there should be enough standalone stuff in there for us to work with.

Any updates on what's required for social and/or the website/blog?

**Comment by OpenMatt** [comment]
- thanks for these @rohanporteous 
- Design work on all the other assets, including works in progress, etc, should be available here: https://github.com/MozillaFoundation/encryption_campaign/labels/design
- Let us know if there's something specific you're looking for that you don't see there?

**Comment by rohanporteous** [comment]
Thanks @OpenMatt, I can see there's a lot going on across many different areas! There's just not much clarity on what you require from us exactly, whether it be a gif, character headshots for the website etc. I guess it'd be great to get a really specific brief from @lovegushwa outlining the format (square fb image, 200px square character headshots, animation/static etc), any included messages/graphics/text and styling direction so we can help. Sally might be able to work up some of these over the next couple of days if we get that information to her shortly :)

**Comment by HPaulJohnson** [comment]
@rohanporteous here's is a brief-brief to get you started on Beat 1 social concepts. I'm meeting with @lovegushwa and @natalieworth in a bit to discuss specifics and will annotate this doc with channel specific specs and requirements. 

https://docs.google.com/document/d/1AuT4zbTNYWjq0zAIjVN2FyttlQfyhxdaF63MDufudTE/edit

Additional creative ideas are welcome based on your experience of what works on social with video.

**Comment by HPaulJohnson** [comment]
@rohanporteous - met on our side this afternoon re: social. At the bottom of the doc above you'll see a list of deliverables we came up with based on our current ideas and test plan. There are a few that we would love your help with: creating ~4 .gifs from the video that we could use on both Facebook and Twitter and some shorter cut of video for use on Instagram (max length for Ad is 30 secs, though most organic videos there are much shorter). Natalie and Jordan are going to tackle most of the rest using the photography from the shoot that you previously provided. 

We'd love to hear any additional creative ideas you have to add to this list as well. Let me know if you and/or your team would be up for a quick check-in on social promos in the next few days.

**Comment by rohanporteous** [comment]
Hey Paul,

Just landed at LAX for a stopover and CC'ing Lara and Sally as mentioned as
they might be able to take a look at it before I get to Sydney.

Sal, the doc Paul's referring to is the one I sent through on Slack! Will
give you a call shortly to discuss options :)

R

On Monday, February 1, 2016, Paul Johnson notifications@github.com wrote:

> @rohanporteous https://github.com/rohanporteous - met on our side this
> afternoon re: social. At the bottom of the doc above you'll see a list of
> deliverables we came up with based on our current ideas and test plan.
> There are a few that we would love your help with: creating ~4 .gifs from
> the video that we could use on both Facebook and Twitter and some shorter
> cut of video for use on Instagram (max length for Ad is 30 secs, though
> most organic videos there are much shorter). Natalie and Jordan are going
> to tackle most of the rest using the photography from the shoot that you
> previously provided.
> 
> We'd love to hear any additional creative ideas you have to add to this
> list as well. Let me know if you and/or your team would be up for a quick
> check-in on social promos in the next few days.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/52#issuecomment-178288883
> .

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by HPaulJohnson** [comment]
@rohanporteous let me know if/when you and team might have some availability in the next few days to jump on a call and discuss. @lovegushwa and @natalieworth should have some initial design concepts to share in the next couple of days as well.

**Comment by rohanporteous** [comment]
@HPaulJohnson @lovegushwa we have all day booked out for one of our designers tomorrow, which is from your 2pm. You able to meet to chat through things then?

**Comment by HPaulJohnson** [comment]
@rohanporteous - yes, works for us. I've put it in @lovegushwa and my calendars for 2 pm PST.

**Comment by HPaulJohnson** [comment]
@lovegushwa @rohanporteous @natalieworth - I cleaned up the document based on our discussion today and hopefully it's more clear what next steps and deliverables are. Take a look, and let me know if there are questions. 

https://docs.google.com/document/d/1AuT4zbTNYWjq0zAIjVN2FyttlQfyhxdaF63MDufudTE/edit

**Comment by lovegushwa** [comment]
@HPaulJohnson I just took over this ticket. (so we can track the design.) But you can take it back and I can start a new one for beat 1 if that's better.

**Comment by HPaulJohnson** [comment]
@lovegushwa - it's all you!

**Comment by rohanporteous** [comment]
@lovegushwa @HPaulJohnson [here](https://drive.google.com/folderview?id=0B3UIshL1Uom0VmpXdzZHaTduaGs&usp=sharing) are some examples of what we talked about earlier. We didn't roll them out on all concepts as we thought it was better for you to get a sense of things. Mostly:
- Limitations of 20% text on ads. Difficult for UI scenes, but possibly OK with message and stylized background.
- Different kinds of options on square posts, but possibly not as useful.
- UI-based GIFs that could be related to each message, acting as a teaser for the campaign. (Could also work as videos, of course, as that's what they're exported from).
  Let me know what you think, and we could work to roll out more/change some tomorrow.

Thanks!
R

**Comment by rohanporteous** [comment]
Forgot to mention: the GIF timing is obviously not adjusted yet, but the
extra seconds needed on each frame won't actually add any size to the file.

On Thursday, February 4, 2016, Paul Johnson notifications@github.com
wrote:

> @lovegushwa https://github.com/lovegushwa - it's all you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/encryption_campaign/issues/52#issuecomment-179650842
> .

## 

Rohan Porteous
Creative Director

http://agency.sc
The creative studio for social change · Sydney · New York
office +1 (646) 583-1538 · cell +1 (646) 932-7169
address  601 West 26th #325 · skype rohanporteous

**Comment by rohanporteous** [comment]
@lovegushwa any thoughts here for additional work today?

**Comment by lovegushwa** [comment]
@rohanporteous thank you, were good to go for now!

**Comment by HPaulJohnson** [comment]
@lovegushwa @natalieworth @KevZawacki 

We currently have slots for 7 tweets and 7 FB posts starting on 2/16 and running for first two weeks of campaign. By end of day tomorrow, let's package up this first batch of social assets. 

For paid portion campaign, we'll just need basic CTA images, 3 copy variations and native version of video with branded bumper for embedding on Facebook and Twitter. Also need this by end of day tomorrow.

**Comment by HPaulJohnson** [comment]
Adding Paid Media ad copy here for consolidate review of social assets tomorrow: 

https://docs.google.com/document/d/1Z-4oftTt0v5gqZp3DD3R0w1rC8D-oSIpixADPdROCQ0/edit

**Comment by HPaulJohnson** [comment]
@lovegushwa video specs for Twitter and FB:

Twitter: https://business.twitter.com/help/promoted-video?lang=en&location=na
FB: https://www.facebook.com/business/ads-guide/video-views/

**Comment by lovegushwa** [comment]
@HPaulJohnson

Social assets for policy review:
https://drive.google.com/folderview?id=0B2qu3ExKWIlvSERfNl9XVGVQaG8&usp=sharing

**Comment by HPaulJohnson** [comment]
All assets (copy/visuals) for paid and organic submitted for final policy review/approval. 

https://docs.google.com/document/d/1WVdsmmm7VO02tPRNdP4SpWQcLYf4Lm_-XTPFDgNBnNk/edit

**Comment by lovegushwa** [comment]
@cassiemc @sabrinang R?
Social shares to kick off our campaign. We're currently bench-marking and starting to concept some heavy hitters to test, but these below have made it through policy review and ready to ship pending design review.

https://redpen.io/emed87f8e808509568

**Comment by sabrinang** [comment]
@lovegushwa I put some feedback on the redpen. For the social shares like the meme that don't have the wordmark or link, I'd assume the copy will link back to to mzl.la/encrypt or #youbeyou. I find the #youbeyou hashtag to not be as strong in design 12 as in design 10 since the encryption message is emphasized more after it. The #youbeyou is also being used for a fashion campaign so emphasizing encryption would help support the hashtag. Overall, the shares have good length of copy, great patterns and colours :)

**Comment by lovegushwa** [comment]
@sabrinang thank you for the review! 

Yes some of the CTAs are simplified / seem to be mission content, in those cases supporting text (like below the image on facebook) will fill in any missing context. @HPaulJohnson has the exact details on why were making which version and how they will be used. Also some of these are for paid so they fall under the facebook 20% copy rule.

**Comment by lovegushwa** [comment]
@cassiemc FYI this has all been through policy and legal so were just reviewing design not copy at this point. This is a new process so we can figure out another way to do it on the next video (.ie design gets a chance to review before policy and legal.)

**Comment by cassiemc** [comment]
@lovegushwa Left a few comments in the redpen. Nothing blocking but I think some can be cleaned up a tad.

**Comment by HPaulJohnson** [comment]
@lovegushwa to update graphics based on design team input and we will start running social campaign today. 

will start a separate ticket for wave 2 social to accompany next video.
