### ISSUE TITLE
Develop copy for Adwords

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#53]
Develop ~10 copy variations for use in Google Adwords campaign/tests for duration of Encryption campaign. 

cc/ @KevZawacki

**Comment by HPaulJohnson** [comment]
Copy due: 1/29
Campaign setup/live: 2/4

**Comment by OpenMatt** [comment]
is @KevZawacki writing these?

**Comment by HPaulJohnson** [comment]
I will take a first crack at drafting and coming up with some test variations. @KevZawacki can come in after that and tighten everything up.

**Comment by HPaulJohnson** [comment]
This got pushed down on the list. Will be tackled next week.

**Comment by HPaulJohnson** [comment]
Copy being developed here: https://docs.google.com/a/mozilla.com/document/d/1cdR24bMckLePN8XKVxo_QOgQIOUVt2rvfhQEgFvaXaE/edit?usp=sharing

Will finalize this week and setup in Adwords for launch.

**Comment by HPaulJohnson** [comment]
Plan is to turn on this campaign Monday eve, 2/15 ahead of Tuesday's launch.

**Comment by HPaulJohnson** [comment]
Submitted for final policy review/approval.

**Comment by HPaulJohnson** [comment]
this is live. will be updating/optimizing keyword list as we go.
