### ISSUE TITLE
Identify possible Podcasts for campaign promotions

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#54]
As an experimental/test channel for this campaign we'd like to identify possible podcasts that would reach target audience for either organic (media) or paid placement. 

Next step: Compile list of potential podcasts (due 1/21). If anyone has ideas, please add them here. 

cc/ @brettgaylor @KevZawacki

**Comment by brettgaylor** [comment]
Gimlet Media:
ReplyAll
Mystery Show
Startup

Also:
Canadaland (I have contact)

**Comment by jgmac1106** [comment]
Rocket (RelayFM)
Overtired (RelayFM)
Anything on Twit network (though CPM is really high) maybe FOSS,
Screensavers, or TWIG would be best fit

**Comment by OpenMatt** [comment]
@KevZawacki got any suggestions to add?

**Comment by KevZawacki** [comment]
@OpenMatt I'll be researching additions and adding them to our encryption media list tomorrow afternoon.

**Comment by KevZawacki** [comment]
Thanks for the start, @brettgaylor and jgmac1106.

Adding to this list:

[Analogue](https://www.relay.fm/analogue)
[Internet History Podcast](http://www.internethistorypodcast.com/)
[FLOSS Weekly](https://twit.tv/shows/floss-weekly)
[Let's Talk About Tech](http://www.bbc.co.uk/programmes/p02nrxgq)
[Media Berkman](https://blogs.harvard.edu/mediaberkman/) -- @brettgaylor, have a relationship here? 
[Spark](http://www.cbc.ca/radio/spark/about)
[Security Now](https://twit.tv/shows/security-now)
[Security Weekly](http://securityweekly.com/)
[The Tech Guy](http://www.techguylabs.com/)
[Tech News Today](https://twit.tv/shows/tech-news-today)
[Tech's Message](http://www.natelanxon.com/podcast)
[TED Radio Hour](http://www.npr.org/programs/ted-radio-hour/?showDate=2016-01-15)
[This Week in Law](https://twit.tv/shows/this-week-in-law)
[Wired UK podcast](http://www.wired.co.uk/podcast)

I'm porting all suggestions from this ticket into our media list. One more question before closing this ticket... @HPaulJohnson, are you thinking we'll pitch Brett as the guest?

**Comment by HPaulJohnson** [comment]
@KevZawacki - I think there are two approaches here once we have a final list. One is to get spokespeople on the appropriate programs. I think Brett or Andrea and, in some cases depending on reach, Mark would be our best bets here. The other angle is paid advertisements on these programs, either by contacting podcaster directly or through various podcast ad networks. 

So there's a media component and an advertising component and we should pursue both.

**Comment by HPaulJohnson** [comment]
Initial list compiled. Next week we will prioritize and start reaching out to understand which are viable as press/media opps vs. paid advertising opps. 

Moving milestone to next week to reflect this next phase.

**Comment by HPaulJohnson** [comment]
This got pushed down the priority pile. Will tackle next week.

**Comment by OpenMatt** [comment]
@HPaulJohnson ok to close this one?

**Comment by HPaulJohnson** [comment]
yes, Kevin is reaching out to the list now. closing this for now.
