### ISSUE TITLE
Identify possible content partners for campaign promotion

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#55]
Identify a list of potential content partners for either organic or paid promotion. Example: Upworthy, AJ+

This work is likely in parallel or in support of some of the partner outreach @brettgaylor brainstormed last week in Victoria.

**Comment by OpenMatt** [comment]
@HPaulJohnson can we close this now?

**Comment by HPaulJohnson** [comment]
I'm going to close this for now. I think once the entire body of content is complete and we have an evergreen version of the microsite, we can "package" this encryption education in a way that we can pitch to partners. This, along with social, can become part of an ongoing/sustained promotional plan for encryption over the next few quarters.
