### ISSUE TITLE
Design promotional tile for mozilla.org homepage

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#57]
Design a tile to promote Encryption campaign for mozilla.org homepage that will go live around campaign launch and stay up for duration of campaign to drive traffic to campaign landing page. 

cc/ @lovegushwa

**Comment by OpenMatt** [comment]
@HPaulJohnson do you think you could add
a) a label to all your new tickets. (e.g., design, comms, etc.) and 
b) a milestone to indicate what _week_ the work needs to get done?

**Comment by OpenMatt** [comment]
@lovegushwa not sure if you or @natalieworth is taking this one.

**Comment by lovegushwa** [comment]
@OpenMatt @valianttry For EOY we just gave them a color, some copy and a icon and they built the tile.
Can you confirm what's needed for this and who the MOCO contact is? (maybe there is a bugzilla ticket.)

**Comment by HPaulJohnson** [comment]
@lovegushwa I can help with this one, as I've already given Jen Bertsch the heads up (either her or Mike Alexis are best points of contact). I also just created the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1243534

I'll work on some copy ideas based on landing page. If you could think about visual component would be great to get the MoCo team this stuff by end of week so they have time to build and deploy.

**Comment by OpenMatt** [comment]
@lovegushwa any status updates on this one?

**Comment by HPaulJohnson** [comment]
Moving to next week's milestone as work continues.

**Comment by natalieworth** [comment]
@valianttry can you review before we get copy from @HPaulJohnson for the promo tile. @lovegushwa helped to narrow these down and I've posted them to redpen: https://redpen.io/dj66752b112945e5fd 
The lock icon was intended to relate to the lock in an encrypted page. There are 3 options that include static and rollover states. I tried to maintain the existing branding of the current mozilla.org page and tiles.

**Comment by natalieworth** [comment]
![tiles-mozilla-final-07](https://cloud.githubusercontent.com/assets/14876567/12760427/3bc30744-c99b-11e5-8f14-43f33f0bd929.png)

**Comment by natalieworth** [comment]
<img width="137" alt="screen shot 2016-02-02 at 10 41 29 am" src="https://cloud.githubusercontent.com/assets/14876567/12760445/465ec990-c99b-11e5-97fd-e1a7eb92a15d.png">

**Comment by valianttry** [comment]
all look great -- what about removing the keyhole so it is an even closer match to the https icon? That's my only (not very important) suggestion. Love the color!

**Comment by HPaulJohnson** [comment]
What about this copy (from end card): 

"Privacy depends on encryption and is worth protecting." [learn more]

Too long?

**Comment by natalieworth** [comment]
![tiles-mozilla-final2-07](https://cloud.githubusercontent.com/assets/14876567/12763858/9ebeda20-c9ab-11e5-8058-45a3cf2681c1.png)

**Comment by HPaulJohnson** [comment]
Feels pretty wordy. @KevZawacki - can you take a quick look and suggest edits to tighten this up?

**Comment by natalieworth** [comment]
@valianttry @lovegushwa Removed the keyhole, I'm okay with either option
@HPaulJohnson Should the "privacy depends..." text be on the rollover? Are you good with the "Learn how encryption affects your privacy"? I was just using it as place holder, but not sure if we could do something better
cc @KevZawacki

**Comment by HPaulJohnson** [comment]
To be consistent with language @shaghdoosti suggested for video end cards, let's try 

"Encryption helps protect your privacy" [learn more]

**Comment by brettgaylor** [comment]
is this the right use of “affects”?

**Comment by natalieworth** [comment]
![tiles-mozilla-final3-07](https://cloud.githubusercontent.com/assets/14876567/12764458/b68fc06c-c9ae-11e5-8dc5-e5ace3c12bd7.png)

@HPaulJohnson @KevZawacki Updated content, let me know if I should alter/ change the "Learn how encryption affects (effects?) your privacy"

**Comment by natalieworth** [comment]
@HPaulJohnson @valianttry Once copy is confirmed for these, I'll upload on bugzilla ticket for the tiles team to create. Hopefully as soon as possible

**Comment by valianttry** [comment]
Options:
-- "Help protect it"
-- "Get the facts about encryption"

**Comment by KevZawacki** [comment]
For possible post-rollover copy:

-- Learn why it's worth defending
-- Learn why it's essential online  
-- Learn more about encryption's importance

I really like @valianttry's suggestion, too: "Get the facts about encryption"

**Comment by HPaulJohnson** [comment]
I like "Get the facts..." too though worry we don't really pay that off until the second video. Probably okay for a week during launch. Let's go with that.

Also, sorted through the multiple bug confusion, let's use this bug for updates: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1244346

(I closed the one referred to up top that I had originally filed last week)

**Comment by natalieworth** [comment]
Provided source files for this on bugzilla for mozilla.org tiles team: https://bugzilla.mozilla.org/show_bug.cgi?id=1244346
Final file on drive: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0dDRFRElzVlVDMTQ/view

**Comment by lovegushwa** [comment]
Thanks! @natalieworth 
This is ready to close.

**Comment by HPaulJohnson** [comment]
Nice work! Closing!!

**Comment by HPaulJohnson** [comment]
@lovegushwa @natalieworth need to update with alt copy for the rollover version: 
- Find out how it works and why it’s worth protecting
- See how it works and why it’s worth protecting
- See why it’s essential and worth protecting

**Comment by lovegushwa** [comment]
Updated tile with new language for rollover state (Moco requested we keep the same color as the gear store.)
<img width="1247" alt="encrypt-tile-preview" src="https://cloud.githubusercontent.com/assets/12228435/13015537/89cc5d2a-d16e-11e5-9b21-4e724e1ce6ad.png">

**Comment by natalieworth** [comment]
@HPaulJohnson I believe there's more feedback for this on the bugzilla ticket today: https://bugzilla.mozilla.org/show_bug.cgi?id=1244346 (regarding tweaks to the "encryption helps protect your privacy). If you want to review, I can update the designs and repost for the mozilla.org team. Thanks

**Comment by HPaulJohnson** [comment]
this is live.
