### ISSUE TITLE
Decide on Encryption campaign name

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#58]
Decide a name for the encryption campaign and beats 1-5

**Comment by OpenMatt** [comment]
Especially beat 1

**Comment by OpenMatt** [comment]
Let's aim to get this nailed down in Wed meeting. @lovegushwa says @KevZawacki has ideas to add here.

**Comment by lovegushwa** [comment]
recap of original brain storm ideas:
1. You be You
   Having privacy via encryption gives you freedom you need to be yourself. You can buy the things you want, your medical records are private, you can choose if people know you have money or don't. With out encryption your private information is public. You can't be yourself.
2. ❤encryption
   Mozilla brand approach. (Lot's of hearts in other Mozilla stuff.)
   The heart also give us a chance to leverage emoji.
3. 3ncrypt10n
   Typographic approach (totally 90's), Visual metaphor for ciphers.
4. Encryption: The thing behind your privacy
   Direct. "The thing behind your privacy" could have alternates or change every campaign beat, similar to FOOD, WATER, SHELTER, INTERNET
5. What if: (possible futures)
   This one is weird, but exploring things like "What if: everyone new your thoughts."
6. 3847593 > 3N6RYPT > ENCRYPT  
   Think animated graphic, visual demonstrates the idea of encryption.
7. Cryptopia 
   Think b movie, This is silly so we play it up.
8. Protect Privacy
   Direct
9. Say No to TMI
   Not having privacy is TMI, plays off of humor in first script.

<img width="1029" alt="screen shot 2016-01-19 at 12 34 55 pm" src="https://cloud.githubusercontent.com/assets/12228435/12431224/16e904fc-bea9-11e5-80a6-dcf0eb407ee2.png">

**Comment by lovegushwa** [comment]
Really great thoughts from @KevZawacki 
https://docs.google.com/a/mozilla.com/document/d/1-qQnKBZZUExY9dLl1CGdbrUFLkuwL1DPkEegLxlIROI/edit?usp=sharing

@HPaulJohnson any thoughts about which direction?
Depending on how TODO idea B shakes out, leveraging the heart and other emoji in the name could would work really well.

**Comment by HPaulJohnson** [comment]
I'm leaning towards: 

Mozilla ❤ Encryption
or 
3847593 > 3N6RYPT > ENCRYPT

Maybe even a hybrid, inspired by some of the ideas from TODO. 

I set up a meeting to discuss social specifically on Thursday. @lovegushwa if we need to meet before then on naming specifically, let me know.

**Comment by KevZawacki** [comment]
My vote is for "Mozilla ❤ Encryption," too

**Comment by OpenMatt** [comment]
Stand up for Encryption

**Comment by OpenMatt** [comment]
Decision-makers:
- Jordan
- Paul
- Andrea
- Kevin
  to be made by end of week

**Comment by brettgaylor** [comment]
I have concerns about "Mozilla <3 Encryption". I think it opens us up to critique on how much globally, as an institution, we have done to support encryption.  I think we ought to focus on the values rather than Mozilla's specific stand or record.

**Comment by lovegushwa** [comment]
ENCRYPTION 
(graphic treatment OR animated .gif like this 3847593 > 3N6RYPT > ENCRYPT)

“the code that protects you"  
(subhead changes with each beat, we also test alternate subheads on social.)

**Comment by HPaulJohnson** [comment]
@lovegushwa, based on our discussion just now, let's move forward with this direction. It's simple, visual and gives us a bunch of flexibility to use and test it in different ways.
