### ISSUE TITLE
Design a User journey - Beat 1

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#61]
Redraw / refine the encryption campaign user journey based on this collaborative sketch and share out:

![img_20160113_121141](https://cloud.githubusercontent.com/assets/12228435/12430305/d60eaaae-bea3-11e5-9204-d319700c356e.jpg)

**Comment by OpenMatt** [comment]
@lovegushwa is this something you'll do some work on this week? Otherwise, feel free to milestone for next week instead.

**Comment by lovegushwa** [comment]
We can stick with the above drawing for now.
