### ISSUE TITLE
Deliver video 1 final cut

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#64]
February 1st

**Comment by brettgaylor** [comment]
Approval
- [x] Brett

**Comment by OpenMatt** [comment]
@brettgaylor @rohanporteous what is the updated delivery date for final cut?

**Comment by rohanporteous** [comment]
@OpenMatt @brettgaylor I'm going to aim for the day I get back, Wednesday the 3rd. That's of course Aus time, so will be finished by your start of day. Could possibly do small changes the next day, but schedules clash with other projects so it's tight.

**Comment by brettgaylor** [comment]
This is fine from my POV. I haven’t been tracking the issues around social with a fine level of detail, so just check with @HPaulJohnson https://github.com/MozillaFoundation/encryption_campaign/issues?q=is%3Aissue+is%3Aopen+author%3AHPaulJohnson 

> On Feb 1, 2016, at 4:04 PM, Rohan Porteous notifications@github.com wrote:
> 
> @OpenMatt https://github.com/OpenMatt @brettgaylor https://github.com/brettgaylor I'm going to aim for the day I get back, Wednesday the 3rd. That's of course Aus time, so will be finished by your start of day. Could possibly do small changes the next day, but schedules clash with other projects so it's tight.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/MozillaFoundation/encryption_campaign/issues/64#issuecomment-178219626.

```
Brett Gaylor
Open Web Fellows + Advocacy Media
Mozilla






```

**Comment by rohanporteous** [comment]
Hey @brettgaylor @lovegushwa @HPaulJohnson @OpenMatt, an updated (very near) final version is available for preview [here](https://drive.google.com/file/d/0B3UIshL1Uom0Zl9kZTVjQzJ2djA/view?usp=sharing), the changes revolving around the SFX mix and the final title elements.

With the SFX, I tried to:
- Reduce many of the digital clicking SFX for subtle swooshes etc, while keeping the text message notification sounds.
- Reduce baby sounds to sit in the background more
- Change secretary's error sound. It was previously happening on every click, overriding her typing sound. Now it happens every couple of clicks to feel more natural.
- Add more message sounds to the boss scene to make it more obvious as to what's happening, and prompt him looking up.
- Add some extra shuffling sounds and clearing throat sound to the awkward office moment

The final screens are taken directly from Jordan's designs, although I combined the #ENCRYPT logo and the URL. The animation is trying to enforce the notions of encryption while not becoming too overwhelming. I haven't exported the multiple different lines of VO yet (with 3/4 clips not having the final logo/URL screen) but can do tomorrow if this is all looking good. Might also add some subtle SFX into the title screens to highlight the movement there as well. 

Let me know what you think!

**Comment by rohanporteous** [comment]
As a complete aside, check [this video from FB about their jump into Slack's territory](https://work.fb.com/).

**Comment by OpenMatt** [comment]
Thanks @rohanporteous!

### Next steps:
- [ ] @brettgaylor will review it Wed morning. Hopefully its a final approval.
- [ ] If there are still any changes that need to be made, Brett will review them EOD pacific time Wed (Wednesday) for a final output Thursday

@brettgaylor: over to you.

**Comment by OpenMatt** [comment]
- Note: final delivery of the video will likely occur tomorrow (Feb 4) instead of today. 
- @brettgaylor and I don't think that poses a problem for anyone. 
- @valianttry @lovegushwa @ScottDowne let us know if that's wrong?

**Comment by brettgaylor** [comment]
Slow clap @rohanporteous !  This is great.

I have two things:

1) I don't think the sound effect for the dad at :13 works.  Just cut it
2) The mug at the end.  You may want to kill me, but right now the credit card details do not seem like the thing we are focusing the audience's attention on.  Could we try making these bold, perhaps in black, or, im serious here, blinking?  On this particular issue I would defer to @lovegushwa.  What do you think of the last shot of the mug?

This came a long way!  Excited to see how our audience responds

**Comment by lovegushwa** [comment]
@brettgaylor @rohanporteous 
I think the mug is always going to overpower the credit cards because it's an image that's moving and your eye is going to track it in that short moment it's on screen.

I showed the most recent cut to Cassie today, she called out the mug as being an inconsistent use of UI. (this has also been eating at me.) It's a funny moment, but we lose consistency and a focus on a credit card transaction.

Feel free to disagree, but the best way to make this about a credit card transaction is to revert to the previous version with the shopping cart icon. I think this is probably the right way to go. @brettgaylor your thoughts? (trade off is it's not as funny.)

**Comment by rohanporteous** [comment]
@brettgaylor yep, fine to cut the SFX at 00:13! As I spoke about with the others, I'd mentioned the mug issue when it was happening it the rough cut notes ('_Changed to WBB mug (removed shopping cart as there was just too much information, and changed text so it didn't repeat the joke and so it made what was happening clearer. It's definitely more about the mug joke now than the issue of CC privacy breach, but your call._'). 

You really lose the emphasis on the CC/privacy element because of the image, and I don't think there's much of a way to get it back without reverting to what we had before. Said it was potentially fine as that moment is really a brief segue to the broader office and final messages, and we can touch back on it in social, but could also revert to other option if required. Just depends on if you want to prioritize the joke over the point on financial privacy.

**Comment by rohanporteous** [comment]
@lovegushwa [here's the first scene](https://www.dropbox.com/s/9wrakgtzbfyvmfh/Screenshot%202016-02-04%2012.50.38.png?dl=0) with the shortened text to make it clearer that it's her text thread. Haven't gone with your option of having both pointing right as I thought it was just a step too far—something that never happens in any text app. (Seemed more like the difference between a normal text and an Apple iMessage with the green/blue than two separate people). Let me know what you think.

**Comment by lovegushwa** [comment]
@rohanporteous that's looking better. You could also do something like this:
<img width="879" alt="screen shot 2016-02-03 at 8 44 24 pm" src="https://cloud.githubusercontent.com/assets/12228435/12806035/32e1f10e-cab7-11e5-9639-ecc4869a9b36.png">

You can make the call on this. The version I'm proposing is a little further from the guy and the visual alignment of the boxes feels a little better. However it might impact this scene: 

<img width="1564" alt="screen shot 2016-02-03 at 8 53 08 pm" src="https://cloud.githubusercontent.com/assets/12228435/12806139/2c4c9942-cab8-11e5-87f7-36580920ee5f.png">

**Comment by rohanporteous** [comment]
@lovegushwa yeah, had considered doing that but was just too jarring between the two screens, as it'd either cover her face or jump strangely from left to right.

**Comment by rohanporteous** [comment]
Oh, one thing that is very very small but I meant to bring up and forgot about @brettgaylor @HPaulJohnson @valianttry: the final notifications in the office scene. With the 'hot date' text I thought it could add a funny element if there was actually someone sending the text and another receiving it—the awkward public previewing of an in-office romance—and gave the messages to two of the women.

Thought it was just broadening the diversity of the piece in a (very) minor way but figured I should double check with you guys before launch. It's easy enough to replace one of the texts of course.

**Comment by rohanporteous** [comment]
Hey guys, [here](https://drive.google.com/folderview?id=0B3UIshL1Uom0WnoybHJROXpSTlU&usp=sharing) are some different versions to match [the video wireframes](https://cloud.githubusercontent.com/assets/12228435/12766029/4c750ebe-c9b6-11e5-9ddb-b97069bd784d.jpg). Very quickly:
- 1a/1b native: the wireframes call for 'join the movement' but we didn't actually record that as a standalone. I've therefore given you 1a 'join Mozilla to find out more' and 1b 'Join the movement for privacy'. Let me know which you prefer and I'll also use it for the social version.
- 2a/2b: I thought she read 'important' slightly strangely so gave you that (wb) as well as an edited together alternative of 'Spread the word about privacy tools like encryption' (2b).

**Comment by brettgaylor** [comment]
@rohanporteous sure like that idea re: the inter-office messages!

@lovegushwa and the Mozilla Foundation design team do a set of design critiques, and jordan brought the video in for review.  They had a few good comments which I thought I'd paste here:

> After the women is finished looking at her phone, the cut off text box in the upper left which doesn’t look like it is coming from her phone at all. When the scene zooms out, the speech bubble looks like it belongs to an external source which is the nearest the approaching man and the green speech bubble is pointed directly at the woman herself. This causes confusion as the first scene since it isn't clear what dialogue or interaction these two are having but it is actually what the woman sees. 

I think this is somewhat covered in the above conversation you two have been having - I think it's good feedback and I agree.

Jordan sent this my way, 

<img width="874" alt="screen shot 2016-02-03 at 3 23 11 pm" src="https://cloud.githubusercontent.com/assets/345974/12808182/d517aac4-cac9-11e5-8829-68788bfec32a.png">
I think @rohanporteous if you can replicate it will clear up any confusion there.  I think the script change to "no baby yet?" and the removal of the baby emoji also helps to make it super clear.

Totally agree with the coffee mug at the end - cut it!

Haven't been able to listen/preview the new sound mix with poor airport wifi, sorry!  Will try to make a bleary-eyed listen tonight.

**Comment by lovegushwa** [comment]
@rohanporteous let's go with 1b "join the moment for privacy" ... I agree important is a little off but I think it's ok. @valianttry @shaghdoosti feelings about version 2a or 2b above?

**Comment by lovegushwa** [comment]
@rohanporteous if you don't hear back I would go with 2b.

**Comment by brettgaylor** [comment]
Agree - go with 2b.

Audio edits work for me, so only outstanding issues are Jordan's graphic suggestions and text change for beginning, and reverting the end shot of boss back to the shopping cart/deleting mug.

**Comment by rohanporteous** [comment]
@brettgaylor already made the changes for the text message conversation at the start—included in the latest version, with rationale as to why we couldn't do it like in the screenshots above. Can lock in the audio choice and revert to the original mug treatment.

**Comment by rohanporteous** [comment]
Updated files are now available in [the same folder as above](https://drive.google.com/folderview?id=0B3UIshL1Uom0WnoybHJROXpSTlU&usp=sharing). (With email/partner UX sharing the one video as per the wireframes).

**Comment by brettgaylor** [comment]
@rohanporteous From the exchange above, I think that you could address both your concerns and jordan's by making the "talk bubble" point to the right instead of the left, ensuring no one gets confused that it's the dad's message.

Other than that, I think we're approved!

**Comment by rohanporteous** [comment]
@brettgaylor what do you think of the issue I raised above about there being no messaging app that exists where both the sender and the receiving appear on the same side? I think it'll appear as very strange, as if she's having a conversation with herself, as it's very much outside our known understanding of all UI. (The color differentiation making it seem more like the difference between a normal sms and an iMessage from one person, than a two person chat).

**Comment by brettgaylor** [comment]
Ah, I'm so torn by text bubble gate!

On my android device, the bubbles line up, but the text justification indicates who is talking.
So if you had something like this:
![image](https://cloud.githubusercontent.com/assets/345974/12833627/a80d904c-cb56-11e5-8f8e-0842dfd0782d.png)

But with the "no baby yet?" justified right, I think that would work!

I'm not too concerned about the jump from left to right, since they're two shots I don't think it would be noticed.

**Comment by rohanporteous** [comment]
Baby gate is over. All videos have been updated [here](https://drive.google.com/folderview?id=0B3UIshL1Uom0WnoybHJROXpSTlU&usp=sharing) with new alignment & points on the right side so should work on all fronts!

**Comment by rohanporteous** [comment]
@brettgaylor @OpenMatt @lovegushwa @HPaulJohnson hey guys, just wondering if you have any more feedback on finals here? We'd scheduled to be wrapped with everything mid-week and I'm out of office next week, so anything for me will have to come through today. Social image updates for next week can go through to lara@agency.sc and sally@agency.sc.

**Comment by valianttry** [comment]
@rohanporteous I have nothing more. Really nice product!

**Comment by brettgaylor** [comment]
Approved and closed!  Will move on to other delivery details.

**Comment by brettgaylor** [comment]
Crud. @rohanporteous I just noticed that the social + emailpartner videos end on black frames. Can we make sure that they end on the CTA screens?

**Comment by HPaulJohnson** [comment]
@brettgaylor - i think this is by design. see ticket #85 

Both social and email end up on the landing page and therefore it's already well branded with ENCRYPT and URL is not necessary (you are already on the site). The CTA's (either join the list or share) will be handled by UX on the site when the video has finished playing. 

@lovegushwa can also confirm.

**Comment by rohanporteous** [comment]
@brettgaylor they've been updated to end on the text. Assuming can cut to the UX once it's finished playing so you should be good either way now.

**Comment by lovegushwa** [comment]
@brettgaylor @HPaulJohnson @rohanporteous 
Yes we can close.

**Comment by brettgaylor** [comment]
But we can't lose.

Clear eyes, full hearts.

**Comment by lovegushwa** [comment]
@brettgaylor @alanmoo @HPaulJohnson @OpenMatt @alicoding 
I move a copy of the final video files to the design drive here: 
https://drive.google.com/folderview?id=0B2qu3ExKWIlvTzRGM1FZazI5Rm8&usp=sharing

**Comment by alicoding** [comment]
@jbuck can you help with the hosting here? Thanks!

**Comment by jbuck** [comment]
@alicoding yerp!

**Comment by jbuck** [comment]
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.1.native.mp4
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.2.social.mp4
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner.mp4

**Comment by alicoding** [comment]
thanks @jbuck ! <3

**Comment by alanmoo** [comment]
These seem to be huge files, what are our options regarding compression? Does the CDN handle this and just need some time to propagate this?

**Comment by jbuck** [comment]
@alanmoo no, we'll need to compress them ourselves

**Comment by brettgaylor** [comment]
Hey @alanmoo @alicoding 

I shouldn't have closed this ticket:
https://github.com/MozillaFoundation/encryption_campaign/issues/98

For snippet, the WebM file. For the microsite, @jbuck's right we haven't encoded these yet.
