### ISSUE TITLE
Select bloggers for each beat

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#65]
We need to identify (and then woo) guest bloggers for each beat. 

Initial suggestions listed [in this spreadsheet](https://docs.google.com/spreadsheets/d/1GAWDMPArKvsprOeO9zagLLhyK0eAdY7HPnS1dcNOf4A/edit#gid=0Journalist). Seeking input and guidance from @HPaulJohnson and @brettgaylor.

**Comment by valianttry** [comment]
For the purposes of building a robust list, I would suggest @shaghdoosti and @jochai would also offer good suggestions as well.

**Comment by valianttry** [comment]
@OpenMatt is Jochai in this repo? Can you add him if not? For some reason Github isn't recognizing my tags so I don't have his handle right in my last comment.

**Comment by OpenMatt** [comment]
@valianttry add him here: https://github.com/MozillaFoundation/encryption_campaign/settings/collaboration

I can't find his GitHub handle

**Comment by OpenMatt** [comment]
- @KevZawacki can people just add suggestions to your spreadsheet / in this ticket?
- or do you need to schedule a meeting?

**Comment by KevZawacki** [comment]
@OpenMatt Suggestions most welcome; no meeting necessary.

**Comment by KevZawacki** [comment]
Moving milestone, since @brettgaylor is needed to make decisions here.

**Comment by OpenMatt** [comment]
@KevZawacki any updates? or can we close?

**Comment by KevZawacki** [comment]
Discussion still needs to happen -- pushing milestone

**Comment by HPaulJohnson** [comment]
@KevZawacki i think we can close at this point. feel free to re-open as needed.
