### ISSUE TITLE
Decide whether we're doing a contest as part of Beat 3

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#66]
We talked about a few options around this at the work week. Our options are: 

--Working with an agency for beat 3
--Launching a competition around content creation.

**Comment by OpenMatt** [comment]
- next step: blocked on getting quote from contractor
- will wait to make contest decision til we get that

**Comment by OpenMatt** [comment]
- we have the quote from TODO and are pushing ahead. So that part's cleared.
- @shaghdoosti did we make a decision about contest vs. no contest? Assigning to you to hold us accountable there.

**Comment by shaghdoosti** [comment]
We decided we'd make that decision after we heard back from Todo - so I'll make sure it's on the agenda for us to revisit next week.

**Comment by OpenMatt** [comment]
k thanks @shaghdoosti -- we can discuss in today's kick-off

**Comment by OpenMatt** [comment]
@shaghdoosti I'm going to assume we're not doing a contest, and close this issue. Re-open if that's wrong.
