### ISSUE TITLE
Develop internal communications and messaging document (narrative)

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#67]
This document will serve as a central repository of 'how we talk about this campaign':
https://docs.google.com/document/d/1yEPe6HNttNnJRfmda8XFJZNxLXziUDkRhtowni7A4qw/edit

@shaghdoosti and @brettgaylor have reviewed

**Comment by valianttry** [comment]
@HPaulJohnson and @KevZawacki can you look? 

Next steps: Turn into a deck (that hopefully Jordan can make pretty?) for Mark, Jascha; etc

**Comment by valianttry** [comment]
@shaghdoosti and I met with Mark and @davidascher and got good notes and feedback on internal marketing planning. I will incorporate those.

Next step: Build a deck.

**Comment by cassiemc** [comment]
@valianttry Design is more than pretty! Just sayin'. :)

**Comment by OpenMatt** [comment]
@valianttry I'd like to get an update to the Executive Team by Tues Jan 26 on the overall campaign status. Showing off all our good work to date, and summarizing our overall total campaign budget, KPIs and beats. Doesn't have to be a deck -- a simple one-pager or even email is fine. 

Possible to turn this into that by Tues, you think? 

cc @brettgaylor

**Comment by cassiemc** [comment]
@OpenMatt This is peripheral, but all the Advocacy home page and Open Web Fellows designs to date are here: https://redpen.io/p/wt1d64bfb93fa6a6b8

**Comment by OpenMatt** [comment]
@valianttry I left notes in your doc

**Comment by valianttry** [comment]
Sent and completed.
