### ISSUE TITLE
Write copy for landing page

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#68]
cc @HPaulJohnson @lovegushwa

**Comment by OpenMatt** [comment]
@lovegushwa when will you need this copy by?

**Comment by KevZawacki** [comment]
@OpenMatt To clarify: is this ticket for the encryption microsite?

**Comment by HPaulJohnson** [comment]
@KevZawacki this is for microsite.

With wireframes to a solid place, we will plan on having draft of copy by 1/26.

**Comment by OpenMatt** [comment]
Yep

**Comment by KevZawacki** [comment]
@HPaulJohnson Microsite copy (see issue #40) tightened up and ready for your review [here](https://docs.google.com/document/d/1rZnC_4uIv7fVlps_RwTIcDR4ohHgIxN6vt_eLMEWcwo/edit?ts=56a67edc).

**Comment by HPaulJohnson** [comment]
This copy is good to go. 

Closing.
