### ISSUE TITLE
Write & submit copy for Firefox and You

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#69]
assigning Kevin -- please re-assign as needed

**Comment by OpenMatt** [comment]
cc @valianttry @shaghdoosti

**Comment by KevZawacki** [comment]
I've reached out to MJ Kelly at MoCo, who oversees Firefox + You. Awaiting her guidance on copy.

**Comment by KevZawacki** [comment]
@valianttry, I've responded to MJ's questions. She should now have a solid background of the campaign. 

Re: Firefox + You, MJ notes:

"Thanks for the ping. I had originally thought this would fit in the February issue, but we've got a story on Smart On Surveillance running.

Something for March could work, provided this product-oriented audience can relate to it. Given that you know a lot more about the campaign, what do you think would be an appealing message for the newsletter audience?"

@valianttry and @shaghdoosti, what do you think the answer is?

**Comment by OpenMatt** [comment]
nudging @valianttry and @shaghdoosti

**Comment by HPaulJohnson** [comment]
Sounds like this is moving to March. @KevZawacki can you let us know when the copy deadline is for March edition of FF&You?

In the mean time, moving out of this milestone.

**Comment by kellymj** [comment]
I can answer that! 

Outline due: Friday Feb. 5 -- I've already included the encryption campaign as a feature.
Draft copy due: Tuesday, Feb. 9
Final copy due: Thursday, Feb. 11

**Comment by HPaulJohnson** [comment]
awesome - thanks, @kellymj. we'll work on copy for next week!

**Comment by KevZawacki** [comment]
@kellymj, welcome to GitHub! 

Draft encryption copy for March's Firefox + You can be found [here](https://docs.google.com/document/d/1dU7pjgMDnrxsDQzoxGwf_StQkg-Cp3JSk8xyOOJJFPg/edit) (I've also pasted below). Let me know how/if I can tweak. 

Static images from the videos are in the works, and should work well as email images. @HPaulJohnson and I will let you know as they emerge.

---

[Header] 
screenshot of/link to encryption campaign microsite

[Hed]
Learn why encryption matters

[Body] 
Did you know encryption protects your privacy online, and helps keep the Internet secure? From safeguarding personal emails and data to enabling online shopping and banking, encryption is key to a healthy Web. Encryption also protects journalists and human rights advocates around the world. In support of encryption, Mozilla is sharing videos, blogs and interactive activities that spotlight its importance. Take a moment to learn more and share the news.

[Button] 
Learn more linkto: encryption microsite

**Comment by kellymj** [comment]
Hey @KevZawacki , thanks for the copy. I'd love to see the tone be more fun and edgy since we're going to entice users with a screen shot of the video, which is on the edgier side, last I saw. Are you up for revising it with that in mind?

Email cannot play a video, so we'll be looking for a still shot and a play button superimposed. The specs for the graphic are 660x160 px, PNG format. Users would click it and go to the microsite to view.

**Comment by KevZawacki** [comment]
@kellymj Definitely! Here we go:

[Header] 
video stillshot + play button

[Hed]
Encryption Keeps Your Private Life Private

[Body] 
Here’s a scary thought: What if your most embarrassing Internet searches appeared on nearby billboards? Or, what if your Mom could read all your emails?

Online privacy matters. It allows us to be curious and authentic with the Internet. Without privacy, the Internet becomes a lot less safe (and far more awkward). Don’t believe us? Watch the video above to see what a world without online privacy looks like. It’s not pretty.   

This is why Mozilla is standing up for encryption, the technology that protects our personal information online. Encryption does it all, from safeguarding emails to enabling secure online shopping. In support of encryption, Mozilla is sharing videos, blogs and interactive activities that spotlight its importance. Take a moment to learn more and share the news.

[Button] 
Learn more linkto: encryption microsite

**Comment by kellymj** [comment]
@KevZawacki Thanks for the revision. I've edited and shortened it [here](https://docs.google.com/a/mozilla.com/document/d/1dU7pjgMDnrxsDQzoxGwf_StQkg-Cp3JSk8xyOOJJFPg/edit?usp=sharing). Please give it a read to make sure it's all still accurate.

**Comment by KevZawacki** [comment]
@kellymj Looks great! I'm going to share with policy and ensure we have their blessing -- then, OK to lock in.

**Comment by kellymj** [comment]
Hey @kevzawacki, the copy has been slightly tweaked in the final version, and now lives in the actual [March newsletter copy doc](https://docs.google.com/document/d/1jPjQ8k_8fIyMii4fs8DD9WoKbtaEOeGjr69lkWyI1HQ/edit?usp=sharing). We'd like to get it locked down. Who, if anyone else, needs to see/review/approve it?

Also, we'll need a header graphic for the newsletter. Is there are separate thread for visuals? I have some thoughts on what would make a good graphic.

**Comment by KevZawacki** [comment]
Hi @kellymj, Jochai from policy needs to sign off -- I'm sending his way this afternoon.

cc @HPaulJohnson and @lovegushwa, who can assist with graphics.

**Comment by KevZawacki** [comment]
Hi @kellymj. Our Firefox + You copy has gone through the policy / legal review process required for the encryption campaign.

[This](https://docs.google.com/document/d/1dU7pjgMDnrxsDQzoxGwf_StQkg-Cp3JSk8xyOOJJFPg/edit) is the language they landed on. Does it work for Firefox + You?  

Thanks again for your patience and help.

**Comment by kellymj** [comment]
Thanks! We're good to go on the March newsletter. I'll share a test send when that's ready to ensure nothing has changed in the time in between.

**Comment by KevZawacki** [comment]
Thanks so much, @kellymj! I know the back-and-forth for approvals wasn't ideal -- thanks for understanding. :-)

**Comment by KevZawacki** [comment]
We're all set here -- closing ticket
