### ISSUE TITLE
Design encryption campaign microsite

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#7]
For the video and CTA

**Comment by OpenMatt** [comment]
This is probably blocked on: deciding what the CTA will be. 
Who's responsible for that?

**Comment by OpenMatt** [comment]
@lovegushwa what are the blockers for you on this one? Do you need to know more about what the CTA will be first?

**Comment by cassiemc** [comment]
Curious about plans for this, and hopefully I have an update this afternoon, but wanted to know wrt the Open Web Fellows updates we're making on the Advocacy site. Could this double as a [new homepage for advocacy.org](https://github.com/MozillaFoundation/movement-building/issues/73), even if temporary? We would need to work together with @kristinashu on [styling the internal pages](https://github.com/MozillaFoundation/movement-building/issues/67).

**Comment by cassiemc** [comment]
Here's a potential wireframe @kristinashu mocked up: https://redpen.io/dwc1eb0d59700704ba

**Comment by lovegushwa** [comment]
@OpenMatt @natalieworth is starting on wire frames today #40. We will review together tomorrow morning.

**Comment by OpenMatt** [comment]
duplicate
