### ISSUE TITLE
Decide hosting / platform for campaign videos

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/encryption_campaign#70]
We need to decide where/how to host the encryption campaign videos.

Youtube / Vimeo 

Pros: 
- Youtube gives us more reach (we can leverage that platform). 
- People can / will also share the videos via Youtube. (could this also be a con?)

Cons:
- We don't have access to our Youtube account!  https://github.com/MozillaFoundation/plan/issues/470 
- Might need cookies or some other nasty bits to get CTAs after video play's to work.

We host

Pros:
- Less weird API things to wrangle 

Cons: 
- We miss out on the additional reach a larger platform gives us.

**Comment by lovegushwa** [comment]
Hey friends, please make a decision about where we are going to host our videos, some notes for discussion above: @thecount @simonwex @HPaulJohnson @valianttry @natalieworth @shaghdoosti

**Comment by OpenMatt** [comment]
@brettgaylor do you have an opinion here?

**Comment by HPaulJohnson** [comment]
@simonwex told me he has reached out (again) to his contact at google to try and resolve. Given how slow that process was previously I wouldn't bank on it. 

I think we should consider just hosting ourselves and cross-posting on Youtube if/when we figure that out (I still think this is a very important thing to resolve and will be a critical channel as we do more video work going forward). 

Also, definitely want to test embedding video directly on Facebook and/or Twitter.

**Comment by OpenMatt** [comment]
ok. @HPaulJohnson can you just be the decider here? I'm going to remove "needs discussion" and treat Paul and Jordan as the deciders on this one. @HPaulJohnson please just close this if you know consider this a decision made. 

(@brettgaylor should chime in here if he has opinions)

**Comment by OpenMatt** [comment]
Also: given that we're going w. self-hosting, let's let @ScottDowne know. (Hi, Scott.)

**Comment by brettgaylor** [comment]
Just make sure in self hosting we have mechanism to see plays of video as
well as how much has been seen. Libraries should exist for this.

Re: YouTube, if we can't solve soon let's just start a new account. Shame
but there were not a lot of followers there.

**Comment by OpenMatt** [comment]
@ScottDowne ^ see re: play count, etc.

**Comment by lovegushwa** [comment]
@alicoding ^ see re: play count, etc.
Closing this issue.
