### ISSUE TITLE
Update from volunteers from Singapore

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#72]
Hey - 

After coming back from Singapore I have some great feedback from the community: 

Topline: There is general excitement about the campaign as well as a few well thought out comments. 

Key Concerns: 
- **Make GIFs?** Many of our volunteers live in areas where internet speed is low and therefore video is hard -- the suggestion was if we could make gifs as well. 
- **Don't lose momentum for localization.** Secondly, one person noted that previously when localization happened after a first release it lost momentum. We need do our best to make sure this doesn't happen. 

Great things for us to keep in mind: 
- **Avoid PDFs** for localization -- apparently this is a major headache.
- **Keep Scripts for videos for localization** -- this makes it a lot easier for the groups to translate. 

We have about 30 people who signed up to be more involved in the campaign -- my current thinking is we reach out to Stacy and Amira about creating a teaching kit that can be localized and then pull together a meeting with the community about next steps afterwards.

**Comment by OpenMatt** [comment]
@shaghdoosti good to know. anything that we should do differently over the next two weeks, based on this?

**Comment by shaghdoosti** [comment]
Only that we should make sure we create gifs and/or other resources from the videos.

**Comment by OpenMatt** [comment]
ok. I'm going to close this then, and we'll just make sure we do #74
