### ISSUE TITLE
Figure out domain name for encryption campaign landing page

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#76]
cc @lovegushwa @ScottDowne @cadecairos

**Comment by lovegushwa** [comment]
@HPaulJohnson suggested using advocacy + the campaign name so ...
 https://advocacy.mozilla.org/encrypt

@shaghdoosti @valianttry @OpenMatt @brettgaylor we can close this if no one has any issues.

**Comment by valianttry** [comment]
As long as we can use shorteners; etc i have no issues.

**Comment by HPaulJohnson** [comment]
We can/should also use mzl.la/ shortlinks in various places (social, etc) to do something punchier and without the advocacy.

**Comment by ScottDowne** [comment]
Cool, so sounds like for now we're going to try for hosting it on advocacy.mozilla.org, and use shorteners where needed. This is a good plan.

@alicoding ^^

This should all be static too and we shouldn't need a server for any of it.

**Comment by OpenMatt** [comment]
This feels like a decision made, so I'm going to close this.
