### ISSUE TITLE
Launch a "movement building open" blog similar to fundraising.mozilla.org

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#79]
Mark has nudged me on this. Let's scope and do it. :smile:

**Comment by valianttry** [comment]
cc @OpenMatt 

@alicoding do you know how difficult it would be to set up a simple wordpress blog at a URL such as advocacy.mozilla.org/open or something like that? Right now we do not need fancy charts or any of the complicated stuff that's on F.M.O. Just blog posts by various authors.

**Comment by alicoding** [comment]
Does it needs to be WordPress?  The reason I ask because WordPress is not easy to setup without having to get help from @jbuck to setup the database and all, but if we go with other modern CMS option here which does pretty much what you want then I might be able to do it easily

**Comment by OpenMatt** [comment]
@simonwex @cassiemc we'd like to volunteer this to be the first / a first implementation of your "better / faster" CMS approach. Would that work? Or should we just go with WordPress?

**Comment by cassiemc** [comment]
@OpenMatt This sounds great to me if the tech exploration is far enough along. When do you need it by?

**Comment by OpenMatt** [comment]
as soon as possible. Ideally: week of Feb 1.

**Comment by OpenMatt** [comment]
Another option, if we don't think this will be ready, would be to just use Medium. Since we're creating a Medium publication for the campaign anyway. @KevZawacki @HPaulJohnson good idea? bad idea?

**Comment by HPaulJohnson** [comment]
What we are building on Medium is an encryption specific conversation/publication whereas - I think - the content of this type of blog is more general/about movement building more broadly. So, I don't think I'd add these to that publication. But generally Medium is not a bad place to be publishing this type of stuff in the mean time. 

@KevZawacki - Gabe at Medium told us about a new publication around non-profit/development  community before the holidays. Do you remember what that was and whether that might be a nice place to start publishing some movement-building content?

**Comment by KevZawacki** [comment]
@HPaulJohnson Publication is called [The Development Set](https://medium.com/the-development-set). Might be a good place to pitch an International Women's Day piece. In terms of day-to-day Mozilla blogging, we'd want to start our own publication.

**Comment by OpenMatt** [comment]
@KevZawacki is going to start a separate publication on Medium for us to post campaign updates, etc. As an interim way to start blogging quickly / easily about the campaign, without us cluttering up the main publication.

**Comment by OpenMatt** [comment]
another option to consider: could use fundraising.mozilla.org...

**Comment by KevZawacki** [comment]
@OpenMatt Happy to -- I can get it set up in a few minutes.

Firstly, is there a specific publication name / URL we'd like? Something like, "Encryption: Working Open"?

Contributors will need Medium accounts. @OpenMatt, @valianttry, can you share your handles?

**Comment by OpenMatt** [comment]
thanks Kevin. @valianttry is meeting with @HPaulJohnson and @simonwex about other potential options -- stay tuned.

**Comment by brettgaylor** [comment]
Hey folks - I think the best option here is to use the netpolicy blog that already exists, but to use smart tagging of this blog and link to the appropriate categories.  I think it's all pretty niche content.

We've started to tag the fellows blog posts with "open web fellows", so that we can link to that category/tag without including all of the policy blogs for instance. So like this:

https://blog.mozilla.org/netpolicy/category/open-web-fellowship/

We could similarly create a tag for "advocacy", and then link to:
https://blog.mozilla.org/netpolicy/category/advocacy

That's my opinion!  We get the most SEO traffic from being directly on the mozilla blog, and I don't think our content will be frequent enough to warrant setting up an entire new instance that we have to maintain, design, fuss with etc.

**Comment by HPaulJohnson** [comment]
@valianttry and @simonwex and I discussed this morning. There's a larger plan afoot to build a CMS that supports program specific blog and, longer-term, a foundation wide presence where stories from these program-level blogs can be leveled up. 

The program specific version is fairly easy (and quick) and I am submitting a /plan ticket now. It will live at advocacy.mozilla.org/movement and we can post both movement building content and campaign level content (e.g. encryption posts/videos, etc). 

In the mean time (next week or so), any movement building content that is more urgent than that will be posted on fundraising.mozilla.org. We can frame those posts by saying we've been building an open fundraising program and we are now doing the same with our advocacy program. Relevant posts will be imported/published to the advocacy.mozilla.org/movement blog when it's up.

RE: /netpolicy blog as a short-term home: that's a place for more wonky content specific to a policy-influencer audience and doesn't feel right for advocacy or movement level content.

**Comment by HPaulJohnson** [comment]
Plan ticket filed for advocacy.mozilla.org/movement blog: 

https://github.com/MozillaFoundation/plan/issues/719#issuecomment-178902884

**Comment by OpenMatt** [comment]
great plan. love it. thanks for the great update and next steps on this @HPaulJohnson

**Comment by valianttry** [comment]
@alicoding we built a version of the fundraising.mozilla.org design that was "post-campaign" so didn't include the totalizer and was simpler... how hard would it be to switch to that template? Possible to do that today / tomorrow?

**Comment by valianttry** [comment]
@alicoding here is the ticket for reference: https://github.com/MozillaFoundation/encryption_campaign/issues/79

**Comment by OpenMatt** [comment]
@alicoding @alanmoo any updates? cc @simonwex

**Comment by alicoding** [comment]
@OpenMatt if you are asking about the update for fundraising.mozilla.org blog that's done on my part, but waiting for @jbuck to push the update on Wordpress :)

**Comment by jbuck** [comment]
FMO is up to date

**Comment by alicoding** [comment]
yay! Thanks @jbuck

**Comment by OpenMatt** [comment]
can we close?

**Comment by KevZawacki** [comment]
This = medium.com/mozilla-advocacy

🎆
