### ISSUE TITLE
Email journey timeline

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/encryption_campaign#80]
Survey email: 

Launch Date: Monday, Feb 1
Audience: 100k sample from EN speaking Mozilla Foundation list (advocacy/fundraising list)
list size: (100k)
Link: https://www.surveygizmo.com/s3/2534675/Mozilla-Encryption-Survey
From: The Mozilla team

Beat 1: 

February 10: Video 1 launch email:

Audience: All english Mozilla advocacy list

Segment 1: Non Committed (Definition: xxx)
list size: xxx
From: Mozilla team? 

Segment 2: Committed (Definition: xxx)
list size: xxx
From: Mark Surman 

February 14: Video 1 Kicker email: 

Audience: People who didn’t open or click Video 1 launch emails. 
Segment: N/A
List size: to be determined 
From: to be determined 

Beat 2: 

February 17: Video 2 launch email: 

Audience: All english Mozilla advocacy list

Segment 1: Non Committed (Definition: xxx)
list size: xxx
From: Mozilla team? 

Segment 2: Committed (Definition: xxx)
list size: xxx
From: to be determined  

February 20: Video 2 Kicker email: 

Audience: People who didn’t open or click Video 2 launch emails. 
Segment: N/A
List size: to be determined 
From: to be determined

**Comment by shaghdoosti** [comment]
@valianttry @stephaniemcv Let me know what you think. I haven't done the other beats yet -- because we are testing messages and I'm assuming our plans would shift based on what we learn.

**Comment by shaghdoosti** [comment]
Also draft emails for the launch are here: https://docs.google.com/document/d/1CEXBJC1jN2wRefRbHzJMSTyUDrC1lMDwbn5od449Hdc/edit

**Comment by stephaniemcv** [comment]
Just a head's up - 2/15 is President's Day, and retail tends to send a lot of emails around this time. We might want to consider changing this one, I don't want our message to get lost in the deluge. 

Also, MOCO is sending their monthly newsletter 2/23. I have made a note to myself to find the number of crossover between our lists but we might want to be wary of back to back emails.

**Comment by stephaniemcv** [comment]
I suggest moving the Video 1 Kicker from 2/15 to 2/16, to avoid the holiday.
Video 2 launch from 2/17 to 2/19 so they have a bit of space.
and then Video 2 Kicker from 2/22 to 2/25 to have some space from MoCo's newsletter

**Comment by OpenMatt** [comment]
@shaghdoosti do you agree? can you update?
