### ISSUE TITLE
Create avatar image for Medium publication

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/encryption_campaign#81]
The skeleton for our encryption Medium publication is here: [medium.com/encryption-matters](https://medium.com/encryption-matters)

We need an avatar image — the small square graphic that sits above the homepage publication title.

We currently have a placeholder:

![screen shot 2016-01-27 at 9 48 43 am](https://cloud.githubusercontent.com/assets/11045250/12616885/31fbc9ae-c4db-11e5-8861-1529098d60d3.png)

This is what we used for MozFest:

![screen shot 2016-01-27 at 9 49 03 am](https://cloud.githubusercontent.com/assets/11045250/12616890/393b0216-c4db-11e5-9788-b0c7c292fd36.png)

I'm trying to track down the specs, but am having trouble. @lovegushwa, do you recall from when we created the MozFest image?

cc @HPaulJohnson, @natalieworth   

...

We also have the option of adding a publication logo, which is displayed at the top of all stories in the publication. This is what we're using now (I think it looks neat):

![screen shot 2016-01-27 at 9 59 17 am](https://cloud.githubusercontent.com/assets/11045250/12617208/99e3c0c0-c4dc-11e5-9c18-b83d9d619788.png)

If we decide to update, specs for this guy are 72px tall and up to 600px wide. It needs to work on a white background.

**Comment by cassiemc** [comment]
If something like this could also work at a large scale as well, we could use it for the advocacy homepage placeholder for the campaign (see top image here: https://redpen.io/yb6b08a51928a755ea)

**Comment by jgmac1106** [comment]
What about the floating eye that was used during the privacy campaign.
Something like that or playing with an icon of a lock or key?

**Comment by KevZawacki** [comment]
Hey @natalieworth @lovegushwa, checking in. Can we expect to have the Medium avatar image ready before the Wednesday, 2/10 campaign launch?

Also, do we need a new publication logo, or is the one above OK?

**Comment by lovegushwa** [comment]
@KevZawacki yes we will get it done. We need to make the avatar and the publication logo.
@natalieworth can you take this on?

**Comment by natalieworth** [comment]
@lovegushwa @KevZawacki Drafts for this here and redpen if you want to leave comments: https://redpen.io/pu93e851c2a9b66866
![medium-encrypt-v1-06](https://cloud.githubusercontent.com/assets/14876567/12958884/aa58d1f4-cfe8-11e5-8a92-3a31fb18f6a9.png)

Thinking we could reuse the lock image for the avatar and maintain the 'encrypt' workmark for the possible publication logo background.

**Comment by KevZawacki** [comment]
@natalieworth Thanks, these look great! Using the lock as the avatar works for me.

**Comment by KevZawacki** [comment]
@natalieworth With Paul now -- these are approved. Can you share a link to the assets? Thanks!

**Comment by natalieworth** [comment]
Thanks @KevZawacki , here's the link to the google drive with png images and the .ai file. I can export any other file format if you need them exported any other way.
https://drive.google.com/drive/folders/0B20-0lpP23c0ZVBfeUotdVU1U1k

**Comment by HPaulJohnson** [comment]
This is good to go, closing. Thanks, @natalieworth and @KevZawacki
