### ISSUE TITLE
Decide if YouTube Donation Card is an option for testing in a video

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#82]
Reference:
http://blog.see3.com/youtube-launches-a-breakthrough-in-nonprofit-fundraising/

Given our investment in video content and our goal to integrate fundraising into our advocacy campaigning, this seems like a good option to explore.

Thoughts / Questions:
- Network for Good is the payment processor. This likely means Network for Good would have to go through security review (if it hasn't already). @simonwex is there a way to check if a vendor has passed security review? (I've not found that kind of search to be easy)
- YouTube obvi is owned by Google, we need to know what happens to user data, and what optins or checkboxes are presented at the point of donation.

cc @adamlofting

**Comment by adamlofting** [comment]
That sounds interesting.

A search for existing vendor reviews would be great - I've not seen one before, but we might have it somewhere. 

From the screenshots it looks like they're using this as a way to sign-up new google payment accounts (I think this is 'wallet'). That has a similar level of review as we do with PayPal. I.e. the user makes the agreement with the provider not us, but we make sure this is clear to them up front.

**Comment by OpenMatt** [comment]
@simonwex do you know answer to Andrea's question above re: vendor review search?
