### ISSUE TITLE
Urgent: finalization of voice over/message text

### ISSUE THREAD

**Issue by rohanporteous** [MozillaFoundation/encryption_campaign#83]
Hey @brettgaylor @OpenMatt @HPaulJohnson @valianttry @shaghdoosti and team,

Now that we've got something solid to reference in the rough draft it's time to finalize all the voice over & messaging! This has to happen ASAP as we need to book/record the VO before _and_ add in all the final graphics before the end of the week.

I've created this doc to provide context around all the individual elements required, and as a place where all brainstorming/comments/decision making can happen. https://docs.google.com/document/d/1a_j7azyrkOHlSNHlpa2Ij4ciHuPjQoW8Lvc7Q6zNr2U/edit?usp=sharing

@OpenMatt are you able to find time for all the necessary team members to jump in/contribute?

**Comment by rohanporteous** [comment]
FYI Gwenith has now officially been hired for the VO gig. Just waiting on confirmation of her schedule to know whether we need the final VO script by tomorrow midday or Friday morning.

**Comment by rohanporteous** [comment]
@brettgaylor @valianttry @HPaulJohnson I've now tried the boss with his new text. I think it might work timing wise! Let me know.

[The clip showing the message appearing](https://drive.google.com/file/d/0B3UIshL1Uom0a28tamp1ZjB0c2s/view?usp=sharing).
[His reaction](https://drive.google.com/file/d/0B3UIshL1Uom0V1ZmM3h0SzFxSDA/view?usp=sharing) after seeing the rest of the office. (Still a little strange, but hopefully OK).

How are you going with the rest of the edit feedback? Would be great to get it ASAP as it's holding off any further work on graphics.

**Comment by rohanporteous** [comment]
@brettgaylor @valianttry @HPaulJohnson @shaghdoosti final line to decide on before getting re-record from voice talent: the lead into the boss. 

Now that we've changed his text, the medical line no longer works. I've added a new section for input at the top of the narrator page in the doc up top. If people can leave ideas/comments in there asap that would be great!

**Comment by HPaulJohnson** [comment]
@rohanporteous: just talked to @valianttry and @lovegushwa about this. There is still some strong feeling that the idea of keeping medical data private is still critical to the campaign message overall, so trying to figure out a way to maintain this and have it match the emotion of the character.  

To unblock forward progress, would it be possible to record two versions of the voice over? One, using the existing "your medical secrets" line (which we would need a new, matching graphic message for - blue poo definitely doesn't work) and one using something that works with the "boss of the year" graphic  (I'll add some ideas for this v/o in gdoc shortly). 

That will give us some options to work with and flexibility to move forward with recording/graphics and hold off on final decision until we all have a chance to discuss as a group (hopefully can find some time  tomorrow to do that). 

Not sure what the rest of the deadlines/timeline looks like so let me know if this is a possible path forward in the short-term. 

Also, there's a lot going on in that gdoc now so if there are any other urgent blockers can you call them out here so we can tackle this afternoon?

**Comment by HPaulJohnson** [comment]
@rohanporteous @brettgaylor @valianttry @shaghdoosti 

I added some alt voice-over thoughts for boss scene. It does lack the power of the medical secrets however. One idea I had about a possible fix that would allow us to keep all the original themes (family, financial, personal, job, medical) would be: 
- Turns the dad w/ strollers moment into "blue poo" message and medical secrets voice/over. His facial expression works I think, but not sure the non-expression from exterminator would. 
- Have the boss' moment be exposing credit card data and use the financial secrets voice/over for this part. The credit card info could either be him exceeding his limit or ordering something like a boss of the year mug. Not sure if the reaction from the office would fit. 

Feel free to ignore if it's too complicated a tweak to make at this point or if it's just a bad idea.

**Comment by rohanporteous** [comment]
@HPaulJohnson don't think it's necessarily a bad idea by any means, but it is probably a little too much to tweak at this stage given that the edits are pretty dependent on the specific messages and their timings. Will take a look through all your other ideas! Thanks for writing them up :)

**Comment by brettgaylor** [comment]
That could work - switching the dad and boss lines.

Rohan, this would likely push us a day, which from our end would still be ok.

I think you’d need to cut away from the dad/exterminator almost right away.

Could be a good solve.

**Comment by rohanporteous** [comment]
In this instance I was more concerned about the delays on my end rather than yours, as it's just getting to the final stages of production and cutting into the animating/polishing. Will give it a quick go in the edit to see if it works.

**Comment by rohanporteous** [comment]
@brettgaylor @HPaulJohnson ok I'm going to leave the office now! I think if we have the edit decisions resolved tomorrow morning that should give us enough time to incorporate all the changes :) (have confusingly been mixing threads. the new edits on the 'rough edit' issue.

**Comment by rohanporteous** [comment]
@HPaulJohnson I think we're there on the script/what we need to record—what do you think! If so, I'll send off immediately.

**Comment by HPaulJohnson** [comment]
@rohanporteous good to go! let's do it.

**Comment by rohanporteous** [comment]
Sent!

**Comment by HPaulJohnson** [comment]
@rohanporteous - This seems done so I'm going to close for now. Please reopen if there are any new (or outstanding) issues here.
