### ISSUE TITLE
Create graphics for end cards

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#85]
We need to create the end titles using the same treatment as rest of campaign.

Jordan can you create and send to @rohanporteous based on the end screens in this document?

https://docs.google.com/document/d/1a_j7azyrkOHlSNHlpa2Ij4ciHuPjQoW8Lvc7Q6zNr2U/edit#

**Comment by lovegushwa** [comment]
@brettgaylor @rohanporteous 

Regarding the end cards. We will have different landing pages. One for our email list, with a UX social share CTA after the video plays. And one for organic/social with a UX Opt-in email CTA. Both these videos just need the campaign branding. Something like this: https://drive.google.com/file/d/0B2qu3ExKWIlvaDN2WEpOS3NIaHc/view?usp=sharing

We will also have video directly on Facebook, that video will need branding and a URL CTA.

I'll have end card templates to you by end of day tomorrow (the identity still needs to be approved.)
@brettgaylor @HPaulJohnson can we confirm the URL CTA?

**Comment by rohanporteous** [comment]
@lovegushwa ooooh that looks cool. Will you have original Photoshop/Illustrator files for me? Would be good to do some subtle animations on the letters.

Would be great to know exactly what narration differences are required for each as well.

**Comment by HPaulJohnson** [comment]
@lovegushwa - let's use mzl.la/encrypt where we need to show a URL as part of a CTA.

**Comment by rohanporteous** [comment]
@lovegushwa should be ok to wait till next week. Earlier the better.

**Comment by OpenMatt** [comment]
@lovegushwa says: still need to figure out motion in final card. He'll follow up here.

**Comment by rohanporteous** [comment]
@OpenMatt great, thanks.

**Comment by lovegushwa** [comment]
@brettgaylor  @shaghdoosti  @valianttry @HPaulJohnson

Hey everyone, worked with Paul this morning to knock out some end card variants. 
Please note, the UX column we control so don't sweat that copy. 

Please post your feedback asap so I can pull this together before @rohanporteous get's back in the office. https://redpen.io/p/vn95d03649423099f0

**Comment by lovegushwa** [comment]
@brettgaylor @rohanporteous 
Here are the end card variants, a few notes:
- Rohan don't worry about the UX column. 
- Email Direct and Partner are the same.
- Native is the same as Social/Organic with the addition of a 3rd card.

![encryption-endcard-flow-02-01](https://cloud.githubusercontent.com/assets/12228435/12766029/4c750ebe-c9b6-11e5-9ddb-b97069bd784d.jpg)

**Comment by lovegushwa** [comment]
@rohanporteous working on graphics for you now, will post asap.

**Comment by rohanporteous** [comment]
@lovegushwa great, thanks!

**Comment by lovegushwa** [comment]
@rohanporteous here is a link to the identity files: 
https://drive.google.com/file/d/0B2qu3ExKWIlvSTNaSmdYblBMTDA/view?usp=sharing

This is an example of how we might animate the text:
https://d157rqmxrxj6ey.cloudfront.net/natalieworth/28603/

**Comment by lovegushwa** [comment]
@rohanporteous 
https://drive.google.com/folderview?id=0B2qu3ExKWIlvdlhoRV9jbUxiX0k&usp=sharing

Feel free to tweak and revise this direction. The type is in the folder.

Native could use 2 extra cards (rather than squeezing the Encrypt and URL on one screen.)
<img width="1331" alt="screen shot 2016-02-02 at 6 42 03 pm" src="https://cloud.githubusercontent.com/assets/12228435/12771290/1cf57d78-c9dd-11e5-8535-b6d47788d2f4.png">

**Comment by lovegushwa** [comment]
@rohanporteous when your ready, can you drop a link to the final ident aftereffects in this ticket?

**Comment by rohanporteous** [comment]
@lovegushwa you should find everything you need [here](https://drive.google.com/file/d/0B3UIshL1Uom0QzlibUg1YXBYNDg/view?usp=sharing). It includes Illustrator files and a new glitch video to add another effect to the final logo.

**Comment by lovegushwa** [comment]
@rohanporteous thank you!
