### ISSUE TITLE
Create new constituent groups for ExactTarget

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/encryption_campaign#86]
Reference: #20 

We would like to send custom messaging to our current Active Advocates (supporters on our list who have signed at least one of our major petitions). We also want to be able to see their responsiveness relative to new optins or other sub-segments.

That means we need to create two new constituent groups in the database for current list subscribers who signed either of these two petitions:
- https://sendto.mozilla.org/page/s/FCCvote-net-neutrality
- https://sendto.mozilla.org/page/s/section-215-petition

@jbuck do you have bandwidth?

**Comment by valianttry** [comment]
Note: This upload only has to happen 1x (not daily like EOY donor data).

**Comment by OpenMatt** [comment]
cc @simonwex

**Comment by jbuck** [comment]
@valianttry I put together all of the email addresses from those two pages, uploaded it to goggle drive, and shared it with you. I don't know how to create constituent groups in ET, but all of the email addresses are there.

**Comment by OpenMatt** [comment]
Thanks @jbuck 
@valianttry anything further needed? can we close?

**Comment by OpenMatt** [comment]
Closing. Please re-open if that's wrong.
