### ISSUE TITLE
Voice Over Record

### ISSUE THREAD

**Issue by KarinaRipper** [MozillaFoundation/encryption_campaign#87]
Hi @OpenMatt @brettgaylor diving in for Beat 2, woot woot :) 

Wanted to check in on the VO record for Beat 2. I saw that the VO artist is Gwenith and she has been hired but would like to know when we can get her VO recorder. Would be great to get this rolling soon (possibly by Monday?) so we can begin animating to her VO track rather than the scratch. Let us know the status. 

Thank you!

**Comment by OpenMatt** [comment]
@brettgaylor are you able to respond?

**Comment by brettgaylor** [comment]
@KarinaRipper hola!

Thanks for flagging this. The narrator we currently have for beat 1 we hadn't actually considered for this beat, and in fact, we don't have a plan here!  The only plan of record is that we wanted somewhat of a gentle old man voice.

I think that @rohanporteous used an online service to find a voice actor.  Do you think you might be able to wrangle this on your end Karina?

I can help with some of this when I return next week, but if you think we should get moving on this now I think we might need you to own this if that's ok!

**Comment by rohanporteous** [comment]
@KarinaRipper could definitely used Gwenith for any/all beats if we wanted some kind of continuity but it's @brettgaylor's call really—I think the plan is to treat each beat separately. I used Voices.com. Not as good as a broader, more traditional talent search but good in a squeeze. (You can get a lot of slightly flat/dull performances, but there are normally a number that shine through).

I sent through a brief with the script and some direction and got between 20–30 auditions back overnight. We then selected our favorite 7 or so to streamline the process, making it easier for the broader team to review.

**Comment by KarinaRipper** [comment]
@rohanporteous Thank you for the tips! Totally will check out Voices.com

@brettgaylor @OpenMatt sent you both a side email about this in regards to contract. Let me know your thoughts and how you would like to collaborate on VO casting. 

Thank you!

**Comment by valianttry** [comment]
@brettgaylor we had a "runner up" male voice we all liked -- was his name Ross? Maybe a fit?

**Comment by rohanporteous** [comment]
@valianttry @KarinaRipper yeah Ross was pretty great. So silky smooth. Could be good if that's what you're after.

I just uploaded all our male auditions here if you need something super quickly. Otherwise they'll be able to find what you want in no time as well. https://drive.google.com/folderview?id=0B3UIshL1Uom0aVhzdWJlcGl4WXc&usp=sharing

**Comment by KarinaRipper** [comment]
Sweet! Thank you so much @rohanporteous @valianttry I'll take a listen to these gents!

**Comment by KarinaRipper** [comment]
Voices.com is so so great!! Thanks for the tips, should have options for the team to review tomorrow (Tues 02/02). @brettgaylor

**Comment by rohanporteous** [comment]
@KarinaRipper great—glad you found it useful!

**Comment by KarinaRipper** [comment]
Hi @brettgaylor and @OpenMatt 
Happy VO audition day! I've got some gems for you to take a listen to for Beat 2. 

VO auditions here:
https://drive.google.com/open?id=0B0X9tL5cdPcYc2hZUkVoaVhGVFE

One note - Ross Huguet's audition has a watermark, hence the sound warble at 5sec. 
Darren and I are both digging Ross and Jim Ripley. 

Would be great to have your thoughts soon, possibly **before 2pm**. So we can hopefully schedule the VO record for tomorrow. Looking forward to hearing your thoughts. 

Thank you!

**Comment by brettgaylor** [comment]
Hi, Kristina! Will give a listen and provide notes around 2pm.

**Comment by KarinaRipper** [comment]
Sounds good, thanks Brett!

**Comment by brettgaylor** [comment]
Hot damn!  That was fun :) Lots of good voices in there.  I think many of them actually had a similar tone, good shortlist.

The standout for me is Jim Ripley - has the nice old man / drifter from Big Lebowsky quality we were after.

Let's go with him!

Do I need to create an account there?  How will that work?

**Comment by KarinaRipper** [comment]
Rad! So glad you liked them. I'll line things up with the talented Jim Ripley. As well as look into the account details and will have these for you shortly ;) 

Will you want to be included in the VO record session tomorrow or is it cool for Darren to direct the session? Let me know so I can schedule accordingly. Thank you!

**Comment by brettgaylor** [comment]
Great. I may need to call you re: account details for financial info. Will
email off list.

Fine for Darren to direct. Tomorrow I'm flying home from vacation and will
be unreachable.

**Comment by KarinaRipper** [comment]
@brettgaylor cool sounds good! Saw your email, looking forward to talking with you this evening. Thanks!
