### ISSUE TITLE
Document next steps with TODO

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#88]
Let's make sure we're all clear on what TODO will be working on / delivering / need from Mozilla team for week of Feb 1 - 5.  We can use this ticket to list deliverables, questions or decisions needed. Then file them as separate tickets for following up. 
### Next steps
- [x] add TODO team to GitHub collaborators
- [ ] ticket work that Mozilla needs to do in house for Beat 3. (Not in scope for TODO)
- [ ] other...

**Comment by michellenebiolo** [comment]
As our deliverable for Week 1, we plan on sharing with you the wireframe for the website on Thursday, Feb. 4th by 10 am PT (7 pm CET). 
Hopefully the time difference will work to our advantage and we can get feedback/approval from you by the end of Thursday (we count on receiving it by Friday 10 am CET, which is 1 am PT but I hope none of you are still working at that hour!).

**Comment by valianttry** [comment]
One critical thing we need to know is exactly what we need to build in-house and ticket that. There are a few items listed as "out of scope" in TODO's outline that we should get in our dev queue.

**Comment by OpenMatt** [comment]
filed #89

**Comment by OpenMatt** [comment]
Next steps for closing this ticket:
- ticket Mozilla-lead work in Beat 3 (Matt will do) 
- ensure all TODO deliverables are ticketed. @michellenebiolo: can you take that on? what else beyond: #89

**Comment by michellenebiolo** [comment]
I filed #92, #93, #94 and #95. 
@OpenMatt please edit labels and milestones as necessary of course.
