### ISSUE TITLE
Wireframe for Beat 3 website

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#89]
Due Thursday, Feb. 4th by 10 am PT (7 pm CET)

Hoping for feedback/approval by  end of Thursday

**Comment by OpenMatt** [comment]
@michellenebiolo let us know if there's anything you need from us on this in order to hit that date.

**Comment by michellenebiolo** [comment]
Hi @OpenMatt, one thing we need is the list of people/emails we should share our Thursday presentation with. 

Can we also arrange a brief video-call to go over the presentation together on the 4th, ideally 9.30 am PT / 6.30 pm CET?

**Comment by michellenebiolo** [comment]
@OpenMatt I wonder if at this time you have any details you can share about the newsletter that will be sent out to launch the Beat 3 website.

In particular, we are assuming the newsletter will contain a short emoji message to be decrypted on the website (and a more or less “hidden” key). We think “Try to decrypt this” would provide a stronger call to action than a generic invitation to visit the website, but perhaps you can confirm that would be consistent with the rest of the campaign?

**Comment by OpenMatt** [comment]
@shaghdoosti @valianttry @HPaulJohnson  are you able to answer?

**Comment by OpenMatt** [comment]
@michellenebiolo re: Thursday meetings. I just added you to the calendar invite for our weekly meetings with the group. I suspect the time zone won't work for your team, though -- can you suggest a time that would be better for you guys?

**Comment by OpenMatt** [comment]
Wireframes are here: http://mzl.la/beat3_wireframes
