### ISSUE TITLE
Email copy and production calendar for Beats 1 and 2 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#9]
Including testing plan

**Comment by OpenMatt** [comment]
@shaghdoosti: not sure who to assign this to. please re-assign as needed.

**Comment by OpenMatt** [comment]
@shaghdoosti are you the right person to assign this to?

**Comment by OpenMatt** [comment]
@valianttry @shaghdoosti is that what this document is?
https://docs.google.com/document/d/18eaF4c0eFR-5kyMGNIAQXRhCTIzprDWooWuoXYfRQO0/edit#heading=h.ey0mzx3c8e87

**Comment by valianttry** [comment]
@OpenMatt nope, that's the document for EOY fundraising email.

We do not yet have a detailed email production schedule, Stephanie will be lead on this -- but I can't seem to tag her in this repo. 
We will draft email schedule and production this week, but need Stephanie to help refine / fill in important details early next week, esp for Beats 1 and 2

**Comment by valianttry** [comment]
FYI we should create separate tickets for each email step. Typically we would use the following 3 tickets (example - Steph continues to perfect and refine our processes for email production):
1. write copy for emails Beat 1 (including tests, segment copy)
2. setup and production emails Beat 1
3. Q&A emails Beat 1

**Comment by OpenMatt** [comment]
ok done. Going to mark this one as closed and we can push ahead with those other tickets.
