### ISSUE TITLE
Make sure optimizely is installed on campaign landing page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#90]
Just wanted to make sure that we include Optimizely on new landing page to enable testing throughout the campaign. 

cc/ @alicoding @lovegushwa

**Comment by lovegushwa** [comment]
@alicoding @alanmoo just checking if this is hooked up.
CC @HPaulJohnson

**Comment by alanmoo** [comment]
@alicoding I'm going to leave this one to you, I'm not sure what I'd be referencing and you've got the page structure understanding

**Comment by alicoding** [comment]
@adamlofting I did something similar to donate.mozilla.org here, but not sure where to get optimizely ID here?

**Comment by adamlofting** [comment]
We use the same Optimizely ID for all sites, so this can be the same as for donate.m.o

Noting we need to use the same subdomain setup to limit the cookies to advocacy.m.o

**Comment by alicoding** [comment]
This is done
