### ISSUE TITLE
Make sure GA is installed on campaign landing page

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#91]
Just wanted to ensure that the proper analytics are installed on new landing page so we can optimize experience as we go. 

cc/ @alicoding @lovegushwa

**Comment by lovegushwa** [comment]
@alicoding @alanmoo just checking if this is hooked up.
CC @HPaulJohnson

**Comment by alanmoo** [comment]
@alicoding I'm going to leave this one to you, I'm not sure what I'd be referencing and you've got the page structure understanding

**Comment by adamlofting** [comment]
@alicoding in reply to IRC ping:
- where will this be hosted? (ie what domain or subdomain)
- is there any existing GA property? (ie is this part of the advocacy site in terms of tracking?)
- how is the site/page built - is it static html or is state managed via react-router or simialr?

**Comment by adamlofting** [comment]
It looks like advocacy.mozilla.org used to have GA tracking on it until recently, and now it doesn't:

<img width="1421" alt="screenshot 2016-02-08 14 43 55" src="https://cloud.githubusercontent.com/assets/1901816/12888490/58d3c464-ce72-11e5-8bf0-36df4c4530b3.png">

But this profile exists with Tracking ID: `UA-49796218-9`

We can use that ID, and the same approach to tracking page views as we did for donate.mozilla.org

**Comment by alicoding** [comment]
1. The page will be hosted on https://advocacy.mozilla.org/encrypt/ 
2. There is no GA script on any page at the moment
3. This site (/encrypt) is React app with similar setup to donate.mozilla.org where we serve static built file and using React-router.

**Comment by alicoding** [comment]
@HPaulJohnson @adamlofting do we want to track any click on the element of the page at all? or just pageview here?

**Comment by adamlofting** [comment]
I'm not close to this project so am not sure what the specific goals of the page are, but I would encourage tracking on any elements linked to the goal of the page. Share buttons, or sign-up forms etc.

**Comment by alicoding** [comment]
This is now done
