### ISSUE TITLE
Prototype Iteration 1 (of 3) for Beat 3 Website

### ISSUE THREAD

**Issue by michellenebiolo** [MozillaFoundation/encryption_campaign#92]
Due Thursday, Feb. 11th by 10 am PT (7 pm CET)
Hoping for feedback/approval by end of Thursday

@OpenMatt I'm not sure whether this needs to be associated with the existing Feb.12th milestone or not

Adding @Giorgio-Olivero and @abusedmedia to make sure they are in the loop.

**Comment by OpenMatt** [comment]
@lovegushwa can you paste the Redpen here for how the experience will be embedded into / fit with the rest of the web site?

**Comment by michellenebiolo** [comment]
Quick update on this deliverable: we are focusing on solving all the major functionality issues before moving on to the desktop version of the website, so please expect a mobile version prototype on Thursday.

Meanwhile, are there any updates you can share with us on how Cryptoloji will fit in the campaign website, in terms of both experience and look&feel?
(As regards the latter, we have seen mockups on https://redpen.io/ but don't know if those are definitive and whether the Cryptoloji website needs to comply with any underlying graphic guidelines or to what extent it can have its own rules.)

**Comment by OpenMatt** [comment]
cc @brettgaylor

**Comment by michellenebiolo** [comment]
Here is the link to the prototype Giorgio is presenting:
http://el.s.todo.to.it/cryptoloji/0164/#/welcome
(please note it's the mobile version, so perhaps viewing it on your phones or with a very narrow window would be best)

@OpenMatt @HPaulJohnson @valianttry @lovegushwa 
(please add anyone else that needs to see this).

**Comment by michellenebiolo** [comment]
As Giorgio was saying, you can also "watch us work" at any time by accessing the last available folder at the bottom of http://el.s.todo.to.it/cryptoloji

**Comment by michellenebiolo** [comment]
Here are also a few links to some prototypes that focus on individual micro-interactions we are testing.
Please let us know if you have any feedback.

https://dl.dropboxusercontent.com/u/15645292/mozilla/moz041/index.html
Swipe the emoji slider and at the end the “+” sign is revealed. Once revealed it is sticky (even if you swipe back). We are focusing on the slider’s behavior in terms of inertia and bounciness. 

https://dl.dropboxusercontent.com/u/15645292/mozilla/moz06/index.html
Click/tap on the “+” sign to open the panel with all the available emojis (we are currently working on the final set to maximize compatibility with all platforms/systems, there should be about 10 in the slider and over 400 in the panel). The “+” then turns into an “x” to close the same panel.

https://dl.dropboxusercontent.com/u/15645292/mozilla/moz07/index.html
Click/tap on the “Share this message” call to action at the bottom: the share section overlaps over the previous sections to bring up sharing options and other relevant content.

https://dl.dropboxusercontent.com/u/15645292/mozilla/moz08/index.html
Same as above, but the section pushes the previous ones up and out of the screen instead of covering them.

**Comment by lovegushwa** [comment]
@cassiemc @vazquez @sabrinang @kristinashu @flukeout @natalieworth @xmatthewx @LauraReynal @edrushka  @HPaulJohnson 

Please try out this prototype and post your feedback today! (See the email I sent for context, start reading from the 4th comment above.) Send me a IRC if you have questions.

Thank you thank you.

**Comment by flukeout** [comment]
On mobile (Nexus 4) I can neither see the message I am typing, nor the encrypted version...

![image](https://cloud.githubusercontent.com/assets/25212/13014957/39076e64-d16b-11e5-8bc1-ec7fe219b764.png)

Maybe you could compress the height of the input and output fields to one line for mobile?

**Comment by flukeout** [comment]
Before picking an emoji key, the typed message doesn't appear in the Secret Message...

![image](https://cloud.githubusercontent.com/assets/25212/13015018/8b6848ae-d16b-11e5-867d-2bb0c92e73ef.png)

Can we...
- Have it appear un-encrypted until you pick a key? <- my pref
- Default to one of the keys right from the start?

**Comment by flukeout** [comment]
Not a huge deal, but the "characters left" indicator goes into the negative when you use up your 400 max chars and you can keep typing a longer message. Can we cap the message length and stop the indicator at 0 chars left?

**Comment by flukeout** [comment]
Until you type your message, the **Share this message** button is hidden. Once it appears, even if you delete your message contents, the **Share** button remains. Maybe we can hide it when the message is blank.

**Comment by Giorgio-Olivero** [comment]
thanks for the feedbacks!  consider that this is still an early prototype and some issues are actually yet-to-be-developed features.

**Comment by flukeout** [comment]
The emojis in the "show me what this is" intro tutorial don't match any of the emojis that I can actually use when writing a message, which is disappointing because i want to use a watermelon! 

It also suggests that the shape of the emojis is going to match the letter, which isn't really the case.

**Comment by flukeout** [comment]
@Giorgio-Olivero Yeah for sure - just listing things I've found since @lovegushwa asked us to take a look. Apologies if you are already aware of these. Let me know if this kind of feedback is helpful at this point. Cheers.

**Comment by flukeout** [comment]
The tutorial carousel indicator doesn't indicate what page you're on...

![image](https://cloud.githubusercontent.com/assets/25212/13015615/e1bb6954-d16e-11e5-82ec-e6c2c7f18247.png)

Ok, I'm done for now :D

**Comment by kristinashu** [comment]
Super cute! Here are a few initial thoughts:

Maybe don't use the happy face emoji here? It' seems a little confusing to see the emoji in the traditional sense (a picture to replace a word) but then the rest of the app emoji's represent a letter. But maybe that's just me:

<img width="322" alt="screen shot 2016-02-12 at 10 30 18 am" src="https://cloud.githubusercontent.com/assets/1068783/13016451/a8df8408-d173-11e5-9fd3-c7e810f8b0bf.png">

Content is super tight on the screen. Maybe we don't need to show the key here? Maybe "pick a key" text could be inline with the emojis instead of above? 

<img width="426" alt="screen shot 2016-02-12 at 10 33 22 am" src="https://cloud.githubusercontent.com/assets/1068783/13016509/14a5d142-d174-11e5-9a4a-30780fe449a3.png">

Don't think it needs so many different keys. Would be great to remove the + icon.

<img width="426" alt="screen shot 2016-02-12 at 10 33 22 am" src="https://cloud.githubusercontent.com/assets/1068783/13016509/14a5d142-d174-11e5-9a4a-30780fe449a3.png">

Selected emoji key could look more obviously selected:

<img width="425" alt="screen shot 2016-02-12 at 10 32 30 am" src="https://cloud.githubusercontent.com/assets/1068783/13016493/f93ed052-d173-11e5-9a08-3f90d8a0fc16.png">

All the emojis in the secret message look very similar (all faces). Would be cool to have more variety (fruit, objects, animals...):

<img width="425" alt="screen shot 2016-02-12 at 10 32 30 am" src="https://cloud.githubusercontent.com/assets/1068783/13016485/f45a9044-d173-11e5-9fd6-adb5f6181c6c.png">

**Comment by Giorgio-Olivero** [comment]
@kristinashu : what's your phone model?

**Comment by Giorgio-Olivero** [comment]
Release 0198
available here: http://el.s.todo.to.it/cryptoloji/0198

Change-log:
- minor bug fixes
- we have freshly introduced the 'decrypt a message logic and view' ('decryption' was missing from previous prototype)
- onboarding slider component, first version (now it's slidable, before only tappable)
- 'more emoji' modal refinement

Please keep on with the comments, we're not answering them 1:1, as many are already known. Next week we'll keep polishing the experience while advancing with the development of the mobile (and the upcoming 'desktop') version.

@abusedmedia (Fabio Franchino) asked if you would be ok with posting the comments as separate issues on our public repository, here: https://github.com/todotoit/cryptoloji/issues

Let us know

**Comment by kristinashu** [comment]
@Giorgio-Olivero i'm on iPhone 5s in Firefox

**Comment by OpenMatt** [comment]
Closing this one, as work is now ongoing in Prototype 2 here: https://github.com/MozillaFoundation/encryption_campaign/issues/93
