### ISSUE TITLE
Copy for campaign promotion in MLN monthly newsletter

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/encryption_campaign#97]
Per our conversation with @KGorr today, there's a space in the March MLN community newsletter for a encryption campaign promotion. Copy due: 2/17

cc/ @KevZawacki

**Comment by KevZawacki** [comment]
Hey @kgorr, I can put together this copy. Can you provide guidance on length and tone? Thanks!

**Comment by KGorr** [comment]
Thanks, @KevZawacki! The Encryption campaign blurb will go in the announcements section (let me know if you need to see Jan's edition for reference). I'd keep it to 2-3 sentences with a brief intro and CTA. Does that help?

**Comment by KevZawacki** [comment]
@KGorr Thanks! I'll get to work. One last question: when is the exact date the newsletter is going out?

**Comment by KGorr** [comment]
March 4, but copy needs to be to me by 2/17

**Comment by KGorr** [comment]
@KevZawacki, would it be possible for you to also provide an image to go along with the encryption campaign blurb?

**Comment by KevZawacki** [comment]
Hi @KGorr, how's this?

"Mozilla is standing up for encryption. Our online privacy depends on encryption. Learn more about how it works, why it's essential, and why it's worth protecting. Visit mzl.la/encrypt."

@HPaulJohnson This is derivative language, most of which has already been used externally. I'll share with Sara just in case. @KGorr, we're waiting on final approval on the above language.  

@KGorr As for images, might [these graphics](https://drive.google.com/drive/folders/0B20-0lpP23c0ZVBfeUotdVU1U1k) work?

**Comment by KGorr** [comment]
Thanks, @KevZawacki! Copy is great and the images are perfect. I'll await the final word that it's approved before sending to Stephanie for uploading in Exact Target.

**Comment by KevZawacki** [comment]
Note to self: awaiting approvals [in this doc](https://docs.google.com/document/d/1QpAMYVblmMSZ3E9l2BzMyRYWIk8Su82ItisDPDJB-Yg/edit)

**Comment by KevZawacki** [comment]
Hi @KGorr, the following language is approved for the MLN newsletter:

"Mozilla is standing up for encryption, the technology that helps protect our online security and privacy. Learn more about how it works, why it's essential, and why it's worth protecting. Visit mzl.la/encrypt."

I think we're all set, so I'm going to close this ticket. Feel free to re-open if something's changed!

**Comment by KGorr** [comment]
Sorry to re-open this, but we discussed on our call Tuesday that having the tracking URL on the encryption link would be helpful. @KevZawacki, is this something you can help with by 3/1?

**Comment by KevZawacki** [comment]
plus @HPaulJohnson, tracking link expert
