### ISSUE TITLE
Deliver compressed video files

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/encryption_campaign#98]
@rohanporteous we are going to be hosting this video in a variety of locations, including, awesomely, firefox.  It will play in the about:home portion of the browser, which has some specific technical requirements.  That page needs to be as light as possible, so we may need you to deliver videos in a specific way.

@ScottDowne what are the formats needed for the snippet?  And is there a file size we need to try and keep the file to?

**Comment by ScottDowne** [comment]
Videos in the snippet are new to me. I have looked at existing snippets and
I found that it used webm and video elements.

I am aware that there is magic involved in the hosting but don't know the
exact details.

I think the essentials are that it'll be a video element, and how to use
the source passed into the snippet via snippit config, though, right?

**Comment by brettgaylor** [comment]
@ScottDowne maybe the thing to figure out is just how heavy the page can be, and then we can pass that info on to our video team.  Could you also find out where to host the video assets?  Is it videos.mozilla.org, or an amazon bucket, etc?

**Comment by ScottDowne** [comment]
And I don't know any details on size requirements. I can figure that out
for you if you like.

**Comment by brettgaylor** [comment]
Yes please re: size!

**Comment by ScottDowne** [comment]
No answer on file size yet, but I can confirm it needs to be 480x270 and webm.

Me or anyone else can then send the source file to the snippet team, and they upload it, and they put the source into the snippet template.

**Comment by ScottDowne** [comment]
I didn't get back a conclusive answer. The longest video ever used had a 6 minute duration.

In general they try to keep videos under 1 min and under 300kb. Right now there is a 33 second 2MB video snippet running.

Looks like it's flexible. What kind of sizes are we talking about for our video?

The question has been pushed to someone in GMT+2 so we can expect a another answer back tomorrow.

**Comment by ScottDowne** [comment]
No technical hard limit.

**Comment by rohanporteous** [comment]
FYI [here's](https://drive.google.com/file/d/0B3UIshL1Uom0VEQ4blczUndZLUk/view?usp=sharing) a webm video, coming in at 5.7mg for 480x270.

**Comment by brettgaylor** [comment]
@rohanporteous I think that's too big - what are you using for compression? Can we try and limit to 3mb?

**Comment by brettgaylor** [comment]
Or perhaps 5mb?

**Comment by rohanporteous** [comment]
@brettgaylor OK… I finally found a convertor that would get us to where we need to be, and exported 4 versions of the main video for comparison, all under (or just at) 5mg. Take a look [here](https://drive.google.com/folderview?id=0B3UIshL1Uom0R0VyTXBYRC02V0U&usp=sharing) and let me know which one you want to go with, and I'll export the other two with the same settings.

**Comment by rohanporteous** [comment]
@brettgaylor just ended exporting/uploading other versions anyways.

**Comment by ScottDowne** [comment]
@brettgaylor @rohanporteous we should probably make a poster image for the video too.

Same dimensions at 480x270.

And also keep in mind there is going to be a big blue play button in the middle, so if we're making this we should consider that we don't want to put someone's face or something under that button.

The button's look and location is this: http://scottdowne.github.io/eoy-snippets/signup-snippet/

**Comment by brettgaylor** [comment]
Scott that work is in #103

**Comment by ScottDowne** [comment]
@brettgaylor ah awesome! carry on!

**Comment by brettgaylor** [comment]
Great, thanks @rohanporteous 
@alanmoo the file we will want to use for the snippet is: 
moz.final.1.native.480x270.default.normal.webm

Which is available here
https://drive.google.com/folderview?id=0B3UIshL1Uom0R0VyTXBYRC02V0U&usp=sharing

**Comment by jbuck** [comment]
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.1.native.480x270.480kbps.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.1.native.480x270.480kbps.normal.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.1.native.480x270.default.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.1.native.480x270.default.normal.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.2.social.480x270.3072kbps.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.2.social.480x270.3072kbps.normal.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.2.social.480x270.480kbps.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.2.social.480x270.480kbps.normal.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner.480x270.3072kbps.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner.480x270.3072kbps.normal.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner.480x270.480kbps.low.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner.480x270.480kbps.normal.webm

**Comment by brettgaylor** [comment]
@rohanporteous realized we haven't compressed these for our microsite.  Would you be able to deliver the "native" video in mp4 and webm?  This one doesn't need to be as highlight compressed - @lovegushwa what are the pixel dimensions on the microsite?

**Comment by lovegushwa** [comment]
5mb mobile, 10mb standard. iOS and edge do not support webm
We could also double 960x540 for retina. So three versions.

@alanmoo  is double checking this. @rohanporteous might know as well.
