### ISSUE TITLE
Provide back-end infrastructure for Beat 3 website

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/encryption_campaign#99]
- Design and front-end development will be provided by our contractor friends at TODO (design ticket is here: https://github.com/MozillaFoundation/encryption_campaign/issues/89)
### Timelines:
- Feb 4: UX design + wireframe complete
- Feb 18: design +  front-end development complete
- Feb 25: testing, QA, debugging complete 
- Feb 26: final delivery to production

**Comment by OpenMatt** [comment]
* @michellenebiolo can you confirm that the timelines above are correct?
* can you also let me know what specifically you will need from our developers this week (if anything) and especially: next week.

**Comment by OpenMatt** [comment]
Here's my understanding of what TODO needs from Mozilla. 
- TODO will provide all the front-end development work, and deliver all production files (HTML, CSS, JS, images, web fonts) to Mozilla in a “ready-for-deploy” file structure.
- But our devs will need to provide: 

### 1) Backend

Development of a custom RESTful API backend with the capability to store messages containing emoji
characters identifiable by unique ID and serve them on request to our front-end. There are no
constrains about the technical stack (language/framework) apart from the capabilities required above
and the RESTful requirement. Authentication is not required. Full specifications TBD.

### 2) Server infrastructure

Server infrastructure needed to deploy and serve the backend and the front-end to the public.
In order to speed up development, deploy and QA, ssh access (with pubkey authentication) to the
deploy server is recommended to publish the front-end.

**Comment by OpenMatt** [comment]
@simonwex , we'll need your help with this. Can you review?

**Comment by simonwex** [comment]
Hey @OpenMatt, anonymous publishing is a problem for us as it could allow people to take advantage of the API for all kinds of nefarious tasks. I'd like to further understand the use of the API, when is the stand for this work?

**Comment by simonwex** [comment]
We won't be providing SSH access, as this isn't how we host web content. There are other ways we enable deployment through github. I'll articulate this need as well as other requirements in an email to the contractors. (Source code availability, source code license, after-hours support, etc.)

**Comment by OpenMatt** [comment]
Cool thanks @simonwex -- trying to schedule a stand-up for Thurs or Fri. But in this case: I think it would be helpful to just schedule a meeting to unpack these technical requirements specifically. And being proactive about how we will meet Mozilla's security / privacy review requirements, in particular. 

@michellenebiolo can you:
1) identify the technical leads from your team who should attend
2) propose a time tmrw or Fri that would work for you?

**Comment by OpenMatt** [comment]
@simonwex here's the full statement of work, for context:
[16.01.20_Beat3_TODO_SOW.pdf](https://github.com/MozillaFoundation/encryption_campaign/files/116278/16.01.20_Beat3_TODO_SOW.pdf)

**Comment by OpenMatt** [comment]
I'm marking this one as P1, because the need for being proactive around Mozilla's privacy and security review process on this one -- given the nature of the campaign and the novelty of the CTA -- is high.

**Comment by michellenebiolo** [comment]
Hi, the timeline stated in the beginning is correct.

We are writing a document with backend specifications to share with you soon, hopefully tomorrow.
Fabio Franchino (@abusedmedia) is in charge of our development team and can get into any necessary details about it with you. 
Please email him any requirements at f.franchino@todo.to.it
I need to confirm his availability but I think we can also arrange to talk on Friday – is sometime around 4-6 pm CET feasible?

(CC @Giorgio-Olivero)

**Comment by OpenMatt** [comment]
@michellenebiolo let's see if that's necessary coming out of today's meeting.

**Comment by OpenMatt** [comment]
@simonwex Here's a new and more detailed tech specs document: http://mzl.la/beat3_tech_specs

Can you review and flag w. questions?

**Comment by OpenMatt** [comment]
we agreed a tech stakeholders meeting is important. @simonwex and @abusedmedia will try to meet Friday (Feb 5)

**Comment by OpenMatt** [comment]
tech stakeholder meeting completed. I'm going to close this and push ahead w. new individual tickets.
